### ISSUE TITLE
ncpa-3.0.0-latest.x86_64.rpm missing from RHEL 7 Repo

### ISSUE THREAD

**Issue by Matty-uk** [NagiosEnterprises/ncpa#1029]
yum update
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: ukhub.a2themes.com
 * epel: mirror.pulsant.com
 * extras: mirror.freethought-internet.co.uk
 * remi-php74: mirror.netweaver.uk
 * remi-safe: mirror.netweaver.uk
 * updates: mirror.freethought-internet.co.uk
Resolving Dependencies
--> Running transaction check
---> Package ncpa.x86_64 0:2.4.1-1.el7 will be updated
---> Package ncpa.x86_64 0:3.0.0-latest will be an update
--> Finished Dependency Resolution

Dependencies Resolved

=============================================================================================================================================================================
 Package                              Arch                                   Version                                       Repository                                   Size
=============================================================================================================================================================================
Updating:
 ncpa                                 x86_64                                 3.0.0-latest                                  nagios-base                                  26 M

Transaction Summary
=============================================================================================================================================================================
Upgrade  1 Package

Total download size: 26 M
Is this ok [y/d/N]: y
Downloading packages:
No Presto metadata available for nagios-base
ncpa-3.0.0-latest.x86_64.rpm   FAILED
https://repo.nagios.com/nagios-test/7/ncpa-3.0.0-latest.x86_64.rpm: [Errno 14] HTTPS Error 404 - Not Found                                 ]  0.0 B/s |    0 B  --:--:-- ETA
Trying other mirror.
To address this issue please refer to the below wiki article

https://wiki.centos.org/yum-errors

If above article doesn't help to resolve this issue please use https://bugs.centos.org/.

Error downloading packages:
  ncpa-3.0.0-latest.x86_64: [Errno 256] No more mirrors to try.

**Comment by ne-jmichaelson** [comment]
This is just a note for the correct location of the RPM:

https://repo.nagios.com/nagios/7/ncpa-3.0.0-latest.x86_64.rpm

**Comment by HSTe** [comment]
The repo file for rhel7 is pointing wrong.
its pointing to https://repo.nagios.com/nagios-test/7/
Should be https://repo.nagios.com/nagios/7/

**Comment by ne-bbahn** [comment]
> The repo file for rhel7 is pointing wrong. its pointing to https://repo.nagios.com/nagios-test/7/ Should be https://repo.nagios.com/nagios/7/

The repo should be fixed by around noon today. If I don't get a response in the next few days, I'll close this assuming that it has been resolved.
