### ISSUE TITLE
Concurrent Connection Limit For Windows Servers

### ISSUE THREAD

**Issue by joerussbowman** [NagiosEnterprises/ncpa#103]
*Edit - I think the problem has to do with plugins blocking rather than any connection limit on the agent.

I've tried taking a mostly agentless approach for out Windows environment with NCPA. I set up a Windows 2012 Server with NCPA, then wrote some custom powershell plugins to do WMI queries to other Windows servers in our environment, basically using the NCPA host as a bridge for WMI querying. The key advantage is I am able to run NCPA as a Managed Service Account so for all the other hosts I only need to grant remote WMI query access to the MSA, no agent required for basic resource/performance monoitoring.

I took down about 4 servers, which each have 5 WMI query checks. The nagios server would connect to NCPA, run the WMI script plugin and hold the connection waiting for the WMI query to time out. What I found is once I had several servers down, the nagios server stopped being able to connect to the NCPA agent. It would timeout. Right now my hypthothesis is the NCPA agent only supports a few concurrent connections. Is there a way to increase this?

* I understand I could try to get around this by posisble using the passive agent to push all the checks, however that would require updating the config on the Windows server. We have multiple nagios servers for different environments and I already have a system set up for updating those via chef, we have not deployed chef on Windows and I'd rather try to figure this out using a method that only requires me to update the config on the nagios server. 

* I haven't looked at nsclient++ as an alterntative yet.

**Comment by scot0357** [comment]
Going to close this, as I'm quite confident this has been fixed. If not, reopen.
