### ISSUE TITLE
Missing dependencies when building NCPA V3 from Source - OL8/OL9

### ISSUE THREAD

**Issue by Matty-uk** [NagiosEnterprises/ncpa#1031]
Have build the rpms on Oracle Linux 8 and 9 ARM (aarch64).  Clean latest OS builds for Raspberry Pi 4b.  I found the following additional dependencies required via "dnf install <package_name>". 

Oracle Linux 8
sudo

Oracle Linux 9
sudo zlib-devel openssl-devel

**Comment by ne-bbahn** [comment]
Currently, all RPM builds of NCPA 3 can be built on CentOS 7 and they should work across all RPM-based distros. To further broaden our support and flexibility, I will however update the scripts to include these, enabling NCPA to be built directly on these Oracle distributions.

**Comment by ne-bbahn** [comment]
I have made some changes to the script for OL 8 and 9 and have been able to build on a freshly installed OL8 and OL9. These changes will be shipped with NCPA v3.0.1 and should release in the next week or two.
