### ISSUE TITLE
NCPA interface monitoring is taking the total in and out bytes value (an incremental value) rather than using the Current rate

### ISSUE THREAD

**Issue by lgroschen** [NagiosEnterprises/ncpa#104]
http://support.nagios.com/forum/viewtopic.php?t=30393#119226

The second to last post shows that monitoring the eth0 interface is using in
and out byte rates instead of using the current rate. 

"Is there any way to ask ncpa to check on current rate rather than total ? In the API I cant see an option to do so ?"

**Comment by scot0357** [comment]
I'm going to  go ahead and close this.
