### ISSUE TITLE
NCPA update breaks graphs

### ISSUE THREAD

**Issue by shodgson11** [NagiosEnterprises/ncpa#1055]
I upgraded an Ubuntu 20.04 server to NCPA 3.0 today and the Memory and Disk Usage graphs are now broken.  Several values swapped places in the graph.

Obviously the disk didn't completely swap its values in an instant this morning, and same with system memory.
![chrome_2023-11-29_10-10-11](https://github.com/NagiosEnterprises/ncpa/assets/43763237/e7b54e7b-4381-4b6c-8b3c-61362a0a881e)
![chrome_2023-11-29_10-09-41](https://github.com/NagiosEnterprises/ncpa/assets/43763237/ad8eb2bb-8585-431d-89ba-5b09e84ba632)

**Comment by ne-bbahn** [comment]
It seems the order of the items is different causing the colors to change, but the actual values should correspond correctly to the labels.

**Comment by shodgson11** [comment]
> but the actual values should correspond correctly to the labels.

The _new_ values do correspond to the _new_ labels, but this corrupts all historical data.  For example on the disk usage chart, obviously the Free space wasn't ~59 GB prior to the NCPA upgrade and then magically ~38 GB after the NCPA upgrade.

**Comment by ne-bbahn** [comment]
This will be fixed with release 3.0.1
