### ISSUE TITLE
NCPA 3.0 service fails on Linux with IPv6 disabled

### ISSUE THREAD

**Issue by shodgson11** [NagiosEnterprises/ncpa#1056]
If IPv6 is disabled, the NCPA 3.0 service won't start.  The error shown in the service status when trying to start the service is OSError: [Errno 97] Address family not supported by protocol.

If you edit the config file and specify ip=0.0.0.0, then the service will start.

This bug seems to have been fixed years ago, but has resurfaced.

**Comment by ne-bbahn** [comment]
Thanks for identifying the cause of this problem. I'll try to get it fixed for 3.0.1.

**Comment by shodgson11** [comment]
> Should the user have ipv6 disabled via sysctl on a per-interface basis, then they'll just have to set the ip manually.

Certainly my Ubuntu 20.04 system has IPv6 baked-in, but my interface does not have IPv6 info configured.  I guess that means the fix here does not apply to my system.  Failing to launch the service and requiring user intervention seems a bit excessive in the case where an interface doesn't have an IPv6 address.

**Comment by ne-bbahn** [comment]
This will be fixed in NCPA v3.0.1 so I have closed this issue.
