### ISSUE TITLE
Provide more correct version for rpm package

### ISSUE THREAD

**Issue by varnar** [NagiosEnterprises/ncpa#106]
Hello dear Developers,
It is possible to provide more correct version for el5,el6,el7
Because you provide the version in file name:
```
CentOS 5.x	ncpa-1.7.2.el5.i386.rpm	ncpa-1.7.2.el5.x86_64.rpm
CentOS 6.x	ncpa-1.7.2.el6.i386.rpm	ncpa-1.7.2.el6.x86_64.rpm
CentOS 7.0	n/a	ncpa-1.7.2.el7.centos.x86_64.rpm
```
But it is different when yum get is from local rpm repo (both versions are in same repo)

```
yum search ncpa*
ncpa-1.7.2-1.x86_64 : A Cross Platform Monitoring Agent
ncpa-1.7.2-1.el6.x86_64 : A Cross Platform Monitoring Agent
```

And if you try to install using yum install ncpa on RedHat 6 it take version from RedHat 5

Here is some example that we have made separate RPM package for plugins, which we installing after ncpa:
```
QT_ncpa_el5-1.7.0-2.x86_64 : QT-Nagios-NCPA-Client-RPM
QT_ncpa_el6-1.7.2-1.x86_64 : QT-Nagios-NCPA-Client-RPM
```

So we never have any issue with yum installation.

**Comment by scot0357** [comment]
Wow, I think I was just being incredibly dense, is what you're talking about simply the filename that is generated for it. Then that is totally doable (sorry for totally missing this at first).

**Comment by varnar** [comment]
I think in Release you must have something like this:
For RH(version)
Release: 1.el(version)

And the proper file name based on release :+1: 

Thanks

**Comment by scot0357** [comment]
@varnar Reading about this topic leads me to believe that the difference is cause by the rpmbuild that is distributed by default is ancient, and doesn't enforce this by default. I'm hoping my work on the build system will fix this.

**Comment by varnar** [comment]
Hello scot0357,

I just checked  it in version 1.8.1 - it does not work
```
[root@sq5vqrhel5002 ~]# rpm -qp ncpa-1.8.1-1.el5.x86_64.rpm
     ncpa-1.8.1-1

[root@sq5vqrhel5002 ~]# rpm -qp ncpa-1.8.1-1.el6.x86_64.rpm
     ncpa-1.8.1-1.el6
```

**Comment by jhomann** [comment]
So let me get this straight, is it not working right because the el5 package does not have `Release: 1.el5` and instead is showing just `Release: 1` ?

**Comment by jhomann** [comment]
The second answer in this thread here http://stackoverflow.com/questions/5135502/rpmbuild-dist-not-defined-on-centos-5-5 should be exactly what we need to do in order to get this working. I'll be sure to make a note of it and do this on our CentOS 5 build servers.

**Comment by jhomann** [comment]
I have this working on our build servers for el5 however it looks like it puts in:

`Release: 1.el5.centos`

I don't know that much about packaging... is this normal for centos boxes? Should it only be saying el5 or will this install fine on RHEL 5 also?

**Comment by jhomann** [comment]
Closing this since it seems to build fine like this. I will still verify it installs on RHEL when we build the final versions.
