### ISSUE TITLE
NCPA 3.0.1 can’t see .ps1 plugin on Windows Server 2019

### ISSUE THREAD

**Issue by fdeyso** [NagiosEnterprises/ncpa#1091]
We use custom ps1 plugins to monitor a number of statuses that are otherwise unsupported. The ps files work fine on their own and in 2.4.1 we have no issues. Updates some servers as test to 3.0.1 and none of them can find any plugins. In the local webUI/API/plugins is empty, but the c:/program files(x86)/nagios/NCPA/plugins still has the .ps1 files. Tried removing, restarting the service, re adding then restart the service. I also tried editing the nagios.cfg to use the full path instead of the plugins/ .
I also use 64 bit poweshell so that change is already in the configs. Changing it back to default makes no difference.
Any ideas?

**Comment by ne-bbahn** [comment]
The issue seems to be due to NCPA 3 being in a different folder than NCPA 2. 
NCPA 3 is located in `C:/Program Files/nagios/NCPA/` instead of NCPA 2's `C:/Program Files(x86)/nagios/NCPA`

If this isn't your issue, let me know here and I will reopen this issue.

**Comment by fdeyso** [comment]
Hi
It was the problem, then just an FYI, it leaves the folders/files in the old Program Files (x86) location, deleting them would be easy by automation for us, but a bit confusing.
