### ISSUE TITLE
Permission denied errors when trying to access a folder accessible by a group that nagios is a member of. 

### ISSUE THREAD

**Issue by mothbitten** [NagiosEnterprises/ncpa#1096]
ncpa 3.0.1. Worked fine with ncpa 2. 

This is on Redhat Linux 8 and 9.

check_ncpa.py reports a permissions error when trying to access remote files that Nagios belongs to with secondary groups. When I sudo to the nagios user on that system, the local user run the check without issue.  

To recreate: 

mkdir /tmp/test
chown root:wheel /tmp/test
chmod 750 /tmp/test
add to wheel group: usermod -a -G wheel nagios

Then add a bash script to /usr/local/ncpa/plugins: test.sh

cat test.sh:
ls /tmp/test

as the nagios user, I can run that script without any permissions issues locally. But from the Nagios server, no:

/usr/local/nagios/libexec/check_ncpa.py -t '<redacted>' -H <IP>  -M 'plugins/test.sh'
ls: cannot open directory '/tmp/frog': Permission denied

Restarted the service, even rebooted. Behavior remains. It does NOT occur when "nagios" is the group. 

Interestingly enough, when I removed nagios from the nagios group and made its primary group "wheel" It could STILL access the directory via check_ncpa.py after the local user no longer had access. 

Selinux is disabled.

**Comment by ne-bbahn** [comment]
This should be fixed in 3.0.2 thanks to [graham-collinson](https://github.com/graham-collinson)'s MR: https://github.com/NagiosEnterprises/ncpa/pull/1113
