### ISSUE TITLE
Migraging NCPA Configs When Upgrading from NCPA 2.X to 3.X on WIndows

### ISSUE THREAD

**Issue by shoreypu** [NagiosEnterprises/ncpa#1097]
When attempting to upgrade from NCPA 2.4 to 3.0.1 in Windows, the new agent no longer has any of the config files from the old agent.  NCPA 2.X is 32-bit and installs to C:\Program Files (x86)... and 3.x is 64-bit and installs to C:\Program Files...  The config from C:\Program Files (x86)... is not copied over to C:\Program Files....

Is there a way to copy over the config files as part of the upgrade?

Thanks

**Comment by shoreypu** [comment]
I kind of implied that with config files, but probably should have spelled that out as well.  Basically, this is a new, un-configured, agent.

**Comment by MrPippin66** [comment]
I would agree this is a pretty serious problem. We've yet to deploy/upgrade from V2 to V3 for Windows and this will cause a lot of headaches.

**Comment by shoreypu** [comment]
> I would agree this is a pretty serious problem. We've yet to deploy/upgrade from V2 to V3 for Windows and this will cause a lot of headaches.

I've run some tests and it looks like you can copy over the files prior to upgrading, which will not be overwritten.  However, I also noticed some differences in the ncpa.cfg files, that I am still reviewing.  The standard set of NCPA checks we run work, but I'm not sure if there are any caveats to running with the old config.  Guidance would definitely be helpful.

**Comment by MrPippin66** [comment]
Regardless, there should be an "upgrade" part of the installation that detects a 32-bit previous installation which does all the requisite migration steps.

**Comment by ne-bbahn** [comment]
I need to verify that there are no differences in configuration that would cause things to break if someone upgrades, but as long as that's not an issue, I'll have the NSIS script copy over the old configs to the new location.

**Comment by MrPippin66** [comment]
Okay, but just to be clear, that really should be the entire current contents of the existing 32bit location (minus the files the upgrade would installing)

**Comment by ne-bbahn** [comment]
> Okay, but just to be clear, that really should be the entire current contents of the existing 32bit location (minus the files the upgrade would installing)

I believe it should copy the contents of the `etc`, `plugins` and `var` folders. If you think anything else should be copied over, let me know.

**Comment by MrPippin66** [comment]
In my case, if you get etc and plugins, we're good. var matters for the existing db
________________________________
From: bb ***@***.***>
Sent: Wednesday, February 28, 2024 2:02 PM
To: NagiosEnterprises/ncpa ***@***.***>
Cc: SCOTT FIELDS ***@***.***>; Comment ***@***.***>
Subject: [EXTERNAL] Re: [NagiosEnterprises/ncpa] Migraging NCPA Configs When Upgrading from NCPA 2.X to 3.X on WIndows (Issue #1097)

Okay, but just to be clear, that really should be the entire current contents of the existing 32bit location (minus the files the upgrade would installing) I believe it should copy the contents of the etc, plugins and var folders. If you think
ZjQcmQRYFpfptBannerStart
This Message Is From an External Sender
This message came from outside your organization.
<https://us-phishalarm-ewt.proofpoint.com/EWT/v1/Dq81_Y1A2Q!eXOKWoFBzM6hVy3hqwp6o30LxmCd-Xi9sP2gh_g3V17-jCyvkeKb61ROG32wrqVseVvSKtRpDBcrkY2ckTYsbPDzxrd3O3Be2iJtUHD8V_c8Q_AyVl4$>
Report Suspicious

ZjQcmQRYFpfptBannerEnd

Okay, but just to be clear, that really should be the entire current contents of the existing 32bit location (minus the files the upgrade would installing)

I believe it should copy the contents of the etc, plugins and var folders. If you think anything else should be copied over, let me know.

**Comment by ne-bbahn** [comment]
This will be included in NCPA 3.1.0

**Comment by MrPippin66** [comment]
And tentative schedule for this release?
