### ISSUE TITLE
Documentation: bug: Installing on DEB-based Linux 

### ISSUE THREAD

**Issue by cepaim** [NagiosEnterprises/ncpa#1098]
The command 

     /etc/init.d/ncpa_listener restart

doesn't exists. 

Instead, 

    /etc/init.d/ncpa restart

exists

**Comment by austinjhunt** [comment]
Any updates on this? Seeing this on our machines as well. Known affected machines are Ubuntu 18 and Ubuntu 22. 

No errors during installation, but when starting the service, we are getting an error message saying  /etc/init.d/ncpa_listener does not exist. 

We customized our config to use a different token and to run on a custom port, and the new "ncpa" service runs on the default 5693, and "ncpa_listener" does not exist.

**Comment by ne-bbahn** [comment]
NCPA 3 is a single service running as `ncpa` instead of NCPA 2's dual services `ncpa_listener` and `ncpa_passive`. This is laid out pretty clearly in the documentation: [https://www.nagios.org/ncpa/help.php](https://www.nagios.org/ncpa/help.php)
