### ISSUE TITLE
executing nagios plugin on ncpa client server using check_ncpa.py

### ISSUE THREAD

**Issue by krobertson71** [NagiosEnterprises/ncpa#110]
I posted this on the nagios forums but thought this might need to be seen here as well...

I am having to do this because the NCPA agent wont monitor mounted file systems.  So what I am trying to do is have the check  check_disk as a plugin which will run against the path of the mounted file system.

--------------------------------

Having a time with this. Trying to get check_ncpa.py to execute a plugin on the ncpa client, check_disk. Pulling my hair out.

It tries to execute the plugin but does not seem to pass the arguments correctly. I am trying to run this [this is how I run it locally on remote server]. check_disk -w 10% -c 5% -p /tmp and it works great.

The plugin is in the proper ncpa plugins directory.

Here is what I have tried so far.

Code: Select all
    ./check_ncpa.py -v -H dcri-vmkar54 -t nagiosxi -M agent/plugin/check_disk -a "-w 10% -c 5% -p /tmp"
    Could not complete with SSL, or there was an error in the JSON
    check_disk: Could not parse arguments
    Usage:
    check_disk -w limit -c limit [-W limit] [-K limit] {-p path | -x device}
    [-C] [-E] [-e] [-f] [-g group ] [-k] [-l] [-M] [-m] [-R path ] [-r path ]
    [-t timeout] [-u unit] [-v] [-X type] [-N type] [-n]
    <type 'int'>

Tried this one below according to the NCPA docs

Code: Select all
    ./check_ncpa.py -v -H dcri-vmkar54 -t nagiosxi -M agent/plugin/check_disk -a "-w '5%' -c '10%' -p '/tmp'"
    Could not complete with SSL, or there was an error in the JSON
    check_disk: Could not parse arguments
    Usage:
    check_disk -w limit -c limit [-W limit] [-K limit] {-p path | -x device}
    [-C] [-E] [-e] [-f] [-g group ] [-k] [-l] [-M] [-m] [-R path ] [-r path ]
    [-t timeout] [-u unit] [-v] [-X type] [-N type] [-n]
    <type 'int'>

So you can see why I am lost. Token is correct. Is there something I am missing on the client side like a setting in the ncpa conf file? LOST!!!!!

**Comment by scot0357** [comment]
Yes, the CCM cannot run commands on the command line exactly as though Nagios would run them. I don't recall the exact details why, but its something about security and running stuff via the shell through the web interface. Anyways, I will mark this as resolved as indicated by @varnar.
