### ISSUE TITLE
Mac Build issue

### ISSUE THREAD

**Issue by ne-bbahn** [NagiosEnterprises/ncpa#1104]
Building on Mac isn't working anymore.

> error: cannot find file/directory named /usr/local/opt/mpdecimal/lib/libmpdec.3.dylib

Something is causing this error and needs to be fixed.

**Comment by coobs1** [comment]
I had similar issues on macOS 10.13. What finally worked for me was creating symlinks for the .dylib files located in /usr/local/ncpa/lib/ inside the /usr/local/lib directory (e.g., ln -s /usr/local/ncpa/lib/libssl.3.dylib /usr/local/lib/libssl.3.dylib)
