### ISSUE TITLE
NCPA3: can't chown('/var/log/ncpa_passive.log', 990, 799): 2, No such file or directory

### ISSUE THREAD

**Issue by Ivan-Roger** [NagiosEnterprises/ncpa#1108]
## Problem

When using a custom log path for ncpa passive the process crashes upon start because it cannot chown a non-existent file.

## Expected result

The log file is created then `chown`ed and the process starts without issue.

## Actual result

Crash on agent startup: `can't chown('/var/log/ncpa_passive.log', 990, 799): 2, No such file or directory`

## Root cause

[agent/ncpa.py line 507](/NagiosEnterprises/ncpa/blob/master/agent/ncpa.py#L507): `chown(self.config.get('general', 'uid'), self.config.get('general', 'gid'), self.passive_logfile)`

This line happens before the file is created if missing, and causes the crash.

## Potential solution

We should check that the file exists before trying to `chown` it.

I'll drop in a PR for this later.

**Comment by sawolf** [comment]
Hi @Ivan-Roger - thanks for reaching out and for providing the patch. For our current timeline, we're looking at starting on another maintenance release of NCPA in the next 2-3 weeks, so we'll have someone review, test, and hopefully merge around that time.
