### ISSUE TITLE
perf counters

### ISSUE THREAD

**Issue by SuperGoodMike** [NagiosEnterprises/ncpa#111]
I would like to get Messages Pending Routing and  Remote Queue Length performance counters from our Exchange environment. Could you add the ability to get all performance counters through ncpa?

**Comment by SuperGoodMike** [comment]
Any update?

**Comment by scot0357** [comment]
I think this might already be in, however I'm unsure of how much its tested. Do you know the full path of the item you'd like? If you can get me that I can formulate something that _should_ work and will use the opportunity to document it as well.

**Comment by SuperGoodMike** [comment]
Well I need to get Messages Pending Routing and Remote Queue Length performance counters for Microsoft Exchange. I would like the same checks Nsclient++ had for exchange.
Don't think these names will help because I could not find them
"\\SMTP Server(_Total)\\Remote Queue Length"
"\\SMTP Server(_Total)\\Messages Pending Routing"
Here is a good document on getting the Perfmon counter names
http://kb.paessler.com/en/topic/50673-how-can-i-find-out-the-names-of-available-performance-counters
btw this works well too
https://github.com/sreinhardt/Nagios_Performance_Counters 
But I cannot justify having to push out powershell 3 to all environments just for monitoring :(

**Comment by scot0357** [comment]
These are actually already accessable (as of 1.8.0, possibly in 1.7.2, I'm not super sharp on that right now:

```/api/windowscounters/SMTP Server(_Total)/Remote Queue Length```

Should work when accessed, try that in your web browser.

**Comment by SuperGoodMike** [comment]
In 1.7.2 the windowscounter is empty 
https://mymailserver:5693/api/windowscounters/

{
  "value": {
    "windowscounters": []
  }
}

:(

If I try any of the suggested I get the following message

{
  "value": {
    "windowscounters": [
      [
        "Error: Unable to parse the counter path. Check the format and syntax of the  specified path."
      ], 
      "c"
    ]
  }
}

Looking forward to 1.8 :D

**Comment by SuperGoodMike** [comment]
One more comment/question
Will there be thresholds for counters in 1.8?

**Comment by vAndrewJ** [comment]
Windows Perf Counters are working in 1.7.2, the API just doesn't list them (same for services). But if you grab the name of the counter and put in the URI:

api/windowscounters/Web%20Service(_Total)/Current%20Connections

This correctly returns the expected data:

{
  "value": {
    "windowscounters": [
      [
        13.0
      ], 
      "Current Connections"
    ]
  }
}

**Comment by cydo67** [comment]
I can get performance counters to work except when a "/sec" is used.  So for example this works fine:

api/windowscounters/Network%20Interface%28*%29/Current%20Bandwidth

But this does not work:

api/windowscounters/Network%20Interface%28*%29/Bytes%20Total/sec

also tried

api/windowscounters/Network%20Interface%28*%29/Bytes%20Total\/sec

Any ideas would be appreciated....

**Comment by SuperGoodMike** [comment]
Thank you @ vAndrewJ
So I can call the following counter below and others but the values getting returned are not correct.  I currently have 0 connections (in perf mon) but the API is returning the value of 160.0??

api/windowscounters/Web%20Service(_Total)/Current%20Connections

{
"value": {
"windowscounters": [
[
160.0
],
"Current Connections"
]
}
}

**Comment by SuperGoodMike** [comment]
@ scot0357 Can you confirm that all perf mon counters visible in NCPA 1.8? Are you able to browse through all through NCPA? Could you provide a screen shot of what you see?
this is what I see in 1.7 
https://server:5693/api/windowscounters/
{
  "value": {
    "windowscounters": []
  }
}

Do you see more?

**Comment by krobertson71** [comment]
Nick,  
Tested this as well in my 1.7.2 releases.  I don't think the Web Connections is returning what you think it is.  It looks like it is just returning all network connections.

1.7.2 is iffy with performance counters as it is.  I would do a pull request, or wait for the 1.8.0 release and test again.

https://servername:5693/api/windowscounters

{
  "value": {
    "windowscounters": []
  }
}

**Comment by cydo67** [comment]
So I figured out the "/" must be replaced with "%2F" when used in reference to "/sec", this works:

api/windowscounters/Network%20Interface%28*%29/Bytes%20Total%2Fsec

**Comment by cydo67** [comment]
When I run perfmon and when I look at the api I see packets sent and received.  However, no matter what I do with performance counters I do not get anything but 0

/api/windowscounters"Network%20Interface%28%2A%29/Bytes%20Sent%2Fsec"
        0.0|bytes=        0.0;;;
/api/windowscounters/"Network%20Interface%28%2A%29/Bytes%20Received%2Fsec" 
        0.0|bytes=        0.0;;;

Some performance counters are working but the network counters seem to fail...am I doing the wrong?

**Comment by SuperGoodMike** [comment]
@cydo67
I agree with krobertson71 comment
"1.7.2 is iffy with performance counters as it is. I would do a pull request, or wait for the 1.8.0 release and test again."

**Comment by scot0357** [comment]
Hmm, I think what cydo67 pointed out is most likely correct where the actual / in the argument when its part of the actual counter needs to HTML escaped. @cydo67 I assume the quotes in your post were some artifact of copy and paste?

**Comment by vAndrewJ** [comment]
Looks like we're still havnig problems with perf counters in 1.8. I'm checking a server running the latest EXE for: /api/windowscounters/W3SVC_W3WP(_Total)/URI%20Cache%20Flushes 

And I get back:
{
  "value": {
    "windowscounters": [
      [
        "Error: No data to return."
      ], 
      "c"
    ]
  }
}

**Comment by jhomann** [comment]
What are you using as the 1.8.0 release?

**Comment by vAndrewJ** [comment]
Sorry I left this one hanging. Most counters are working for me on 1.8 now, with the exception of anything using 'per second'. %2fsec will return an OK, but always a value of 0.

**Comment by vAndrewJ** [comment]
And now trying to call Windows mount point % Free from PerfCounters:

-M 'windowscounters/LogicalDisk(D%3A%5CMSSQL_Data)%5C%25%20Free%20Space' -w 20 -c 10

I'm getting critical threshold tripped: 

CRITICAL: \\LogicalDisk(D:\\MSSQL_Data)\\% Free Space was 49% Free Space

**Comment by box293** [comment]
I experienced similar results with:
```
\LogicalDisk(C:)\% Disk Read Time

windowscounters/LogicalDisk(C:)/%%20Disk%20Read%20Time
```
Always seemed to return result of 0 event when I could watch performance monitor while I created disk activity to confirm values existed. However the activity only existed for about 20 seconds so not sure if thats enough activity time for NCPA to get a valid number.

The formatting seems correct, as this one returned valid values when I had loaded up the CPU on the system:
```
\Processor(_Total)\% User Time

windowscounters/Processor(_Total)/%%20User%20Time
```

**Comment by jhomann** [comment]
Looking at the code, and this can definitely be documented, the way to get per second ones to work is by using the `sleep `attribute ... adding on `?sleep=5` will wait 5 seconds and give the delta in seconds.

**Comment by jomann09** [comment]
Adding this to the documentation now - should be one of the last parts of the 2.0 release.
