### ISSUE TITLE
Happy New Year

### ISSUE THREAD

**Issue by varnar** [NagiosEnterprises/ncpa#112]
Hello All NCPA users and developers and contributors.

Many people await new years day, to make a new start to their old habits. I wish you otherwise, Happy New Year !!!

Health and good luck to all of us

Thanks for your support !!!

The best and the last issue in this year, 2014.

**Comment by scot0357** [comment]
@varnar Happy new year to you as well! Thanks for all input, fixes and bug reports you've given this year and I hope the best for you this coming year. Cheers!
