### ISSUE TITLE
Allow multiple passive NRDP target servers

### ISSUE THREAD

**Issue by ne-bbahn** [NagiosEnterprises/ncpa#1125]
Implementation: probably separate NRDP server addresses/tokens by commas?

**Comment by HunnyPuns** [comment]
I feel like this should be a bug. I had this setup in 2.4, and when I updated to 3, it broke. Found out about it yesterday.

**Comment by wbneville** [comment]
How the heck is this not fixed yet???

**Comment by wbneville** [comment]
Can this be re-categorized to a bug in order to expedite?

**Comment by ne-bbahn** [comment]
I just set up NCPA 3.1.0 with two XI servers and it is working properly. Have you set up your configuration correctly?

![image](https://github.com/user-attachments/assets/06d2e7a5-38ea-4e8a-89d0-f1cbce5a0f2f)

![image](https://github.com/user-attachments/assets/c06a2989-cf60-4732-9874-f7a4f20345dc)

**Comment by ne-bbahn** [comment]
I have verified that this is working on both CentOS 9 and Windows 10. If you find a case where this doesn't work when configured properly, feel free to reopen this.
