### ISSUE TITLE
NCPA service will not start Server 2008 R2 or 2011 SBS

### ISSUE THREAD

**Issue by uGeeko** [NagiosEnterprises/ncpa#1145]
![NCPA Service](https://github.com/NagiosEnterprises/ncpa/assets/166120058/896014aa-36d3-4e64-86d2-3ba4faab9a5a)

NCPA service will not start after upgrade from 2.4.0 32-bit to 3.0.2 64-bit

**Comment by MrPippin66** [comment]
The NCPA agent for Windows V3 officially is only supported on Windows server at or greater than 2016.

FYI, both of those Windows releases are out of support as well.

**Comment by uGeeko** [comment]
I have managed to resolve this by using a missing dll file for Python. The version of python being used isnt compatible with 2016 and below so needs this extra file.

**Comment by ne-bbahn** [comment]
As we do support versions of Windows below Windows Server 2016, I will close this issue. Anyone looking to use older versions of Windows can choose to either use an older version of NCPA that supports those versions, upgrade their servers or find a similar solution as uGeeko here.
