### ISSUE TITLE
cfg files in ncpa.cfg.d folder not parsed in NCPA 3.0.2 Windows

### ISSUE THREAD

**Issue by fraas04** [NagiosEnterprises/ncpa#1149]
The .cfg files in the ncpa.cfg.d folder are not getting parsed into to the configuration while using NCPA 3.0.2 on Windows. Downgrading to 3.0.1 solves the problem, and the additional config files get parsed. 

The issue is not present on Linux however.

**Comment by ne-bbahn** [comment]
I cannot replicate this issue. Can you give more information on your setup/configuration/settings/permissions that might be causing this?

**Comment by fraas04** [comment]
Sorry for not answering. However with 3.1.0 installed, the issue got resolved
