### ISSUE TITLE
NCPA Services not starting on windows 2008 R2 STD

### ISSUE THREAD

**Issue by prakhead** [NagiosEnterprises/ncpa#115]
I had the issue where installing NCPA  1.7.2 failed to create services so I created them manually with the following commands:

`sc.exe create "NCPA Listener ncpalistener" binPath= "C:\Program Files (x86)\Nagios\NCPA\ncpa_listener.exe" displayname= "NCPA Listener - ncpalistener" start= delayed-auto`

`sc.exe create "NCPA Passive ncpapassive" binPath= "C:\Program Files (x86)\Nagios\NCPA\ncpa_passive.exe" displayname= "NCPA Passive - ncpapassive" start= delayed-auto`

When I started the services the first time they hung in the "starting" state, after a reboot the passive service started but the listener hung again, after ending the listener process and restarting the service it came up and worked until the next reboot. 
Now both services hang in the "starting" state. I have checked the log files (C:\Program Files (x86)\Nagios\NCPA\var) which are empty and event logs and nothing seemingly relevant is showing, what am I doing wrong?

**Comment by prakhead** [comment]
Thanks for suggestions but still not working, this is what I did:
Disabled passive service, run diskperf -y and rebooted. 
Listener service still hangs, `netstat -n -a | find "5693"` but shows ports open.
Used pskill to end process and restarted service, still hangs.

I noticed that a machine I am successfully running NCPA 1.7.2 on had VS 2008 C++ redistributable libraries installed, so I installed both x86 and x64 but still no joy.

Any other dependencies I should install or has anyone got any other suggestions?

**Comment by prakhead** [comment]
Now installed, I removed the services with `sc.exe`, run `diskperf -y`, rebooted, uninstalled ncpa, run `diskperf -y` again (in an administrative command prompt, to be sure) then installed ncpa (run as administrator). The installer complained about not finding disks but installed the services and they show as "started" and were functioning correctly when queried form the nagios host.

I also noticed that log files in the `C:\Program Files (x86)\Nagios\NCPA\` had appeared and were populated, I wasn't expecting these log file here, I was expecting them in the var sub folder.. oh well.

I have tested this on another host that was having problems and the administrative `diskperf -y` before installation seems to do the trick.

**Comment by varnar** [comment]
I glad to hear that your issue has been resolved.
The fix for issue with diskperf, as I understand NCPA developers, will be in 1.8 version.

**Comment by scot0357** [comment]
Yes, @varnar you are absolutely right, I'm going through and merging all the known issue into 1.8 to get it out ASAP so we don't have to deal with these known issue for much longer. I will leave this open until it is merged however.

**Comment by scot0357** [comment]
Absolutely fixed in https://github.com/NagiosEnterprises/ncpa/commit/0bc57a631000ee061168b9a014f8a7f11338060c.
