### ISSUE TITLE
Error parsing JSON

### ISSUE THREAD

**Issue by joeytrungale** [NagiosEnterprises/ncpa#116]
Using 1.7.2 I was getting this response:
 python ./check_ncpa.py  -H server  --token=token --list -s -v
Connecting to: https://server:5693/api//?token=token
File returned contained:

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>404 Not Found</title>
<h1>Not Found</h1>
<p>The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.</p>

The stack trace:Traceback (most recent call last):
  File "./check_ncpa.py", line 237, in main
    info_json = get_json(options)
  File "./check_ncpa.py", line 212, in get_json
    return json.load(f)['value']
  File "/usr/lib64/python2.7/json/__init__.py", line 290, in load
    **kw)
  File "/usr/lib64/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.7/json/decoder.py", line 365, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python2.7/json/decoder.py", line 383, in raw_decode
    raise ValueError("No JSON object could be decoded")

The double '//' in the request caught my eye, removing it returns valid JSON. Patch below.

--- check_ncpa.py       2015-01-07 16:00:43.663549043 -0600
+++ /usr/libexec/nagios/check_ncpa.py   2015-01-07 17:07:49.876483141 -0600
@@ -145,7 +145,7 @@
         metric = ''
 
     arguments = get_check_arguments_from_options(options)
-    api_address = 'https://%s:%d/api/%s/%s' % (hostname, port, metric, arguments)
+    api_address = 'https://%s:%d/api%s/%s' % (hostname, port, metric, arguments)
 
     return api_address

**Comment by varnar** [comment]
It looks like same issue
https://github.com/NagiosEnterprises/ncpa/issues/113

**Comment by scot0357** [comment]
@varnar Yes it would appear so. Fixed in https://github.com/NagiosEnterprises/ncpa/commit/46ea4e1ad49df6677e746a2d02879323275f2332
