### ISSUE TITLE
Passive checks not respecting intervals on Windows

### ISSUE THREAD

**Issue by ne-bbahn** [NagiosEnterprises/ncpa#1169]
https://support.nagios.com/forum/viewtopic.php?p=356948#p356948

> Have a situation where I want to start using passive checks. I installed NCPA 3.1 onto my laptop just now to test. I have this in my checks section:
> 
> 
```
[passive checks]
%HOSTNAME%|__HOST__ = system/agent_version
%HOSTNAME%|Disk Usage = disk/logical/C:|/used_percent --warning 80 --critical 90 --units Gi
```
> 
> 
> %HOSTNAME%|CPU Usage|3600 = cpu/percent --warning 60 --critical 80 --aggregate avg
> sleep is set to 300 in nrdp.cfg and every 5 minutes in unconfigured objects the last seen gets updated for the host, Disk and CPU. It doesn't seem to be respecting the 3600 interval for CPU.

**Comment by SNapier** [comment]
Looks like this is in the handler, the entities of the split will never total greater than two (one yes, two no) thus the default of 300 is being set due to the error.
![image](https://github.com/NagiosEnterprises/ncpa/assets/50675926/d2c7b8a4-9138-47f7-bee5-c052602a6493)
 
Was having same issue, thanks for posting.

**Comment by SNapier** [comment]
It seems you can work around this in the sort term by adding a another pipe in the service check definition.
![image](https://github.com/NagiosEnterprises/ncpa/assets/50675926/8efc52a0-ed0d-426e-947e-5b96ebbb4f28)

**Comment by ne-bbahn** [comment]
> Looks like this is in the handler, the entities of the split will never total greater than two (one yes, two no) thus the default of 300 is being set due to the error. 
> 
> Was having same issue, thanks for posting.

Hello @SNapier, are you sure that is what was happening for you? I tried tracking the duration and it is correctly using the given duration.

**Comment by SNapier** [comment]
@ne-bbahn yup, try setting it to 60 seconds and see if that works for you or if it stays with the default

**Comment by ne-bbahn** [comment]
> @ne-bbahn yup, try setting it to 60 seconds and see if that works for you or if it stays with the default

I did and it was correctly sending every 60 seconds. What OS are you working on? I am currently using CentOS 9 Stream.

**Comment by SNapier** [comment]
OS was Windows 10
I did not see the issue on RHEL or Centos Linux

**Comment by ne-bbahn** [comment]
I tried replicating this on Windows 10 and 11 and it is working properly on both machines. 
Did you restart NCPA after making these changes? You can either do this from a terminal with `sc stop ncpa` `sc start ncpa` or by restarting the service with the task manager.

**Comment by SNapier** [comment]
This was several months ago, the machine has long since been re-imaged with an active agent.

**Comment by ne-bbahn** [comment]
I can't replicate this issue, so unless someone else has encountered a similar issue, I will assume this was due to not restarting NCPA properly and close this issue in two weeks.
