### ISSUE TITLE
Solaris 11.4.69 (SRU69+) with libffi.so.8 - linker isn't picking it up

### ISSUE THREAD

**Issue by bish0polis** [NagiosEnterprises/ncpa#1175]
Hi everyone,

I'm encountering some challenges rebuilding ncpa 2.4.1 for Solaris 11.4.69 after the changes in SRU69 for libffi, and I'm hoping someone else has seen this before.

Our process:

1. `$ gtar xzf v2.4.1.tar.gz ncpa-2.4.1/build/resources/Python-2.7.18.tgz --wildcards --to-stdout | tar xzf -`
2. `$  (cd Python-2.7.18 ;  ./configure --with-system-ffi && make)`
3.  {more stuff }
4. `$  gtar xzf v2.4.1.tar.gz`
5. `$ Python-2.7.18/python ncpa_listener.py -n`

And that's where we see:
`ImportError: ld.so.1: python: libffi.so.6: open failed: No such file or directory`

So it's not finding the libffi.so.8 which *is* there:
![image](https://github.com/NagiosEnterprises/ncpa/assets/13486046/672c3129-8f54-428d-89d4-48f594bfa5ea)

Notes:
- I'm coming back to Solaris (UnixWare) after 16 years of Linux time, so lots of things are challenging.  ;-)
- I know about v3.x.y but the task is 2.4.1 pending a proper review of 3 and its better python options
- I know about IPS, but we're doing PKGs today.  Ideally we can generate both by task's end.
- I can bulldoze and rebuild this build box, but it'll take a day (#ansible ssh-storm)
- our security doesn't allow build or in-service boxes to contact the world (no direct `pip` action).  So, we do need to `python -m pip download` and sneakernet it into the buildmonkey box to generate a package (worked for 2.4.1/ffi6).

But, here's what I'm hoping:
- have we seen this before?  (or something like it, as I'm not sure everyone's on SRU69+ yet) 
- have we solved this before?

The good news is that we were able to generate a usable PKG for 2.4.1 in SRU<=68, so I know we can get close.

**Comment by bish0polis** [comment]
Argh.

I know it's in the build of python27 .  I can feel it in my spleen.  But I can't ldd the static binary and `--enable-shared` produces a fiesta of

![image](https://github.com/NagiosEnterprises/ncpa/assets/13486046/b7cc1062-9e21-47e8-86ef-1ee4f4a8d9e5)

... NO, really!  120k lines of that so far!  ...with solutions that don't look tasty and also don't seem to change things (eg `-fPIC`) 

Still chipping at it.

**Comment by sawolf** [comment]
> I know about v3.x.y but the task is 2.4.1 pending a proper review of 3 and its better python options

Just so you know it, our internal team is more focused on getting NCPA 3 to work on Solaris. The project lead is on vacation at the moment but I think we'll see more movement on it soon. Hopefully, we'll run into enough of the same issues that we can share solutions "back" to older builds

**Comment by bish0polis** [comment]
> Just so you know it, our internal team is more focused on getting NCPA 3 to work on Solaris. 

Our team meeting has just ended, and were *just* discussing ditching 2.4 and rebasing on 3.  One of the seniors did look at 3 on 11.3 or 11.4 and decided a change in the code introduced a lot of dependencies that made it essentially a non-starter.  The news that it's possible *and* a listed goal will be welcome.

Thanks!

**Comment by bish0polis** [comment]
Update:  GET THEE TO SRU71 and the temporarily re-included libffi6.so will still be there for you.  Maybe it goes away with 73, maybe it stays forever.  We don't ask these questions of the gods and expect an answer.

Still testing the ghetto factor of our current homebrew PKG, though.  More to follow as this gets on the front burner but it's lookin' good with a fresh, clean rebuild.

**Comment by bish0polis** [comment]
Yeah, this is totally solved.
![image](https://github.com/user-attachments/assets/734b9999-26ee-4a21-85e2-d7ede7a28e0f)
Works on SRU71 too, of course, with the temporary reappearance of libffi.so.6.  SRU72 is still being deployed into test.

It was all down to a polluted build/test env.  Argh.  My kingdom for a vagrant workflow !
