### ISSUE TITLE
Ubuntu 24.04 repository

### ISSUE THREAD

**Issue by kevinfilipe** [NagiosEnterprises/ncpa#1188]
Hi. I can't find the repository for Ubuntu 24.04 [here](https://repo.nagios.com/?repo=deb-ubuntu).

Will it be supported? If so, would it be possible to add it?

Thank you.

**Comment by markbevill811** [comment]
Repo support for Ubuntu 24.04 would be nice. We are currently holding off on deploying 24.04 because of the lack of the NCPA repo. It provides a seamless way for us to make sure that NCPA remains updated across our fleet of machines.

**Comment by ne-bbahn** [comment]
The NCPA Ubuntu 24 repo is in the works. It should be up within the next week or so.

**Comment by ne-bbahn** [comment]
apt-get isn't designed to download packages directly from URLs. When you're putting it as above, it's interpreting that as a package name, which leads to the errors you are seeing. 

I recommend either adding the Nagios repo as can be seen here: https://repo.nagios.com/?repo=deb-ubuntu
or using wget/curl to grab the package from the url and then apt installing the downloaded .deb.

**Comment by iamfasal** [comment]
Hello,

I even tried by downloading the dep package to the server and local install.

```
root@server:/home/shuser# wget https://assets.nagios.com/downloads/ncpa3/ncpa-latest-1.amd64.deb
--2024-10-15 17:55:51--  https://assets.nagios.com/downloads/ncpa3/ncpa-latest-1.amd64.deb
Resolving assets.nagios.com (assets.nagios.com)... 45.79.49.120, 2600:3c00::f03c:92ff:fef7:45ce
Connecting to assets.nagios.com (assets.nagios.com)|45.79.49.120|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 26713364 (25M) [application/vnd.debian.binary-package]
Saving to: ‘ncpa-latest-1.amd64.deb’

ncpa-latest-1.amd64.deb               100%[======================================================================>]  25.48M  6.46MB/s    in 4.1s    

2024-10-15 17:55:56 (6.18 MB/s) - ‘ncpa-latest-1.amd64.deb’ saved [26713364/26713364]

root@server:/home/shuser# apt install ncpa-latest-1.amd64.deb 
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package ncpa-latest-1.amd64.deb
E: Couldn't find any package by glob 'ncpa-latest-1.amd64.deb'
root@server:/home/shuser# 
```

I also don't see any repository for Ubuntu 24.04 in https://repo.nagios.com/?repo=deb-ubuntu

**Comment by ne-bbahn** [comment]
> root@server:/home/shuser# apt install ncpa-latest-1.amd64.deb 

This is checking against your repos for a package called ncpa-latest-1.amd64.deb. You need to do `apt install ./ncpa-latest-1.amd64.deb` if you're in the folder with the ncpa deb as the ./ indicates the current folder and should be whatever path points to the .deb.

> I also don't see any repository for Ubuntu 24.04 in https://repo.nagios.com/?repo=deb-ubuntu

I was told that this was up. I'll check with the guys in charge of the repo.

**Comment by ne-bbahn** [comment]
After testing the repo, it definitely isn't working for Ubuntu 24. I'll reopen this until they fix it.

**Comment by chiefthunderpants** [comment]
Anything on this?  I have been looking to deploy but would prefer direct repo rather than a manual deployment.

**Comment by ne-bbahn** [comment]
The repo has been updated.

**Comment by yohay-h** [comment]
@ne-bbahn sorry to bring this up again, 
but as far as I can tell - Ubuntu 24.04 still seems to be missing from https://repo.nagios.com/?repo=deb-ubuntu

Any idea why / when will it be updated?

**Comment by ne-bbahn** [comment]
We have a repo up for 24.04 and the commands listed on the page will work for installing NCPA on Ubuntu 24.04, we just forgot to update the website listing the repo. We will also be adding a repo for 24.10, though we don't officially support non-LTS versions of Ubuntu. I talked with those in charge of the Nagios repo website and they'll be updating the website shortly.

**Comment by yohay-h** [comment]
Thanks for the update @ne-bbahn 👍 

I can confirm that ubuntu 24.04 now appears on https://repo.nagios.com/?repo=deb-ubuntu, 
and it's great to see that you've updated the "installation instructions" commands section for importing the repo based on `gpg --dearmour` , rather than the deprecated `apt-key add`.

However, this doesn't seem to be working...

Following your instructions  

```
# Create folder to place the GPG key
sudo mkdir -m 0755 -p /etc/apt/keyrings/

# Add the GPG key
curl -fsSL https://repo.nagios.com/GPG-KEY-NAGIOS-V3    | sudo gpg --dearmor -o /etc/apt/keyrings/GPG-KEY-NAGIOS-V3.gpg

# Add the repository with the our GPG key
echo "Types: deb
URIs: https://repo.nagios.com/deb/$(lsb_release -cs)
Suites: /
Signed-By: /etc/apt/keyrings/GPG-KEY-NAGIOS-V3.gpg"    | sudo tee /etc/apt/sources.list.d/nagios.sources > /dev/null

# Update your repositories
sudo apt-get update
```

we're getting: 

```
Hit:1 http://security.ubuntu.com/ubuntu noble-security InRelease
Hit:2 http://archive.ubuntu.com/ubuntu noble InRelease
Hit:3 http://archive.ubuntu.com/ubuntu noble-updates InRelease
Hit:4 http://archive.ubuntu.com/ubuntu noble-backports InRelease
Get:5 https://repo.nagios.com/deb/noble  InRelease [1775 B]
Reading package lists... Done
E: Unable to parse package file  (1)
E: The repository 'https://repo.nagios.com/deb/noble  InRelease' provides only weak security information.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

Trying to look this up online, other users seem to be affected by the same issue:
https://support.nagios.com/forum/viewtopic.php?p=361364

Could you please have your team look into it?

**Comment by ne-bbahn** [comment]
> Thanks for the update [@ne-bbahn](https://github.com/ne-bbahn) 👍
> 
> I can confirm that ubuntu 24.04 now appears on https://repo.nagios.com/?repo=deb-ubuntu, and it's great to see that you've updated the "installation instructions" commands section for importing the repo based on `gpg --dearmour` , rather than the deprecated `apt-key add`.
> 
> However, this doesn't seem to be working...
> 
> Following your instructions
> 
> ```
> # Create folder to place the GPG key
> sudo mkdir -m 0755 -p /etc/apt/keyrings/
> 
> # Add the GPG key
> curl -fsSL https://repo.nagios.com/GPG-KEY-NAGIOS-V3    | sudo gpg --dearmor -o /etc/apt/keyrings/GPG-KEY-NAGIOS-V3.gpg
> 
> # Add the repository with the our GPG key
> echo "Types: deb
> URIs: https://repo.nagios.com/deb/$(lsb_release -cs)
> Suites: /
> Signed-By: /etc/apt/keyrings/GPG-KEY-NAGIOS-V3.gpg"    | sudo tee /etc/apt/sources.list.d/nagios.sources > /dev/null
> 
> # Update your repositories
> sudo apt-get update
> ```
> 
> we're getting:
> 
> ```
> Hit:1 http://security.ubuntu.com/ubuntu noble-security InRelease
> Hit:2 http://archive.ubuntu.com/ubuntu noble InRelease
> Hit:3 http://archive.ubuntu.com/ubuntu noble-updates InRelease
> Hit:4 http://archive.ubuntu.com/ubuntu noble-backports InRelease
> Get:5 https://repo.nagios.com/deb/noble  InRelease [1775 B]
> Reading package lists... Done
> E: Unable to parse package file  (1)
> E: The repository 'https://repo.nagios.com/deb/noble  InRelease' provides only weak security information.
> N: Updating from such a repository can't be done securely, and is therefore disabled by default.
> N: See apt-secure(8) manpage for repository creation and user configuration details.
> ```
> 
> Trying to look this up online, other users seem to be affected by the same issue: https://support.nagios.com/forum/viewtopic.php?p=361364
> 
> Could you please have your team look into it?

Sorry about this. It seems our release techs forgot to sign the package before going on vacation... we have since got someone in to fix it and everything will be working now.
