### ISSUE TITLE
psutil sdiskparts has no 'maxfile' on Windows

### ISSUE THREAD

**Issue by ne-bbahn** [NagiosEnterprises/ncpa#1191]
It seems that the psutil sdiskparts has no `maxfile` on Windows, causing an error to be dumped into the error log and the API to display an error in the field `max_file_length`.

> 2024-08-08 08:37:48,055 listener ERROR 'sdiskpart' object has no attribute 'maxfile'
> Traceback (most recent call last):
>   File "listener\nodes.py", line 210, in walk
> TypeError: make_mountpoint_nodes.<locals>.<lambda>() got an unexpected keyword argument 'debug'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "listener\nodes.py", line 67, in walk
>   File "listener\nodes.py", line 212, in walk
>   File "listener\psapi.py", line 96, in <lambda>
> AttributeError: 'sdiskpart' object has no attribute 'maxfile'
> 2024-08-08 08:37:48,055 listener ERROR 'sdiskpart' object has no attribute 'maxpath'
> Traceback (most recent call last):
>   File "listener\nodes.py", line 210, in walk
> TypeError: make_mountpoint_nodes.<locals>.<lambda>() got an unexpected keyword argument 'debug'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "listener\nodes.py", line 67, in walk
>   File "listener\nodes.py", line 212, in walk
>   File "listener\psapi.py", line 99, in <lambda>
> AttributeError: 'sdiskpart' object has no attribute 'maxpath'
> 2024-08-08 08:37:48,058 listener ERROR 'sdiskpart' object has no attribute 'maxfile'
> Traceback (most recent call last):
>   File "listener\nodes.py", line 210, in walk
> TypeError: make_mountpoint_nodes.<locals>.<lambda>() got an unexpected keyword argument 'debug'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "listener\nodes.py", line 67, in walk
>   File "listener\nodes.py", line 212, in walk
>   File "listener\psapi.py", line 96, in <lambda>
> AttributeError: 'sdiskpart' object has no attribute 'maxfile'
> 2024-08-08 08:37:48,058 listener ERROR 'sdiskpart' object has no attribute 'maxpath'
> Traceback (most recent call last):
>   File "listener\nodes.py", line 210, in walk
> TypeError: make_mountpoint_nodes.<locals>.<lambda>() got an unexpected keyword argument 'debug'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "listener\nodes.py", line 67, in walk
>   File "listener\nodes.py", line 212, in walk
>   File "listener\psapi.py", line 99, in <lambda>
> AttributeError: 'sdiskpart' object has no attribute 'maxpath'

**Comment by MrPippin66** [comment]
FYI, The linux field for this was also removed for performance reasons in recent version of psutils, so this may need to be accounted for there as well.

https://github.com/giampaolo/psutil/pull/2405
