### ISSUE TITLE
Pulling process metrics

### ISSUE THREAD

**Issue by krobertson71** [NagiosEnterprises/ncpa#120]
Is there not  a way to pull the memory usage of the process?  Would like to monitor how much memory , or cpu, is being used by a certain process.  I have tried and tried but I think I am either missing something or we are not able to pull that level with the nagios check_ncpa plugin yet?

example.. I wand a critical alert if mem_vms goes over 21000000.

{
  "value": {
    "processes": [
      {
        "mem_vms": 1962639360, 
        "exe": "/opt/local/sas/sas93/SASHome/SASFoundation/9.3/sasexe/sas", 
        "mem_rss": 972181504, 
        "name": "sas", 
        "cpu_percent": 49.0
      },

**Comment by scot0357** [comment]
I just took a look, looks like it only pulls it and can only report on the count of the process unfortunately.

However, that data is _right_ there, I'm gonna mark this as a feature request for 1.9.0, but I would like to ask your input for how asking for this information would make sense. As in, what makes sense to fill in for check_ncpa.py to get this information? Seems to me something like

```/api/processes/?name=System&check=1&property=mem_vms&warning=1&unit=G```

Would check the mem_vms of the System process to make a warning if it was taking more than 1G of memory.  This would equate to the following in check_ncpa.py

```check_ncpa.py -H <host> -t <token> -M /api/processes -q property=mem_vms,name=System --unit G --warning 1```

That would be how it would work with the current `check_ncpa.py`. But I'm open for suggestion of how to access the data, even if that means new ways of using check_ncpa.py to access that data.

**Comment by krobertson71** [comment]
When you say 'current ncpa' are you talking with what ships with Nagios XI or the current .3.1 version available on github.  I think you you have for the api makes sense and flows well.
