### ISSUE TITLE
XSS Vulnerability in NCPA 2.4.0

### ISSUE THREAD

**Issue by aaronjcolclough** [NagiosEnterprises/ncpa#1203]
Who can i talk to about a cross-site scripting vulnerability I've discovered in NCPA 2.4.0? Is there an email address i can send information to?

**Comment by ne-bbahn** [comment]
Hello @aaronjcolclough,

You can send this vulnerability to security@nagios.com. Note that there have been a number of security updates and fixes since NCPA 2.4.0 and this may not exist on more recent versions of NCPA.
