### ISSUE TITLE
NCPA error on Nagios Core

### ISSUE THREAD

**Issue by GolfTitan1** [NagiosEnterprises/ncpa#1211]
NCPA works fine from command line.

Nagios runs fine on all other checks for services.
Only NCPA checks are erroring out.

Errors on Nagios Core interface on checks.
(No output on stdout) stderr: /bin/sh: 1: Syntax error: Unterminated quoted string

**Comment by GolfTitan1** [comment]
# Aaron Added me! NCPA
define command {
    command_name    check_ncpa
    command_line    $USER1$/check_ncpa.py -H $HOSTADDRESS$ $ARG1$
}

**Comment by GolfTitan1** [comment]
Command works from CLI with no issues. 

./check_ncpa.py -H 10.0.0.170 -t 'Password!' -M 'system/uptime' --warning 3456000 --critical 5184000

OK: Uptime was 14 days 20 hours 56 minutes 54 seconds | 'uptime'=1285014.06s;3456000;5184000;

**Comment by GolfTitan1** [comment]
Nagios WebUI Alerts error
![checks](https://github.com/user-attachments/assets/dc05dfa6-0ee6-4e57-97cb-c6265f8a5b85)

**Comment by ne-bbahn** [comment]
Your shell might be interpreting the `!` character as a special character. Have you tried escaping the ! with a `\`? (`-t 'Password\!'`)

**Comment by MrPippin66** [comment]
What's the command definition for one of the service checks?

**Comment by GolfTitan1** [comment]
#NCPA Checks
define command {
    command_name    check_ncpa
    command_line    $USER1$/check_ncpa.py -H $HOSTADDRESS$ $ARG1$
}

Contents for Command.cfg

**Comment by GolfTitan1** [comment]
Figured it out!
Need to run the following on Ubuntu for Python connection from older versions.
**sudo apt install 2to3 python-is-python3**

**Comment by GolfTitan1** [comment]
Fixed!
