### ISSUE TITLE
builds at newer CentOS

### ISSUE THREAD

**Issue by btrnka63** [NagiosEnterprises/ncpa#1219]
Hello, in BUILDING.rst you recommend to use CentOS 7 as easiest way to get a working package for all Linux distributions. 
As the CentOS Linux 7 end of life was June 30, 2024, are there any plans to update the building procedures?
Thanks.

**Comment by ne-bbahn** [comment]
I need to go back and remove/update that. Currently you can build NCPA on the listed available distributions and those builds should work on newer OSs than that in which NCPA was built.
i.e. NCPA built on Ubuntu 20 will work on Ubuntu 22, but NCPA built on Ubuntu 22 will not work on Ubuntu 20.

**Comment by ne-bbahn** [comment]
Updated
