### ISSUE TITLE
ncpa v3.1.1 for Windows: error during upgrade

### ISSUE THREAD

**Issue by vtracnagios** [NagiosEnterprises/ncpa#1222]
A client is attempting to upgrade Windows NCPA agent from 3.1.0 to 3.1.1 and I get the following error:

![image](https://github.com/user-attachments/assets/2bae5f51-ce5e-4309-b9ed-6311620bb9cb)

Here are the client's finding and resolutions:

_"I did some troubleshooting and I believe I found a bug with the upgrade & uninstall. When I do an upgrade or a reinstall from the old agent (3.0.0) to the new one (3.1.1), all the running processes that uses the DLL, servicemananger.pyd will stop for the ncpa processes. But the svchost.exe also has a lock on the file, which doesn't stop. This is preventing the file to be upgrade or uninstalled. Both the upgrade and reinstall will run without errors. But the old file doesn't get replace which will cause the service not to start.

If I manually kill the process svchost.exe that has the lock on the DLL first, I can successfully upgrade and reinstall the the new agent successfully."_

Ticket: 11696
https://nagiosenterprises.lightning.force.com/lightning/r/Case/500Vm00000FaDe6IAF/view

**Comment by ne-bbahn** [comment]
This item has been moved to the internal documentation.
