### ISSUE TITLE
Suggestion for Windows installer Configuration Screen

### ISSUE THREAD

**Issue by box293** [NagiosEnterprises/ncpa#133]
![ncpa_parameters](https://cloud.githubusercontent.com/assets/8356113/5749633/bf3b71fe-9c9e-11e4-8259-9ffb7a87287f.png)

On this screen, it might be a little clearer if the Active and Passive headings had a little more description. Like:

Active Specifications (NCPA)
This setting is to allow remote machines to connect to it to perform active checks.

<br>
Passive Specifications (NRDP)
Configure this machine to send passive check results to a Nagios server.

<br>
Also perhaps an extra line feed / horizontal line that seperates the two sections. To a newbie it looks like all settings may be required.

**Comment by varnar** [comment]
Also, it will be nice to have SSL setting in screen and also way to provide in command line, like we do it for token

Thanks

**Comment by scot0357** [comment]
Good ideas guys. These would definitely make a good addiiton to the Windows installer.

@varnar, I'm not sure what you mean by SSL settings? Which SSL settings?

**Comment by varnar** [comment]
I mean providing which version of SSL to use
Reference: https://github.com/NagiosEnterprises/ncpa/pull/122

**Comment by scot0357** [comment]
@varnar I've add your SSL fix because I was in the area in fix https://github.com/NagiosEnterprises/ncpa/commit/6b2b73ff049a90f2f25e85fb2835a2101a5342c6.

**Comment by varnar** [comment]
Thank you very much

**Comment by jhomann** [comment]
I think it might be easier to pass the settings in 2 pages instead of one. The problem we were having (why there's two bars on one line that makes it look kind of cluttered) is caused by the size of the window that you are allowed to use. If we split the two sections into two separate pages, one for Active settings and one for Passive settings we can not only fit more settings on them but we could easily make some more short descriptions.

**Comment by box293** [comment]
I think that will be better overall, it will make it clearer for sure.

**Comment by jhomann** [comment]
We are getting ready to release 1.8.0 so this will probably not be happening until the next version of NCPA.

**Comment by jhomann** [comment]
In the latest commits I have added more setup features/configuration in the windows installer, including setting up passive checks, listener and passive agent settings, etc.

**Comment by jhomann** [comment]
![image](https://cloud.githubusercontent.com/assets/6423215/16105901/f395c6d6-3354-11e6-85df-80ca244ffbaa.png)
![image](https://cloud.githubusercontent.com/assets/6423215/16105908/002d7ef2-3355-11e6-9334-173fefd6da84.png)
![image](https://cloud.githubusercontent.com/assets/6423215/16105917/09b91594-3355-11e6-8883-ffbcd0d2b80a.png)
