### ISSUE TITLE
NCPA 1.7.2 documentation is missing conf file directory for log level

### ISSUE THREAD

**Issue by krobertson71** [NagiosEnterprises/ncpa#136]
Here is the current config for 1.7.2.  just listing the [Listener] section as same for passive:

[listener]
uid = nagios
certificate = adhoc
loglevel = debug
ip = 0.0.0.0
gid = nagcmd
logfile = var/ncpa_listener.log
port = 5693
pidfile = var/ncpa_listener.pid

Here is the help page.. the loglevel directive is not listing in the documentation with options (debug, info,warn,error)

[listener]¶

This section controls NCPA’s active check settings including how you actively connect to this agent to ask it for information. NCPA starts up an HTTP server to handle Nagios requests which makes much of the specification in this section relevant to that server.

ip
    This determines what IP the agent will listen on. By default, it will listen on 0.0.0.0, which means it will listen on all interfaces and all name references. Specify this if you would only like the agent to listen on a specific IP or name.
port
    This specifies the TCP port the NCPA server will bind to.
uid
    Determines which user the NCPA server will run as.
gid
    Determines the group by which the NCPA server will run as.
pidfile
    The named file location where the PID file for the NCPA server will be stored and maintained.
logfile
    The named file location where the log file for the NCPA server will be stored.
certificate
    EXPERIMENTAL. Allows you to specify the file name for the SSL certificate you wish to use with the NCPA server. If left adhoc, a new self-signed certificate will be generated and used for the server.

**Comment by krobertson71** [comment]
If this has already been noticed and corrected in 1.8.0 then I apologize.

**Comment by scot0357** [comment]
It has not, but I did fix it in https://github.com/NagiosEnterprises/ncpa/commit/6b2b73ff049a90f2f25e85fb2835a2101a5342c6.
