### ISSUE TITLE
Service status shows different states depending on how check is triggered

### ISSUE THREAD

**Issue by jm-welch** [NagiosEnterprises/ncpa#137]
Checking the status of a service using wget locally on a system shows a different result than the same service status check run as a passive check or triggered externally.

    [root@server1 var]$ wget -q -O- --no-check-certificate --post-data="token=mytoken" "https://127.0.0.1:5693/api/service?service=entsm&status=running&check=1"
    {
      "value": {
        "returncode": 0, 
        "stdout": "OK: Service entsm is running"
      }
    }

    [root@server1 var]$ # Just in case it's a user permission issue
    [root@server1 var]$ su - nagios

    [nagios@server1 ~]$ wget -q -O- --no-check-certificate --post-data="token=mytoken" "https://127.0.0.1:5693/api/service?service=entsm&status=running&check=1"
    {
      "value": {
        "returncode": 0, 
        "stdout": "OK: Service entsm is running"
      }
    }

We've tried both of the following in ncpa.cfg in the passive checks section:

``` ini
#%HOSTNAME%|entsm = /services?service=entsm&status=running
%HOSTNAME%|entsm = /services --service entsm --status running
```

But the log lines in ncpa_passive.log show the same result either way.
    
**ncpa_passive.log:**

    2015-01-22 15:05:31,947 28064 INFO Running check: /services?service=entsm&status=running
    2015-01-22 15:05:31,947 28064 DEBUG Getting API url for instruction /services?service=entsm&status=running
    2015-01-22 15:05:31,947 28064 DEBUG Determined instruction to be: /services?service=entsm&status=running
    2015-01-22 15:05:31,948 28064 DEBUG Access the API with /api/services/?status=running&check=1&service=entsm
    2015-01-22 15:05:31,948 28064 DEBUG Getting accessor: services/
    2015-01-22 15:05:32,410 28064 DEBUG Handling JSON response: {
      "value": {
        "returncode": 2, 
        "stdout": "CRITICAL: Service entsm is stopped"
      }
    }
    2015-01-22 15:05:32,411 28064 DEBUG JSON response handled found stdout='CRITICAL: Service entsm is stopped', returncode=2

Initially, we thought that it might be due to the service (entsm is notorious for not wanting to share its status with anyone other that its user and root), but we just ran a similar test on a server with ncpa_listener active (the server above is passive-only), and the results hold up there, as well.

Command executed locally from the server:

    [root@server2 plugins]# wget -q -O- --no-check-certificate --post-data="token=mytoken" "https://127.0.0.1:5693/api/services?service=ncpa_listener&status=running&check=true"
    {
      "value": {
        "returncode": 0,
        "stdout": "OK: Service ncpa_listener is running"
      }
    }

Same command executed from the Nagios server:

    [root@nagios ~]# wget -q -O- --no-check-certificate --post-data="token=mytoken" "https://server2:5693/api/services?service=ncpa_listener&status=running&check=1"
    {
      "value": {
        "returncode": 2,
        "stdout": "CRITICAL: Service ncpa_listener is stopped"
      }
    }
    
Any ideas what's going on?

**Comment by krobertson71** [comment]
For the passive command try running it this way:

service?service=netfs&status=stopped&check=true

That works for me on my setup.  Just checking a different service.

**Comment by jm-welch** [comment]
Is `netfs` running on the box you're checking with that line? From the API doc, that check should come back OK if the service is stopped, and Critical if it's running.

And we did check a different service - the second example above uses the ncpa_listener service, which has to be running if Nagios is receiving a response from that server at all, yet the check comes back showing that it's stopped.

**Comment by krobertson71** [comment]
check=true is basically saying -- make sure the status=stopped

Basically you are saying , I want to make sure this isnt running and check if that is true or not.

**Comment by jm-welch** [comment]
Correct. That's what I was asking.

In my scenario, checking to see if a service is stopped will always succeed, for an existing service. The problem I'm having is that even if a service is running (and checking the API locally on the system shows that it is running), the status when I check from another machine or via a passive check is always stopped.

**Comment by krobertson71** [comment]
Sorry yes that service is indeed not running.

Tell me this.. is the ncpa service you are checking on Linux servers?

Check this following list and you will see that ncpa_listener and passive are saying "stopped" even though they are running.  Linux serivces are weird.  It all depends on the app and how it runs whether it registers itself as a service or not.  You will also see a numara service.  That is running but the service says stopped.

I check those by checking for the running process instead.  You might want to try that and see if you get a different result.

{
  "value": {
    "services": {
      "kudzu": "stopped", 
      "lvm2-monitor": "stopped", 
      "vsock": "stopped", 
      "rdisc": "stopped", 
      "ncpa_listener": "stopped", 
      "netfs": "stopped", 
      "single": "stopped", 
      "employeemove": "stopped", 
      "netconsole": "stopped", 
      "gpm": "running", 
      "functions": "stopped", 
      "network": "stopped", 
      "restorecond": "stopped", 
      "iscsi": "running", 
      "messagebus": "stopped", 
      "sendmail": "running", 
      "vmware-tools-services": "stopped", 
      "iscsid": "running", 
      "killall": "stopped", 
      "saslauthd": "stopped", 
      "ntpd": "running", 
      "iptables": "stopped", 
      "rawdevices": "stopped", 
      "halt": "stopped", 
      "vmci": "stopped", 
      "sshd": "running", 
      "netplugd": "stopped", 
      "multipathd": "stopped", 
      "crond": "running", 
      "haldaemon": "stopped", 
      "atd": "running", 
      "ip6tables": "stopped", 
      "syslog": "running", 
      "NumaraFootPrintsAssetCoreAgent": "stopped", 
      "besclient": "stopped", 
      "vmmemctl": "running", 
      "nscd": "stopped", 
      "mcstrans": "stopped", 
      "ncpa_passive": "stopped"
    }
  }
}

**Comment by jm-welch** [comment]
That's what I see on the local machine, as well. The difference here is that if I query the API from the local machine's command line for a specific service, I get a status of running for `ncpa_listener`. If I run the exact same query from an external machine, or try to put that query in a passive check, I get a status of stopped for the same service.

These two commands are executed locally on the server. In the services list, `ncpa_listener` shows as stopped, but if I query that service directly, I get a running status.

```
[root@server2 ~]# wget -q -O- --no-check-certificate --post-data="token=mytoken" "https://127.0.0.1:5693/api/services"                         {
  "value": {
    "services": {
      "spice-vdagentd": "stopped",
      "rpcbind": "running",
      "lvm2-lvmetad": "stopped",
      "lvm2-monitor": "stopped",
      "wpa_supplicant": "stopped",
      "auditd": "running",
      "ncpa_listener": "stopped",
      "udev-post": "stopped",
      "nfslock": "stopped",
      "single": "stopped",
      "blk-availability": "stopped",
      "rsyslog": "running",
      "firstboot": "stopped",
      "netconsole": "stopped",
      "rpcidmapd": "stopped",
      "restorecond": "running",
      "functions": "stopped",
      "rpcsvcgssd": "stopped",
      "network": "stopped",
      "ntpdate": "stopped",
      "messagebus": "stopped",
      "rhsmcertd": "running",
      "killall": "stopped",
      "NetworkManager": "stopped",
      "rhnsd": "running",
      "saslauthd": "stopped",
      "ntpd": "stopped",
      "iptables": "stopped",
      "mdmonitor": "stopped",
      "sssd": "running",
      "winbind": "stopped",
      "rdisc": "stopped",
      "certmonger": "stopped",
      "oddjobd": "running",
      "crond": "running",
      "haldaemon": "stopped",
      "wdaemon": "stopped",
      "sshd": "running",
      "dnsmasq": "stopped",
      "ip6tables": "stopped",
      "netfs": "stopped",
      "postfix": "running",
      "nrpe": "stopped",
      "halt": "stopped",
      "osad": "stopped",
      "sandbox": "stopped",
      "nfs": "stopped",
      "autofs": "running",
      "swlem-agent": "stopped",
      "rpcgssd": "stopped",
      "ncpa_passive": "stopped"
    }
  }
}

[root@server2 ~]# wget -q -O- --no-check-certificate --post-data="token=mytoken" "https://127.0.0.1:5693/api/services?service=ncpa_listener&status=running&check=true"
{
  "value": {
    "returncode": 0,
    "stdout": "OK: Service ncpa_listener is running"
  }
}
```

This is the result of the same command run from my Nagios server. The only difference here is the server address in the API URL:

```
[root@nagios ~]# wget -q -O- --no-check-certificate --post-data="token=mytoken" "https://server2:5693/api/services?service=ncpa_listener&status=running&check=true"
{
  "value": {
    "returncode": 2,
    "stdout": "CRITICAL: Service ncpa_listener is stopped"
  }
}
```

If it just didn't work, I'd understand. My question is, why is the API query showing one result from the local command line, but a different result from a remote system?

**Comment by jm-welch** [comment]
Regarding some of the other questions:

> Tell me this.. is the ncpa service you are checking on Linux servers?

Yes. This is a RHEL 6.5 box.

> Linux serivces are weird. It all depends on the app and how it runs whether it registers itself as a service or not.

```
[root@server2 ~]# service ncpa_listener status
Process running with PID 10826
[root@server2 ~]# chkconfig --list ncpa_listener
ncpa_listener   0:off   1:off   2:on    3:on    4:on    5:on    6:off
```

Unless I'm mistaken (and I'm prepared to be) that means it's registered as a service.

> I check those by checking for the running process instead.

I just read over #135, and I'm seeing the same behavior. I can check to see if the process is there, but can't seem to write a check that will properly warn or critical if a process drops below a specific number (only if it goes over).

```
[root@server2 ~]# wget -q -O- --no-check-certificate --post-data="token=mytoken" "https://127.0.0.1:5693/api/processes?name=ncpa_posix_listene&check=true&warning=1"
{
  "value": {
    "returncode": 0,
    "stdout": "OK: Process count for processes named ncpa_posix_listener was 1c | 'process_count_0'=1c;1;;"
  }
}
[root@server2 ~]# wget -q -O- --no-check-certificate --post-data="token=mytoken" "https://127.0.0.1:5693/api/processes?name=foobar&check=true&warning=1"
{
  "value": {
    "returncode": 0,
    "stdout": "OK: Process count for processes named nyourmom was 0c | 'process_count_0'=0c;1;;"
  }
}
```

**Comment by krobertson71** [comment]
You have to use c1:  

This means must be a minimum of 1.

Here is the table from the plugin dev guide. How I got around that same issue with process checks.
Here is the link if the below paste does not show up well for you:

https://nagios-plugins.org/doc/guidelines.html

Go to Table 4 in that document.

---------------------------------------------------------
Table 4. Command line examples

Command line
	

Meaning
check_stuff -w10 -c20	Critical if "stuff" is over 20, else warn if over 10 (will be critical if "stuff" is less than 0)
check_stuff -w~:10 -c~:20	Same as above. Negative "stuff" is OK
check_stuff -w10: -c20	Critical if "stuff" is over 20, else warn if "stuff" is below 10 (will be critical if "stuff" is less than 0)
check_stuff -c1:	Critical if "stuff" is less than 1
check_stuff -w~:0 -c10	Critical if "stuff" is above 10; Warn if "stuff" is above zero (will be critical if "stuff" is less than 0)
check_stuff -c5:6	Critical if "stuff" is less than 5 or more than 6
check_stuff -c@10:20	OK if stuff is less than 10 or higher than 20, otherwise critical

**Comment by jm-welch** [comment]
That'll work for process checking, but I'm still curious about the service check showing different results locally vs externally.

**Comment by daVikes** [comment]
I seem to be having the same issue.

api/services?service=vmware-tools&status=running&check=true

service vmware-tools status
vmtoolsd is running

**Comment by jhomann** [comment]
With this new version I cannot seem to get this to happen. I will close this for now since psutil and some of the service checking backend has been changed and should, hopefully, be more stable and accurate.
