### ISSUE TITLE
Successful MSSQL service check triggers Critical in Nagios Core 3.5.1

### ISSUE THREAD

**Issue by sgcardinal** [NagiosEnterprises/ncpa#138]
We're using RHEL 6 and have installed Nagios from the EPEL repo, which is 3.5.1. Have installed NCPA 1.7.2 on Windows 2008 R2 and installed check_ncpa.py v0.3.1 on linux. I created a number of service checks between the Linux and Windows hosts to verify services are running. For most of my service checks it responds correctly using the deprecated syntax:

define command{
     command_name    check_ncpa_service
     command_line    $USER1$/check_ncpa.py -H $HOSTADDRESS$ -t mytoken -P 5555 -M $ARG1$
        }
define service{
     use                     generic-service
     host_name               MYSERV
     service_description     IIS
     check_command           check_ncpa_service!'service/W3SVC/running'
     normal_check_interval   5
     retry_check_interval    1
     }

With my MSSQL instance (MSSQL$TEST), the message is: Service MSSQL$TEST is running, but Nagios is flagging it as critical. Running from command-line and testing the return code (echo $?) suggests the script is working ok, but maybe the output containing the $ is throwing Nagios off?

./check_ncpa.py -H MYSERV -t mytoken -P 5555 -M 'service/MSSQL$TEST/running/'
OK: Service MSSQL$DDESB is running

So, as near as I can tell, something in the output from the script to Nagios is confusing the system.

Any suggestions on how to troubleshoot this? My python mojo is weak - I'm more a sysadmin than a developer.

Thanks!

**Comment by scottwilkerson** [comment]
The $ is going to be the gotcha:
http://support.nagios.com/wiki/index.php/Nagios_XI:FAQs#Problems_with_.24_Signs_in_the_Check_Command

Does your $ARG1$ have
'service/MSSQL$TEST/running/'
or
service/MSSQL$TEST/running/
??

**Comment by sgcardinal** [comment]
I started with this:

define service{
        use                     generic-service
        host_name              MYSERV
        service_description     SQL
        check_command           check_ncpa_service!'service/MSSQL$TEST/running/'
        normal_check_interval   5
        retry_check_interval    1
        }

If I remove the single quotes or if I add an additional pair:
check_command           check_ncpa_service!service/MSSQL$TEST/running/
or
check_command           check_ncpa_service!''service/MSSQL$TEST/running/''

Nagios shows:
CRITICAL: Service MSSQL was not found 

Suggesting if I use anything but single quotes it subsitutes the $ before sending to check_ncpa.py
With the single quotes it appears to get handed to check_ncpa.py properly, but the return message from check_ncpa.py, which contains the $ seems to throw off Nagios in reporting what type of return it got. The Nagios console shows:

CRITICAL: Service MSSQL$TEST is running 

I'm only guessing that the $ is the issue, but is there a way for check_ncpa.py to quote the return message in some way?

**Comment by sgcardinal** [comment]
I did just try adding the \\ double-escape with and without the single quotes with no change to the result. Still gives a successful message but a critical status.

**Comment by dhaselhorst** [comment]
It doesn't appear to be resolved just yet so I figured I would help out the next person looking for an answer that ends up here. Configure the service as you normally would, but edit the service so the check command follows the format below. It is important to note this does not follow standard Nagios in how to escape a dollar character as it only has one slash. In addition, make sure you change the single quotes to double quotes.   
Example: "service/MSSQL\$$VEEAM/running"
