### ISSUE TITLE
NCPA installation issue on a set of Windows 2008 r2 64 bit servers

### ISSUE THREAD

**Issue by krobertson71** [NagiosEnterprises/ncpa#141]
This is a weird one as we have other Windows 2008 r2 64 bit servers and NCPA installs just fine.

But we have a set of Cognos 10.21 servers where the agent install runs normally, exits normally, but no directory/services/processes are created after. It is like it didn't even happen.

Is there anything you can think of that can be going on that could either be blocking the install (event though the install runs normally) or removing it immediately after?

It is no showing up in Control Panel - Programs either. It is throwing errors in the Application log. When researching the error it is related to the Microsoft C++ redistributable package

I posted this as well on the Nagios forums and basically sent me here.  

Just FYI Symantec Anti-Virus is running on these set of servers as well, but it runs on all our Windows servers.

Really at a loss here and we need to get this looked at.

Here is the error I found in the Application log on the server.

----------------------------------------------------------------------------------------

Log Name:      Application
Source:        SideBySide
Date:          2/3/2015 1:07:20 PM
Event ID:      33
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      cgn1021cv01.dcri.int
Description:
Activation context generation failed for "C:\Program Files (x86)\Nagios\NCPA\ncpa_passive.exe". Dependent Assembly Microsoft.VC90.CRT,processorArchitecture="x86",publicKeyToken="1fc8b3b9a1e18e3b",type="win32",version="9.0.21022.8" could not be found. Please use sxstrace.exe for detailed diagnosis.
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="SideBySide" />
    <EventID Qualifiers="49409">33</EventID>
    <Level>2</Level>
    <Task>0</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2015-02-03T18:07:20.000000000Z" />
    <EventRecordID>3402</EventRecordID>
    <Channel>Application</Channel>
    <Computer>cgn1021cv01.dcri.int</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Microsoft.VC90.CRT,processorArchitecture="x86",publicKeyToken="1fc8b3b9a1e18e3b",type="win32",version="9.0.21022.8"</Data>
    <Data>
    </Data>

**Comment by scot0357** [comment]
Googling `Microsoft.VC90.CRT,processorArchitecture="x86",publicKeyToken="1fc8b3b9a1e18e3b",type="win32",version="9.0.21022.8" could not be found.` leads me to https://msdn.microsoft.com/en-us/library/ms235299.aspx which I'm assuming you've already found. I'm assuming this same version on VC is running on other Windows servers as you seem too smart for that, but is something worth noting. I have never ever seen this before and do not have Cognos available to me. However, if Cognos is an antivirus worth it's salt it better have a log that is logging any rejections it is making.

```
System log: Cognos_BI_install_path/logs/cogserver.log
AIX or Linux: /opt/IBM/CognosBI/logs/cogserver.log
Windows: C:\Program Files\IBM\Cognos\logs\cogserver.log
```

Are these showing any rejections when you try to install?

**Comment by krobertson71** [comment]
Cognos BI.  Finally took a shot while working with the Windows admin and we installed Visual C++ 2008 SP1 Redistributable Package (x86).  This corrected the issue. 

Turns out the server was not built using the standard template.
