### ISSUE TITLE
Eventlog Monitoring with NCPA

### ISSUE THREAD

**Issue by cydo67** [NagiosEnterprises/ncpa#143]
I see that NCPA can monitor eventlogs but I cannot figure out the required fields.  Anyone provide an example of using NCPA for eventlog monitoring?  Thanks.

**Comment by jhomann** [comment]
This section will be documented better soon (hopefully before I finish releasing 1.8.0) but you can do it as follows:

https://localhost:5693/api/logs/?name=System
https://localhost:5693/api/logs/?name=Security

You can have both at the same time:

https://localhost:5693/api/logs/?name=System&name=Security

Specifying the application:

https://localhost:5693/api/logs/?name=System&application=Service%20Control%20Manager

That actually works for any fields that are in the rendered JSON:

https://localhost:5693/api/logs/?name=System&application=Service%20Control%20Manager&category=0
