### ISSUE TITLE
NCPA not refreshing storage nodes after startup.

### ISSUE THREAD

**Issue by uptoisomorphism** [NagiosEnterprises/ncpa#146]
Recently we ran in to an issue with NCPA while monitoring a MSSQL cluster. The way this is configured, there is an active and a passive node. When the active goes down, the DB storage drives are hotswapped to the passive node. During the last fail over, we noticed that NCPA did not recognize the new drives after they were added.

A simpler example of this would be to start NCPA on a desktop machine, and then plug in a removable drive and check the /api/disk page. The removable drive does not get listed here until NCPA is restarted. Similarly, after a restart of the service, and ejecting the drive NCPA still checks this drive and errors out:
>"E:|": {
>"total_size": "Error retrieving child: \"[Errno 2] No such file or directory: 'E:\\\\'\"", 
>"used_percent": "Error retrieving child: \"[Errno 2] No such file or directory: 'E:\\\\'\"", 
>"used": "Error retrieving child: \"[Errno 2] No such file or directory: 'E:\\\\'\"", 
>"free": "Error retrieving child: \"[Errno 2] No such file or directory: 'E:\\\\'\"", 
...
> },

I'm not sure if NCPA is caching a list of drives to check at service start, but it would be great if NCPA could be a little more flexible/dynamic with respect to hardware changes.

**Comment by scot0357** [comment]
Yes, after looking at it, NCPA is generating those nodes on startup and only on startup. I think something like rechecking every minute and then rehupping itself would solve the problem and probably be the best solution.

**Comment by jhomann** [comment]
From what I can tell the global "root" node is not re-created each time the API is called, however I am wondering whether or not there is actually a performance decrease on running the creation of the root node each time the API is called. Unless there is a way to update just a specific section, this might be more annoying than anything. I don't really see why we would want to wait a minute for it to do that, however I could definitely default it to a set amount of time and then give the option of just setting it to 0 and would just re-update itself every call.

**Comment by jhomann** [comment]
I'm actually really struggling with understanding why this isn't created each time the API is called, from my testing it seems almost insignificant to create the API object each time it's called.

**Comment by jhomann** [comment]
I've added this with fec611e6f8da40bc4a06d0de9ecf26c4c16ec748
