### ISSUE TITLE
New Version NCPA

### ISSUE THREAD

**Issue by varnar** [NagiosEnterprises/ncpa#150]
Hello

ANY UPDATE ABOUT NEW VERSION of NCPA - 1.8 or 1.9

THANKS

**Comment by vAndrewJ** [comment]
Yeah, I've been wondering about 1.8 as well.

**Comment by krobertson71** [comment]
Why is that a deal breaker??  I just monitor the processes. Sometimes it all depends on how the installer registers with Linux.

**Comment by vAndrewJ** [comment]
Well, when managers saw that 1.7.2 was not capable of correctly monitoring servers, they called NOGO on move to production. We have fairly strict QA procedures, even for mgmt layers and they want to see the next version.

**Comment by jhomann** [comment]
I'm going to be building a new version of NCPA today/tomorrow. This version will be 1.8.0 and will address issues seen on github.
