### ISSUE TITLE
NCPA 1.7.2 Mac OS X install.sh Bug

### ISSUE THREAD

**Issue by ssaxnagios** [NagiosEnterprises/ncpa#155]
In the NCPA 1.7.2 Mac OS X install.sh on line 11 it is checking if the group exists when it should be checking if the user exists.

Change (Line 11):
if ! dscl . -read /Groups/${groupname} > /dev/null;

To:
if ! dscl . -read /Groups/${username} > /dev/null;

**Comment by jhomann** [comment]
This was already fixed in #61 and been applied in 1.8.0 - but the Mac OS X build hasn't been done yet.
