### ISSUE TITLE
MacOSX NCPA 1.7.2: Not recognizing plugins

### ISSUE THREAD

**Issue by fermatcapital** [NagiosEnterprises/ncpa#156]
On a MacOSX Yosemite OS, My NCPA server does not recognize plugins. I have setup NCPA 1.7.2 running on CentOS and the plugins are listed in the web API interface, so I feel I understand how to install the plugins. Also, I have worked on support.nagios.com and the folks there have put me through all the rigors of setting up ncpa, and they do not have any other suggestions. So here I am to report this.

Here is a link to the forum regarding my conversations with folks on support.nagios.com:

http://support.nagios.com/forum/viewtopic.php?f=7&t=31957&sid=2934fa98392efa092ded7a00a035eac0

**Comment by fermatcapital** [comment]
Here's a snippet from the log file:
```
2015-03-18 12:37:46,101 96165 DEBUG Initializing WebSocket
2015-03-18 12:37:46,101 96165 DEBUG Validating WebSocket request
2015-03-18 12:37:46,102 96165 DEBUG Getting accessor: 
2015-03-18 12:37:46,110 96165 WARNING Unable to assemble plugins. Does the directory exist? - OSError(2, 'No such file or directory')
2015-03-18 12:37:46,160 96165 INFO 127.0.0.1 - - [2015-03-18 12:37:46] "GET /api/ HTTP/1.1" 200 14998 0.058587
```

**Comment by scot0357** [comment]
Does /usr/local/bin/ncpa/plugins or /usr/local/bin/ncpa/agent/plugins exist?

**Comment by fermatcapital** [comment]
No those (/usr/local/bin/ncpa/plugins or /usr/local/bin/ncpa/agent/plugins) did not. SO I did create those (both). I restarted the listener and the passive services and still get the same error in the log file.

**Comment by fermatcapital** [comment]
@scot0357,  I would like to try to debug and possibly contribute. Are there any explicit build instructions that I can get my hands on?

**Comment by jhomann** [comment]
There isn't too much documentation on the actual build processes yet, however this repo has a script called install-prereqs that has a list of the required packages that need to be installed to be able to build ... if you look at the build script in there also you'll probably be able to get the idea of how it's doing it.

https://github.com/NagiosEnterprises/ncpabuild

**Comment by fermatcapital** [comment]
I got this to work by setting the working directory to /usrlocal/ncpa, which is accomplished by adding the property to the com.nagios.ncpa.listener.plist:

```
	<key>WorkingDirectory</key>
	<string>/usr/local/ncpa</string>
```

So the modified files looks as follows:

```
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN” “http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
    <dict>
        <key>RunAtLoad</key>
        <true/>
        <key>UserName</key>
        <string>nagios</string>
        <key>GroupName</key>
        <string>nagcmd</string>
	<key>WorkingDirectory</key>
	<string>/usr/local/ncpa</string>
        <key>ProgramArguments</key>
        <array>
                <string>/usr/local/ncpa/ncpa_posix_listener</string>
                <string>-n</string>
        </array>
        <key>Label</key>
        <string>com.nagios.ncpa.listener</string>
    </dict>
</plist>
```

And the corresponding com.nagios.ncpa.passive.plist:

```
?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN” “http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
    <dict>
        <key>RunAtLoad</key>
        <true/>
        <key>UserName</key>
        <string>nagios</string>
        <key>GroupName</key>
        <string>nagcmd</string>
        <key>WorkingDirectory</key>
        <string>/usr/local/ncpa</string>
        <key>ProgramArguments</key>
        <array>
                <string>/usr/local/ncpa/ncpa_posix_passive</string>
                <string>-n</string>
        </array>
        <key>Label</key>
        <string>com.nagios.ncpa.passive</string>
    </dict>
</plist>
```

**Comment by fermatcapital** [comment]
Ooops. Perhaps I was premature in applying the property to com.nagios.ncpa.passive.plist. Not that I saw any errors in the logs, but I haven't tested out the passive features of NCPA.

**Comment by fermatcapital** [comment]
I have verified that the WorkingDirectory must also be set for the  com.nagios.ncpa.passive.plist configuration file for the com.nagios.ncpa.passive service.

**Comment by jm-welch** [comment]
I'm seeing this error now on Windows Server 2008 R2.

**Comment by jhomann** [comment]
@jm-welch are you still seeing this issue? I am not certain but it may be a different issue than this if its a problem with windows. I may have a 2008 server to test this on though so I can try it out.

**Comment by jm-welch** [comment]
I am. We've got several systems with this bug at the moment.

**Comment by jhomann** [comment]
I believe there were some changes to paths since 1.8.1 and it is looking like we will need to comb through and figure out what is going on for some of these;

- OS X now tries to write to /var/log and /var/run instead of the same directories in /usr/local/ncpa) which causes NCPA to not run since even running it as a LaunchDaemon it doesn't have permissions (even if you change plist to root)
- Linux is running the passive service from the full path whereas the listener is being ran from a relational path

@lgroschen mentioned he tried testing this ... I am wondering if he was using the master branch and that was why it was working for him.

**Comment by jm-welch** [comment]
Unfortunately, all of the systems I'm seeing this on are in production, and the active checks are the bulk of what I need there. I haven't been able to reproduce it in demo or test to be able to tinker with things.

I'll give it another shot as soon as possible and see what I can do.

**Comment by jhomann** [comment]
Sounds good! I got the OS X version of 2.0 building so I will try and test this on the OS X version so I will figure out what is going on. Thanks for the response though.

**Comment by jhomann** [comment]
It looks like the WorkingDirectory is what helps this issue. It must be an issue with permissions given from LaunchDaemon since if you run the ncpa_posix_listener binary manually from it's location as root the plugins directory also appears. This is most likely why the WorkingDirectory needs to be set. At this time, the directory for NCPA on Mac OS X cannot be changed, so it's safe to hardcode the base path in there for now. We can revisit this later if we want to make the agent relocatable like it is on Linux.
