### ISSUE TITLE
CPU Average result question

### ISSUE THREAD

**Issue by krobertson71** [NagiosEnterprises/ncpa#157]
Is there an way with the api / check_ncpa.py command to get the average of all the cpus combined?

Right now it just delvers the percentage of each individual cpu.

I have tried /api/cpu/percent  api/cpu/percent?total.. etc...

This has become a requirement as Operations teams to not want to get alerted if just 1 out of 12 cpus are above 90%.

Any help here would go a long way!

Thanks!

**Comment by krobertson71** [comment]
Anybody?

**Comment by scot0357** [comment]
For some reason this fell out of 1.8.0, it was committed, but I have no idea how it made it into the build nor can I find the commit. I readded here:

https://github.com/NagiosEnterprises/ncpa/tree/add-aggregate

**Comment by krobertson71** [comment]
so this will be in 1.8.0?

Also, can I use the node.py now in 1.7.2 just to test it out?

**Comment by jhomann** [comment]
You could potentially use the node.py in the 1.7.2 version if there aren't any other breaking changes that were made in that. However, it will be in 1.8.0 which will be out next week. Just finishing some things with the windows installer for it before we release.

**Comment by krobertson71** [comment]
awesome!

**Comment by jhomann** [comment]
Confirming this works in the 1.8.0 build I am working on via:

https://localhost:5693/api/cpu/percent?aggregate=avg

**Comment by krobertson71** [comment]
https://localhost:5693/api/cpu/percent?aggregate=avg

Is not working for us.

Fresh install or upgraded install.  Just keep getting all cpu results individually.

**Comment by vAndrewJ** [comment]
Working for me on W2k8 through the API, but I can't get check_ncpa.py to call this avg function.

**Comment by jhomann** [comment]
Looks like it works with windows in 1.8.0 but not in linux. Looking at a way to fix this right now.
