### ISSUE TITLE
Aggregate function not working for cpu/percent?aggregate=avg in 1.8.0

### ISSUE THREAD

**Issue by krobertson71** [NagiosEnterprises/ncpa#161]
https://localhost:5693/api/cpu/percent?aggregate=avg

Is not working for us.

Fresh install or upgraded install. Just keep getting all cpu results individually.

**Comment by jhomann** [comment]
What OS are you installing NCPA on? Also, what version. Are you using the new 1.8.0?

**Comment by krobertson71** [comment]
Redhat el5 and el6.. and Yes we are running 1.8.0.  We have tried this with a fresh install and an upgraded uninstall.

**Comment by krobertson71** [comment]
Also the link for the Windows 1.8 install is not functioning.

**Comment by krobertson71** [comment]
https://hostname:5693/api/cpu/percent?aggregate=avg is working on Windows servers.

I was finally able to test now that dl link is working.

**Comment by jhomann** [comment]
Yeah I fixed the DL link and I'm going to test the aggregation on the el5/el6 versions. Looking at the code, it shouldn't make a difference what OS it's running on but I will look into it.

**Comment by krobertson71** [comment]
I agree.  I couldn't understand it either.

**Comment by krobertson71** [comment]
Fresh install of 1.8.0 RPM

https://xxxxxd02:5693/api/cpu/percent?aggregate=avg - same if you leave off aggregate.  Like it ignores it completely.

  "value": {
    "percent": [
      [
        3.0, 
        2.0, 
        1.0, 
        3.0
      ], 
      "%"
    ]
  }
}

**Comment by jhomann** [comment]
This is fixed. I'm adding it to the 1.8.1 version.

**Comment by vAndrewJ** [comment]
This is working through the API, but the check_ncpa fails when trying to pull the aggregate:

COMMAND: /usr/local/nagios/libexec/check_ncpa.py -H <HOST> -t '<token>' -P 5693 -M cpu/percent?aggregate=avg -w 90 -c 95
OUTPUT: UNKNOWN: Error occurred while running the plugin.

**Comment by kevinjm** [comment]
vAndrewJ,

If you run check_ncpa.py version 0.3.5, you can use the -q QUERYARGS option.  Such as:

COMMAND: /usr/local/nagios/libexec/check_ncpa.py -H host.my.domain -t 'token' -P 5693 -M cpu/percent -q aggregate=avg -w 90 -c 95

At least this appears to have worked for me.

-Kevin

**Comment by daVikes** [comment]
Agree, check your plugin version so its at 0.3.5 otherwise it may not have the -q option.

**Comment by jhomann** [comment]
Can confirm this works in 0.3.5 +
