### ISSUE TITLE
Uptime check error v1.8.0

### ISSUE THREAD

**Issue by uptoisomorphism** [NagiosEnterprises/ncpa#162]
I'm unable to get any information from the new uptime check on a Windows 7 machine. Is this expected?

A call to /api/system/uptime returns an Internal Server Error.

The corresponding line on the /api page is "uptime": "Error retrieving child: 'Invalid format string'",

**Comment by jhomann** [comment]
After taking a look at this I have found a solution and implemented it in our master branch. The fix will be available in 1.8.1 which should be released very soon.
