### ISSUE TITLE
Passive Checks on Linux: Finding Plugin Directory

### ISSUE THREAD

**Issue by cydo67** [NagiosEnterprises/ncpa#163]
I am trying to use the plugins directory on Linux (Centos 6.x 64_bit) but no matter what path I set it seems not to be able to find the plugin directory.  Here is what I keep seeing in debug:

2015-04-07 05:30:30,275 197006 ERROR Encountered exception while trying to read plugin directory: OSError(2, 'No such file or directory')

The path works from the API in the web interface but not from a passive check in ncpa.cfg.  The plugins work from the API in the web interface but not as passive...at least I cannot get them to work.

**Comment by jm-welch** [comment]
Can you post the passive check line you've added to ncpa.cfg? May be something odd there.

**Comment by cydo67** [comment]
Here is an example of the plugin check that works from the API but not passive:

%HOSTNAME%|CPU_Average = /api/agent/plugins/check_cpu_core.sh

**Comment by jm-welch** [comment]
Try it without the /api

    %HOSTNAME%|CPU_Average = /agent/plugins/check_cpu_core.sh

That's how I've got my custom plugins set in passive checks.

**Comment by cydo67** [comment]
Not working, this is 1.8.0 that I am using.  Here are the permissions for the script and the debug info:
-rwxr-xr-x 1 nagios nagcmd 1343 Apr  4 15:29 check_cpu_core.sh


2015-04-07 08:21:28,759 197006 INFO Running check: /agent/plugins/check_cpu_core.sh
2015-04-07 08:21:28,759 197006 DEBUG Getting API url for instruction /agent/plugins/check_cpu_core.sh
2015-04-07 08:21:28,759 197006 DEBUG Determined instruction to be: /agent/plugins/check_cpu_core.sh
2015-04-07 08:21:28,759 197006 DEBUG Access the API with /api/agent/plugins/check_cpu_core.sh/?check=1
2015-04-07 08:21:28,762 197006 DEBUG Handling JSON response: {
  "value": {
    "returncode": 3, 
    "stdout": "Unable to run check on non-child node. Revise your query."
  }

**Comment by fermatcapital** [comment]
The error, "No such file or directory.", that was reported seems to be identical to the issue for MacOSX 1.7.2 plugin problem where the working directory of the daemon was not set in the install directory.

https://github.com/NagiosEnterprises/ncpa/issues/156

I found the problem by running the daemon from command line in the install directory.

**Comment by krobertson71** [comment]
This is strange as we are not having that particular issue on our linux systems.

Are you trying to create this check on the Nagios side or the NCPA agent side?  Where is the check being called from?

**Comment by cydo67** [comment]
This passive check is in the ncpa.cfg on the Linux host not on Nagios.

**Comment by krobertson71** [comment]
Ok cool, was not clear to me but I have not had my coffee yet.

Never tried to use it as a passive check.

**Comment by jhomann** [comment]
I haven't actually looked fulling into this but I can tell you from my dev environment right now that this will not work:

**/api/agent/plugins/check_cpu_core.sh**

Because it needs to be **plugin** not plugins, probably something that will be changing in 2.0.0 (will still be able to use plugin for backwards comparability) but I had to do the same thing with service/process and I think it makes more sense when the actual file is called "plugins" not "plugin"
