### ISSUE TITLE
1.8.1 version

### ISSUE THREAD

**Issue by krobertson71** [NagiosEnterprises/ncpa#164]
J.O. said the aggregate function was being fixed, which is a big deal for us right now.

I understand if other things are being added to it. But, it seemed like it was going to be released quickly.

Is there an ETA?

**Comment by jhomann** [comment]
I will be able to release a 1.8.1 by the end of today if there are no other bugs like this that we need to fix. Unfortunately the other bugs that take more time to test/understand won't get fixed as soon.

**Comment by krobertson71** [comment]
Thank you!

**Comment by jhomann** [comment]
Do you need a windows version or a linux version of 1.8.1 ? I could make you a build for now so I can continue working on some other bug fixes I am finding before we release 1.8.1

**Comment by krobertson71** [comment]
Linux version.  Aggregate for cpu percent works fine on Windows 1.8.0.

Quicker the better for us as we are now waiting on this before doing a bigger mass deployment.

Also, how to you configure the "command line" ./check_ncpa command to include the aggregate and check against it?

I see there is a 0.3.4 varnar edition check_ncpa.  Would I need this?

**Comment by jhomann** [comment]
1.8.1 is out. No you do not need to upgrade your check_ncpa in fact I'd continue using the one you're on for right now (the new one is being tested again)
