### ISSUE TITLE
Russian usernames in api

### ISSUE THREAD

**Issue by ravenich** [NagiosEnterprises/ncpa#165]
Hi, i have troubles with usernames in russian using the user api:
https://localhost:5693/api/user?token=IT
{
  "value": {
    "user": {
      "count": [
        1, 
        ""
      ], 
      "list": [
        [
          "\u0410\u0434\u043c\u0438\u043d\u0438\u0441\u0442\u0440\u0430\u0442\u043e\u0440"
        ], 
        "name"
      ]
    }
  }
}

My active user is "Администратор". OS: Windows Server 2008 SP. NCPA: 1.8.0.

**Comment by jhomann** [comment]
Is everything that is in Russian Unicode numbers like that? Or just the list of usernames?

**Comment by ravenich** [comment]
Usernames in unicode numbers, names of network connections like "". 
By default network connection named "Подключение по локальной сети" in api it looks like:
"interface": {
        "": {
          "packets_sent": [
            50077757, 
            "c"
          ], 
          "dropin": [
            0, 
            "c"
If I change connection name to "LAN" and restart NCPA services, in api it looks good"LAN": {
          "packets_sent": [
            50078925, 
            "c"
          ], 
          "dropin": [
            0, 
            "c"
          ], :

**Comment by jhomann** [comment]
I believed this is fixed in 2.0.0 with the new psutils and gives a value for me so I am going to close this. If someone can test this on their system when 2.0.0 is built please do so!
