### ISSUE TITLE
check_ncpa.py, Version 0.3.4 Varnar Edition - An error occurred:Values instance has no attribute 'query_args'

### ISSUE THREAD

**Issue by ccztux** [NagiosEnterprises/ncpa#167]
Hi!

I have some troubles with the check_ncpa.py check plugin. It always returns:
```
UNKNOWN: Error occurred while running the plugin. Use the verbose flag for more details.
```

Calling the plugin with -v switch returns:
```
An error occurred:Values instance has no attribute 'query_args'
```

This issue doesnt occure with check plugin version:
```
check_ncpa.py, Version 0.3.1
```

Best regards,

ccztux

**Comment by jhomann** [comment]
I've just added a 0.3.5 version into the clients folder in the master branch. The 0.3.4 version wasn't tested as much as I'd like and I have yet to test 0.3.5 but you can go ahead and try it out - basically it looks like it was checking options.query_args and it never existed. Made a few changes to resolve that issue and add in the functionality that was wanted.

**Comment by ccztux** [comment]
Version 0.3.5 seems to work.
Thanks!
