### ISSUE TITLE
NCPA: v1.7.2: Windows ncpa agent put in wrong place uninstall in registry 

### ISSUE THREAD

**Issue by varnar** [NagiosEnterprises/ncpa#169]
I dont know how re-open closed issue, but this one:
https://github.com/NagiosEnterprises/ncpa/issues/66

Is not resolved.

**Comment by varnar** [comment]
-!define UNINST_KEY \
+!define UNINST_KEY HKCU\
   "Software\Microsoft\Windows\CurrentVersion\Uninstall\NCPA"

It must be HKLM

**Comment by jm-welch** [comment]
Is this why it's impossible to uninstall NCPA 1.7.2 on Windows unless you're logged in as the user that installed it?

If this gets changed in 1.8.x, the installer should detect for the old values, so that it can move them to the right locations.

**Comment by varnar** [comment]
Yes
But you can uninstall it from any user that has admin privilege just using manual execution of uninstall.
```
"C:\Program Files (x86)\Nagios\NCPA\uninstall.exe" / /S
```
But version 1.8.1 has not fixed it.

**Comment by jhomann** [comment]
I've committed a fix for this so that it uses HKLM instead for the registry key - it will be in the next release.
