### ISSUE TITLE
NCPA passive dependencies (Question)

### ISSUE THREAD

**Issue by MadeofWood** [NagiosEnterprises/ncpa#173]
Do passive checks require any other plugins like NSCA?

**Comment by mpp4manu** [comment]
I believe that passive checks operate just like NSCA would.  The bottom line is that any check that can be executed on the monitored host can be executed actively or passively.  The NCPA agent just does it in a single agent versus using NRPE and NSCA.

Once you've configured the NCPA agent /usr/local/nagios/ncpa.cfg file, you should see 3 passive checks on your designated Nagios server (I'm using Nagios XI Enterprise).
