### ISSUE TITLE
Porting NCPA to platforms other than Linux and Windows

### ISSUE THREAD

**Issue by mpp4manu** [NagiosEnterprises/ncpa#174]
I am trying to compile (port) the NCPA agent to Solaris 10.  We would like to use a single agent if possible.  Nagios support suggested that because this is primarily Python, there's probably no inherent reason why this can't be done.
I have tried to compile the agent using the build files, which I have modified as needed for the Solaris 10 environment.  I have not been successful as yet.
Is this something I shouldn't even be trying to do?  Do you have any recommendations on how I might be successful with this?
I can tell you that my attempts do produce errors such as the following:
- Cannot find Tcl/Tk libraries ( I can see them on the server and have tried to change the library paths.  It also can't find the curses libraries.  ).
- No ldconfig on the server ( Building a Solaris 10 ldconfig is serious surgery on this platform.  Instead, I used a workaround suggested in an unrelated forum by substituting "crle" for ldconfig.
The build at this point actually compiles most of Python but ultimately hits this fatal error:
  File "/tmp/tmpJVKg0R/pip.zip/pip/_vendor/__init__.py", line 92, in load_module
ImportError: No module named 'pip._vendor.requests'
make: *** [pip] Error 1

I've had to use some chewing gum and baling wire to get this far, but perhaps I'm missing something obvious.  
I realize this build was for Linux primarily, but we have a large number of Solaris (and other) servers, so I thought I would make the effort.
PS: Your graphs are really cool.

**Comment by jhomann** [comment]
We'd like to get it built for as many operating systems as possible if they are compatible with the version of python we are using and are able to be ready by psutil (what looks up most of the system information that is fed into the API) and if those two things happen then it's possible.

I don't have a Solaris box to test this on though, so it hasn't happened. Plus for the time being I am going to be working on making sure that the current base NCPA is more stable and gives proper results.
