### ISSUE TITLE
NCPA CPU Check not graphing at all when using aggregate=avg

### ISSUE THREAD

**Issue by krobertson71** [NagiosEnterprises/ncpa#175]
Is there a way to correct this?  I cannot generate CPU reports nor trending data now.

The default graph is trying to show each CPU but cannot.

Is there a way to refresh the perfdata for CPU so the graphs will display correctly?

**Comment by daVikes** [comment]
I'm seeing this as well.

**Comment by krobertson71** [comment]
I am assuming you had a check in place and then added the -q aggregate=avg after the fact.

You have to remove the rrd and xml file for the CPU check after you add that in. 

You are basically changing the metrics the rrd file is receiving, throwing it into a tailspin.
