### ISSUE TITLE
Units are not used in passive checks

### ISSUE THREAD

**Issue by ludmilmm** [NagiosEnterprises/ncpa#177]
In addition to issue #171, I would like to add another one concerning the use of "-u" (--unit=) flag. 
When I use it with active checks, it works (kind of):
```
/usr/local/nagios/libexec/check_ncpa.py -H <client ip> -t 'mytoken' -P 5693 -M 'disk/logical/C:|/free' -u G -w 50: -c 30:
OK: free was 70Gb | 'free_0'=70Gb;50:;30:;
```
70Gb should be 70GB (issue #171), but this is not my concern at the moment.
When I use the "-u" flag in passive checks:
```
%HOSTNAME%|disk usage free passive = /disk/logical/C:|/free -u G --warning 50: --critical 30:
```
I get the following output:
```
OK: free was 74115067904G
```
This is definitely not correct.

Note: I am using the ":" after the warning and critical thresholds, because without it, I would get a wrong output. In my opinion, the logic should be reversed when checking "free" space (compared to checking "used" space". For example:
This output is correct:
```
/usr/local/nagios/libexec/check_ncpa.py -H <client ip> -t 'mytoken' -P 5693 -M 'disk/logical/C:|/used' -u G -w 400 -c 500
WARNING: used was 415Gb | 'used_0'=415Gb;400;500;
```
but this is not correct (intuitive):
```
/usr/local/nagios/libexec/check_ncpa.py -H <client ip> -t 'mytoken' -P 5693 -M 'disk/logical/C:|/free' -u G -w 100 -c 50
CRITICAL: free was 70Gb | 'free_0'=70Gb;100;50;
```
The state is critical because the 70Gb is higher than the critical threshold. I would expect to see:
Warning: when free space < 100 GB
Critical: when free space < 50 GB

**Comment by jhomann** [comment]
The unit fixes (B instead of b) will be in 1.8.2 the actual thresholds will have to be taken into account later and looked at. They are supposed to adhere exactly to the plugin guidelines for Nagios Core, so I will look into that further in 2.0.0 to make sure they are accurate.
