### ISSUE TITLE
Comment out passive checks in ncpa.cfg included in package

### ISSUE THREAD

**Issue by jm-welch** [NagiosEnterprises/ncpa#182]
I like that there are [examples](/NagiosEnterprises/ncpa/blob/v1.8.1/agent/etc/ncpa.cfg#L44-L46) of passive checks included in the default config file that comes with NCPA, but with the ability to extend the configuration via the `./etc/ncpa.cfg.d/` path, I think it would be better to comment the defaults out, so that folks can leave passive checks on from the get-go and extend via cfg.d without having to touch the core config file (unless they really want to).

This also ensures that extending the configuration via ncpa.cfg.d that will not be overwritten during an upgrade that overwrites ncpa.cfg itself.

**Comment by jhomann** [comment]
As stated in the merge request I would like to double check this works on all OS that we build for just to be safe - then we can add this in.

**Comment by daVikes** [comment]
This is a great idea.  Perhaps move the examples to ./etc/ncpa.cfg.d/examples directory to copy from?  Then there could be some different examples of each type of check.

**Comment by jm-welch** [comment]
That's a good idea, @daVikes. I can withdraw my pull request and resubmit with those changes after I've tested building it, as well.

**Comment by jhomann** [comment]
This has been updated in master. There are examples in the ncpa.cfg.d folder that can be un-commented if someone wants to use them. I also added a __HOST__ to give the actual passive hostname a check so it's not always pending. I have also disabled all passive items by default when you install. You'll have to manually edit your passive settings and restart the passive agent.
