### ISSUE TITLE
ncpa can't monitor zfs filesystems

### ISSUE THREAD

**Issue by dfberger** [NagiosEnterprises/ncpa#184]
I have boxes with zfs filesystems, and while they appear in /proc/mounts, attempting to query them via the NCPA agent fails (they don't appear in the logical disk portion of the API tree).

it looks like this is a limitation in the python psutil package: https://github.com/giampaolo/psutil/issues/534

**Comment by jhomann** [comment]
We should be able to update psutil when it comes out with the fix!

**Comment by jhomann** [comment]
Latest version 2.0.0 will be using psutil 4.1.0 and this should no longer be an issue!
