### ISSUE TITLE
Disable SSL3 in NCPA Listener

### ISSUE THREAD

**Issue by jtromble** [NagiosEnterprises/ncpa#186]
I've seen some of the comments around the issue with SSL3 being related to some of the modules that NCPA leverages.  I was wondering  if there is a way around it.  Is there a reason we cannot make a change to the ssl_patch.py?

I tried to modify the patch (as below) however, it ended up disabling all traffic.  Maybe others have some ideas on how to achieve this?

<pre>
def new_sslwrap(sock, server_side=False, keyfile=None, certfile=None, cert_reqs=__ssl__.CERT_NONE, ssl_version=__ssl__.PROTOCOL_SSLv23, ca_certs=None, ciphers=None):
    #context = __ssl__.SSLContext(ssl_version)
MY HACK -->    context = __ssl__.SSLContext(SSL.SSLv23_METHOD)
MY HACK -->    context.set_options(__ssl__.OP_NO_SSLv2 | __ssl__.OP_NO_SSLv3)
    context.verify_mode = cert_reqs or __ssl__.CERT_NONE

    if ca_certs:
        context.load_verify_locations(ca_certs)
    if certfile:
        context.load_cert_chain(certfile, keyfile)
    if ciphers:
        context.set_ciphers(ciphers)

    caller_self = inspect.currentframe().f_back.f_locals['self']
    return context._wrap_socket(sock, server_side=server_side, ssl_sock=caller_self)

if not hasattr(_ssl, 'sslwrap'):
</pre>

**Comment by jhomann** [comment]
I will look into this here shortly, I'm not sure why this would break anything but I will have to try it myself. Haven't done much with the SSL.

**Comment by jhomann** [comment]
This should be fixed in 2.0.0 and in master already but I can manually specify OP_NO_SSLvX in the certificate contexts. We no longer need the ssl_patch.py with the updated openssl and PyOpenSSL versions.

**Comment by jtromble** [comment]
Thanks for the update!
----
Jay A Trombley, PMP

Office : +1 (802) 458-0814
Mobile : +1 (415) 238.4780
Fax : +1 (802) 329.2064
Email : jay@jaytrombley.net
Skype : jay.trombley
Web : http://www.linkedin.com/in/jaytrombley
