### ISSUE TITLE
CPU/Percent issues

### ISSUE THREAD

**Issue by vAndrewJ** [NagiosEnterprises/ncpa#190]
This is becoming very frustrating for me. 

NagiosXI polling through gearmand to a single vcpu VM with check_ncpa.py v0.3.5

<token> -M cpu/percent -w 90 -c 95 consistent returned crazy high utilization yet direct calls to the api shows next to no utilization.

When looking at the Top Processes UI, I see CPU Load % high, but only the ncpa_posix_listener taking 2-10%, with nothing else going on with the box. 

htop shows the system is essentially running ice cold. No load, or wait, no CPU util.

**Comment by jhomann** [comment]
How many cpus show up on the system being monitored?

**Comment by jhomann** [comment]
I'm closing this since -q aggregate=avg added to the check should return a good value to monitor that will be more stable.
