### ISSUE TITLE
Powershell plugins - does not load modules

### ISSUE THREAD

**Issue by celticguy42** [NagiosEnterprises/ncpa#192]
We have NCPA 1.8.1 running on a Windows 2012 R2 file server that has DFS replication.

NOTE: all PowerShell scripts & commands work fine when logged into the server (either directly or using enter-pssession).  This includes invoking PowerShell using the plugin directive as it is in ncpa.cfg.

ANOTHER NOTE: I have other powershell scripts that run commands such as get-netadapter that work fine via the NCPA API.

I want to monitor the replication status, however, when I attempt to use get-dfsrstate, we get:

"stdout": "get-dfsrstate : The term 'get-dfsrstate' is not recognized as the name of a cmdlet, function, script file, or operable program. [...]"

So I tried loading the DFSR module at the beginning of the script (although it should auto-load) with 'import-module DFSR', and now we get:

"stdout": "import-module : The specified module 'DFSR' was not loaded because no valid module file was found in any module directory [...]"

This only happens when accessing the plugins remotely via the API.  Running the scripts directly works fine.

Here's the script as is (it is quite simple):

#Check_DFSReplication.ps1
import-module DFSR

$backlog = (get-dfsrstate).Count
if ($backlog -gt 100) {
	$nagioscode = 2
	$nagiosmsg = "CRITICAL: Backlog is " + [string]$backlog
} elseif ($backlog -gt 25) {
	$nagioscode = 1
	$nagiosmsg = "WARNING: Backlog is " + [string]$backlog
} elseif ($backlog -lt 26) {
	$nagioscode = 0
	$nagiosmsg = "OK: All DFSR volumes appear to be replicating properly."
} else {
	$nagioscode = 3
	$nagiosmsg = "UNKNOWN: get-dfsrstate returned an unexpected response."
}

write $nagiosmsg
exit $nagioscode

**Comment by celticguy42** [comment]
I also just tried running this script through the NSClient++ agent (via check_nrpe) and it works.

**Comment by celticguy42** [comment]
This is the error occurs when trying to run the script via the API:
{
  "value": {
    "returncode": 0, 
    "stdout": "import-module : The specified module 'DFSR' was not loaded because no valid module file was found in any module \ndirectory.\nAt C:\\Program Files (x86)\\Nagios\\NCPA\\plugins\\test.ps1:3 char:1\n+ import-module DFSR\n+ ~~~~~~~~~~~~~~~~~~\n    + CategoryInfo          : ResourceUnavailable: (DFSR:String) [Import-Module], FileNotFoundException\n    + FullyQualifiedErrorId : Modules_ModuleNotFound,Microsoft.PowerShell.Commands.ImportModuleCommand\n \nget-dfsrstate : The term 'get-dfsrstate' is not recognized as the name of a cmdlet, function, script file, or operable \nprogram. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.\nAt C:\\Program Files (x86)\\Nagios\\NCPA\\plugins\\test.ps1:7 char:13\n+ $backlog = (get-dfsrstate).Count\n+             ~~~~~~~~~~~~~\n    + CategoryInfo          : ObjectNotFound: (get-dfsrstate:String) [], CommandNotFoundException\n    + FullyQualifiedErrorId : CommandNotFoundException\n \nOK: All DFSR volumes appear to be replicating properly."
  }
}

**Comment by jhomann** [comment]
I'm not really a PowerShell user so I don't really know how modules work - but is it possible that the module directory is checking relative to the script being ran? Is it possible to tell the script to pull the module from the exact location? Only asking because looking into this we may need to find out a way to tell the script to run from a specific directory or set some sort of environment variable when it runs.

**Comment by celticguy42** [comment]
I actually just found the issue... the NCPA service is 32 bit, and calls the 32 bit PowerShell.  The 32 bit powershell loads modules from C:\Windows\SysWOW64\WindowsPowerShell\v1.0\Modules not C:\Windows\System32\WindowsPowerShell\v1.0\Modules.

Any idea when we may see a 64 bit NCPA for Windows?

**Comment by celticguy42** [comment]
I found this at http://poshcode.org/3827 - it detects if the 32 bit PowerShell is running and re-launches as 64 bit.

if ($pshome -like "*syswow64*") {
	# relaunch this script under 64 bit shell
	# if you want powershell 2.0, add -version 2 *before* -file parameter
	& (join-path ($pshome -replace "syswow64", "sysnative") powershell.exe) -ExecutionPolicy Unrestricted -noprofile -nologo -file `
		(join-path $psscriptroot $myinvocation.mycommand) @args

	# exit 32 bit script
	exit
}

**Comment by bgshacklett** [comment]
Interesting. I'll have to experiment with this and see if it affects issue #196.

**Comment by lgroschen** [comment]
I've replicated all of these steps on my Windows Server 2012 Vagrantfile and it seems to work as you described.  Anything you think should be done as far as NCPA for parsing the proper path to the WindowsPowerShell path or is this something that should be handled for each script?  Otherwise I'll close this Issue.

**Comment by ccztux** [comment]
We had the same problem on multiple hosts. We have changed de default command line for powershell scripts in ncpa.cfg to:
```
.ps1 = c:\windows\sysnative\windowspowershell\v1.0\powershell.exe -ExecutionPolicy Unrestricted -File $plugin_name $plugin_args
```

Found here:
[running-64-bit-powershell-from-nagios-ncpa](http://joerussbowman.tumblr.com/post/99853640886/running-64-bit-powershell-from-nagios-ncpa)

It works like a charm!

**Comment by jhomann** [comment]
I've added ccztux's solution he found to the information before the directives so that people who are having a similar problem will be able to try this solution. I think that it's best since it really revolves around how you want to run the script not so much NCPA. Feel free to open another issue or this one again if there is more discussion on this.

00f873db238da6a8d572e96cbbf104dae68f0ec5
