### ISSUE TITLE
CPU/Percent

### ISSUE THREAD

**Issue by daVikes** [NagiosEnterprises/ncpa#193]
With CPU/Percent it seems to be alerting if any CPU is reaching warning or critical with multiple processors.   I have a 20 core server and 2 of the cores were at 100% and it was alerting to this.  So not sure if this is an issue or something I need to configure to avoid alerting unless all CPU's are at the same percentage?     Also, considering using Load Average instead.

Thanks!

**Comment by krobertson71** [comment]
There is a aggregate function we use to avoid this.  We had the same issue and this was the resolution

-t 'mytoken' -P 5693 -M cpu/percent -q aggregate=avg -w 90 -c 97

**Comment by daVikes** [comment]
I had to update the plugin to get the -q option, but after that this seems to be working.

Thanks!
