### ISSUE TITLE
NCPA still being actively developed?

### ISSUE THREAD

**Issue by krobertson71** [NagiosEnterprises/ncpa#194]
Noticed things have gone quiet since 1.8.1.

There was buzz about 1.9 but that seems to have died off in the past few months.

Just asking as I need to prepare for an agent change if this is the case.

**Comment by scottwilkerson** [comment]
Yes, it is still being actively developed.

As an open project, you may feel free to make a pull request with any contributions you would like to see added to the project.

**Comment by tmcnag** [comment]
To be clear, we are closing this issue as we try to keep all non-bug- and non-feature-related posts to our forums:

https://support.nagios.com/forum

If you have general questions it is best to post them there.
