### ISSUE TITLE
NCPA 1.8.1—return code incorrect for PowerShell script

### ISSUE THREAD

**Issue by bgshacklett** [NagiosEnterprises/ncpa#196]
I'm having some trouble with the returncode from PowerShell plugin scripts. It's returning zero even though the script, itself, returns 1 or 2. To simplify, I created a script with the contents `exit 1` and it's still returning `"returncode": 0,`. 

Any thoughts?

**Comment by jhomann** [comment]
Are you running the PowerShell script via a passive check or are you getting this when running it from the API?

**Comment by bgshacklett** [comment]
Running it from the API.

**Comment by celticguy42** [comment]
If you create a test.ps1 file with only these commands, what does it return?

#test.ps1
$nagiosmsg = "Test script"
$nagioscode = 1
write $nagiosmsg
exit $nagioscode
#end of script

It should return:
{
  "value": {
    "returncode": 1, 
    "stdout": "Test script"
  }
}

**Comment by bgshacklett** [comment]
The last time I tried, I had some difficulty reproducing this issue. I don't want to clutter up the feed, so I'm going to mark this closed for now. I'll reopen or open a new issue when I have some more solid information.
