### ISSUE TITLE
ERROR Cannot parse passive directive

### ISSUE THREAD

**Issue by daVikes** [NagiosEnterprises/ncpa#198]
Always see quite a few of these when changing the loglevel to ERROR

2015-10-13 13:40:22,989 32455 ERROR Cannot parse passive directive for loglevel, name malformed, skipping.
2015-10-13 13:40:22,989 32455 ERROR Cannot parse passive directive for logmaxmb, name malformed, skipping.
2015-10-13 13:40:22,989 32455 ERROR Cannot parse passive directive for gid, name malformed, skipping.
2015-10-13 13:40:22,989 32455 ERROR Cannot parse passive directive for logbackups, name malformed, skipping.
2015-10-13 13:40:22,989 32455 ERROR Cannot parse passive directive for uid, name malformed, skipping.

**Comment by jhomann** [comment]
Can you post your configuration file? Make sure to strip out any password/ips before you copy it in here.

**Comment by daVikes** [comment]
Sure, but you can just change your log level to ERROR you will see these in the output file.  




---------------------------------------
[listener]
uid = nagios
gid = nagcmd
ip = 0.0.0.0
port = 5693
certificate = adhoc
ssl_version = TLSv1
loglevel = error
logmaxmb = 10
logbackups = 10
logfile = var/ncpa_listener.log
pidfile = var/ncpa_listener.pid

[passive]
uid = nagios
gid = nagcmd
handlers = nrdp
sleep = 10
loglevel = error
logmaxmb = 10
logbackups = 10
logfile = var/ncpa_passive.log
pidfile = var/ncpa_passive.pid

[nrdp]
token = mytoken
parent = http://mynagioshost.mydomain.local/nrdp/
hostname = myhost.mydomain.com

[api]
community_string = mystring

[plugin directives]
plugin_path = plugins/
.sh = /bin/sh $plugin_name $plugin_args
.ps1 = powershell -ExecutionPolicy Bypass -File $plugin_name $plugin_args
.vbs = cscript $plugin_name $plugin_args //NoLogo

[passive checks]
#%HOSTNAME%|cpu_usage = /cpu/percent --warning 90 --critical 95
%HOSTNAME%|swap_usage = /memory/swap/percent --warning 50 --critical 80
%HOSTNAME%|memory_usage = /memory/virtual/percent --warning 80 --critical 90

**Comment by jhomann** [comment]
This looks like it could be caused by the configparser somehow trying to parse the passive section as passive checks. Will have to test this out and verify that it's a bug.

**Comment by jhomann** [comment]
I can't get this to happen, is there any more info you can give?
