### ISSUE TITLE
Check multiple services - only returns first service

### ISSUE THREAD

**Issue by celticguy42** [NagiosEnterprises/ncpa#201]
Per the documentation, this should return the status of both services:

`https://server:5693/api/servicesservice=LanmanServer&service=LanmanWorkstation&status=running&check=true`

However, it only returns the status of the first service.

```
{
  "value": {
    "returncode": 0, 
    "stdout": "OK: Service LanmanServer is running"
  }
}
```

**Comment by jhomann** [comment]
Fixed in 1.8.2
