### ISSUE TITLE
Add ability to use regex pattern for service name matching

### ISSUE THREAD

**Issue by ssaxnagios** [NagiosEnterprises/ncpa#203]
It would be nice if you could use a regex pattern in order to check a group of services.

**Comment by ssaxnagios** [comment]
Original request here:

https://support.nagios.com/forum/viewtopic.php?t=35516

**Comment by jhomann** [comment]
Not sure if this will get added or not but I will mark it as enhancement for now.

**Comment by ccztux** [comment]
It would be great, when checks would support regex matching for API endpoints in generally, not only for services and partitions.
#178

**Comment by jomann09** [comment]
As a side note, matching is probably going to be as follows:

By default - matches will be "searches" (like matches) using `in` to find out if the string is inside the value. I will be adding the ability to change the way you should match it by using `match=<type>` where match type can be `exact`, `regex`, `like`.

An example would be `api/services?service=test&service=test123&match=exact`

A small issue with this is that currently both the processes `name` and `exe` value along with services `service` value are all exact matches. This would change the default, but seems like it should be that way anyway. I am going to think on this and decide what to set the default to.
