### ISSUE TITLE
TLSv1.1 and TLSv1.2 support

### ISSUE THREAD

**Issue by Grimrapper** [NagiosEnterprises/ncpa#204]
Hello,

I've been trying for a couple of days now to make client and server side SSL authentication for ncpa_passive. In Python docs it is said that from version 2.7.9 on, it has support for TLSv1.1 and TLSv1.2. As suggested in requests lib docs I created a custom adapter that sets TLSv1.X protocol but when I try to start ncpa_passive I get the following error:

AttributeError: 'module' object has no attribute 'PROTOCOL_TLSv1_X'

I would like to ask if this is a limitation on NCPA's side (the bundled Python version) or on the requests library's side. If it is in NCPA's side, I would like to know how can I approach this problem.

Thanks in advance.

**Comment by jhomann** [comment]
This probably won't be in 1.8.2 but I can look into it in 2.0.0 which will be using updated versions of PyOpenSSL, Flask, and Python 2.7.11 instead of 2.7.8**

**Comment by jhomann** [comment]
This has been added in 2.0.0
