### ISSUE TITLE
Warning and critical values less then xx (and not greater than)

### ISSUE THREAD

**Issue by antoine-habran** [NagiosEnterprises/ncpa#205]
I'm just trying to use check_ncpa.py with the "Windows Listener" and this is working like a charm. 

I create some nagios command to check CPU, RAM and other stuff. While I analyze the API possibilities, I found the value of the uptime of the host (system/uptime). 

I would like to check if the uptime is less than, by example, 86400s (one day) to check if a host reboot unexpectedly. But I cannot find a flag other than "-c" or "-w" who check if the returned value is greater than "xx" or "yy".

There is a flag other than these or another option to "invert" the comparaison and check if the returned value is lesser than "xx" or "yy"?

Sorry if my english is bad. Feel free to ask me if you have a question.

Regards

**Comment by jm-welch** [comment]
The threshold syntax is a bit odd. I don't recall where I read about it first, but it's common to a number of Nagios plugins. The number defines the range that is considered "okay" for the severity specified. Anything outside of that range fails the test, and that severity is raised.

The full notation would include a colon, to separate the beginning and end of the range, like so: `-c 15:20`. That would mean that if the observed value were within 15-20, it would not be considered critical, but any number outside that range would be considered critical (so either 14 or 21). Just a number is treated as `-c :15` which means anything up to 15 passes the test, but anything above 15 fails.

For an uptime counter, I've used this before:

`-w 86400:776000 -c 3600:31536000`

That will warn on anything that's been up for less than a day or over 3 months, and critical on anything that's been up for less than an hour or more than a year.

**Comment by bgshacklett** [comment]
That's incredibly useful information. Thank you.

**Comment by lgroschen** [comment]
@antoine-habran can you confirm what @jm-welch suggested works for you?  If it does we can close this issue.
