### ISSUE TITLE
windows interface empty

### ISSUE THREAD

**Issue by wangyishuai007** [NagiosEnterprises/ncpa#206]
like this \:
<pre>https://192.168.1.235:5693/api/interface/?token=1.235&delta=1
{
  "value": {
    "interface": {
      "": {
        "packets_sent": [
          [
            722.358776522458
          ], 
          "c"
        ], 
        "dropin": [
          [
            0.0
          ], 
          "c"
        ], 
        "bytes_recv": [
          [
            76799.01317057501
          ], 
          "b"
        ], 
        "packets_recv": [
          [
            74242.7208502657
          ], 
          "c"
...
</pre>
In my windows 7 and windows server 2008 r2.
by the way, system language is Chinese, does it matter?

**Comment by lgroschen** [comment]
I just tried checking the interface in my Windows Server 2012r2 virtual machine and it shows the following interfaces:
"Ethernet":
"Local Area Connection* 12":
"*.nagios": 
"Loopback Pseudo-Interface 1":

If you are using Chinese this may be similar to #165 which I will have to test on another NCPA install where I can verify all supported languages are working.  We can try and get this together for the 1.8.2 release.

**Comment by jhomann** [comment]
This is the same bug as what Luke linked to in #165 so I'm closing this. I'm not sure how we will be able to fix this as it seems it's windows related. I will continue looking into it though but it seems like something maybe in psutil that causes this to not convert correctly.
