### ISSUE TITLE
Make Mounted Volumes Visible via the API on Windows

### ISSUE THREAD

**Issue by bgshacklett** [NagiosEnterprises/ncpa#209]
If a volume is mounted at an empty directory on Windows, it should appear under the /disk/logical node of the API, similar to the way lettered volumes do.

Ex:

```
   "disk": {
      "logical": {
        "VolumeName": {
          "total_size": [
            64422408192, 
            "b"
          ], 
          "used_percent": [
            50.4, 
            "%"
          ], 
          "used": [
            32457572352, 
            "b"
          ], 
          "free": [
            31964835840, 
            "b"
          ], 
          "device_name": [
            [
              "C:\Path\To\Volume"
            ], 
            "name"
          ]
        }
```

**Comment by krobertson71** [comment]
If you are asking why it does not, then I have the same issue on Windows and Linux.
For some reason the current release will not detect mounted shares/volumes.

For Linux I just use the check_disk plugin and put in into the remote host's ncpa plugins directory and create a check with ./check_ncpa.  Works like a champ.

You just need a powershell version to do the same.  Workaround I came up with.

**Comment by bgshacklett** [comment]
While a custom script is a reasonable workaround, which I will probably employ in the short term, checking disk stats is something that is built into the native API. Does it not make sense for all volumes to be checked, rather than just those which are assigned a drive letter?

**Comment by krobertson71** [comment]
Oh please do not get me wrong, I agree with you 100%.  It just does not work in the currently developed version.  I am just letting you know how I got around it.  Linux is an even better headache than Windows in this area.  Plugin just make it easy to get around it.

**Comment by bgshacklett** [comment]
Gotcha. Yeah, I'm hoping to take a look at the code this weekend and see if I can figure out how it ticks, maybe make a pull request if I can get it figured out. I'm really surprised that Linux has more issues, as mount points are the only way to make volumes available on Linux. I suspect I'm missing something there. Anyway, thanks for the replies. Hopefully I'll have more to add to this conversation before long.

**Comment by bgshacklett** [comment]
It looks like NCPA uses the psutil module to enumerate volumes on a system. Unfortunately, my testing with psutil has shown that it doesn't enumerate Windows volumes unless they have a drive letter assigned.

**Comment by krobertson71** [comment]
Ah ok.  

Now I should take a closer look at why the agent can not see mounted remove filesystems on Linux hosts.  They are configured in fstab so not sure why it misses those.

**Comment by lgroschen** [comment]
Hey @bgshacklett!

I found that psutil was not using the "all=True" flag when calling psutil.disk_partitions().  This will expose all the mounted devices.  Source: https://pythonhosted.org/psutil/#disks

I'll push this shortly and have you test it to verify.  Thanks!

Luke

**Comment by bgshacklett** [comment]
@lgroschen Thank you very much for working on this. I've just compiled and tested it on a Windows 10 computer, and it doesn't seem to be working. I'm going to see if I can run it on a couple of servers running different version of Windows in the lab. Perhaps something changed with the API that psutil uses in Windows 10. I'll report back once I know more.

**Comment by lgroschen** [comment]
@bgshacklett I haven't tried it on Windows 10, but I could do that at home easily enough on my own PC.  I tested this on a Windows Server 2012r2 virtual machine which only showed "C:|" as the mounted drive and after adding all=True I saw the smb share that I mounted and mapped to D as "D:|".  Definitely would be good to make sure this will work one everything so that as much as possible will be exposed no matter what type of OS it's being run on.

**Comment by bgshacklett** [comment]
@lgroschen I got the following:
```
>>> psutil.disk_partitions(all=True)
[sdiskpart(device='C:\\', mountpoint='C:\\', fstype='NTFS', opts='rw,fixed'), sdiskpart(device='D:\\', mountpoint='D:\\', fstype='FAT32', opts='rw,fixed'), sdiskpart(device='E:\\', mountpoint='E:\\', fstype='', opts='cdrom'), sdiskpart(device='G:\\', mountpoint='G:\\', fstype='FAT32', opts='rw,removable'), sdiskpart(device='H:\\', mountpoint='H:\\', fstype='NTFS', opts='rw,remote'), sdiskpart(device='N:\\', mountpoint='N:\\', fstype='NTFS', opts='rw,remote'), sdiskpart(device='P:\\', mountpoint='P:\\', fstype='NTFS', opts='rw,remote')]
```
There's no mention of `C:\\Temp` in there, which should exist. If I look at WMI, it gives me that mount point:
```
__GENUS          : 2
__CLASS          : Win32_MountPoint
__SUPERCLASS     :
__DYNASTY        : Win32_MountPoint
__RELPATH        : Win32_MountPoint.Directory="Win32_Directory.Name=\"C:\\\\Tem
                   p\"",Volume="Win32_Volume.DeviceID=\"\\\\\\\\?\\\\Volume{b0e
                   8dc24-ed0f-49db-8f41-32b9d41a9c63}\\\\\""
__PROPERTY_COUNT : 2
__DERIVATION     : {}
__SERVER         : ITOPS04
__NAMESPACE      : root\cimv2
__PATH           : \\ITOPS04\root\cimv2:Win32_MountPoint.Directory="Win32_Direc
                   tory.Name=\"C:\\\\Temp\"",Volume="Win32_Volume.DeviceID=\"\\
                   \\\\\\?\\\\Volume{b0e8dc24-ed0f-49db-8f41-32b9d41a9c63}\\\\\
                   ""
Directory        : Win32_Directory.Name="C:\\Temp"
Volume           : Win32_Volume.DeviceID="\\\\?\\Volume{b0e8dc24-ed0f-49db-8f41
                   -32b9d41a9c63}\\"
PSComputerName   : ITOPS04
```
...plus the other mountpoints existing on the system.

**Comment by lgroschen** [comment]
This looks to be a feature request that might need to be added later.  When using psutils to show mounted drives it doesn't look for mounted directories and since the C:\ drive is a mapped drive for the filesystem it's showing just the 'C:\\'.  Psutil is using the [GetDriveType](https://msdn.microsoft.com/en-us/library/aa364939(v=vs.85).aspx) function as described here: [psutil](https://pythonhosted.org/psutil/#disks).  This might be something I would ask the maintainers of psutil to be able to expose mounted directories and it may already exist.  If that's the case we could just add the logic into the API to parse through a mounted drive and look for directory based mounts.

I hope you can give me a hand with this when I get a chance to test the possible ways to expose this.  Your WMI data will definitely help.

**Comment by bgshacklett** [comment]
Interesting. That gave me similar output to the previous command.

```
>>> import psutil; psutil.disk_partitions('C:\\')
[sdiskpart(device='C:\\', mountpoint='C:\\', fstype='NTFS', opts='rw,fixed'), sdiskpart(device='D:\\', mountpoint='D:\\', fstype='FAT32', opts='rw,fixed'), sdiskpart(device='E:\\', mountpoint='E:\\', fstype='', opts='cdrom'), sdiskpart(device='G:\\', mountpoint='G:\\', fstype='FAT32', opts='rw,removable'), sdiskpart(device='H:\\', mountpoint='H:\\', fstype='NTFS', opts='rw,remote'), sdiskpart(device='N:\\', mountpoint='N:\\', fstype='NTFS', opts='rw,remote'), sdiskpart(device='P:\\', mountpoint='P:\\', fstype='NTFS', opts='rw,remote')]
```

**Comment by lgroschen** [comment]
I'm just going to tag this as an enhancement and I can test a way to expose the directories and maybe query the psutil folks to see what can be done about getting more information from the disk_partitions() function.

**Comment by lgroschen** [comment]
I pushed the all=True to master since it exposes more mounts.  We have to find out how to expose mounted directories that exist in a mapped network drive using psutil, but this enhancement might have to wait until we move to Python 3.

**Comment by bgshacklett** [comment]
Why was this closed? I don't see any reference to a resolution.

**Comment by jhomann** [comment]
@lgroschen has already applied the all=True to the psutils call for all directories

**Comment by jhomann** [comment]
This probably won't be in here until this gets resolved:
https://github.com/giampaolo/psutil/issues/775

**Comment by bgshacklett** [comment]
Awesome.  Much appreciated.

**Comment by jomann09** [comment]
I managed to have time to make a PR for psutils to fix this. It should be available soon (either in NCPA 2.1 or the next bug fix afterwards, depending on psutils release cycle)

**Comment by jvandermeulen** [comment]
Jake, what is the status on Windows volume mountpoints? We tried version 2.1.3 to no avail.

**Comment by jomann09** [comment]
What kind of mount points are we talking about? Depending on how/what is mounted it may be in the list of excluded file system types. I know for sure my PR to psutils was included a few versions ago.

**Comment by jvandermeulen** [comment]
I created a new NTFS partion on allocated space and mounted it on c:\MyMountpoint following all steps described in the TechNet article https://technet.microsoft.com/en-us/library/cc938934.aspx

To be sure I (temporary) set 
`exclude_fs_types = aufs,autofs,binfmt_misc,cifs,cgroup,debugfs,devpts,devtmpfs,encryptfs,efivarfs,fuse,hugelbtfs,mqueue,nfs,overlayfs,proc,pstore,rpc_pipefs,securityfs,smb,sysfs,tmpfs,tracefs`
to
`exclude_fs_types = nfs`

This mountpoint remains unvisible to API endpoint disk unless I attach a drive letter to it.

**Comment by jomann09** [comment]
Hmm I will have to check this ... I do think it should show up but maybe it's blocking it.

**Comment by jvandermeulen** [comment]
Jake, can you reopen this issue please?
