### ISSUE TITLE
Ubuntu 14.10 https://server:5693/api/services is an empty list

### ISSUE THREAD

**Issue by fermatcapital** [NagiosEnterprises/ncpa#210]
This is the result:

{
  "value": {
    "services": {}
  }
}

I've installed a fresh 1.8.1 version.

I do not have this problem with my CentOS machines.

Please advise.

**Comment by fermatcapital** [comment]
Bump!  Am I the only one seeing this problem?

**Comment by lgroschen** [comment]
Hey Fermat!

We are going to go through the list of all the bugs and this will definitely not be ignored.  Ubuntu will be easier to test also!

**Comment by jhomann** [comment]
Can I get confirmation this was a problem on Ubuntu 14.04? I don't believe there is a 14.10. I tested it on 15.10 which I had installed but I will install a 14.04 version and test it on there too. Of course I am testing 2.0.0 which has a couple fixes that I think already fixed this issue but just want to make sure.

**Comment by jhomann** [comment]
Can confirm this is fixed in 2.0.0
