### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by ccztux** [NagiosEnterprises/ncpa#211]
Thats all i want to know. :-)

Best regards,

ccztux

**Comment by daVikes** [comment]
They do work on it but not as much as I guess I would like them to.  At least with it here I think anybody can contribute?

**Comment by jhomann** [comment]
daVikes is correct. It is a community project and not one of our commercial solutions. Therefore, it's open for anyone to help contribute and make it better. Unfortunately we have been very busy with a lot of projects and the original author has become quite busy himself. This means it's been pretty slow development that last 6 months or so.

**Comment by ccztux** [comment]
My mistake. I thought NCPA is one of your commercial solutions. Is the relase date of 1.8.2 foreseeable? I urgently need the "Fix systemctl service list on el7".

Best regards,

ccztux

**Comment by krobertson71** [comment]
Is there a commercial solution coming?  This was heavily promoted at the 2013 con as the new universal agent.  Now it doesn't see to carry the same clout.  

I had this agent deployed to all our Windows and Linux servers.  Now I am wondering if that was a mistake.

**Comment by daVikes** [comment]
i agree, I hope this can be more of a focus area in the future to do regular updates to this as I think this agent is a great step forward but still needs some TLC.

**Comment by krobertson71** [comment]
I love using the agent.  Only one agent to manage across Linux and Windows.  Not sure why it's not getting the attention as it was presented and a big step forward.

Nsclient++ is basically maintained by 1 or two guys, neither are employed by Nagios.

The others are older agents.  Worries me a little.

**Comment by krobertson71** [comment]
Forgot to mention.  I love the plugin ability.  So far, to date, I have never had a plugin not function with the agent.  Helps in a lot of ways.  Been writing our own plugins for our Linux servers.

**Comment by jhomann** [comment]
We have recommended NCPA to people who want a cross-platform agent in the past. NCPA has only had one developer from the beginning. The developer has since moved on and now we are supporting the project. I would say that due to the busy workload it's been on the back-burner for a while now. There's a lot of things we want to get added into it but like you've stated, it needs a bit of cleanup. It's not going away though and we certainly want to continue to fix bugs and help everyone with the problems they have with it.

That being said, we can definitely get a 1.8.2 release out soon. I will take a look at the current state of the 1.8.2 version and verify it works. I will also take a little time to check over the current bugs too and see if there is anything else we can push into a 1.8.2 release.

**Comment by krobertson71** [comment]
If you want me to help test the release I can do that.  We have test servers I can run it on.

**Comment by krobertson71** [comment]
The feature I am looking for the most, and I think some others, is the ability to capture process memory and/or CPU.  If I have to choose it would be memory.  Been getting some questions around this.

**Comment by daVikes** [comment]
Awesome thanks Jake!  We appreciate that you are willing to take a look at this again.   I think its a great way to do this so you can do one universal agent across your systems.    Wish I could help contribute more to the code, however, I'm more of a shell scripter at this point than anything else.

**Comment by mon0brew** [comment]
I agree that it would be great to see movement on this project again (sorry, I'm not a devel... ) 

As it's a great agent for those running XI, it seems like it compliments that commercial product stream. I know the issue on single-core linux VMs was a blocker for me before. Not so much at my new shop. But recently found that linux machines with oodles of mounts don't seem to like NCPA on them. Had to go back to NRPE for those.

Jake, all that you folks up in St. Paul are doing is great. Scott has built a great team and we're always excited to see the next release of the various components.

-Andrew

**Comment by jhomann** [comment]
We are currently working on some processes that will make it easier for us to test and build new releases which should help a bit with getting new releases out faster for everyone. We've been working hard to try to get NCPA to integrate well with XI - that was one of the main goals and there are still a lot of ideas for how to make it integrate even better.

As for the mount problem, I think with the next release we will be updated to Python 3.x and will be able to use the newest version of psutils which should help some of the cross-platform issues.

**Comment by bgshacklett** [comment]
@jhomann, that's some great news. Any thoughts on what the most pressing issues are? I'd love to help if I can get the time.

**Comment by lgroschen** [comment]
@bgshacklett  I think the it would be nice to get #42 / #47 and most of the bugs (there's about 16 of them- [Bug List](https://github.com/NagiosEnterprises/ncpa/issues?q=is%3Aopen+is%3Aissue+label%3Abug)) that are present in Issues for a 1.8.2 release.  I also talked to @jhomann and @scot0357 about moving NCPA to Python3 which would remove a lot of the required packages (and the problems and bugs with them), but would be more of a 2.0.0 release.  

I know a lot people have been asking about the passive stuff as well and having problems on different installs.  I have been working on a dev environment I can share that I want to work on *nix, Windows and OSX hosts- I recently pushed a Vagrantfile into the development branch, but have only tried Linux host/windows guest so far.

@scot0357 also created a Docker file that can be used in the development branch.  There are instruction for the Dockerfile in ncpa/docs/development.rst. I will add more to that file on the Vagrantfile once I get it working for multiple guest and host vms.

**Comment by ccztux** [comment]
Thats good news!
Is there a plan, when future versions will be released?

**Comment by lgroschen** [comment]
Still working on testing some of the bugs slow and steady.  Would be nice to get a bugfix version out before the end of summer. I'll chat with @jhomann and find out in the next few weeks what we can get together.

**Comment by ccztux** [comment]
That sounds good, thx.

**Comment by doneil326** [comment]
Will the disk space issue in https://github.com/NagiosEnterprises/ncpa/issues/102 be addressed in these as well?

**Comment by lgroschen** [comment]
Not 100% sure on this since superuser is required to see the missing blocks.  I believe there is a way to compare them as @scot0357 said in that issue, but it will take testing.  Something like check open block count and maybe add the difference to the used partition space.  Keep an eye on that issue for updates.

**Comment by jhomann** [comment]
I'm sorry this is taking so long to get out the next version. I've decided the amount of issues has snowballed into creating a version 2.0.0.

There will be just a couple of things that will be broken in this version versus the current versions that I will explain in the new version help documents.

That being said, you will be able to use the NEW 1.0.0 check_ncpa.py to check both the 1.7.x and 1.8.x versions along with the latest so _as long as you don't update your NCPA installs but not your plugin there shouldn't be any problems_.

**Comment by doneil326** [comment]
Is there an estimated release data for 2.0.0 now that it has been scoped?

**Comment by jhomann** [comment]
Given the amount of work (and the fact I would like to have it thoroughly tested) I would expect an rc1 of the 2.0.0 release by the 27th of May.

**Comment by jhomann** [comment]
Closing this, with a new release coming up soon!
