### ISSUE TITLE
NRDS Functionality in 1.8.1 - Expects [settings] and [services] section headers

### ISSUE THREAD

**Issue by ssaxnagios** [NagiosEnterprises/ncpa#213]
The NRDS configs generated in Nagios XI do not contain [settings] and [services] section headers which causes the NRDS updater through an error.

Also, even if you do fix that portion it looks like it replaces the entire ncpa.cfg with the updated file and will cause NCPA to not work properly because it needs more settings (and sections).

**Comment by jhomann** [comment]
Duplicate - plus NRDS doesn't work at all in NCPA.
