### ISSUE TITLE
Linux : Mounted volumes not being seen?

### ISSUE THREAD

**Issue by daVikes** [NagiosEnterprises/ncpa#215]
After the ncpa listener agent was started, we had mounted another Volume however ncpa didnt seem to list this in the api tree?   restart then saw it however, would think adding/removing of volumes would be updated?

Thanks!

**Comment by lgroschen** [comment]
Currently working with some volumes not being detected in #209 - which OS are you doing this on?  I would think that you are correct in assuming that when you access the API for the list of mounts it would refresh them when the psutils command is run.  Any info you can give to replicate this would help!

**Comment by daVikes** [comment]
Redhat Linux 6.6.   How would I run the psutils command directly?

**Comment by lgroschen** [comment]
Open a python 2.7 shell and run the following:
```
import psutils
psutils.disk_partitions()
psutils.disk_partitions(all=True)
```

Try both of those and see how they show up.  Then you can add a new mount and see if it shows up- there might be a time delay, but I'm thinking it's just not updating the API when the command is ran again.

**Comment by daVikes** [comment]
I did that but apparently psutils isn't installed. I searched for it but didnt see it listed in the rh repos.

**Comment by jhomann** [comment]
Your default version of python on the machine will not have psutils installed since it's bundled with the python version that comes with NCPA.
