### ISSUE TITLE
Add local system time to API

### ISSUE THREAD

**Issue by jm-welch** [NagiosEnterprises/ncpa#217]
Would it be possible to add the local system time to the API, likely under `/api/system`? We're working on monitoring time drift between connected systems, and this would allow Nagios to monitor this for any two arbitrary servers.

**Comment by lgroschen** [comment]
I think this would definitely be something nice to add.  I'm sure there would be other good reasons to get system time.

**Comment by jhomann** [comment]
Hello, so far I've added two new API endpoints:

```
api/system/timezone
"time": 1463122812.516
```

```
api/system/time
"timezone": [
      "Central Standard Time", 
      "Central Daylight Time"
 ]
```

Is there any other way to represent the time that you think would be helpful?

**Comment by jhomann** [comment]
Closing this for now. If there is anything else that would be helpful please open up this thread and let me know!
