### ISSUE TITLE
Centos 6 / NCPA 2.0.0 build / ImportError when installing

### ISSUE THREAD

**Issue by fermatcapital** [NagiosEnterprises/ncpa#221]
Everything builds per instructions from:

https://gist.github.com/gene1wood/9673278c99440a5a1ac8

But when I install, I have the following error:

root@ctdropboxAFCM build]# rpm -i ncpa-2.0.0-1.el6.x86_64.rpm 
nagios:x:495:490::/home/nagios:/bin/bash
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/cx_Freeze-4.3.4-py2.7-linux-x86_64.egg/cx_Freeze/initscripts/Console.py", line 27, in <module>
    exec(code, m.__dict__)
  File "ncpa_posix_listener.py", line 19, in <module>
  File "/usr/lib64/python2.7/site-packages/gevent/monkey.py", line 587, in patch_all
    patch_builtins()
  File "/usr/lib64/python2.7/site-packages/gevent/monkey.py", line 514, in patch_builtins
    patch_module('builtins')
  File "/usr/lib64/python2.7/site-packages/gevent/monkey.py", line 155, in patch_module
    gevent_module = getattr(__import__('gevent.' + name), name)
ImportError: No module named builtins
Started listener...
Started passive agent...

**Comment by jhomann** [comment]
Getting a little ahead of ourselves here :) I haven't made the builds work on Linux yet - currently 2.0.0 only builds on Windows. I know, strange right? Essentially gevent.builtins needs to be added. I committed the change to 799c84b41b48e2194bac031ed07d9ca05d633530

You should note however that there is going to be a lot of weirdness right now since NCPA 2.0.0 is currently under heavy development and should NOT be used in production.

**Comment by fermatcapital** [comment]
Thank you for the gentle note!

**Comment by jhomann** [comment]
No problem, the commit I just made should make it work on Linux though if you want to continue with trying out the build.

**Comment by fermatcapital** [comment]
Just tried a fresh build and now I get another error.  I realize this isn't your main focus.  Should I just dive in and try to resolve this or should I wait for development to stabilize before going down the Linux effort?

[root@ctdropboxAFCM build]# rpm -i ncpa-2.0.0-1.el6.x86_64.rpm 
nagios:x:495:490::/home/nagios:/bin/bash
error: unpacking of archive failed on file /usr/local/ncpa/libpython2.7.so.1.0;57335a74: cpio: Digest mismatch
[root@ctdropboxAFCM build]#

**Comment by jhomann** [comment]
That is an error I haven't encountered yet, if you'd like to look into it feel free to do so. I probably won't be getting around to making sure the builds work on all the systems until later this week. While I'm working on 2.0.0 the actual pushes to github shouldn't really break anything once the builds are fixed but the module updates have caused the problems you're running into.
