### ISSUE TITLE
Add inodes to linux disk checks

### ISSUE THREAD

**Issue by ccztux** [NagiosEnterprises/ncpa#222]
It would be very useful when it was possible to monitor the inode usage of a linux disk. Then there is no need to use check_disk plugin.

**Comment by jhomann** [comment]
This is probably possible to add in the disk section of the API in the future. I think it will require some thought and time to implement in a good way so we will probably hold off on this until another release.

**Comment by jomann09** [comment]
Added in this commit 4812aac6e328c9ed9eb5d8bf54ff14a66bbef5e1 and added three new node endpoints (for Unix systems only):

`inodes` - the total number of inodes available
`inodes_used` - the total number of inodes used
`inodes_free` - the total number of free inodes (this isn't the available)
`inodes_available` - the total number of inodes available (may have a reserved number on system)
