### ISSUE TITLE
NCPA doesn't Compile in Windows 8.1 x64

### ISSUE THREAD

**Issue by ravenich** [NagiosEnterprises/ncpa#224]
Doesn't compile in Windows 8.1 x64. Error:
Traceback (most recent call last):
  File "build\build_windows.py", line 16, in <module>
    with open('VERSION.md') as version_file:
IOError: [Errno 2] No such file or directory: 'VERSION.md'
I rename VERSION to VERSION.md and get this:
Не удается найти указанный файл.
"C:\Python27\Scripts\sphinx-build" не является внутренней или внешней
командой, исполняемой программой или пакетным файлом.
running build_exe
Traceback (most recent call last):
  File "setup_windows.py", line 53, in <module>
    options=dict(build_exe=buildOptions),
  File "C:\Python27\lib\site-packages\cx_Freeze\dist.py", line 362, in setup
    distutils.core.setup(**attrs)
  File "C:\Python27\lib\distutils\core.py", line 151, in setup
    dist.run_commands()
  File "C:\Python27\lib\distutils\dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "C:\Python27\lib\distutils\dist.py", line 972, in run_command
    cmd_obj.run()
  File "C:\Python27\lib\site-packages\cx_Freeze\dist.py", line 231, in run
    metadata = metadata)
  File "C:\Python27\lib\site-packages\cx_Freeze\freezer.py", line 137, in __init
__
    self._VerifyConfiguration()
  File "C:\Python27\lib\site-packages\cx_Freeze\freezer.py", line 520, in _Verif
yConfiguration
    executable._VerifyConfiguration(self)
  File "C:\Python27\lib\site-packages\cx_Freeze\freezer.py", line 724, in _Verif
yConfiguration
    freezer._GetBaseFileName(self)
  File "C:\Python27\lib\site-packages\cx_Freeze\freezer.py", line 240, in _GetBa
seFileName
    raise ConfigError("no base named %s", name)
cx_Freeze.freezer.ConfigError: no base named Win32Service
Traceback (most recent call last):
  File "build\build_windows.py", line 47, in <module>
    os.path.join(basedir, 'agent', 'build', 'NCPA', 'listener', 'static', 'help'
))
  File "C:\Python27\lib\shutil.py", line 171, in copytree
    names = os.listdir(src)
WindowsError: [Error 3] : 'D:\\ncpa-master\\docs\\_build\\html/*.*'

I installed sphinx and sphinx-bootstrap-theme and finally get this:

Running Sphinx v1.4.1
WARNING: The config value `version' has type `float', defaults to `str.'
loading pickled environment... not yet created
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 8 source files that are out of date
updating environment: 8 added, 0 changed, 0 removed
reading sources... [100%] passive
D:\ncpa-master\docs\active.rst:57: WARNING: Inline substitution_reference start-
string without end-string.
D:\ncpa-master\docs\active.rst:62: WARNING: Inline substitution_reference start-
string without end-string.
D:\ncpa-master\docs\active.rst:64: WARNING: Inline substitution_reference start-
string without end-string.
D:\ncpa-master\docs\installation.rst:2: WARNING: Duplicate explicit target name:
 "32-bit".
D:\ncpa-master\docs\installation.rst:2: WARNING: Duplicate explicit target name:
 "64-bit".
D:\ncpa-master\docs\installation.rst:2: WARNING: Duplicate explicit target name:
 "64-bit".
D:\ncpa-master\docs\installation.rst:2: WARNING: Duplicate explicit target name:
 "32-bit".
D:\ncpa-master\docs\installation.rst:2: WARNING: Duplicate explicit target name:
 "64-bit".
D:\ncpa-master\docs\installation.rst:2: WARNING: Duplicate explicit target name:
 "32-bit".
D:\ncpa-master\docs\installation.rst:2: WARNING: Duplicate explicit target name:
 "64-bit".
D:\ncpa-master\docs\installation.rst:2: WARNING: Duplicate explicit target name:
 "32-bit".
D:\ncpa-master\docs\installation.rst:2: WARNING: Duplicate explicit target name:
 "64-bit".
D:\ncpa-master\docs\installation.rst:2: WARNING: Duplicate explicit target name:
 "32-bit".
D:\ncpa-master\docs\installation.rst:2: WARNING: Duplicate explicit target name:
 "64-bit".
D:\ncpa-master\docs\installation.rst:2: WARNING: Duplicate explicit target name:
 "32-bit".
D:\ncpa-master\docs\installation.rst:2: WARNING: Duplicate explicit target name:
 "64-bit".
D:\ncpa-master\docs\installation.rst:235: WARNING: Literal block expected; none
found.
D:\ncpa-master\docs\passive.rst:38: WARNING: Literal block expected; none found.

looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] passive
generating indices... genindex
writing additional pages... search
copying images... [100%] images/win-install-screenshot.png
copying static files... done
copying extra files... done
dumping search index in English (code: en) ... done
dumping object inventory... done
build succeeded, 19 warnings.

Build finished. The HTML pages are in _build/html.
running build_exe
Traceback (most recent call last):
  File "setup_windows.py", line 53, in <module>
    options=dict(build_exe=buildOptions),
  File "C:\Python27\lib\site-packages\cx_Freeze\dist.py", line 362, in setup
    distutils.core.setup(**attrs)
  File "C:\Python27\lib\distutils\core.py", line 151, in setup
    dist.run_commands()
  File "C:\Python27\lib\distutils\dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "C:\Python27\lib\distutils\dist.py", line 972, in run_command
    cmd_obj.run()
  File "C:\Python27\lib\site-packages\cx_Freeze\dist.py", line 231, in run
    metadata = metadata)
  File "C:\Python27\lib\site-packages\cx_Freeze\freezer.py", line 137, in __init
__
    self._VerifyConfiguration()
  File "C:\Python27\lib\site-packages\cx_Freeze\freezer.py", line 520, in _Verif
yConfiguration
    executable._VerifyConfiguration(self)
  File "C:\Python27\lib\site-packages\cx_Freeze\freezer.py", line 724, in _Verif
yConfiguration
    freezer._GetBaseFileName(self)
  File "C:\Python27\lib\site-packages\cx_Freeze\freezer.py", line 240, in _GetBa
seFileName
    raise ConfigError("no base named %s", name)
cx_Freeze.freezer.ConfigError: no base named Win32Service
MakeNSIS v2.51 - Copyright 1995-2015 Contributors
See the file COPYING for license details.
Credits can be found in the Users Manual.

Processing config:
Processing plugin dlls: "C:\Program Files (x86)\NSIS\Plugins\*.dll"
 - AdvSplash::show
 - Banner::destroy
 - Banner::getWindow
 - Banner::show
 - BgImage::AddImage
 - BgImage::AddText
 - BgImage::Clear
 - BgImage::Destroy
 - BgImage::Redraw
 - BgImage::SetBg
 - BgImage::SetReturn
 - BgImage::Sound
 - Dialer::AttemptConnect
 - Dialer::AutodialHangup
 - Dialer::AutodialOnline
 - Dialer::AutodialUnattended
 - Dialer::GetConnectedState
 - InstallOptions::dialog
 - InstallOptions::initDialog
 - InstallOptions::show
 - LangDLL::LangDialog
 - Math::Script
 - NSISdl::download
 - NSISdl::download_quiet
 - Splash::show
 - StartMenu::Init
 - StartMenu::Select
 - StartMenu::Show
 - System::Alloc
 - System::Call
 - System::Copy
 - System::Free
 - System::Get
 - System::Int64Op
 - System::Store
 - TypeLib::GetLibVersion
 - TypeLib::Register
 - TypeLib::UnRegister
 - UserInfo::GetAccountType
 - UserInfo::GetName
 - UserInfo::GetOriginalAccountType
 - VPatch::GetFileCRC32
 - VPatch::GetFileMD5
 - VPatch::vpatchfile
 - nsDialogs::Create
 - nsDialogs::CreateControl
 - nsDialogs::CreateItem
 - nsDialogs::CreateTimer
 - nsDialogs::GetUserData
 - nsDialogs::KillTimer
 - nsDialogs::OnBack
 - nsDialogs::OnChange
 - nsDialogs::OnClick
 - nsDialogs::OnNotify
 - nsDialogs::SelectFileDialog
 - nsDialogs::SelectFolderDialog
 - nsDialogs::SetRTL
 - nsDialogs::SetUserData
 - nsDialogs::Show
 - nsExec::Exec
 - nsExec::ExecToLog
 - nsExec::ExecToStack

!define: "MUI_INSERT_NSISCONF"=""

Changing directory to: "D:\ncpa-master\agent\build"

Processing script file: "D:\ncpa-master\agent\build\ncpa.nsi"
!include: "C:\Program Files (x86)\NSIS\Include\MUI.nsh"
!include: "C:\Program Files (x86)\NSIS\Contrib\Modern UI\System.nsh"
NSIS Modern User Interface version 1.8 - Copyright 2002-2015 Joost Verburg (C:\P
rogram Files (x86)\NSIS\Contrib\Modern UI\System.nsh:8)
!define: "MUI_INCLUDED"=""
!define: "MUI_SYSVERSION"="1.8"
!define: "MUI_VERBOSE"="3"
!include: closed: "C:\Program Files (x86)\NSIS\Contrib\Modern UI\System.nsh"
!include: closed: "C:\Program Files (x86)\NSIS\Include\MUI.nsh"
!include: "C:\Program Files (x86)\NSIS\Include\nsDialogs.nsh"
!define: "NSDIALOGS_INCLUDED"=""
!include: closed: "C:\Program Files (x86)\NSIS\Include\nsDialogs.nsh"
!include: "C:\Program Files (x86)\NSIS\Include\WinMessages.nsh"
!include: closed: "C:\Program Files (x86)\NSIS\Include\WinMessages.nsh"
!include: "C:\Program Files (x86)\NSIS\Include\LogicLib.nsh"
!include: closed: "C:\Program Files (x86)\NSIS\Include\LogicLib.nsh"
!include: "C:\Program Files (x86)\NSIS\Include\InstallOptions.nsh"
!include: closed: "C:\Program Files (x86)\NSIS\Include\InstallOptions.nsh"
!include: "C:\Program Files (x86)\NSIS\Include\FileFunc.nsh"
!define: "FILEFUNC_INCLUDED"=""
!include: "C:\Program Files (x86)\NSIS\Include\Util.nsh"
!include: closed: "C:\Program Files (x86)\NSIS\Include\Util.nsh"
!define: "Locate"="!insertmacro LocateCall"
!define: "un.Locate"="!insertmacro LocateCall"
!define: "GetSize"="!insertmacro GetSizeCall"
!define: "un.GetSize"="!insertmacro GetSizeCall"
!define: "DriveSpace"="!insertmacro DriveSpaceCall"
!define: "un.DriveSpace"="!insertmacro DriveSpaceCall"
!define: "GetDrives"="!insertmacro GetDrivesCall"
!define: "un.GetDrives"="!insertmacro GetDrivesCall"
!define: "GetTime"="!insertmacro GetTimeCall"
!define: "un.GetTime"="!insertmacro GetTimeCall"
!define: "GetFileAttributes"="!insertmacro GetFileAttributesCall"
!define: "un.GetFileAttributes"="!insertmacro GetFileAttributesCall"
!define: "GetFileVersion"="!insertmacro GetFileVersionCall"
!define: "un.GetFileVersion"="!insertmacro GetFileVersionCall"
!define: "GetExeName"="!insertmacro GetExeNameCall"
!define: "un.GetExeName"="!insertmacro GetExeNameCall"
!define: "GetExePath"="!insertmacro GetExePathCall"
!define: "un.GetExePath"="!insertmacro GetExePathCall"
!define: "GetParameters"="!insertmacro GetParametersCall"
!define: "un.GetParameters"="!insertmacro GetParametersCall"
!define: "GetOptions"="!insertmacro GetOptionsCall"
!define: "un.GetOptions"="!insertmacro GetOptionsCall"
!define: "GetOptionsS"="!insertmacro GetOptionsSCall"
!define: "un.GetOptionsS"="!insertmacro GetOptionsSCall"
!define: "GetRoot"="!insertmacro GetRootCall"
!define: "un.GetRoot"="!insertmacro GetRootCall"
!define: "GetParent"="!insertmacro GetParentCall"
!define: "un.GetParent"="!insertmacro GetParentCall"
!define: "GetFileName"="!insertmacro GetFileNameCall"
!define: "un.GetFileName"="!insertmacro GetFileNameCall"
!define: "GetBaseName"="!insertmacro GetBaseNameCall"
!define: "un.GetBaseName"="!insertmacro GetBaseNameCall"
!define: "GetFileExt"="!insertmacro GetFileExtCall"
!define: "un.GetFileExt"="!insertmacro GetFileExtCall"
!define: "BannerTrimPath"="!insertmacro BannerTrimPathCall"
!define: "un.BannerTrimPath"="!insertmacro BannerTrimPathCall"
!define: "DirState"="!insertmacro DirStateCall"
!define: "un.DirState"="!insertmacro DirStateCall"
!define: "RefreshShellIcons"="!insertmacro RefreshShellIconsCall"
!define: "un.RefreshShellIcons"="!insertmacro RefreshShellIconsCall"
!include: closed: "C:\Program Files (x86)\NSIS\Include\FileFunc.nsh"
!insertmacro: GetParameters
!insertmacro: end of GetParameters
!insertmacro: GetOptions
!insertmacro: end of GetOptions
!define: "NAME"="NCPA"
!define: "COMPANY"="Nagios Enterprises, LLC"
!define: "NCPA_VERSION"="2.0.0"
!define: "UNINST_KEY"="Software\Microsoft\Windows\CurrentVersion\Uninstall\NCPA"

!define: "MULTIUSER_INSTALLMODE_COMMANDLINE"=""
!include: "C:\Program Files (x86)\NSIS\Include\MultiUser.nsh"
!define: "MULTIUSER_INCLUDED"=""
----------------------------------------------------------------------
NSIS String Functions Header File 1.09 - Copyright 2004 Diego Pedroso
----------------------------------------------------------------------
 (C:\Program Files (x86)\NSIS\Include\StrFunc.nsh:52)
$ {StrStr} - Copyright 2004 Diego Pedroso - Based on functions by Ximon Eighteen
 (macro:STRFUNC_FUNC:11)
$ {UnStrStr} - Copyright 2004 Diego Pedroso - Based on functions by Ximon Eighte
en (macro:STRFUNC_FUNC:5)
!include: closed: "C:\Program Files (x86)\NSIS\Include\MultiUser.nsh"
!define: "CONFIG_INI"="$INSTDIR\Config.ini"
BrandingText: "Nagios Enterprises, LLC"
Name: "NCPA"
OutFile: "ncpa-2.0.0.exe"
!define: "MUI_ICON"="NCPA\build_resources\ncpa.ico"
InstallDir: "$PROGRAMFILES32\Nagios\NCPA"
ShowInstDetails: hide
LoadLanguageFile: C:\Program Files (x86)\NSIS\Contrib\Language files\English.nlf

VIAddVersionKey: "ProductName" "NCPA"
VIAddVersionKey: "CompanyName" "Nagios Enterprises, LLC"
VIAddVersionKey: "FileVersion" "2.0.0"
LangString: "PAGE_TITLE" 1033 "Nagios Cross-Platform Agent (NCPA)"
LangString: "PAGE_SUBTITLE" 1033 "2.0.0 - Windows Version"
LangString: "LICENSE_TOP" 1033 "License Agreement"
LangString: "LICENSE_BOTTOM" 1033 "Nagios Software License 1.3"
!define: "MUI_PAGE_HEADER_TEXT"="$(PAGE_TITLE)"
!define: "MUI_PAGE_HEADER_SUBTEXT"="$(PAGE_SUBTITLE)"
!define: "MUI_LICENSEPAGE_TEXT_TOP"="$(LICENSE_TOP)"
!define: "MUI_LICENSEPAGE_TEXT_BOTTOM"="$(LICENSE_BOTTOM)"
!insertmacro: MUI_PAGE_LICENSE
Error while loading icon from "NCPA\build_resources\ncpa.ico": can't open file
Error in macro MUI_INTERFACE on macroline 64
Error in macro MUI_PAGE_INIT on macroline 2
Error in macro MUI_PAGE_LICENSE on macroline 5
Error in script "D:\ncpa-master\agent\build\ncpa.nsi" on line 61 -- aborting cre
ation process
Traceback (most recent call last):
  File "build\build_windows.py", line 56, in <module>
    os.path.join(basedir, 'build', 'ncpa-%s.exe' % version))
  File "C:\Python27\lib\shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: 'D:\\ncpa-master\\agent\\build\\nc
pa-2.0.0.exe'

Please, update build-windows,py (or change VERSION to VERSION.md) and add information about installing sphinx in BUILDING.rst

**Comment by jhomann** [comment]
It's not really supposed to build at the moment since there are some breaking changes. However, the requirements file that tells you what all needs to be installed is now in build/resources/require.txt and it used to be loaded in through build_windows.py but it's not done in a way that allows flexability when building NCPA. I want to be able to build NCPA automatically, manually, via scripts, do half a build, etc. The way the current build script works is it tries to do everything in a single script and it is going to be broken apart.

That being said it looks like you're missing the build_resources directory inside the repo.
