### ISSUE TITLE
Solaris build for version 2.0.0?

### ISSUE THREAD

**Issue by ccztux** [NagiosEnterprises/ncpa#225]
Hi!

Maybe it is possible to offer a build for solaris when version 2.0.0 will be released?

Best regards,

ccztux

**Comment by jhomann** [comment]
I actually don't have a solaris box to try to build on, so I am not sure if this will be possible.

**Comment by jhomann** [comment]
I should give a better explanation! We could try to get builds working for Solaris 10/11 on x86 but I do not have a SPARC box to test on that we could try to build a version on. Also, in the past via this thread #105 the only time someone has tried to build for Solaris it's come up with many problems which means that it may have a lot of specific things we would have to do that may make building using our build scripts much harder and likely require a lot of manual configuration and installation of dependencies.
