### ISSUE TITLE
Linux: Change filegroup membership from nagcmd to nagios

### ISSUE THREAD

**Issue by ccztux** [NagiosEnterprises/ncpa#233]
Hi!

A default nagios installation uses the linux group: nagcmd only for nagios.cmd file:

```
[root@localhost~]# grep nagcmd /etc/group
nagcmd:x:500:nagios,apache
[root@localhost~]# find /usr/local/nagios/ -gid 500
/usr/local/nagios/var/rw
/usr/local/nagios/var/rw/nagios.cmd
```

I dont know if group nagcmd is really necessary for NCPA. By default all files installed by NCPA have the following user/group membership:

```
drwxrwxr-x.  7 nagios nagcmd 4.0K Mar 15 18:54 ncpa
```

**Comment by jhomann** [comment]
I actually tend to agree with this. I am not sure why it was set to nagios:nagcmd but I'd much rather it be nagios:nagios like all the other projects we have. I'll set this as a bug and update it for 2.0.0.

**Comment by jhomann** [comment]
I've updated everything to use nagios:nagios now instead. Thanks for pointing this out! ad3defef05bed27e0a1557a82215626eb5a20fbd

**Comment by ccztux** [comment]
Hi!

Thank you for fixing this.
Have you overlook this?:

```
./ncpa/build/scripts/linux_build_setup.sh:72:groupadd nagcmd
```

**Comment by jhomann** [comment]
Yeah thanks for pointing that out! I've fixed it locally it'll get pushed here soon.
