### ISSUE TITLE
Specifying a custom port causes the web server live stats/graphs to not update

### ISSUE THREAD

**Issue by ssaxnagios** [NagiosEnterprises/ncpa#236]
The fix:

agent/listener/templates/graph.html

`var ws_loc = ws_protocol + '://' + loc.hostname + ':5693/api-websocket/' + '{{ graph_path }}';`

To:

`var ws_loc = ws_protocol + '://' + loc.hostname + ':' + loc.port + '/api-websocket/' + '{{ graph_path }}';`

agent/listener/templates/top.html

`var ws_loc = ws_proto + '://' + loc.hostname + ':5693/top-websocket/';`

To:

`var ws_loc = ws_proto + '://' + loc.hostname + ':' + loc.port + '/top-websocket/';`

**Comment by jhomann** [comment]
Fixed in 704a3fd5e6c42fc782ba268e966a25dc46ad88b0 and 7f1f33ef1f957859be2363f51578faeb12b5c90d unfortunately I had to make two commits... forgot to save the file when I did the first one :)

**Comment by ccztux** [comment]
Here the port is also hardcoded:

```
./ncpa/agent/listener/templates/tail.html:39:            var ws_loc = ws_proto + '://' + loc.hostname + ':5693/tail-websocket/' + '{{ tail_path }}';
./ncpa/agent/listener/templates/view-api.html:27:        <input class="view-api-input form-control" type="text" value="https://localhost:5693/api">
```

**Comment by jhomann** [comment]
Nice catch, those pages aren't finished yet - and tail isn't actually available since it doesn't work properly... hopefully we will get it implemented in time.
