### ISSUE TITLE
OS X does not have permissions to see most processes

### ISSUE THREAD

**Issue by jomann09** [NagiosEnterprises/ncpa#238]
While running the system-wide daemon as `nagios` the service cannot read most processes except those that are running as the user it is running as, which is `nagios` ... However, changing the `UserName` in the plist file to `root` runs the daemon as root and allows reading of all processes, giving much more information. This should be documented for people who want more information than what is available from a normal user. 

If anyone has any good ideas to get data on things like processes while not as root, please feel free to let me know so that I can test it out.

**Comment by jhomann** [comment]
As a side note: As a non-admin user you can run `ps aux` and get all information for processes so we can definitely, on a OS X box, parse the output with the processes that we get back from pstuil in order to get the stats for things like username, cpu, and memory usage.

**Comment by jomann09** [comment]
Double checked this and the problem still exists, will be writing a simple fix that runs the `ps aux` command to get the data we need and link it to the processes that get returned by psutil.

**Comment by jomann09** [comment]
Fixed in latest dev revision
