### ISSUE TITLE
IPv6 Support

### ISSUE THREAD

**Issue by celticguy42** [NagiosEnterprises/ncpa#246]
Running NCPA 1.8.1 on Windows.

ncpa_listener does not bind to IPv6 address, only IPv4 addresses.

**Comment by jomann09** [comment]
Have you edited the ncpa.cfg file to update the listen address? I am not sure if 0.0.0.0 will allow it to bind to an IPv6 address. Have you tried with `::1`? I have not done any testing on getting it to bind on an IPv6 address but I do know that we are running a WSGI server and whatever it can bind to is what the listener can use as long as it meets their formatting.

**Comment by celticguy42** [comment]
I need it to bind to the IPv4 and IPv6 addresses during the transition.

I just a quick test with :: as the ip on ncpa.cfg and it bound to IPv6, but not IPv4.  I also tried with nothing in the config for ip, and the service would not start.

**Comment by jomann09** [comment]
I am going to have to test this out, because it says that it can and should be able to bind to both, including updating the traffic to use IPv6 first, then IPv4 depending on what is available to the client.

**Comment by celticguy42** [comment]
Here's what's in my ncpa.cfg:

[listener]
uid = nagios
certificate = adhoc
loglevel = info
# Also tried deleting this entry completely, using :: (binds only to IPv6), 0.0.0.0, :: & 0.0.0.0 :: (service does not start)
ip = 0.0.0.0
gid = nagcmd
logfile = var/ncpa_listener.log
port = 5693
pidfile = var/ncpa_listener.pid
# Available versions: PROTOCOL SSLv2, SSLv3, TLSv1
ssl_version = TLSv1

**Comment by jomann09** [comment]
This looks like partial answer here https://github.com/gevent/gevent/pull/495. However I am unsure what else is causing this. I do believe that `""` should work but maybe when you do not supply an `ip` value in the config it breaks. I will test this.

**Comment by celticguy42** [comment]
I just tried "" on a system here (2012 R2), and it's only listening on 0.0.0.0 - nothing on IPv6.

**Comment by jomann09** [comment]
I meant that `""` would work with gevent 1.2.0 but that isn't out yet. We use a version of `WSGIServer` that is part of `gevent` for Python and from what I've read so far it looks like it can only bind to a port on either IPv6 or IPv4 currently. That should be fixed in 1.2.0 though, whenever that is available.

**Comment by jomann09** [comment]
Going to close this since there's not much we can do, with new versions of gevent this should work as expected though.

**Comment by jomann09** [comment]
If it is an issue with the gevent version (which I think it is) it should work in the next version of NCPA (whether it be 2.0.3 or 2.1.0) since when we build, gevent is always the latest available stable version.

**Comment by kenyon** [comment]
Binding to :: will create a dual-stack socket by default on most operating systems, including Windows and Linux.
