### ISSUE TITLE
Empty /agent/plugins list

### ISSUE THREAD

**Issue by ericloyd** [NagiosEnterprises/ncpa#247]
Wondering if anyone's seen this issue, where the /agent/plugins tree is empty?
```
]# curl -k --data "token=mytoken" "https://localhost:5693/api/agent/plugin"
{
  "value": {
    "plugin": []
  }
```
Yet /usr/local/nagios/libexec has lots of plugins:
```
# ls /usr/local/nagios/libexec/
Bcheck_asterisk_channels  check_clamd     check_dns       check_http          check_ircd    check_mrtgtraf     check_nt        check_overcr  check_sensors  check_ssmtp  check_users
Bcheck_asterisk_peers     check_cluster   check_dummy     check_icmp          check_jabber  check_mysql        check_ntp       check_ping    check_simap    check_swap   check_wave
Bcheck_by_ssh             check_dhcp      check_file_age  check_ide_smart     check_load    check_mysql_query  check_ntp_peer  check_pop     check_smtp     check_tcp    negate
check_apt                 check_dig       check_flexlm    check_ifoperstatus  check_log     check_nagios       check_ntp_time  check_procs   check_snmp     check_time   urlize
check_breeze              check_disk      check_ftp       check_ifstatus      check_mailq   check_nntp         check_nwstat    check_real    check_spop     check_udp    utils.pm
check_by_ssh              check_disk_smb  check_hpjd      check_imap          check_mrtg    check_nntps        check_oracle    check_rpc     check_ssh      check_ups    utils.sh
```
What am I missing?

**Comment by jomann09** [comment]
Your plugins directory is actually related to NCPA so, by default the `ncpa.cfg` has the plugins directory located at `plugins/` which is actually wherever you installed NCPA (normally `/usr/local/ncpa`) so it would be looking for plugins at `/usr/local/ncpa/plugins` by default. If you wanted it to look for the plugins in `/usr/local/nagios/libexec` then you just need to change the `plugins_dir` value in `ncpa.cfg`.

**Comment by ericloyd** [comment]
Okay, thanks.  That explains that.  Any idea why the plugins would not be installed as part of the rpm?  Never had to pay attention to that before.  Downloaded for CentOS 5 (can't be upgraded) via:
```
wget http://assets.nagios.com/downloads/ncpa/download.php?type=rpm&arch=x86&os=el5
```

**Comment by jomann09** [comment]
Because of the way NCPA works it doesn't ship with any plugins, nor does it require the base set of `nagios-plugins` (unlike NRPE) to be installed to monitor most of the generic information on the server.

**Comment by ericloyd** [comment]
I get that it doesn't require plugins.  Can you save me sometime of reading through what's in the rpm, and tell me how it gets the plugins if it doesn't install them?  Copy them from /usr/local/nagios/libexec?  If so, then it failed to do it in this instance.

**Comment by jomann09** [comment]
It doesn't add any plugins by default. By default the plugins directory will always be empty on install, no matter what exists on the server, etc. It doesn't try to populate it or anything, just creates the directory so that if you decide to add plugins on your own, you have a place to put them that will update in the API.

Some of this, I hope, will be explained better when I update the documentation for 2.0 and hopefully it will also be easier when the internal API browser is finished. There will be more information on things like what places/areas are used for and what to expect from them.

**Comment by ericloyd** [comment]
Thanks.  In a sense, that disturbs me even more, because that means that at some point, I copied /usr/local/nagios/libexec over to /usr/local/ncpa/plugins and both forgot that I did it AND forgot to update our installation documentation!  :-)  Thanks, @jomann09

**Comment by jomann09** [comment]
No problem, closing this then :)
