### ISSUE TITLE
Upgrade to use Python 3.5.x instead of 2.7.x

### ISSUE THREAD

**Issue by jomann09** [NagiosEnterprises/ncpa#248]
We have not done this upgrade due to the fact that `gevent-websocket` was not compatible with Python 3 and after some digging found it would be harder to get working than originally planned. However, it looks like at this time we will be able to use `gevent-websocket` `python3-support` branch located [in their git repos](https://bitbucket.org/noppo/gevent-websocket/src/2141053485feae3431488b2f3a486c520e4be444/?at=python3-support) and package it up and install on the build servers much like we do with the patched `cx_Freeze`, which happens to already work with Python 3.

Reasons for doing this are pretty much just performance increases. There are many parts in Python 3 that are much faster and more efficient than in Python 2.7.

This will most likely happen in a 2.1 or higher release since it looks like they might be almost done with Python 3 support in `gevent-websocket` anyway, so if they bring it out soon we can upgrade much easier.

**Comment by jm-welch** [comment]
I'll get a pull down and start looking for any other Py3 gotchas that can be updated without changing things (`print` statement vs `print()` function, etc). May not be any, but if there's anything that can be worked on in preparation, it's probably a good way to dive into the code to begin with.

**Comment by jomann09** [comment]
Sounds good. At one point I had it working in 3.x and I don't think it really requires all that many changes, the problem really lies in that `gevent-websocket` was not working which meant that all our graphs wouldn't display. Since that's a key part of the software and after tinkering with the module I couldn't get it to work so I decided to wait for a little bit. If they get the module out before 2.0.0 is released it might be worth upgrading purely for speed and efficiency boosts from Python 3.x.

**Comment by jomann09** [comment]
Looks like this + the `gevent-websocket` patch might just have to happen. It looks like gevent and ssl is causing major problems in new releases with `cx_Freeze` and whatnot. I cannot build Linux versions of the agent with the latest packages via `pip`.

**Comment by jomann09** [comment]
Experimental branch `dev-python3` has an updated code-base that works with Python 3.5.x as long as you install a special version of `gevent-websocket` which I will include in the `build/resources` folder for the time being. This was purely done as an experiment of the feasibility of starting to build with Python 3.5.x and I have not tested the actual freezing process.

As a side note, `cx_Logging` needs to be built and installed manually and requires a C++ compiler (VS 2015 works) in order to compile on windows. Also needs `pypiwin32` installed via `pip`.

**Comment by jomann09** [comment]
Hmm looks like `cx_Freeze` also is having problems with Python 3.5.x - how stupid. Looks like we have to wait on both packages to catch up and _maybe_ we can get it working... I can't test the build process without `cx_Freeze` obviously and that is sure to have lots of issues. Back to working with 2.7.x and getting this new release out!

**Comment by jomann09** [comment]
#261 relates to this. Once it's included we can make the changes we need to get Python 3 working with websockets in the `dev-python3` branch.

**Comment by jomann09** [comment]
Good news! We can use `karellen-geventws` and we can now use the updated version of `cx_Freeze` along with Python 3.5.x so I have started working on NCPA 3 in the `dev-v3` branch and have currently updated all of these in there and it is working. Closing this!
