### ISSUE TITLE
Error in Logical Disk API Request When Using Units

### ISSUE THREAD

**Issue by antonc42** [NagiosEnterprises/ncpa#249]
When using the units option and requesting all the logical disks (`/api/disk/logical/?token=token&units=K`), an error is displayed in the `device_name` of every disk: `"Error retrieving child: \"unsupported operand type(s) for /: 'str' and 'float'\"`. It does not matter what units are given, the error is always shown.

OS: CentOS 7 x86_64
NCPA: v1.8.1 via the `ncpa-1.8.1-1.el7.centos.x86_64.rpm` package

**Comment by jomann09** [comment]
Interesting! I can reproduce this on my CentOS 7 system here. I will have to check my CentOS 6 and see if it happens there also. With the changes to `units` in 2.0.0 on the back-end, this might already be resolved but I will do a couple tests to verify.

**Comment by jomann09** [comment]
I can actually confirm this is fixed in 2.0.0 so I am going to close this, and will mention it in the changelog.

**Comment by antonc42** [comment]
Awesome, thanks!
