### ISSUE TITLE
Update permissions in Linux (and verify Windows/OS X)

### ISSUE THREAD

**Issue by jomann09** [NagiosEnterprises/ncpa#252]
Need to verify the permissions of checks being ran. As it stands it looks like the permissions are not properly set when executing a plugin. Also need to document the way permissions work better in NCPA. Since I was not the original author, I do not know how they were intended to work, but we can find a good way we believe they should work and put in the proper permissions to secure the agent better.

**Comment by jm-welch** [comment]
I have actually always had questions about this. The installer creates a Nagios account, but it seems like the API and its constituent processes run as root. What is the intended run level for the listener and for plugins?

Honestly, what I'd like is something similar to Ansible's "become" statement, where we could specify that a specific plugin needs to run as root instead of nagios, but have the assumption that everything should run as a non-privileged user. I realize that may be prohibitively complex to code, but hey - it's nice to want things.

**Comment by jomann09** [comment]
I do think that is how we should go about doing it. I just don't know what the original intent of the way it currently runs is. I would definitely like to give people the option to run certain plugins as a specific user, and to default to run as the nagios user and not root.

**Comment by jm-welch** [comment]
The issue there is that, to have the agent run as a non-root user, but still be able to execute a plugin as a root user (or another user), the non-root user running the agent would need to have password-less su/sudo access (afaik), which kinda defeats the purpose, or you'd have to pass a password as part of the API call - which leaves it open to interception - or specify it in a file on the machine being monitored - which, in addition to potentially being quite insecure, requires even more manual manipulation of the clients, especially if that password changes regularly.

Might need the daemon to run as root, with the web service and plugins running as a non-privileged user, unless specified by the API call?

**Comment by jomann09** [comment]
I'm okay with the daemon running as root as long as everything it does besides it's internals are done as a user unless properly escalated via config values specified in the config somewhere on the system. I think if that is fixed, and we document how it runs, it'll resolve most issues people have regarding permissions.

**Comment by jomann09** [comment]
I added this in with 9e4eeb7f337f12ef87321d0a73ca9f5d05f810fd and I think that it will work as intended. I will test it before I close this task. The only issue I could see is the environment and if we have to we can set environment variables for the user too.

**Comment by jomann09** [comment]
Tested this and it looks like the plugins are properly running as the nagios user. The one exception to this is on Windows, where it runs it as a service, which is acceptable for the Windows environment. There are ways to limit the powershell execution based on the `plugin directives` section.
