### ISSUE TITLE
check_ncpa.py throws error in case a proxy is set

### ISSUE THREAD

**Issue by ccztux** [NagiosEnterprises/ncpa#263]
If a proxy is set on the nagios server, check_ncpa.py is using this proxy and throws an error.

Without proxy:

```
[root@localhost ~]# env | grep -i proxy
http_proxy=
FTP_PROXY=
ftp_proxy=
SOCKS_PROXY=
socks_proxy=
HTTPS_PROXY=
https_proxy=
HTTP_PROXY=

[root@localhost ~]# /usr/local/nagios/libexec/check_ncpa.py -H host_to_check -t token -M /service/Dhcp/running -v
Connecting to: https://host_to_check:5693/api/service/Dhcp/running/?token=token&check=1
File returned contained:
{
  "value": {
    "returncode": 2,
    "stdout": "CRITICAL: Service Dhcp is stopped"
  }
}
An error occurred:No JSON object could be decoded

```

With proxy:

```
[root@localhost ~]# env | grep -i proxy
http_proxy=http://user:password@proxy:port
FTP_PROXY=http://user:password@proxy:port
ftp_proxy=http://user:password@proxy:port
SOCKS_PROXY=http://user:password@proxy:port
socks_proxy=http://user:password@proxy:port
HTTPS_PROXY=http://user:password@proxy:port
https_proxy=http://user:password@proxy:port
HTTP_PROXY=http://user:password@proxy:port

[root@localhost ~]# /usr/local/nagios/libexec/check_ncpa.py -H host_to_check -t token -M /service/Dhcp/running -v
Connecting to: https://host_to_check:5693/api/service/Dhcp/running/?token=token&check=1
An error occurred:<urlopen error Tunnel connection failed: 403 Forbidden>

```

I dont know, how to handle this. Maybe check_ncpa.py should ignore the proxy?

**Comment by jomann09** [comment]
The `check_ncpa.py` script uses the default Python urllib library and `urlopen`, which is what is giving the error. If you don't want it to use the proxy then we'd have to look up a way to tell Python to ignore the system settings. Checking quickly it looks like you might be able to set a `NO_PROXY` environment variable to tell it not to use it. More info here: http://stackoverflow.com/questions/28521535/requests-how-to-disable-bypass-proxy

**Comment by jomann09** [comment]
This won't be changed in NCPA 2 and likely won't be changed in the future. We are just using the standard urlopen from Python and if it uses proxies it does - I haven't been able to find anything that allows you to tell it not to use it.

**Comment by clanli** [comment]
# Turn off proxy
os.environ['no_proxy'] = '*'
