### ISSUE TITLE
Feature request: allowed_hosts config directive

### ISSUE THREAD

**Issue by ccztux** [NagiosEnterprises/ncpa#264]
Hi!

An allowed_hosts config directive in ncpa.cfg would be nice to restrict access to one or multiple ip`s/subnets.

**Comment by jomann09** [comment]
Good idea, I'll add this into the FR for 2.1.0

**Comment by jomann09** [comment]
Added in ec866eb0c3a1fec4518a72ba63498cdcc40fe008
