### ISSUE TITLE
Ncpa configurations

### ISSUE THREAD

**Issue by karatalapu80** [NagiosEnterprises/ncpa#267]
Hi;

I am trying to test ncpa passive checks. I have few questions/issue while setting I was hoping you could help me out with.

1.  When trying to add custom plugin, I added the plugin path to the [plugin directives] but I am seeing the below error on the nagios server. 
   Unable to run check on non-child node. Revise your query.

Here is my plugin directives definition.

[plugin directives]
plugin_path = plugins/ /usr/lib64/nagios/plugins/
.sh = /bin/sh $plugin_name $plugin_args
.ksh = /bin/ksh $plugin_name $plugin_args
.py = /usr/bin/python $plugin_name $plugin_args
.pl = /usr/bin/perl $plugin_name $plugin_args
.ps1 = powershell -ExecutionPolicy Bypass -File $plugin_name $plugin_args
.vbs = cscript $plugin_name $plugin_args //NoLogo

2. How can I setup custom sleep time for different checks.

-Krishna

**Comment by jomann09** [comment]
So the first part, you want to use just the full plugin path if you're going to change it. The default value of `plugins/` is relative to your NCPA install... so if you want to use your plugins in the Nagios plugins directory just remove that and do this:
`plugin_path = /usr/lib64/nagios/plugins/`

For the second part - you cannot set individual sleep times in NCPA 1.8.1 and below. In 2, there is a way to set sleep times when you define the check by adding an optional `|<sleeptime>` to the end of the `<hostname>|<servicename> = <check>`

**Comment by karatalapu80** [comment]
Do you know when is the version 2 going to be available ?

-Krishna

**Comment by jomann09** [comment]
I am finishing up documentation and code cleanup right now... My estimate is an RC1 will be available for select systems very soon ~ sometime in the next week or so.
