### ISSUE TITLE
check_ncpa.py

### ISSUE THREAD

**Issue by mkhammar** [NagiosEnterprises/ncpa#273]
Hi, 

I did some test with version 2.0 and the check_ncpa.py v 1.0.1 but I faced some issues with the arguments when I'm trying to run a plugin.

I never been able to run any scripts with arguments getting "You cannot specify arguments and try to run a plugin." when I'm running:
check_ncpa.py -v -H  host -t token -M 'plugins/check_idle_cpu.sh' -a ' 10 5'

I tried to run the same plugin but changing the metric argument:
check_ncpa.py -v -H  host -t token -M 'agent/plugin/check_idle_cpu.sh' -a ' 10 5'
Unfortunately I got the "Could not parse arguments" error:
check_idle_cpu.sh: Could not parse arguments
Please include two arguments, eg.
Usage: /usr/local/ncpa/plugins/check_idle_cpu.sh {warning} {critical}
Example :-
/usr/local/ncpa/plugins/check_idle_cpu.sh 20 10

Anyway, I found a fix, I modified the following line:
git diff
diff --git a/client/check_ncpa.py b/client/check_ncpa.py
index 9315241..3c904e5 100755
--- a/client/check_ncpa.py
+++ b/client/check_ncpa.py
@@ -109,7 +109,7 @@ def parse_args():
         print(version)
         sys.exit(0)
 
-    if options.arguments and options.metric and not 'agent/plugin' in options.metric:
+    if options.arguments and options.metric and not 'plugins/' in options.metric:
         parser.print_help()
         parser.error('You cannot specify arguments and try to run a plugin.')

And now, all is working like a charm, but I just would like to inform you and to make sure this is the right way to fix the issue.

Thx

**Comment by jomann09** [comment]
Thanks for pointing this out - I am not sure why it is worded that way ... it's confusing but either way I fixed the check in 1.0.2 and made the commit here cdb723fdd6cb2195425ab4fbccb5a772c6244540

Does the "could not parse arguments" error still happen? Can you show me the output using -v? I will test it on my end too.

**Comment by mkhammar** [comment]
No "could not parse arguments" errors anymore.

I updated the script with your last commit, and it works. Below the out with -v:

check_ncpa.py -v -H host -t token -M plugins/check_idle_cpu.sh -a '10 5'
Connecting to: https://host:5693/api/plugins/check_idle_cpu.sh/10/5?token=token&check=1
File returned contained:
{
    "returncode": 0, 
    "stdout": "OK: CPU Idle = 98.20% | CpuUser=0.60; CpuNice=0.00; CpuSystem=1.19; CpuIowait=0.01; CpuSteal=0.00"
}
OK: CPU Idle = 98.20% | CpuUser=0.60; CpuNice=0.00; CpuSystem=1.19; CpuIowait=0.01; CpuSteal=0.00

Thx

**Comment by jomann09** [comment]
Looks good, thanks for your help with this!
