### ISSUE TITLE
[Windows/Update 1.8.1 ==> 2.0.0] Add new sample config file or new directives

### ISSUE THREAD

**Issue by ccztux** [NagiosEnterprises/ncpa#275]
I have already updated NCPA 1.8.1 to 2.0.0 on my windows box. It would be great, if the new config directives would be added to ncpa.cfg automatically or otherwise the installtion would add a sample config file like ncpa.cfg.2.0.0.sample, so that you could make a diff on it and add the new directives manually.

**Comment by jomann09** [comment]
The sample should be in there, I just looked at mine and noticed that it does not get packaged with the current Windows build... I am not sure why, but will get this in the next release.

As for plugin directives, it's a bit hard to edit them nicely, but will look into it.

**Comment by jomann09** [comment]
New sample config (which will be updated on upgrades) has been added in 4ab655d1c0d7e44098bc40e7d2c35b881c2a2864.

Also fixed issue where Windows was missing the example.cfg/README in the ncpa.cfg.d directory.
