### ISSUE TITLE
[Windows/Update 1.8.1 ==> 2.0.0] NCPA services were set to autostart

### ISSUE THREAD

**Issue by ccztux** [NagiosEnterprises/ncpa#276]
After update from 1.8.1 to 2.0.0 both windows services (ncpa_listener and ncpa_passive) were set to starttype: automatic. It would be great, if the update of the agent would not change the starttype of the services.

**Comment by jomann09** [comment]
I will look into this a bit more in depth, but from what I can tell - it doesn't look like we can change this easily since it's part of the way cx_Freeze does services... you either set the value to auto-start or you don't.

**Comment by jomann09** [comment]
This will be fixed in 2.0.1 - it only restarts the service and doesn't re-install it, since the settings do not change it doesn't need to wipe the service settings. Fixed in 392cefe019bcb28bd7e0445f4e910e35b03f5168.
