### ISSUE TITLE
[Windows/Update 1.8.1 ==> 2.0.0] Could not close plugin arguments help box

### ISSUE THREAD

**Issue by ccztux** [NagiosEnterprises/ncpa#278]
Hi!

I can not close the plugin arguments help box under:
"GUI/API/API Endpoint/Plugins/Plugin Arguments/?"

```
<div id="popover342626">
```

Browser: Firefox 50.1.0

**Comment by jomann09** [comment]
If it's a popover, it's the bootstrap popup and you have to press the (?) again to close it. Is that not working either? (just tested in firefox)

I could add the `data-trigger="dismiss"` to them in order for them to go away on next click off them.

**Comment by ccztux** [comment]
Thank you, this works. For me this was a little bit confusing, so i would prefer the ```data-trigger="dismiss"``` method. :-)

**Comment by jomann09** [comment]
Fixed in f646e6445e62b3e5d00f145b9fb9cd7f0c26ea86
