### ISSUE TITLE
[Windows XP, fresh install 2.0.0] No ncpa_listener, ncpa_passive services after installation

### ISSUE THREAD

**Issue by ccztux** [NagiosEnterprises/ncpa#279]
Hi!

I have already installed the new version 2.0.0 on a new Windows XP machine. Installation completed successfully, but the two services (ncpa_listener, ncpa_passive) doesnt exist.

Windows XP Version: Microsoft Windows XP [Version 5.1.2600]

**Comment by jomann09** [comment]
Hmm, can you post the output of the ncpa_listener log that is in the main directory? (`C:\Program Files (x86)\Nagios\NCPA`) The actual ncpa_listener and ncpa_passive .exe files are what create the services... I have a feeling we might need to drop XP support if `pypiwin32` no longer works on XP.

**Comment by jomann09** [comment]
Alright I tested this on a XP version I have and it looks like `psutil` no longer supports XP - meaning I am going to remove XP support also. Updated readme.
