### ISSUE TITLE
[2.0.0 Question] GUI/Live Data/Top Processes/Threshold Boxes

### ISSUE THREAD

**Issue by ccztux** [NagiosEnterprises/ncpa#280]
What should the threshold boxes: Warning/Critical here do? I have entered serveral values, but nothing happens.

**Comment by jomann09** [comment]
They should highlight the boxes in the memory/cpu usage when the threshold is met. It looks like this broke when the page got updated. I'll tag this as a bug.

**Comment by jomann09** [comment]
Fixed in f646e6445e62b3e5d00f145b9fb9cd7f0c26ea86
