### ISSUE TITLE
v2.0.0 on OEL 7.2, which RPM prerequisites?

### ISSUE THREAD

**Issue by AMG1978** [NagiosEnterprises/ncpa#284]
We have over 3000 Linux servers in our environment (most without NCPA), and I am not a Unix admin, nor am I the people who provision these things.  This is just an application server that I need monitoring on, and previously had v1.8.1 x64 for EL6 installed and working fine.  Other servers with almost the same name "i001" vs "d002" seem to work, so I know there has to be some RPM differences, but I figured I'd just come straight out and ask what prerequisites are needed to avoid this error I am getting below.  This is OEL 7.2 x64.

[myname@servernamei001 ~]$ sudo service ncpa_listener restart
Stopping NCPA Listener: /usr/local/ncpa/ncpa_listener: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /usr/local/ncpa/ncpa_listener)
/usr/local/ncpa/ncpa_listener: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /usr/local/ncpa/libpython2.7.so.1.0)
                                                           [FAILED]
Starting NCPA Listener: /usr/local/ncpa/ncpa_listener: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /usr/local/ncpa/ncpa_listener)
/usr/local/ncpa/ncpa_listener: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /usr/local/ncpa/libpython2.7.so.1.0)
                                                           [FAILED]
[myname@servernamei001 ~]$ rpm -qa | grep glib
glib2-2.28.8-5.el6.x86_64
glibc-devel-2.12-1.192.el6.x86_64
dbus-glib-0.86-6.el6_4.x86_64
glibc-2.12-1.192.el6.x86_64
glibc-2.12-1.192.el6.i686
glibc-common-2.12-1.192.el6.x86_64
glibc-headers-2.12-1.192.el6.x86_64
[myname@servernamei001 ~]$ ls -al /lib64/libc.so.6 
lrwxrwxrwx. 1 root root 12 Aug 26 13:34 /lib64/libc.so.6 -> libc-2.12.so

It may be "compat-glibc-2.12-4.el7.x86_64" but at this moment, the RHN (Spacewalk) isnt setup properly on the hosts, so I cant even test by adding other stuff Yet...

Any thoughts?

**Comment by jomann09** [comment]
Looks like the rpm version you are using requires `glibc` version 2.14 and it's running 2.12 ... you're using the El7 rpm right? And you're trying to install on OEL 7.2 - which "should" have the same versions of glibc on them... I can spin up a OEL 7 and take a peek myself... we may have to build an rpm special for that distro and version if they messed with packages.

I know they've messed with some others in the OEL 7.x versions so it isn't actually that surprising to me.

**Comment by AMG1978** [comment]
So for this app team they have 2 dev, 2 int, 2 qa, 2 prod.  For their 2 dev servers, the same el7 rpm works great.  For all the other 6, it complains with glibc errors.

$ rpm -qa | grep ncpa
ncpa-2.0.0-1.el7.centos.x86_64

You can see the "rpm -qa | grep glibc" above for the failing i001
Here it is for the working d001.

$ rpm -qa | grep glibc
compat-glibc-2.12-4.el7.x86_64
glibc-common-2.17-106.0.1.el7_2.8.x86_64
glibc-headers-2.17-106.0.1.el7_2.8.x86_64
compat-glibc-headers-2.12-4.el7.x86_64
glibc-devel-2.17-106.0.1.el7_2.8.x86_64
glibc-2.17-106.0.1.el7_2.8.x86_64


Now that I look at it, it seems these are 2.17, so if the RPM needs 2.14, and that failing box had 2.12 I can understand.  If 2.17 is acceptable as it supercedes 2.14, then thats why it works

You agree?  If so I need to ask why d001/d002 are updated and the others are not.  It could be related to the fact that if you do any "yum" command on the 6 failing boxes, it says cant connect to the Spacewalk / RHN server, so possibly fix that and the unix team updates fully.

I'll actually open a ticket for these guys and get that ball rolling.  Thx

**Comment by jomann09** [comment]
I believe that your assessment is correct, although the above i001 is running el6 though according to your output from the `rpm -qa` right?

**Comment by AMG1978** [comment]
good eyes.  I just installed to d001, d002, then figured i001, i002, q001, q002, p001, p002 were all el7.  same apps, same naming convention, etc.  Nope, they are el6.  I installed the 2.0 el6 and it is fine.

Sorry about this...  I still need to find out why theyd be different distro versions, but i now know the root cause of the issue.

thanks for a keen eye.

**Comment by jomann09** [comment]
No problem, just so you are aware though there is a known issue with upgrades on linux systems. Since it no longer runs as root, you may need to clear out your temp files in `/tmp` that have "ncpa" in their name since they will be root `rw` only. Or I suppose you can just give them proper permissions (`nagios:nagios` default now) and it'd do the same thing.

I plan on having the service change the permissions on it's files on startup before dropping user level for the next bug fix release.
