### ISSUE TITLE
NCPA 2.0 on Windows 2012 Monitoring Multiple Related Services with Search Match

### ISSUE THREAD

**Issue by kevinjm** [NagiosEnterprises/ncpa#286]
Hi Folks,

Kudos on the release of 2.0.  I'm excited to put some of the new features to work.  

I'm hoping someone could help me out.  I'm trying to monitor multiple windows services with the name of Sophos.  For example, when using the API tool in the web UI, I can match multiple instances of Sophos as seen below:

https://x.x.x.x/api/services?service=sophos&match=search

{
    "services": {
        "Sophos Web Control Service": "running",
        "Sophos Agent": "running",
        "Sophos Message Router": "running",
        "Sophos AutoUpdate Service": "running",
        "sophossps": "running"
    }
}

However when I enable the "Run as a Nagios check", i get the following:

https://x.x.x.x:5693/api/services?service=sophos&match=search&check=true&status=running
{
    "returncode": 2,
    "stdout": "CRITICAL: Service sophos was not found"
}

Any ideas?  What am I doing wrong?

Thanks!

-Kevin

**Comment by jomann09** [comment]
You are doing nothing wrong! It appears to be a bug, the check seems to be doing an exact match which is causing this issue. I'll take a look and should be able to get this fixed for 2.0.1

**Comment by jomann09** [comment]
Fixed in 4eedbcd1a32684c83f80c7767d1e2a532180911b
