### ISSUE TITLE
[NCPA 2.0.1/Windows] Dead website link in NCPA installer

### ISSUE THREAD

**Issue by ccztux** [NagiosEnterprises/ncpa#292]
At the last step, when installing NCPA on Windows, there is a website link: "View NCPA website and documentation":
```
https://www.nagios.org/ncpa/
```

But this link delivers http error code: 403 Forbidden

**Comment by jomann09** [comment]
Nice to see you noticed that, the website is in the process of being finalized for uploading

**Comment by jomann09** [comment]
Just for the record it was just uploaded

**Comment by ccztux** [comment]
The new homepage looks cool. Its a great pitty, that it is very hard to find something about NCPA on nagios.org

**Comment by jomann09** [comment]
That should be changing over time. As the stability of NCPA improves and we get more of it completed we can push it forward as our preferred agent - but we still have a bit or work to do.
