### ISSUE TITLE
[NCPA 2.0.1/Windows Update] Services are running after update

### ISSUE THREAD

**Issue by ccztux** [NagiosEnterprises/ncpa#293]
Hi Jake!

Thank you for your great work on NCPA!

The issue #276 is solved when updating from 2.0.0 to 2.0.1. The service config will not be changed by the installer, but both services are started after update, allthough they where set to start type manual.

**Comment by jomann09** [comment]
So the issue I had with this is finding out the process state before the install. Unfortunately it's quite annoying to do inside the NSIS script. If you think it's worth the time I can add this as a feature request.

**Comment by jomann09** [comment]
I will try to get this into 2.1 if possible.
