### ISSUE TITLE
request for libffi5  blocks install of ncpa-2.0.1.d7.amd64.deb - Ubuntu Linux 14.04.5

### ISSUE THREAD

**Issue by ashleydrees** [NagiosEnterprises/ncpa#300]
I was upgrading NCPA from ncpa-1.8.1-1.amd64.deb to ncpa-2.0.1.d7.amd64.deb - the install fails due to a dependancy on libffi5, we have libffi6 installed on 14.04.5 - installing ncpa-2.0.0.amd64.deb does not throw up this dependancy.

Unpacking ncpa (2.0.1-1) over (1.8.1-1) ...
dpkg: dependency problems prevent configuration of ncpa:
 ncpa depends on libffi5 (>= 3.0.4); however:
  Package libffi5 is not installed.

**Comment by jomann09** [comment]
Looks like you were using the wrong deb file. The d7 version is for Debian 7 only (Debian 8 and Ubuntu 12-16) and I think what you want is this one: https://assets.nagios.com/downloads/ncpa/ncpa-2.0.1.amd64.deb

**Comment by ashleydrees** [comment]
Thanks.

That did the job.. no idea how i got ncpa-2.0.1.d7.amd64.deb - i guess d7 is deb 7

---

A B D
t:+447968726775
e:ash@trellick.net <mailto:ash@trellick.net>

**Comment by jomann09** [comment]
Yup it is, you probably just clicked the wrong one in the list. I actually updated the links to the new page which has them shown differently since I forgot to update it when I did the last release.
