### ISSUE TITLE
[NCPA 2.0.2/Windows Update] Livedate and graphs are not working

### ISSUE THREAD

**Issue by ccztux** [NagiosEnterprises/ncpa#305]
After update from 2.0.1 to 2.0.2 on Windows 7 system, i cant see any livedata or graphs.

**Comment by jomann09** [comment]
It looks like when I updated the build server it put in the wrong version of `gevent-websocket` and I've re-build the .exe file for 2.0.2 - it should be updated in about 10 minutes. You can just re-install the new one over the old one.

**Comment by ccztux** [comment]
It works like a charm. :-)
Thanks!
