### ISSUE TITLE
[NCPA 2.0.2/Windows] Fresh installation: Error opening file for writing

### ISSUE THREAD

**Issue by ccztux** [NagiosEnterprises/ncpa#306]
I have deinstalled 2.0.1 and wanted to install 2.0.2 on Windows 7. The installation runs into following error:
```
Error opening file for writing:
C:\Program Files (x86)\Nagios\NCPA\etc\ncpa.cfg

Click Abort to stop the installation,
Retry to try again, or
Ignore to skip this file.
```

Retrying doesnt work. If i click to Ignore, the next error ocures:
```
Error opening file for writing:
C:\Program Files (x86)\Nagios\NCPA\etc\ncpa.cfg.sample

Click Abort to stop the installation,
Retry to try again, or
Ignore to skip this file.
```

Retrying doesnt work. If i click to Ignore, the next error ocures:
```
Error opening file for writing:
C:\Program Files (x86)\Nagios\NCPA\etc\ncpa.cfg.d\example.cfg

Click Abort to stop the installation,
Retry to try again, or
Ignore to skip this file.
```

Retrying doesnt work. If i click to Ignore, the next error ocures:
```
Error opening file for writing:
C:\Program Files (x86)\Nagios\NCPA\etc\ncpa.cfg.d\README.txt

Click Abort to stop the installation,
Retry to try again, or
Ignore to skip this file.
```

After the installation there is no \etc\ directory.

**Comment by jomann09** [comment]
When you un-installed, did you happen to have the old etc files open? Typically, if something is holding the file open you will not be able to install due to the process not able to write to it - same if you try to un-install it won't remove files that it cannot open.

**Comment by ccztux** [comment]
Thank you for your reply and support. I have retried it and it worked without issues. I have not opened the file with an editor, but in the cli (cmd) the cwd was the NCPA directory, already when i have uninstalled NCPA. Maybe this caused this issue.

**Comment by jomann09** [comment]
Oh yeah, that definitely causes problems in windows - if you're inside the directory in the cli it will not remove the files due to the weird locking it has in place! Good to know it was resolved.
