### ISSUE TITLE
RHEL 6.8 Installation Problem

### ISSUE THREAD

**Issue by sm00thindian** [NagiosEnterprises/ncpa#307]
The install of the NCPA agent went in without error.  However, when attempting to start we get the following error.

Starting NCPA Listener: /usr/local/ncpa/ncpa_listener: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /usr/local/ncpa/ncpa_listener)
/usr/local/ncpa/ncpa_listener: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /usr/local/ncpa/libpython2.7.so.1.0)

**Comment by sm00thindian** [comment]
This is the systems glib situation:
[root@br1plpnrt019 lib64]# ls -l libc*
-rwxr-xr-x  1 root root 1930416 Jan 28  2016 libc-2.12.so
lrwxrwxrwx. 1 root root      18 Aug 24 21:09 libcap-ng.so.0 -> libcap-ng.so.0.0.0
-rwxr-xr-x. 1 root root   18672 Nov  5  2010 libcap-ng.so.0.0.0
lrwxrwxrwx  1 root root      14 Sep 27 15:21 libcap.so.1 -> libcap.so.1.10
-rwxr-xr-x  1 root root   15224 Aug 24  2010 libcap.so.1.10
lrwxrwxrwx. 1 root root      14 Aug 24 21:09 libcap.so.2 -> libcap.so.2.16
-rwxr-xr-x  1 root root   19016 Aug 23  2011 libcap.so.2.16
lrwxrwxrwx  1 root root      19 Sep 27 14:22 libcgroup.so.1 -> libcgroup.so.1.0.40
-rwxr-xr-x  1 root root  103096 Jun 22  2016 libcgroup.so.1.0.40
-rwxr-xr-x  1 root root  201632 Jan 28  2016 libcidn-2.12.so
lrwxrwxrwx  1 root root      15 Sep 27 14:21 libcidn.so.1 -> libcidn-2.12.so
lrwxrwxrwx  1 root root      17 Sep 27 14:21 libcom_err.so.2 -> libcom_err.so.2.1
-rwxr-xr-x  1 root root   17256 Jun  4  2015 libcom_err.so.2.1
-rwxr-xr-x  1 root root   43928 Jan 28  2016 libcrypt-2.12.so
lrwxrwxrwx  1 root root      22 Sep 27 14:22 libcryptsetup.so.1 -> libcryptsetup.so.1.1.0
-rwxr-xr-x  1 root root   97592 Jun 23  2014 libcryptsetup.so.1.1.0
lrwxrwxrwx  1 root root      16 Sep 27 14:21 libcrypt.so.1 -> libcrypt-2.12.so
lrwxrwxrwx  1 root root      12 Sep 27 14:21 libc.so.6 -> libc-2.12.so

**Comment by jomann09** [comment]
My version of CentOS 6 that we build on is giving me the same (libc.so.6 -> libc-2.12.so) which makes me wonder which rpm you ended up downloading, can you link the RPM URL?

**Comment by sm00thindian** [comment]
https://assets.nagios.com/downloads/ncpa/ncpa-2.0.2.el7.x86_64.rpm

**Comment by sm00thindian** [comment]
Is it because it's not an el6 package?

**Comment by sm00thindian** [comment]
For some reason, selecting the RHEL 6.x didn't update the download.  We downloaded the EL6 rpm and didn't have an issue.  I am now getting authentication issues.  But the agent appears to be running.

**Comment by jomann09** [comment]
Oh yeah sorry was in a meeting, yes that would definitely be why. What is the authentication issue? Is it related to the NCPA service?

**Comment by sm00thindian** [comment]
The service is running but getting unknown alerts in Nagios Xi

**Comment by jomann09** [comment]
Oh, did you upgrade from < 2.0.0 ? You may need to go to your config wizard management page in the Admin section and check for updates - make sure your NCPA wizard is up-to-date so that you get the lastest version of check_ncpa.py

**Comment by sm00thindian** [comment]
1.8.1 to 2.0.2

**Comment by sm00thindian** [comment]
We're upgrading our xi instance to 5.4 will that resolve any ncpa check
issues?

**Comment by jomann09** [comment]
You will still need to update the config wizard, since the 5.4 upgrade doesn't force the config wizards and components to upgrade. You can install the upgrade for the wizard right inside XI in the "Manage Config Wizards" page in the admin section.

**Comment by sm00thindian** [comment]
We're an offline system

**Comment by jomann09** [comment]
Oh that makes sense then, can you download and upload this in that section though?
https://assets.nagios.com/downloads/nagiosxi/wizards/xi5/ncpa.zip

If not, you can open that zip file up, grab the check_ncpa.py file and place it in /usr/local/nagios/libexec on the XI server and make sure to chmod +x it.
