### ISSUE TITLE
Windows silent Install removes the IP address from the listener section in the ncpa.cfg file.

### ISSUE THREAD

**Issue by tgriep** [NagiosEnterprises/ncpa#310]
When installing NCPA version 2.0.2 and using the silent install, the listener ip address is left blank in the ncpa.cfg file causing the agent to only listen on the localhost / 127.0.0.1 IP address and no others.
ip = 

It should default to 0.0.0.0 like the example below to listen on all IP address or it should be customized on the command line when a silent install is used.
ip = 0.0.0.0

**Comment by jomann09** [comment]
I'll make this change for the next bug fix or 2.1 if there are no more bug fix releases before then.

**Comment by jomann09** [comment]
Fixed in 695c3bf8cf3e68c187998436b4bfcf52e9aac120
