### ISSUE TITLE
Typo in the default ncpa.cfg file.

### ISSUE THREAD

**Issue by tgriep** [NagiosEnterprises/ncpa#311]
The example for the default port for the listener is
# Default: port = 5963
and it should be
# Default: port = 5693

The 9 and 6 are transposed. Should be fixed to avoid confusion.

**Comment by TechnoChimp** [comment]
The current version 2.0.2 from the website still has this bug in it.

**Comment by jomann09** [comment]
Yeah it's fixed in 2.0.3 which I am building right now

**Comment by TechnoChimp** [comment]
Awesome, thanks for the update.
