### ISSUE TITLE
Add more options for Windows silent install

### ISSUE THREAD

**Issue by jomann09** [NagiosEnterprises/ncpa#312]
Add additional options for windows silent install, possibly including IP, Port, and a couple others.

**Comment by jomann09** [comment]
Added additional IP and PORT options in a2370ff

**Comment by jvandermeulen** [comment]
@jomann09 Silent install parameter /PORT is not documented, neither at https://assets.nagios.com/downloads/ncpa/docs/Installing-NCPA.pdf nor at https://www.nagios.org/ncpa/getting-started.php#win-silent-install)

If `/PORT` is omitted during a silent install it is set to an empty string: `port =`.  That's a cosmic problem only. A more serious problem is that remote connections cannot be made to NCPA 2.1.6 systems if `/IP` is  omitted. In ncpa.cfg the option is also set to an empty string `ip =` but it actually **blocks** non-local traffic. It took me quite a while to find that the default '0.0.0.0' should be in that file. 
I noticed it happened on Windows 2016 and 2019 server edition, possibly on other editions as well.
Could you reopen this issue and mark this as bug as well as documentation issue?

**Comment by jomann09** [comment]
I've actually fixed the second part of this, and it'll be out for the next version, basically it's setting it to `::` instead of `0.0.0.0` as the default when it loads up. I'll mark it in the changelog and will add the port specification to the documentation.

**Comment by jvandermeulen** [comment]
@jomann09 Could you please double check that IP is not set to and empty string on Windows? I notice the difference between https://github.com/NagiosEnterprises/ncpa/blob/v2.1.5/agent/ncpa_windows.py#L136 and https://github.com/NagiosEnterprises/ncpa/blob/v2.1.6/agent/ncpa_windows.py#L136 but on all v2.1.6 silent installs these options are left blank:

listener section:
- ip =
- port =

nrdp section:
- hostname =

Isn't `::` for linux servers only? I was referring to Windows 2016 and 2019 Server Edition.
Leaving IP blank won't work from non-local connections and setting '::' won't work either.

Attached you'll find a screenshot of two ncpa.cfg file, on the left hand side a graphical install (accepting all defaults) and on the right hand side a silent install (with no params at al)

![ncpa_216_silent_install](https://user-images.githubusercontent.com/838001/52820497-7069c980-30ac-11e9-850f-5050536f12c4.png)

**Comment by jomann09** [comment]
Yes in 2.1.6 it was, but if you check in master it is not.
