### ISSUE TITLE
2.0.2 + 1.1.0 returns subset of results on plugin interrogation.

### ISSUE THREAD

**Issue by ashleydrees** [NagiosEnterprises/ncpa#313]
check_ncpa.py __VERSION__ = '1.1.0' + NCPA 2.0.2 
...using the web API to check a remote PBX suggests...

./check_ncpa.py -H ncpa.server -t token -M 'plugins/check_asterisk_peers/-t sip/-p '227 320 333''

suggests I should get an answer..

OK: 227, 320, 333

The GUI for core reports OK: 227

From the CORE server CL.
./check_ncpa.py -H ncpa.server -t  token -M 'plugins/check_asterisk_peers/-t sip/-p '227 320 333''
OK: 227

On the PBX
./check_asterisk_peers -t sip -p '227 320 333'
 OK: 227, 320, 333

Is there something that i should do to get the full reply from the plugin as it seems that i am just getting the first item - or is this an issue with 2.0.2/1.1.0?

**Comment by jomann09** [comment]
The quoting looks like it might be one of the issues, can you try using "" on the outside, like this:
```
./check_ncpa.py -H ncpa.server -t token -M "plugins/check_asterisk_peers/-t sip/-p '227 320 333'"
```

If that doesn't work it could also be an issue with the way the json is formatted, but I think that the ending single `'` is causing the space to create a second argument that is passed to check_ncpa.py and since it doesn't know what to do with it, it's likely just thrown out.

**Comment by ashleydrees** [comment]
OK, that does the trick - but that quoting scheme i used directly from NCPA 2.0.2 from its example - does this mean any example that has double single quotes will not work?

---

A B D
t:+447968726775
e:ash@trellick.net <mailto:ash@trellick.net>

**Comment by jomann09** [comment]
For the actual check you have to follow command line quoting so really this should also work:
```
./check_ncpa.py -H ncpa.server -t token -M 'plugins/check_asterisk_peers/-t sip/-p "227 320 333"'
```
This other one may work, but I'm not 100% certain how it quotes this when it runs it on the NCPA side:
```
./check_ncpa.py -H ncpa.server -t token -M 'plugins/check_asterisk_peers/-t/sip/-p/227 320 333/'
```
