### ISSUE TITLE
Typo in examples in ncpa.cfg

### ISSUE THREAD

**Issue by jm-welch** [NagiosEnterprises/ncpa#314]
In [ncpa.cfg](https://github.com/NagiosEnterprises/ncpa/blob/master/agent/etc/ncpa.cfg#L133-L134), there's a typo in the examples:

```
# Example:
# handlers = nrds,ndrp
```

That should be `nrdp` instead.

**Comment by jm-welch** [comment]
I know this is small, but my colleague ran afoul of it a bit ago. I'll put a PR in with this sometime soon, but just rebuilt my machine and need to get my tooling back online first.

**Comment by jomann09** [comment]
I swear I had fixed that - I updated master 631648b36de3461d5bc908e50a09eaa9713a0d7b
