### ISSUE TITLE
Unable to install NCPA client silent installation on Windows

### ISSUE THREAD

**Issue by aritradey70** [NagiosEnterprises/ncpa#315]
Hi Team,
As per the installation manual, I tried to install NCPA client2.0.2 via a Batch file:
ncpa-2.0.2.exe /S /TOKEN=059h7j4b2lnu /NRDPURL=https://tst.monitoring.im.insim.biz/nrdp/ /NRDPTOKEN=059h7j4b2lnu /HOST=%host% /CONFIG=default01

But after the installation of client it is unable to communicate with the Nagios server. But the same batch file worked for NCPA-1.8.1.exe.

We had a look at the "\\Client\c$\Program Files (x86)\Nagios\NCPA\etc\ncpa.cfg" file and found that few fields remained empty. like ip,port,ssl_version, parent, Hostname.

ip = 0.0.0.0 (Should be)
port =5693 (Should be)
ssl_version = TLSv1_2 (Should be)
parent =https://tst.monitoring.im.insim.biz/nrdp/(Should be)
Hostname= client Hostname(Should be)

We manually entered those settings and a extra line at the bottom
2. in ncpa.cfg, add one line at the bottom: .bat = cmd /c $plugin_name $plugin_args

Then only it communicate with the Nagios server. 
Client server is windows server 2008 R2.

Please help me in this case.

[ncpa.txt](https://github.com/NagiosEnterprises/ncpa/files/799169/ncpa.txt)

**Comment by jomann09** [comment]
`/HOST=` should be `/NRDPHOSTNAME=` for the host name and the `/CONFIG=` does not exist.

However, I believe the reason the NRDP URL does not get populated is because you have / in your `NRDPURL`, and you should be doing:
```
/NRDPURL="https://myurl.com/nrdp/"
```
Without the quotes you will only get a portion of the URL in your config.

Currently there is no defaults for quite a few options (including `ssl_version`) and I can add the defaults to the silent install because it does cause issues.

**Comment by jomann09** [comment]
Defaults have been added for 2.0.3 here 384277234e425bdef08922071dcb4af0e204e9e8

I will be closing this, just a reminder that the default checks in `ncpa.cfd.d/example.cfg` are by default commented out, in 2.1.0 I think I will add a new value such as `/DEFAULTNRDP=1` to allow using the default NRDP checks that can be pre-installed. Possibly allowing people to pass their own file too.

**Comment by aritradey70** [comment]
I've also added .bat files as a standard executable type in the default ncpa.cfg file given.
I am not getting your point.
Will there be a new version released with the solution of my problems?
"\Client\c$\Program Files (x86)\Nagios\NCPA\etc\ncpa.cfg" file and found that few fields remained empty. like ip,port,ssl_version, parent, Hostname.

ip = 0.0.0.0 (Should be)
 port =5693 (Should be)
 ssl_version = TLSv1_2 (Should be)
 parent =https://tst.monitoring.im.insim.biz/nrdp/(Should be)
 Hostname= client Hostname(Should be)

We manually entered those settings and a extra line at the bottom
 2. in ncpa.cfg, add one line at the bottom: .bat = cmd /c $plugin_name $plugin_args

**Comment by aritradey70** [comment]
I want to do the silent installation via a batch file. Could you please make a syntax for me. As the arguments passing with the NCPA client2.0.2 just didn't work as I told you earlier.
Please help me in making Silent installation batch file or please provide me an example.

**Comment by jomann09** [comment]
The next release will have the fixes for this in it.

The only way to make it work from a batch file if you need those values to be populated is to actually run commands to set those values in the ncpa.cfg file. Unfortunately I am not a Windows admin and don't know how you'd do that in a .bat file.

**Comment by aritradey70** [comment]
I ran the command like ncpa-2.0.2.exe /S /TOKEN=059h7j4b2lnu /NRDPURL=https://tst.monitoring.im.insim.biz/nrdp/ /NRDPTOKEN=059h7j4b2lnu /HOST=%host% /CONFIG=default01
 I will try the same with the new version, Once it is released.
With some other argument as well like : /ip = 0.0.0.0 /port =5693 /ssl_version = TLSv1_2 /parent =https://tst.monitoring.im.insim.biz/nrdp/
As it was not taking automatically now.

**Comment by jomann09** [comment]
There is no `/CONFIG` option, or really most of those options. In 2.1 there will be `/IP` and `/PORT` but the only options available are what is listed here https://www.nagios.org/ncpa/getting-started.php#win-silent-install

**Comment by aritradey70** [comment]
Great. I will try the installation with those parameters only. I hope all other missing fields will be set automatically.
When can we expect the new release?

**Comment by jomann09** [comment]
Hopefully the new release will be in the next week. I'm just finishing up an issue now and then I will go ahead and build.

**Comment by aritradey70** [comment]
Is the new version released with all the fixes? As I can see ncpa2.0.2.exe is still the latest one.

**Comment by aritradey70** [comment]
Hi Team,

I have installed NCPA client 2.0.3 on a server and found few fields are still empty:

* 'admin_password' should be set to prevent issues with CAS. Somethign difficult like 'klg%rdggE3=pvb'. This will be the same for all hosts I guess.
* 'parent' should be https://tst.monitoring.im.insim.biz/nrdp/ (for DEV/TEST) or https://monitoring.im.insim.biz/nrdp/ (for ACC/PRD)
* 'hostname' should be filled as well, with it's own name.

These three fields are still empty after installing the agent by:
set host=%COMPUTERNAME%
ncpa-2.0.3.exe /S /TOKEN=059h7j4b2lnu /NRDPURL=https://tst.monitoring.im.insim.biz/nrdp/ /NRDPTOKEN=059h7j4b2lnu /HOST=%host%

Please have a look and suggest.

Even I have tried to put the server name directly but same issue:
ncpa-2.0.3.exe /S /TOKEN=059h7j4b2lnu /NRDPURL=https://tst.monitoring.im.insim.biz/nrdp/ /NRDPTOKEN=059h7j4b2lnu /HOST=SERVERNAME

Please suggest.

**Comment by aritradey70** [comment]
In our environment We have Windows server 2008 R2 and server 2012 only.

**Comment by jomann09** [comment]
I think you're looking for `NRDPHOSTNAME` not `HOST` as far as the changing 'parent' which is `NRDPURL` I don't really have a good way of distinguishing 2 different NRDP servers. In the future, it is on the roadmap to be able to put in multiple NRDP servers, but likely won't be until version 3. The admin password is not used at all unless you set your ncpa.cfg to use it, but we could easily add a random string to the config on install - and give people the option of changing that password on silent install in 2.1.

**Comment by aritradey70** [comment]
I am talking about the host where the clients are being installed.
That server name should be in the .cfg file in the host field.

I am passing the NRDPURL value by passing /NRDPURL=https://tst.monitoring.im.insim.biz/nrdp/ But still Parent: field remains empty.

And it will be really helpful if we can pass the admin password as well.

Can I expect all of those in the next release?

**Comment by jomann09** [comment]
The admin password I will add to the next release and possibly grabbing the hostname on install for host that isn't specified, that is a good idea. I will see what I can do for 2.1.

You do have to quote your URL for the silent install like /NRDPURL="https://urlhere/nrdp/" or all the / will cause problems on the command line.

**Comment by aritradey70** [comment]
I have installed the agent with /NRDPURL="https://urlhere/nrdp/"  and the parent name filed seems to be fine for us. field is no more empty now.
But the Host and Admin password need to be fixed still.
Please let us know, Once you have sorted this thing out.

**Comment by jomann09** [comment]
I'll add it to the list of new variables that will be available in 2.1
