### ISSUE TITLE
Check_disk.vbs stopped working on 2.0.X

### ISSUE THREAD

**Issue by tonykli** [NagiosEnterprises/ncpa#316]
This plugin did work on 1.8.1, but not on 2.0.1/2 

https://exchange.nagios.org/directory/Plugins/Operating-Systems/Windows-NRPE/Check-free-disk-space/details

From debug  log it seems that the slashes vanishes from the command line:

2017-03-01 17:05:18,914:DEBUG:pluginnodes:Running process with command line: `cscript C:\Program Files (x86)\Nagios\NCPA\plugins\check_disk.vbs w:5000 c:3000 u:MB x:BQ //NoLogo

Which  causes the plugin to fail because it needs the slashes..
 
The same log entry from a 1.8.1 client.

2017-03-01 16:56:48,237:DEBUG:__init__:Running process with command line: `cscript C:\Program Files (x86)\Nagios\NCPA\plugins\check_disk.vbs /w:5000 /c:3000 /u:MB /x:BQ //NoLogo`

And the plugin does work.

I really would prefer a native multiple disk check, but have to settle with this until that.

**Comment by jomann09** [comment]
Can you show how you are sending the command to run that plugin to NCPA?

**Comment by tonykli** [comment]
/usr/lib64/nagios/plugins/check_ncpa.py -T 15 -H host.on.fi  -t ******  -M agent/plugin/check_disk.vbs -a "/w:5000 /c:3000 /u:MB /x:BQ" 

This is what is sent by nagios and works on 1.8.1

**Comment by jomann09** [comment]
Thanks, I will take a look. I forgot, but one more useful piece of info would be the version of the check_ncpa.py you are running. You should be able to get the version by doing `check_ncpa.py --version`.

**Comment by tonykli** [comment]
The version was 1.0.2, but now updated it to 1.1.0.  Same result. Then again it probably does not matter, because when testing with the api forms through web I get the same errors. Tried with all kinds of formats, several slashes ///w:5000, html coded %2Fw:5000, but nothing seems to work.

Another check that I have a problem with involves also slashes. Maybe this is related? On a linux host I use check_writable ( https://exchange.nagios.org/directory/Plugins/Operating-Systems/Linux/check_writable/details) and on 2.0.1 it works, if I use html encoded slash %2F instead of /, like this:

/usr/lib64/nagios/plugins/check_ncpa.py -T 15 -H host.on.fi -t ***** -M "plugins/check_writable" -a "--dir=%2Fvar%2Ftmp"

But not with normal slashes.

If I update the client to 2.0.2, even this form fails. Haven't tried 1.8.1 on linux so don't know.

Clearly there is a challenge with slashes in arguments. 

So summa summarum, I am stucked on 1.8.1 on windows clients and 2.0.1 on linux clients for now.

**Comment by jomann09** [comment]
Well the challenge with slashes in arguments is that it's sending them via typical URL structure... what is weird is that something on the NCPA side must not be properly decoding it. I'll take a look and if I can figure out why it's happening we can get it fixed in 2.0.3.

**Comment by jomann09** [comment]
I'm going to push this into 2.1 so that we can push out a 2.0.3 - since I need to edit the check_ncpa.py and do some modifications so that this works out nicely.

**Comment by jomann09** [comment]
Added the `args` variable in 2.1 for `plugins` so that you can now pass something like this instead of the path style, which will be deprecated in future versions.

```
/usr/lib64/nagios/plugins/check_ncpa.py -T 15 -H host.on.fi -t ***** -M "plugins/check_writable" -q "args=--dir=/Fvar/tmp"
```

In future versions of the client (`check_ncpa.py`) I think we will move to running plugins by passing the args you specify with `-a` to `args=<args>` instead of passing them as part of the path. However, because it is going to cause a lot of issues with backwards compatibility, I don't think it will happen until NCPA version 3.
