### ISSUE TITLE
process check critical if not running

### ISSUE THREAD

**Issue by kingdingaling83** [NagiosEnterprises/ncpa#317]
/usr/local/nagios/libexec/check_ncpa.py -H 10.252.32.253 -t 'mytoken' -P 5693 -M 'process/farmerswife 64bit.exe/count' 

this correctly shows it's running
OK: Process count for processes named farmerswife 64bit.exe was 1 | &apos;process_count&apos;=1;;;

but i'd like it to be critical if it isn't running

can i do that within the api or as a warning / critical option?

**Comment by jomann09** [comment]
You should be able to do it by doing `-c 1:` I believe, the NCPA checks follow the guidelines of the nagios plugins https://nagios-plugins.org/doc/guidelines.html#THRESHOLDFORMAT

**Comment by kingdingaling83** [comment]
That works!
thank you!
