### ISSUE TITLE
Typo in the ncpa.cfg

### ISSUE THREAD

**Issue by ludmilmm** [NagiosEnterprises/ncpa#321]
There is a typo in the [passive] section's comments in the ncpa.cfg file that needs to be fixed.

This:

> \# -------------------------------
> \# Passive Configuration (daemon)
> \# -------------------------------
>\#
> 
> [passive]
> 
> \#
> \# Handlers are a comma separated list of what you would like the passive agent to run
> \# Default: None
> \# Options:
> \#   nrds, nrdp
> \#
> \# Example:
> \# handlers = nrds,**ndrp**
> \#
> 

should be changed to this:

> \# -------------------------------
> \# Passive Configuration (daemon)
>\# -------------------------------
> \#
> 
> [passive]
> 
> \#
> \# Handlers are a comma separated list of what you would like the passive agent to run
> \# Default: None
> \# Options:
> \#   nrds, nrdp
> \#
>\ # Example:
> \# handlers = nrds,**nrdp**
> \#
>

**Comment by jomann09** [comment]
This was already fixed in #314 / 631648b36de3461d5bc908e50a09eaa9713a0d7b
