### ISSUE TITLE
CRLF terminators need to be removed from the check_ncpa.py plugin and the ncpa.cfg file

### ISSUE THREAD

**Issue by tgriep** [NagiosEnterprises/ncpa#322]
The check_ncpa.py plugin version 1.1.0 from the download page has CRLF line terminators and they need to be removed so the plugin will function correctly when it is upgraded.
Also the ncpa.cfg config file in the NCPA Linux Agent installer also has CRLF line terminators and they need to be removed as well.

**Comment by jvandermeulen** [comment]
Issue 1:
https://assets.nagios.com/downloads/ncpa/check_ncpa.tar.gz 

Issue 2:
```
[root@ncpa202 etc]# pwd
/usr/local/ncpa/etc

[root@ncpa202 etc]# ls -l
total 20
-rwxrwxr-x 1 nagios nagios 6491 Jan 19 11:41 ncpa.cfg
drwxrwxr-x 2 nagios nagios 4096 Mar 15 08:44 ncpa.cfg.d
-rwxrwxr-x 1 nagios nagios 6238 Jan 19 11:41 ncpa.cfg.sample
[root@ncpa202 etc]# file *
ncpa.cfg:        ASCII text, with CRLF line terminators
ncpa.cfg.d:      directory
ncpa.cfg.sample: ASCII text
```

Please observe that ncpa.cfg is "**ASCII text, with CRLF line terminators**" while the sample file is just plain ASCII.

**Comment by jomann09** [comment]
I agree, I think my git was set to commit with windows line endings. I will update these.

**Comment by jomann09** [comment]
I fixed the check_ncpa.tar.gz yesterday and I will fix the rest of the files today.

**Comment by jomann09** [comment]
Updated with 829c16689ba654721d485d36efa160b09713e334
