### ISSUE TITLE
Does not install on MacOS Sierra (10.12.3)

### ISSUE THREAD

**Issue by daniel-beard** [NagiosEnterprises/ncpa#325]
Running the setup script I get this:

```
 linter@distbuild-osx-coremobile-pro4  ~  sudo zsh /Volumes/NCPA-2.0.3/install.sh     
Starting install...
Users and group set
Loading services...done
Setting permissions...chown: nagios: illegal group name
```

Any help? Looks like maybe that group might not exist?

**Comment by jomann09** [comment]
Hmm I did test it on sierra, can you try running:
```
dscl . -read /Groups/nagios
```
to see what it returns?

**Comment by daniel-beard** [comment]
Returns this: 

```
AppleMetaNodeLocation: /Local/Default
GeneratedUID: 44668CA9-FB2F-47BA-AA4E-C5F4D30E2254
PrimaryGroupID: 501
RecordName: nagios
RecordType: dsRecTypeStandard:Groups
```

**Comment by jomann09** [comment]
So it looks like the group got added, it may be that the user never got added to the group, can you run ```sudo dseditgroup -o edit -a nagios -t user nagios```
which should place the nagios user into the group and then re-run the install.

**Comment by daniel-beard** [comment]
OK, that gets me a little further: 

```
AppleMetaNodeLocation: /Local/Default
GeneratedUID: 44668CA9-FB2F-47BA-AA4E-C5F4D30E2254
GroupMembers: FA61C61B-1B1D-4F4A-B790-AD73493D4946
GroupMembership: nagios
PrimaryGroupID: 501
RecordName: nagios
RecordType: dsRecTypeStandard:Groups
```

And the result from the install:

```
 linter@distbuild-osx-coremobile-pro4  ~  sudo zsh /Volumes/NCPA-2.0.3/install.sh          
Starting upgrade...
Stopping old NCPA services...%  
```

I'm guessing that's maybe because the launchctl stuff was never started?

**Comment by jomann09** [comment]
Most likely, I would manually go and delete the `/usr/local/ncpa` directory and run:
```
launchctl unload /Library/LaunchDaemons/com.nagios.ncpa.listener.plist
launchctl unload /Library/LaunchDaemons/com.nagios.ncpa.passive.plist
```
Then for good measure delete those two files and try the install once more. I am unsure why it had the issue, I am upgrading one of my OS X VMs to 10.12.3 to test this out myself too.

**Comment by daniel-beard** [comment]
Also seems to be failing here now as well :( 

```
chown -R nagios:nagios /usr/local/ncpa
chown: nagios: illegal user name
```

Thanks for the lightning fast responses btw!

**Comment by jomann09** [comment]
Sorry they are no longer lightning fast! :( but hmm it seems like it didn't even generate the nagios user, which is very weird. I will get back to you tomorrow morning once I get a chance to figure out what might be differnt in 10.12 that could cause this. Essentially to make it work, you'd need to make sure the nagios user exists and the group exists.

**Comment by jomann09** [comment]
Can you do a `dscl . -read /Groups/nagios` when you get a chance? I just tested on a clean 10.12.4 system and it worked - although something must be different since my output for the `dscl` read commands is slightly different than yours.

**Comment by daniel-beard** [comment]
Here is the output: 

```
AppleMetaNodeLocation: /Local/Default
GeneratedUID: C24A9801-784D-426C-ABCE-0B8A848D7EF4
Password: *
PrimaryGroupID: 703
RealName: nagios
RecordName: nagios
RecordType: dsRecTypeStandard:Groups
```

I dug a little further and it appears that two groups are being created:
```
 linter@distbuild-osx-coremobile-pro4  ~/Documents/ncpa  sudo dscl . -list /Groups | grep nagios
_nagios nagios
nagios
```

**Comment by jomann09** [comment]
Sorry I meant `dscl . -read /Users/nagios` yeah I see that in the script, I am not sure why it is doing that - I am pretty sure it doesn't need the _nagios group. I'm not sure how that is even included.

**Comment by daniel-beard** [comment]
```
 ✘ linter@distbuild-osx-coremobile-pro4  ~/Documents/ncpa  dscl . -read /Users/nagios
dsAttrTypeNative:accountPolicyData:
 <?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
        <key>creationTime</key>
        <real>1490718646.6397259</real>
        <key>failedLoginCount</key>
        <integer>0</integer>
        <key>failedLoginTimestamp</key>
        <integer>0</integer>
        <key>passwordLastSetTime</key>
        <real>1490718647.181222</real>
</dict>
</plist>

AppleMetaNodeLocation: /Local/Default
AuthenticationAuthority: ;Kerberosv5;;nagios@LKDC:SHA1.6F86EED26140A40CDF0B7C1E0400886F48B577BD;LKDC:SHA1.6F86EED26140A40CDF0B7C1E0400886F48B577BD ;ShadowHash;HASHLIST:<SMB-NT,CRAM-MD5,RECOVERABLE,SALTED-SHA512-PBKDF2,SRP-RFC5054-4096-SHA512-PBKDF2>
GeneratedUID: 44BC2FC4-32B1-4912-B3D0-4DA4E4EB2E20
NFSHomeDirectory: /usr/local/ncpa
Password: *
RealName: nagios
RecordName: nagios
RecordType: dsRecTypeStandard:Users
UniqueID: 502
UserShell: /usr/bin/false
```

**Comment by jomann09** [comment]
Well that is really odd, both group and user is created, so I am not sure why chown wouldn't work with `nagios:nagios` ... when you do a `chown` from the cmdline do you get the error?

**Comment by daniel-beard** [comment]
Yep, here's the output:

```
 linter@distbuild-osx-coremobile-pro4  ~  chown -R nagios:nagios /usr/local/ncpa 
chown: nagios: illegal user name
```

I'll try running this on a different machine and see if I end up getting the same output.

**Comment by jomann09** [comment]
It's strange it looks like the nagios user you showed at the bottom has a different UID than the one that is attached to the nagios group, which is probably why it gives the username error... wonder how that could happen. Maybe it's worthwhile to just remove all nagios users/groups and try again for that specific machine.

**Comment by jomann09** [comment]
I'm going to close this since I can't replicate it and haven't heard back from you for a while. I am assuming the install on a different machine worked. If you're still having trouble, feel free to open this issue or create a new one.

**Comment by mattrose** [comment]
This happened to me as well.  The dscl commands create directory entries, but somehow don't create the actual user entry.  After running the script "id nagios" returns "no such user"

I had to add the user with sysadminctl -addUser (which is not documented very well), and then the install was able to complete.

**Comment by jomann09** [comment]
Interesting, thanks for the update on this ! I will definitely look into it. I am not sure why it wouldn't create the user using the current method but I will look up a few alternatives to see if there is a better way.
