### ISSUE TITLE
NCPA 2.0.3 silent install token failure

### ISSUE THREAD

**Issue by jvandermeulen** [NagiosEnterprises/ncpa#326]
NCPA 2.0.3 for Windows has an issue in silent install mode when using **/TOKEN=** as an argument.
This issue can be reproduced on Windows Server 2008 and 2012. One of the token characters that is skipped in the ncpa.cfg configuration file (community_string) is the **^** sign. Screenshot attached.

![ncpa_203_token_failure](https://cloud.githubusercontent.com/assets/838001/24430455/fd55d794-1416-11e7-84ec-b1dd992fa34b.png)

**Comment by jomann09** [comment]
It looks like `^` is an escape character, so to use it you have to do `^^`

**Comment by jvandermeulen** [comment]
Indeed, I can confirm that escaping `^` with `^^` does the job. Are you planning on adding some comment in the `[api]` section of ncpa.cfg to summarize what characters need to be escaped?
Other users might experience the same pitfall while doing a silent install, however sooner or later they'll check what the token related contents of the ncpa.cfg looks like. It would be useful to find the solving hint in the same section.

**Comment by jomann09** [comment]
I could add something to the silent install documentation, and possibly elsewhere, but it's a Windows command line escaping issue, NCPA gets whatever value is passed to the installer.

**Comment by jomann09** [comment]
Updated our main silent install documentation to explain this!
https://www.nagios.org/ncpa/getting-started.php#win-silent-install
