### ISSUE TITLE
Stdout Returning Insignificant (to me) Data

### ISSUE THREAD

**Issue by chooko** [NagiosEnterprises/ncpa#327]
Hey Guys,

I'm sure this is just something wrong/stupid that I'm doing, not an actual problem with the software, but I can't figure it out, even after reading through the documentation.

NCPA is installed and works great on the client, firewall rule is in place to do my checking. Nagios XI built-in checks for CPU, memory, disk space are working like a charm. However, when I try to add additional service checks for some performance counters we want to watch, I get strange output on testing the check.

`/usr/local/nagios/libexec/check_ncpa.py -H <hostIP> -t '<mytoken>' -P 5693 -M windowscounters/Hyper-V%20Hypervisor/Total%20Pages -v
Connecting to: https://hostIP:5693/api/windowscounters/Hyper-V%2520Hypervisor/Total%2520Pages/?token=<mytoken>&check=1
File returned contained:
{
"returncode": 0,
"stdout": "OK: \\Hyper-V%20Hypervisor\\Total%20Pages was 0 c | '\\Hyper-V%20Hypervisor\\Total%20Pages'=0c;;;"
}
OK: \Hyper-V%20Hypervisor\Total%20Pages was 0 c | '\Hyper-V%20Hypervisor\Total%20Pages'=0c;;;`

What am I missing that it's returning so strange? It will return this way even if I put in Warning and Critical constraints.

Thanks in advance for the help. This is an awesome tool!

**Comment by jomann09** [comment]
Well the first thing is that you're running with `-v` which is verbose mode, which gives much more data than you want. Second, is the counter actually at 0 total pages? That seems a bit odd.

**Comment by chooko** [comment]
Run without verbose mode:

`/usr/local/nagios/libexec/check_ncpa.py -H <hostIP> -t '<mytoken>' -P 5693 -M windowscounters/Hyper-V%20Hypervisor/Total%20Pages
OK: \Hyper-V%20Hypervisor\Total%20Pages was 0 c | '\Hyper-V%20Hypervisor\Total%20Pages'=0c;;;`

If I run this same counter through the API, I get:
`{
    "windowscounters": [
        566522,
        "Total Pages"
    ]
}`

**Comment by jomann09** [comment]
First, can you double check to make sure your config wizard is version 1.4.4 in the manage config wizards admin page? Just to verify you're using the latest `check_ncpa.py` file.

Second, once you verify that, I would wrap your `-M` value with double quotes and remove the %20 that gets added, since that may be messing with the value sent to NCPA.

**Comment by chooko** [comment]
NCPA Config wizard is version 1.4.3. Will update that if necessary. 

Wrapping the M value in double quotes returns the following (in verbose mode)

`Connecting to: https://hostIP:5693/api/windowscounters/Hyper-V%20Hypervisor/Total%20Pages/?token=<mytoken>&check=1
An error occurred:<urlopen error [Errno -2] Name or service not known>`

Happens when trying to check other Hyper-V Performance counters as well.

**Comment by chooko** [comment]
Just updated NCPA Config Wizard to 1.4.4.

Will continue to test.

**Comment by jomann09** [comment]
Also, what version of NCPA are you running on the windows machine? There were some changes recently to fix some issues with the way things were passed.

**Comment by chooko** [comment]
NCPA Version 2.0.3 running on the monitored host.

**Comment by chooko** [comment]
Interesting. After updating to 1.4.4:

`$ /usr/local/nagios/libexec/check_ncpa.py -H <hostIP> -t '<myToken>' -P 5693 -M "/Hyper-V Virtual Machine Health Summary/Health Ok" -v
Connecting to: https://hostIP:5693/api/Hyper-V%20Virtual%20Machine%20Health%20Summary/Health%20Ok/?token=<myToken>&check=1
File returned contained:
{
"returncode": 3,
"stdout": "The node (Hyper-V Virtual Machine Health Summary) requested does not exist."
}
The node (Hyper-V Virtual Machine Health Summary) requested does not exist.`

Connecting directly to the API on URL: https://hostIP:5693/api/windowscounters/Hyper-V Virtual Machine Health Summary/Health Ok shows the right number for the counter after entering the token.

**Comment by chooko** [comment]
Just remembered, I need the /windowscounters/ in the check. Added that in and now it seems like I'm grabbing data properly.

`$ /usr/local/nagios/libexec/check_ncpa.py -H <hostIP> -t '<token>' -P 5693 -M "windowscounters/Hyper-V Virtual Machine Health Summary/Health Ok" -v
Connecting to: https://hostIP:5693/api/windowscounters/Hyper-V%20Virtual%20Machine%20Health%20Summary/Health%20Ok/?token=<token>&check=1
File returned contained:
{
"returncode": 0,
"stdout": "OK: \\Hyper-V Virtual Machine Health Summary\\Health Ok was 49.00 Health Ok | '\\Hyper-V Virtual Machine Health Summary\\Health Ok'=49.00;;;"
}
OK: \Hyper-V Virtual Machine Health Summary\Health Ok was 49.00 Health Ok | '\Hyper-V Virtual Machine Health Summary\Health Ok'=49.00;;;`

**Comment by jomann09** [comment]
So with the new plugin and doing it with windowscounters, does the Total Pages one show up correctly in the new check_ncpa.py ?

**Comment by chooko** [comment]
So this is working properly now after the update. Is there any easy way to remove the trailing"\" chars in the stdout to make it a little more clean in my Nagios?

Other than that, I'm gonna call this one good to be closed. Thanks so much for your help!

**Comment by jomann09** [comment]
Can you show me a screenshot or something of just the output that you're seeing in XI ?

**Comment by chooko** [comment]
![inked2017-03-31 16_24_59-nagios xi_li](https://cloud.githubusercontent.com/assets/3309140/24571494/cb8e6d10-162e-11e7-966b-29f983d86cc6.jpg)
 
Github cut out the char that I referenced in my last post. There are a few trailing backslashes, as you can see in the attached.

**Comment by jomann09** [comment]
Oh I see, those backslashes are because of the name of the windows counter, that is how windows shows them when you view the counter - so we just output that as the name of the counter that you're checking.

**Comment by chooko** [comment]
Ahhhh gotcha. Not a huge deal, just a cosmetic personal preference. If that's the case, doesn't seem like I can parse those out.

We can call this one good to go. Thanks for your help! :)
