### ISSUE TITLE
exclude some fstype by default

### ISSUE THREAD

**Issue by metabsd** [NagiosEnterprises/ncpa#328]
It's an idea. I just read the code of Digital Ocean monitoring and I find the idea great. It's in GoLang.

// excludedDevices are psudeo filesystems that are excluded from metrics.
var excludedDevices = []string{
	"fusectl",
	"lxcfs",
	"mqueue",
	"none",
	"rootfs",
	"sunrpc",
	"systemd",
	"udev",
}

// excludedFSes are pseudo filesystems that are excluded from metrics
var excludedFSes = []string{
	"aufs",
	"autofs",
	"binfmt_misc",
	"cifs",
	"cgroup",
	"debugfs",
	"devpts",
	"devtmpfs",
	"ecryptfs",
	"efivarfs",
	"fuse",
	"hugetlbfs",
	"mqueue",
	"nfs",
	"overlayfs",
	"proc",
	"pstore",
	"rpc_pipefs",
	"securityfs",
	"smb",
	"sysfs",
	"tmpfs",
	"tracefs",
}

**Comment by metabsd** [comment]
The source : [do-agent - disk.go](https://github.com/digitalocean/do-agent/blob/master/collector/disk.go)

**Comment by jvandermeulen** [comment]
I like the idea of hiding these pseudo devices (at least from the NCPA wizard).

**Comment by jomann09** [comment]
It is certainly capable of being done, we could add something to the ncpa.cfg if you'd like to remove certain types. It doesn't do any automatic checks though so even if it shows up in the API you don't have to do anything special for it.

**Comment by mon0brew** [comment]
Our Linux admins are asking for the feature as well. We've been having issues with NFS shares and that problem causes the agent to go unresponsive.

**Comment by jomann09** [comment]
Thanks for the comment, we will definitely be getting this in here soon, I would like to add it for 2.1 which should be out in a month or so.

**Comment by jomann09** [comment]
Added in 1ea67eec9a34fe3e72ec6d87ed098b613b3dcb4a as `exclude_fs_types` in the `ncpa.cfg` file.
