### ISSUE TITLE
Multiple services [exact match] are not honoured by check_ncpa

### ISSUE THREAD

**Issue by jvandermeulen** [NagiosEnterprises/ncpa#332]
Our customer is trying to achieve monitoring of some MS Exchange related Windows servers. Not all of them are running, so with an "exact match" of multiple services we would like to make one single check.
The API is capable of doing such, it even helps with getting all arguments for check_ncpa.py

> Running the following active check from the command line:
./check_ncpa.py -H <ncpa server> -t '<your token>' -M 'services' -q 'service=MSExchangeFDS,service=MSExchangeMailboxReplication,service=MSExchangeProtectedServiceHost,service=MSExchangeRPC,status=running'
>
> Would result in the following output:
OK: MSExchangeProtectedServiceHost is running, MSExchangeMailboxReplication is running, MSExchangeFDS is running, MSExchangeRPC is running

However the output of 
`../check_ncpa.py -H exch-cas-p100 -t ${MYTOKEN} -P 5693 -M 'services' -q 'service=MSExchangeFDS,service=MSExchangeMailboxReplication,service=MSExchangeProtectedServiceHost,service=MSExchangeRPC,status=running'
`

is showing the last mentioned service only:

> OK: MSExchangeRPC is running

I tried to changed the `,` characters to `&` but that did not help me.

The output of this curl command proves that the NCPA listener is not the problem:
`curl "https://exch-cas-p100:5693/api/services?service=MSExchangeFDS&service=MSExchangeMailboxReplication&service=MSExchangeProtectedServiceHost&service=MSExchangeRPC&check=true&status=running&token=$MYTOKEN" -k `

The output is:
> {
    "returncode": 0,
    "stdout": "OK: MSExchangeProtectedServiceHost is running, MSExchangeMailboxReplication is running, MSExchangeFDS is running, MSExchangeRPC is running"
}

**Comment by jvandermeulen** [comment]
![bugreport check_ncpa multilple services exact match](https://cloud.githubusercontent.com/assets/838001/24960819/4258172c-1f97-11e7-8574-ef15268860d3.png)

**Comment by jomann09** [comment]
I'm pretty sure this is a bug in the check_ncpa.py code, which is not allowing them to be passed through... I will take a look in a bit here but it should be a pretty simple fix.

**Comment by metabsd** [comment]
Any update about that issue. I have the same problem. Thank you in advance.

**Comment by jomann09** [comment]
This should be fixed in 0be7a7c9a2b3cf54e52a68984c2ea26b57226be0, for version 1.1.1 of the check_ncpa.py plugin.
