### ISSUE TITLE
check_ncpa has problems with end-of-line character that is part of regex

### ISSUE THREAD

**Issue by jvandermeulen** [NagiosEnterprises/ncpa#333]
While trying to find a regex workaround for #332 I bumped into this phenomenon

`-M 'services' -q 'match=regex,service=MSExchange[A-Za-z].*[A-Za-z]$,status=running'` 

![ncpa services regex run gui](https://cloud.githubusercontent.com/assets/838001/24961551/71ac9514-1f99-11e7-86fc-b82a69732e5a.png)

fails in the GUI (performing a "Run Check Command" in Nagios XI outputs OK)

The regex is filtering out numbers at the very end of the line, resulting these stopped services are filtered out:
> CRITICAL: MSExchangePop3 is stopped (should be running), MSExchangeImap4 is stopped (should be running)

When I change the order of `status=running` it works fine: 

`-M 'services' -q 'match=regex,status=running,service=MSExchange[A-Za-z].*[A-Za-z]$' `

So in the end I found a workaround for the GUI.

**Comment by jomann09** [comment]
This is incredibly strange, it could easily be that the same code I mentioned in #332 does not cut out the proper arguments. I'll take a look into this one too.

**Comment by jvandermeulen** [comment]
May I suggest to add a "documentation" tag also? The "active check example" function in the NCPA webUI does not mention the need for `match=regex` or `match=search` part of the query argument for check_ncpa.

**Comment by jomann09** [comment]
Sure, I can make sure that gets added to the UI output also.

**Comment by jomann09** [comment]
I could not get the regex problem to happen while testing this more in depth but for now I will assume that the fix to the plugin helped. The GUI has also been fixed, it was just a selection issue. Closing this for now.
