### ISSUE TITLE
Disk Space Checks Still Have Misleading %

### ISSUE THREAD

**Issue by sm00thindian** [NagiosEnterprises/ncpa#335]
On a RedHat System running check_ncpa.py with the following
-t <<token>> -P <<port>> -M 'disk/logical/|data1/used_percent' -w 79 -c 90
shows 62% usage on the server but 58% on Nagios.  This disparity has caused outages for us on tight disk systems.

**Comment by jomann09** [comment]
What version are you running? The disk space should take into account reserved space as of the fix in psutils back before psutils 5+

**Comment by sm00thindian** [comment]
just to verify .. how do I check the version on the box.  I believe it's 2.0.1

**Comment by jomann09** [comment]
You should be able to do a `yum info ncpa` but it should definitely be fixed in 2.0.1 - can you show me the output of `df` and the output of the check?

**Comment by sm00thindian** [comment]
The issue box is secure... what part of the DF output do you need?
/dev/mapper/vg00-lv06 2064110752 1224513660 734739700 63% /data1
is the mount point we noticed it on.

**Comment by sm00thindian** [comment]
OK, so the agent on this box is the legacy agent.  1.8.1 but I've updated the check_ncpa.py script.  So updating the agent should take care of it?

**Comment by jomann09** [comment]
That should be enough, let me test some things here. The issue I was referring to be fore was #102 which was not showing reserved space.

**Comment by jomann09** [comment]
Yes I believe updating the agent would take care of it. If you've already updated your check_ncpa.py to the latest version you should be fine upgrading the agent itself.

**Comment by sm00thindian** [comment]
I'll try and report

**Comment by sm00thindian** [comment]
You were correct 2.0.2 installed and we're good to go.

Thanks,
-krw
