### ISSUE TITLE
NCPA 2.0.2 Passive Check service name with space in between unable to parse correctly

### ISSUE THREAD

**Issue by lovemenot** [NagiosEnterprises/ncpa#336]
Configuration on the server side for passive checks:

[passive checks]
%HOSTNAME%|CAFE 101 = /services service=CAFE 101

NCPA log file result:

DEBUG:ncpacheck:Initializing NCPA check with /services service=CAFE 101
DEBUG:ncpacheck:Next run set to be 0
INFO:ncpacheck:Running check: /services service=CAFE 101
DEBUG:ncpacheck:Getting API url for instruction /services service=CAFE 101
DEBUG:ncpacheck:Parsing command line style instruction: /services service=CAFE 101
WARNING:ncpacheck:Unable to parse all arguments from instruction. Mis-paired option: 101
DEBUG:ncpacheck:Determined instruction to be: /services service=CAFE 101
DEBUG:ncpacheck:Access the API with /api/service/?check=1&service=CAFE
DEBUG:psapi:Imported windowscounters into the API tree.
DEBUG:psapi:Imported windowslogs into the API tree.
DEBUG:ncpacheck:Handling JSON response: {
    "returncode": 3,
    "stdout" : "UNKNOWN: No services selected with 'service' value given"
}

Thanks,

Ronald Canete

**Comment by jomann09** [comment]
Let me test this today and I will get back to you on this. It's odd that it is trying to send it to `/api/service` instead of using the services endpoint when it does the actual check.

**Comment by jomann09** [comment]
So it looks like you can also pass a URI so you can try something like this:

```
%HOSTNAME%|CAFE 101 = services?service=CAFE 101&status=running
```

You may need to put in a `%20` instead of a space in CAFE 101 but I am not sure. You should also make sure it's the correct service name from the services list in `/api/services` too.

**Comment by lovemenot** [comment]
Hi Jomann,

It works with %20. 

Thank you very much.

- Ronald

**Comment by jomann09** [comment]
Awesome, glad it worked. I'll update the API and docs at some point to show that API URLs also work for these passive check definitions.

**Comment by jomann09** [comment]
Updated this as a part of 4c0f5e86b2d3093f21eee98ad61ff646ffbd72f4

**Comment by wsantunes** [comment]
hi everyone, 
  can i use the same process in passive check?
 Thanks for the help.

**Comment by jomann09** [comment]
Yeah, anything that is in a URL will require a `%20` instead of a space.
