### ISSUE TITLE
Bug Report - check_ncpa.py doesn't support multiple services per documentation

### ISSUE THREAD

**Issue by ssaxnagios** [NagiosEnterprises/ncpa#339]
Per the documentation check_ncpa.py should allow you to specify multiple services:

https://www.nagios.org/ncpa/help/2.0/api.html#api-modules-services

```
[root@ssc66xid libexec]# ./check_ncpa.py -H X.X.X.X -t 'token' -M 'service' -q 'service=wscsvc,service=LanmanServer,status=running' -v
Connecting to: https://X.X.X.X:5693/api/service/?status=running&token=token&check=1&service=LanmanServer
File returned contained:
{
    "returncode": 0,
    "stdout": "OK: LanmanServer is running"
}
```

The problem is here (around line 196):

```
if options.queryargs:
        for argument in options.queryargs.split(','):
            key, value = argument.split('=')
            arguments[key] = value
```

The last line will overwrite the array value of the key (which would be 'service') and the end result is that only a single service will be check no matter how many you pass in.

**Comment by jomann09** [comment]
You just missed it, just fixed this for duplicate #332
