### ISSUE TITLE
NCPA fails to start in Centos 7 LXC

### ISSUE THREAD

**Issue by flowjo-mikej** [NagiosEnterprises/ncpa#340]
I am triying to get NCPA listener running in a Centos 7 LXC, the container is running in Proxmox VE and using the base image centos-7-default_20161207_amd64.tar.xz. I installed NCPA via repo, but after installing and configuring, NCPA is failing to start:

ncpa_listener.service - LSB: This manages the NCPA Listener service
Loaded: loaded (/etc/rc.d/init.d/ncpa_listener; bad; vendor preset: disabled)
Active: active (exited) since Wed 2017-05-10 00:05:33 UTC; 1min 48s ago
Docs: man:systemd-sysv-generator(8)
Process: 8472 ExecStop=/etc/rc.d/init.d/ncpa_listener stop (code=exited, status=0/SUCCESS)
Process: 8481 ExecStart=/etc/rc.d/init.d/ncpa_listener start (code=exited, status=0/SUCCESS)

ncpa_listener[8481]: File "/root/ncpa/agent/ncpadaemon.py", line 14, in <module>
ncpa_listener[8481]: File "/root/ncpa/agent/listener/database.py", line 5, in <module>
ncpa_listener[8481]: File "/root/ncpa/agent/listener/server.py", line 11, in <module>
ncpa_listener[8481]: File "/root/ncpa/agent/listener/psapi.py", line 213, in <module>
ncpa_listener[8481]: File "/root/ncpa/agent/listener/psapi.py", line 184, in get_root_node
ncpa_listener[8481]: File "/root/ncpa/agent/listener/psapi.py", line 147, in get_disk_node
ncpa_listener[8481]: File "/usr/local/lib/python2.7/site-packages/psutil/__init__.py", line 2053, in disk_io_counters
ncpa_listener[8481]: RuntimeError: couldn't find any physical disk
ncpa_listener[8481]: [FAILED]
systemd[1]: Started LSB: This manages the NCPA Listener service.

I have successfully installed this latest NCPA version on another Centos 7 physical machine and VM without issue. Any help would be greatly appreciated.

**Comment by jomann09** [comment]
This is an issue with `psutil` and looks like it is being addressed right now https://github.com/giampaolo/psutil/issues/1016 - we will build version 2.0.4 with the newest 5.3.0 version of psutil once it comes out... by the way the changelog looks, that should be fairly soon.

**Comment by flowjo-mikej** [comment]
Thank you very much for the quick response! I will keep an eye out for 2.0.4.

**Comment by jomann09** [comment]
I am building version 2.0.4 builds right now and this will be in for EL6 and EL7 builds even though it's just a patch for psutils 5.2.2 - once it gets updated to psutil 5.3.x the rest of the builds will be working properly too.
