### ISSUE TITLE
NCPA 2.0.3-1 ncpa.cfg on linux has the wrong EOL character

### ISSUE THREAD

**Issue by tellierd** [NagiosEnterprises/ncpa#341]
When installing the NCPA agent from repo, I noticed that the config file _/usr/local/ncpa/etc/ncpa.cfg_ has a bad EOL (End Of Line) character.

Using _Ansible_ to deploy, on the step where I replace values in the config file, it always ended with a **^M** at each end of line.

To temporary fix this issue, I pass the config file through the **dos2unix** package to convert it.

I think it would be nice to fix the config file during the installation process.

This was tested on these distros:
_

- _Red Hat Enterprise Linux Server release 7.1_
- _Red Hat Enterprise Linux Server release 7.2_
- _CentOS Linux release 7.2.1511 (Core)_

_

**Comment by jomann09** [comment]
This is already fixed in the master branch for 2.0.4 but will make sure to remove all windows line endings on all the python files in the future.

Commit here 829c16689ba654721d485d36efa160b09713e334

**Comment by tellierd** [comment]
Excellent!
Thanks for the update
