### ISSUE TITLE
Network Interface Check & Utilization - Performance data

### ISSUE THREAD

**Issue by 4gemenot** [NagiosEnterprises/ncpa#343]
Is it possible to combine the check for bytes_recv and bytes_send, Packets_sent & Packets_recv, Dropin & dropout, errib and errout?

**Comment by jomann09** [comment]
You can't currently... though this is something I've wanted to add so I will put this in as a feature request. I am not sure when it'll get added but probably in one of the next minor releases.

**Comment by lovemenot** [comment]
Hi Jake... Thank you for the update.

**Comment by jomann09** [comment]
This has been added for 2.1
