### ISSUE TITLE
NCPA accessing file on filesystem for pkcs12 SSL check 

### ISSUE THREAD

**Issue by micoots** [NagiosEnterprises/ncpa#345]
Hi. I've tried to get this script:

https://raw.githubusercontent.com/Matty9191/ssl-cert-check/master/ssl-cert-check

which supports Nagios via -n switch, to query a certificate file on the filesystem like so:

# /usr/local/nagios/libexec/ssl-cert-check -c /somepath/somepfxcert.p12 -k somepasswd -n
FILE:/somepath/somepfxcert.p12         Valid        Mar 20 2020  |days=1030

As you can see, it works fine when run manually.

When attempted through a ncpa passive check, like so:

[passive checks]
%HOSTNAME%|SSL certs local status = /agent/plugin/ssl-cert-check/-k/somepasswd/-c/%7Csomepath%7Csomepfxcert.p12/-n

it fails with error of the form:

The file named _(some random stuff)_ is unreadable or doesn't exist

I've tried both passive, via API URL on the host, via check_ncpa.py and all the same unreadable error.

The certificate file has been placed worldreadable and in /tmp with full read/write world, and still no go.

So I believe that ncpa itself can't actually read files from a filesystem?

Please advise or provide a workaround/advice.

In the mean time, I've scheduled the script to run via cron and generate an email for each pfx/p12 cert on the filesystem.

Thank you.

**Comment by jomann09** [comment]
I will test this but before I do... when you go to `https://<address>:5693/api/plugins` what do you get a list of? Also, did you change your location for plugins in the `ncpa.cfg` ? NCPA by default runs as the nagios user and nagios group, which should allow you access to everything you've mentioned.

**Comment by micoots** [comment]
Hi. Thank you for responding. 

The ncpa version is 1.8.1 so I can't go to /api/plugins but instead need to go to:

https://<address>:5693/api/agent/plugin

where I get:

value	
plugin	
0	"check_breeze"
1	"check_mrtgtraf"
2	"check_disk"
3	"check_dummy"
4	"check_ssh"
5	"check_mrtg"
6	"check_nagios"
7	"check_wave"
8	"negate"
9	"check_ups"
10	"check_flexlm"
11	"check_ncpa.py"
12	"check_dns"
13	"check_uptime"
14	"check_swap"
15	"check_file_age"
16	"check_cluster"
17	"urlize"
18	"check_time"
19	"check_ssmtp"
20	"check_pop"
21	"check_ifoperstatus"
22	"check_icmp"
23	"check_spop"
24	"check_imap"
25	"check_health"
26	"check_users"
27	"check_by_ssh"
28	"check_ntp_peer"
29	"check_jabber"
30	"check_ide_smart"
31	"check_real"
32	"check_ifstatus"
33	"check_ping"
34	"utils.sh"
35	"check_ntp_time"
36	"ssl-cert-check"
37	"check_disk_smb"
38	"utils.pm"
39	"check_oracle"
40	"check_log"
41	"check_rpc"
42	"check_load"
43	"check_mailq"
44	"check_tcp"
45	"check_apt"
46	"check_sensors"
47	"check_nwstat"
48	"check_udp"
49	"check_ntp"
50	"check_nntp"
51	"service_check"
52	"check_ircd"
53	"check_ftp"
54	"check_http"
55	"check_dig"
56	"check_smtp"
57	"check_procs"
58	"check_simap"
59	"check_nntps"
60	"check_overcr"
61	"check_clamd"
62	"check_dhcp"
63	"check_nt"

Item 36 shows ssl-cert-check is present.

Technically I can upgrade to 2.0.x series since we have this in test and the passive checks are slightly changed, but the issue is 1.8.1 is used on many (hundred) machines so it's a big job going through an upgrade.

The location for the plugins is:

plugin_path = /usr/local/nagios/libexec/

which contains plugins of all the standard nagios plugins.

I can see in our process list ncpa_passive runs as the root user.

So when I apply it as a passive check, I get:

2017-05-25 23:52:17,772 17195 INFO Running check: api/agent/plugin/ssl-cert-check/-k/somepasswd/-c/%7Csomepath%7Csomepfxcert.p12/-n
2017-05-25 23:52:17,772 17195 DEBUG Getting API url for instruction api/agent/plugin/ssl-cert-check/-k/somepasswd/-c/%7Csomepath%7Csomepfxcert.p12/-n
2017-05-25 23:52:17,772 17195 DEBUG Determined instruction to be: api/agent/plugin/ssl-cert-check/-k/somepasswd/-c/%7Csomepath%7Csomepfxcert.p12/-n
2017-05-25 23:52:17,772 17195 DEBUG Access the API with /api/agent/plugin/ssl-cert-check/-k/somepasswd/-c/%7Csomepath%7Csomepfxcert.p12/-n/?check=1
2017-05-25 23:52:17,773 17195 DEBUG Running process with command line: `/usr/local/nagios/libexec/ssl-cert-check -k somepasswd-c |somepath|somepfxcert.p12 -n`
2017-05-25 23:52:17,794 17195 DEBUG Handling JSON response: {
  "value": {
    "returncode": 3,
    "stdout": "ERROR: The file named |somepath|somepfxcert.p12 is unreadable or doesn't exist\nERROR: Please check to make sure the certificate for FILE:|somepath|somepfxcert.p12 is valid"
  }

Yet running it from cli, works fine:

/usr/local/nagios/libexec/ssl-cert-check -k somepasswd -c /somepath/somepfxcert.p12 -n
FILE:/somepath/somepfxcert.p12         Valid        Mar 20 2020  |days=1030

As mentioned previously, have put the file into /tmp with world read/write, and tried it on a x509 cert file, all the same problem.

Would be really nice to get this one working, as checking these certs can only be done in this was as these certs are not used for listening web servers we can check against.

Thanks.

**Comment by jomann09** [comment]
Okay that's good to know, it shouldn't have any problems with 1.8.1 but just wanted to make sure when testing. However, the first thing I do notice is this:

```
2017-05-25 23:52:17,773 17195 DEBUG Running process with command line: `/usr/local/nagios/libexec/ssl-cert-check -k somepasswd-c |somepath|somepfxcert.p12 -n`
```

Which it looks like you are passing `%2C` (`|`) but I think you want to be passing `%2F` (`/`) in replacement of the `/` characters.

**Comment by micoots** [comment]
Hi. Thanks again for your replies.

Yes, in the 1.8.1 docs it says to pass | characters to be interpreted as /, since / is used as the separator between options.

The character used in this case is `%7C`

Using `%2F` produces space characters between the path:

`2017-05-29 03:01:23,170 32700 DEBUG Running process with command line: `/usr/local/nagios/libexec/ssl-cert-check -k somepasswd -c somepath somepfxcert.p12 -n`
`

I'm trying to trouble-shoot this again today, as it's important to try and get this working.

**Comment by jomann09** [comment]
I would try putting double or single quotes around the file name with the `%2F` because I see what you're saying, since it's converting the forward slash it causes it to break the command up - the pipe character won't work in your plugin unless it allows it though... it doesn't do any conversions.

This is kind of one of the reasons we are working on changing the way the values are passed in the next version of NCPA (it'll be backwards compatible but this is one of the biggest issues)

**Comment by micoots** [comment]
Hi. Thanks for your reply. It makes sense what you're saying.

I got it working using a wrapper script. This is how:

1. I use a keyword in the passive check of "_slash_" (without quotes)
2. I call the wrapper script (ssl-cert-check-custom) from the passive check
3. the wrapper script pulls the variables from the passive check command line
4. the wrapper script converts the "_slash_" keyword into /
5. the wrapper script then calls the ssl-cert-check script with the variables

So for point 1 for example, I define the path as:

_slash_somepath_slash_somepfxcert.p12

this works by running the correct command and outputting:

`FILE:/somepath/somepfxcert.p12         Valid        Mar 20 2020  |days=1030`

to Nagios.

However, in the Nagios web display I only see the:

`/somepath/somepfxcert.p12`

part on the right most column, instead of the rest of the `Valid Mar 20 2020| days= 1030`

Not sure how to fix that one?

I believe Nagios should warn if days are less than x days if I re-visit the script to add the days as a variable, modify the wrapper script to pull that variable.

It's not perfect but it overcomes the / problem in the passive checks.

**Comment by jomann09** [comment]
Closing this in favor of #316 which is what I am going to use to track the solution for passing `/` properly. Thanks for the information on all of this!
