### ISSUE TITLE
Problem with Windows EventLog Monitoring

### ISSUE THREAD

**Issue by ludmilmm** [NagiosEnterprises/ncpa#350]
The issue was originally reported by "onegative" user on the Nagios support forum:
[https://support.nagios.com/forum/viewtopic.php?t=44188#222995](url)

>  Seems like if your query as defined in the field "Log Timeframe" exceeds the actual amount of logging time in the log it craters the query and hangs the web server.

FYI, I was able to recreate the issue, and can confirm this is a bug. NCPA becomes unusable, unless you restart the service.

**Comment by jomann09** [comment]
Fixed this in e7547e19705340c2b5baebb3ead22a8c7eadd83a so that now once the loop reaches the end of all the logs it'll cancel out of the loop.
