### ISSUE TITLE
API system/uptime

### ISSUE THREAD

**Issue by ludmilmm** [NagiosEnterprises/ncpa#353]
Feature request: provide "human readable" output for system/uptime in NCPA. Currently, uptime is shown in seconds. There should be an option to show it in days, hours, minutes, etc.

**Comment by jvandermeulen** [comment]
It would also be nice if optional thresholds are honored with regards to uptime. If threshold ranges (https://nagios-plugins.org/doc/guidelines.html#THRESHOLDFORMAT) are obeyed than NCPA would be able to perform _reboot detection_ (uptime is less than _X_ minutes) or the opposite: a warning that you might want to reboot (uptime of MS Windows system is over _X_ weeks).

**Comment by jomann09** [comment]
Sounds like a good addition to me, I will check if it's possible right now or if I need to add anything on the agent side of things.

**Comment by jomann09** [comment]
Closing this for two reasons:

1) Added output when running the check to be human readable, example:
```
{
    "returncode": 0,
    "stdout": "OK: Uptime was 7 days 1 hour 54 minutes 20 seconds | 'uptime'=611660.00s;;;"
}
```

2) For the thresholds, all types of thresholds currently work with NCPA. As of 2.1 you can only do a check against the amount of seconds that the system has been online for.
