### ISSUE TITLE
Upgrade to ncpa 2.0.4 on rhel7 stops systemd services

### ISSUE THREAD

**Issue by jvandermeulen** [NagiosEnterprises/ncpa#356]
Updating to ncpa 2.0.4 (from 2.0.3) on rhel7 leads to **stopped** systemd services for NCPA. 
This is very undesirable, especially for customers that make use of http://repo.nagios.com/nagios/7/ and update ncpa together with their operating system packages.

> [root@rhel7-ncpa etc]# systemctl is-active  ncpa_listener
> inactive
> [root@rhel7-ncpa etc]# systemctl is-active  ncpa_passive
> inactive

**Comment by jomann09** [comment]
This was addressed in the new .spec file, but unfortunately the rpm runs the old rpms uninstall which is why this won't actually be fixed until your rpm has been updated to 2.0.4, so when you upgrade again it will no longer leave it stopped after upgrade.

**Comment by jomann09** [comment]
Closing this like the others because once you're on 2.0.4 or higher, the next upgrade will work! Sorry about the confusion!
