### ISSUE TITLE
Please include a "latest" download link

### ISSUE THREAD

**Issue by wood4sheep** [NagiosEnterprises/ncpa#361]
It'd be helpful if in downloads there were a non-changing link pointing (symbolic link perhaps?) to the latest build.
IE
https://assets.nagios.com/downloads/ncpa/ncpa-latest.el7.x86_64.rpm -> https://assets.nagios.com/downloads/ncpa/ncpa-2.0.4.el7.x86_64.rpm

**Comment by jomann09** [comment]
We can do that, I'll add it to the list.

**Comment by jomann09** [comment]
Added and should be uploaded now.
