### ISSUE TITLE
NCPA mangling eventID

### ISSUE THREAD

**Issue by ludmilmm** [NagiosEnterprises/ncpa#362]
It seems like NCPA is reporting a wrong Windows event id. For example, in the Event Viewer I see:

`Event ID:    2001`

but in NCPA, I see:

`"event_id": "-1073739823",`

for the same event.

The issue was originally reported by mvndnburg on the Nagios XI support forum here:

[https://support.nagios.com/forum/viewtopic.php?t=44630#226067](url)

**Comment by jomann09** [comment]
This I fixed with commit c236ed1b72a9e3cffce0f5f1fbdda9b2bf9b2afb but I am probably rolling it into 2.1.0 since that is likely the next release, if there is 2.0.5 it will be in that though.
