### ISSUE TITLE
Sending arguments with spaces enclosed within quotes

### ISSUE THREAD

**Issue by box293** [NagiosEnterprises/ncpa#363]
I created a KB article that demonstrated how you can use scripts/plugins with NCPA and Nagios XI.

https://support.nagios.com/kb/article/nagios-xi-using-scripts-plugins-with-ncpa.html

I was testing with NCPA 2.0.4 on Windows 10 with check_ncpa.py 1.1.0 on XI 5.4.6.

I came across an unusual behavior. When you send arguments using `check_ncpa.py` the arguments surrounded with quotes are sent to the script, whereas when you test a script at the command line it doesn't add the quotes. Here's an example:
```
PS C:\Program Files (x86)\Nagios\NCPA\plugins> powershell.exe -executionpolicy bypass -File check_dummy.ps1 2 'Something Is Critical'
Argument 0 is:  2
Argument 1 is:  Something Is Critical
```
You can see the output of `Something Is Critical` was enclosed in single quotes and PowerShell did not receive the quotes but it did receive the string as one argument, which is the intended behavior.

Now here's the test from Nagios XI:
```
[root@xitest libexec]# /usr/local/nagios/libexec/check_ncpa.py -H 10.25.14.10 -t 'TT00kk33nn' -P 5693 -M 'plugins/check_dummy.ps1' -a "2 'Something is CRITICAL'"
Argument 0 is:  2
Argument 1 is:  'Something is CRITICAL'
```
You can see that PowerShell is receiving the single quotes used to encapsulate the string with spaces. This is not a desired behavior and as I've demonstrated when you execute it at the command line it doesn't exist this behavior.

VBS files are similar:
```
C:\Program Files (x86)\Nagios\NCPA\plugins>cscript.exe //NoLogo check_dummy.vbs 2 "Something is CRITICAL"
Argment 0 is 2
Argment 1 is Something is CRITICAL
```
I did need to use double quotes as for some reason single quotes would receive the argument as `'Something` however this seems to be a Windows thing. 

Testing from Nagios XI:
```
/usr/local/nagios/libexec/check_ncpa.py -H 10.25.14.10 -t 'TT00kk33nn' -P 5693 -M 'plugins/check_dummy.vbs' -a "2 'Something is CRITICAL'"
Argment 0 is 2
Argment 1 is 'Something is CRITICAL'
```
Flipping the single and double quotes around does strange stuff:
```
[root@xitest libexec]# /usr/local/nagios/libexec/check_ncpa.py -H 10.25.14.10 -t 'TT00kk33nn' -P 5693 -M 'plugins/check_dummy.vbs' -a '2 "Something is CRITICAL"'
Argment 0 is 2
Argment 1 is \Something
```

Batch files are the worst.
```
C:\Program Files (x86)\Nagios\NCPA\plugins>check_dummy.bat 2 "Something is CRITICAL"
Argument 1 is: 2
Argument 2 and after is: Something is CRITICAL

[root@xitest libexec]# /usr/local/nagios/libexec/check_ncpa.py -H 10.25.14.10 -t 'TT00kk33nn' -P 5693 -M 'plugins/check_dummy.bat' -a "2 'Something is CRITICAL'"
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.
```
Flipping the single and double quotes doesn't make a difference:
```
[root@xitest libexec]# /usr/local/nagios/libexec/check_ncpa.py -H 10.25.14.10 -t 'TT00kk33nn' -P 5693 -M 'plugins/check_dummy.bat' -a '2 "Something is CRITICAL"'
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.
```

Here are the three different scripts I used in those tests:
check_dummy.ps1
```
if ($args.count -lt 1) { write-host "No exit code was supplied, aborting!"; exit 3 } 
if ($args.count -lt 2) { write-host "No dummy message was supplied, aborting!"; exit 3 } 
write-host "Argument 0 is: " $args[0]
write-host "Argument 1 is: " $args[1]
exit $args[0] 
```

check_dummy.vbs
```
on error resume next 
If wscript.Arguments.Count < 1 Then 
    wscript.Echo "No exit code was supplied, aborting!" 
    wscript.Quit(3) 
ElseIf Wscript.Arguments.Count < 2 Then 
    wscript.Echo "No dummy message was supplied, aborting!" 
    wscript.Quit(3) 
End If 
wscript.Echo "Argment 0 is " & wscript.arguments.item(0) 
wscript.Echo "Argment 1 is " & wscript.arguments.item(1) 
wscript.Quit(wscript.arguments.item(0))
```

check_dummy.bat
```
@echo off 
if [%1] == [] echo No exit code was supplied, aborting! & exit /B 3 
if [%2] == [] echo No dummy message was supplied, aborting! & exit /B 3 
echo Argument 1 is: %1
echo Argument 2 and after is: %~2
exit /B %1%
```

**Comment by jomann09** [comment]
Thanks for the in-depth report... this should be resolved when we change the preferred argument passing method to be POST/GET parameters instead of paths... I am not sure how it will end up working yet but it definitely needs to happen in order for us to be able to pass not only quotes but also things like / correctly to the plugins.

**Comment by jomann09** [comment]
I'm going to close this for #316 so it's condensed and so I can refer back here from that one.
