### ISSUE TITLE
AIX Service problem.

### ISSUE THREAD

**Issue by metabsd** [NagiosEnterprises/ncpa#367]
Hi, 

It's me again :)

I just find a bug with ncpa on AIX. One of our AIX server restart (Because it's our test env) and NCPA don't 
 restart.

To restart ncpa on AIX I have to use that command `/usr/bin/startsrc -e LIBPATH=/usr/local/ncpa -s ncpa_listener`

I don't understand why but I have to manually remove ncpa_listener.pid to restart ncpa_listener with success.

If I enable debug mode in ncpa.cfg I have nothing in the ncpa_listener.log. If I delete the log and try to restart it, the log don't recreate itself. I really need to delete the pid and all the thing work again.

**Comment by metabsd** [comment]
I stop it with `stopsrc -s ncpa_listener` and the PID disappear.

**Comment by jomann09** [comment]
I think this might be a similar issue to the other one with the empty pid file. I am going to put in some code to check a few things and hopefully have it work better.

**Comment by jomann09** [comment]
Should be fixed in #365 / cab54698e0a9338eac5fa37dbb138448a6a8a5d3
