### ISSUE TITLE
NCPA wizard 1.5.0 still ships check_ncpa.py 1.1.0

### ISSUE THREAD

**Issue by jvandermeulen** [NagiosEnterprises/ncpa#375]
On May 2nd check_ncpa.py script was updated to version 1.1.1 #332 however the lastest version of the Nagios XI configuration wizard (1.5.0) still ships version 1.1.0

**Comment by jomann09** [comment]
Pushed a 1.5.1 of the wizard and you should see it shortly. I typically try to let stuff sit for a little bit before including it just to be sure there are no issues that got through testing. It looks good though and so you should see it shortly.
