### ISSUE TITLE
2.0.5 empty key and crt files in directory

### ISSUE THREAD

**Issue by metabsd** [NagiosEnterprises/ncpa#380]
We have +- 500 Linux server and 1 on them got the same bug as [issue 379](https://github.com/NagiosEnterprises/ncpa/issues/379).

```
-rw-r--r-- 1 nagios nagios    0 Sep  1 09:56 ncpa.crt
-rw-r--r-- 1 nagios nagios    0 Sep  1 09:56 ncpa.key
```
I just restart it and the certificat file is stay empty but it's working. Really wierd.

**Comment by metabsd** [comment]
I check couple linux server and all of them have empty certificate file :(

But it's working fine ...

I have to delete those file and restart to make sure of the stability of ncpa on our linux server ?

**Comment by jomann09** [comment]
The empty files should be fine actually. The linux version places them in /usr/local/ncpa and then puts an empty cert/key files in /usr/local/ncpa/var due to the RPM spec file. This will get fixed in the next version but should not be a problem since it doesn't actually use them.

**Comment by jomann09** [comment]
Going to update this for 2.1 to do two things:
1. Actually check to verify that the .crt and .key are actually populated and not just empty files
2. Update the spec file to better handle the /var directory data on uninstall (and upgrade)

**Comment by jomann09** [comment]
This has been fixed
