### ISSUE TITLE
NCPA check process cpu, mem usage by process name

### ISSUE THREAD

**Issue by pilot513** [NagiosEnterprises/ncpa#382]
Hello.
I need check some parameters in run java process, like Apache tomcat, storm, kafka
In process list by name meny process like "java", but i need **tomcat only** (example)

like:
./check_ncpa.py -H localhost -t 'token' -M 'processes' -q 'name=tomcat'

but not find it ;(

Can you help me ? 
PS
may be seek process by pid (from lidfile ? 

ps -fC java
### UID        PID  PPID  C STIME TTY          TIME CMD
storm      717  8856  0 Sep08 ?        00:29:56 java -server -Ddaemon.name=logviewer -Dstorm.options= -Dstorm.h
storm      790  8856  0 Sep08 ?        00:14:40 java -server -Ddaemon.name=drpc -Dstorm.options= -Dstorm.home=/
storm      841  8856  0 Sep08 ?        00:14:51 java -server -Ddaemon.name=ui -Dstorm.options= -Dstorm.home=/op
storm      878  8856  2 Sep08 ?        03:24:48 java -server -Ddaemon.name=nimbus -Dstorm.options= -Dstorm.home
zookeep+ 16249     1  0 Aug15 ?        01:29:17 java -Dzookeeper.log.dir=. -Dzookeeper.root.logger=INFO,CONSOLE
storm    16508 46349  0 Sep14 ?        00:00:23 java -cp /opt/apache-storm-1.1.1/lib/storm-core-1.1.1.jar:/opt/
storm    16524 16508  3 Sep14 ?        00:36:51 java -server -Dlogging.sensitivity=S3 -Dlogfile.name=worker.log
storm    22588 46349  0 Sep12 ?        00:01:21 java -cp /opt/apache-storm-1.1.1/lib/storm-core-1.1.1.jar:/opt/
storm    22604 22588  3 Sep12 ?        02:02:23 java -server -Dlogging.sensitivity=S3 -Dlogfile.name=worker.log
**tomcat   25112**     1  0 Sep12 ?        00:32:21 /usr/java/latest/bin/java -Djava.util.logging.config.file=/opt/
storm    25442 46349  0 Sep12 ?        00:01:21 java -cp /opt/apache-storm-1.1.1/lib/storm-core-1.1.1.jar:/opt/
storm    25458 25442  3 Sep12 ?        02:09:44 java -server -Dlogging.sensitivity=S3 -Dlogfile.name=worker.log
storm    26549 26525  0 Sep12 ?        00:07:09 /bin/java -Xms256m -Xmx256m -Dlogback.configurationFile=/opt/st
storm    46349  8856  0 Sep11 ?        00:18:54 java -server -Ddaemon.name=supervisor -Dstorm.options= -Dstorm.
storm    64410 46349  0 Sep14 ?        00:00:26 java -cp /opt/apache-storm-1.1.1/lib/storm-core-1.1.1.jar:/opt/
storm    64426 64410  3 Sep14 ?        00:41:57 java -server -Dlogging.sensitivity=S3 -Dlogfile.name=worker.log

**Comment by jomann09** [comment]
Unfortunately there is no filter for pid or uid/username (which is tomcat) but could certainly add it. The name field corresponds to the name of the binary that is running, exe is the name of the actual location of the binary, and then there is the cmd which is what was called to run it.

I can add this to the features to add into 2.1, to be able to filter by uid/user and pid.

**Comment by pilot513** [comment]
Adding such functionality would be useful

**Comment by pilot513** [comment]
Hello.
I want to ask about can NCPA in passive mode when send information to NRDP server (1.4.0) send not only "ticket", but and "username" and "password" ?
Because when NRDP server configured to basic auth (example, in httpd) like this:
`<Directory "/usr/local/nrdp">
   SSLRequireSSL
   Options None
   AllowOverride None

  AuthName "NRDP"
  AuthType Basic
  AuthUserFile /usr/local/nrdp/htpasswd.users
<IfModule mod_authz_core.c>
      # Apache 2.4
      <RequireAll>
         Require all granted
         Require valid-user
      </RequireAll>
</IfModule>
</Directory>`
NCPA return error on auth:

`curl -k -L -XPOST 'https://hostname/nrdp/?cmd=submitcmd&token=3n8C7xq15I9qOLnv&command=DISABLE_HOST_NOTIFICATIONS;somehost&btnSubmit=Submit+Command'
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>401 Unauthorized</title>
</head><body>
<h1>Unauthorized</h1>
<p>This server could not verify that you
are authorized to access the document
requested.  Either you supplied the wrong
credentials (e.g., bad password), or your
browser doesn't understand how to supply
the credentials required.</p>
</body></html>
`

**Comment by jomann09** [comment]
If it's basic auth you'd have to add it to the `ncpa.cfg` file for the NRDP url, like:
```
parent = http://username:password@hostname/nrdp/
token = test
```

**Comment by pilot513** [comment]
Thanks!  I'll try it

**Comment by pilot513** [comment]
Hello!
One more question
How to pass a string for:
`check_netsnmp_memory.pl/-H localhost/-C 'Eas5rPI76anpI4w'/-a 'total,user,cached,buffer,%used_real,%used_swap,%user_real,%cached_real'/-w ',,,800MB,,45%,96%,'/-c ',,,950MB,,50%,98%,'`
When i set argument  with symbol "%" agent not responding

**Comment by pilot513** [comment]
Source: https://exchange.nagios.org/directory/Plugins/System-Metrics/Memory/check_snmp_memory-2Epl/details

**Comment by pilot513** [comment]
I'ts actual for ncpa_passive only. For ncpa active check with check_ncpa.py work fine with:
`/usr/lib64/nagios/plugins/check_ncpa.py -H HOSTIP -t 'Eas5rPI76anpI4w' -P 5693 -M 'plugins/check_netsnmp_memory.pl' -a '-L Memory_Utilization -H localhost -C Eas5rPI76anpI4w -a total,user,cached,buffer,%used_real,%used_swap,%user_real,%cached_real -w ,,,800MB,,45%,96%, -c ,,,950MB,,50%,98%,'
Memory_Utilization OK - total is 272223.9 MB [263835.3 MB real 8388.6 MB swap : 11977.3 MB free], user is 215454 MB, cached is 44255.9 MB, buffer is 536.7 MB, %used_real is 98.64%, %used_swap is 0.00%, %user_real is 81.66%, %cached_real is 16.77%`

**Comment by jomann09** [comment]
I'm sorry I thought I had replied to this. Were you asking how to do the above call passively?

**Comment by pilot513** [comment]
Yes. When i try it in passive mode,  argument with symbol "%" agent not responding

**Comment by jomann09** [comment]
Okay I couldn't figure out a good way to run that through as a plugin, this is a similar issue to #316 and will be resolved in this version but I am not going to fix it for this issue. For this issue, I will add in the username filter so you can do `-a 'name=java,username=tomcat` and get your data. In 2.1 you now get memory usage and cpu usage back in the long output and in the perfdata.

**Comment by Shikari0744** [comment]
@jomann09 
I actually need to calculate network usage per process(PID) in java. Common to all operating system ?
Can anyone help me with this ?
