### ISSUE TITLE
Windows service monitoring

### ISSUE THREAD

**Issue by briancamp** [NagiosEnterprises/ncpa#386]
Question, not an issue.

I currently use check_nc_net to monitor Windows services, in this way -

1) Find all service set to start Automatically
2) Check the status of each of those services (running/stopped)
3) Return Critical if any of those services are stopped

Its a good, minimal configuration way of catching various issues on Windows servers. Really hoping to do the same sort of thing using NCPA. I couldn't find a baked in way to find/filter services based on how they're set to start though. Is there one?

Also, I notice in the documentation that the service command is deprecated. What should one use instead?

Thanks much

**Comment by jomann09** [comment]
Currently there is no way in NCPA to be able to tell if a service was supposed to be started or set to stopped, etc. You have to actually specify the status of what you want. You can do a check over multiple services but again, you still have to set the status that you want to warn against.

The service command is now services, just a naming difference and a new way of running the check, previous versions set the service name and status directly in the URI path.

**Comment by briancamp** [comment]
Thanks
