### ISSUE TITLE
NCPA exact match function for checking service status is not functioning correctly.

### ISSUE THREAD

**Issue by tgriep** [NagiosEnterprises/ncpa#388]
When checking to see if a service is running on a Linux host and the service is not running but there is another process running with the search string in it, it will incorrectly state the service is running.

Example if you run the following command to see is Apache is running but the service is not running.

/usr/local/nagios/libexec/check_ncpa.py -H 192.168.4.167 -M 'service/httpd/running' -t ncpapass

It will return that the service is running because of this process has httpd in the command line
root      1642  0.0  0.0  11304  1256 ?        S    12:50   0:00 /bin/sh -c tee -a /var/log/httpd/error_log | nc -u 192.168.223.6 5444

**Comment by jvandermeulen** [comment]
See also issue #265

**Comment by jomann09** [comment]
I think this one is different than that one, because in that there really was an issue with match=exact, this one isn't actually related to the exact match, it's related to how the service is checked for it's status. It does a ps call that it thinks means it's running, if there is anything with an httpd value in it.

**Comment by jomann09** [comment]
This should be fixed with 50401a550f88b18c511a9ea48095bc641c16adfd as best I could, it now uses the `psutil` processes that are running and checks for a processed named as the service. If one does not exist (or it is not running) it tries to do a `service <name> status` and checks the output and exit code - it also times out after 2 seconds. If neither of these work, then the service will be considered stopped. I may actually change this to unknown.

**Comment by jomann09** [comment]
Did what I could on EL6 for this, some processes are going to be in a new `unknown` state due to the permissions. Things like rsyslog and iptables are not able to show up in the status. I would rather not show something as down if it is unable to check for it, so it will now show as unknown in 2.1.

**Comment by jvandermeulen** [comment]
Unfortunately the problem does not see to be fixed. On RHEL6 I installed `zend-server` that uses `lighttpd` and stopped Apache server. This situation matches our customer's environment where Tom Griep raised this issue for.
However an exact match for service "httpd" still reports: "OK: httpd is running" while it's state is stopped.

**Comment by jomann09** [comment]
Is there a process running with the name httpd? Because it checks that before it checks the actual "service httpd status" and if it finds a process then it returns as running.

**Comment by jvandermeulen** [comment]
Not exactly, but httpd is _part_ of the name. What about doing a more precise process name match or perhaps a service check before doing a process check?

```
[root@rhel6-ncpa ~]# ps -ef|grep [h]ttpd
zend      1723     1  0 16:25 ?        00:00:00 /usr/local/zend/gui/lighttpd/sbin/php -c /usr/local/zend/gui/lighttpd/etc/php-fcgi.ini
zend      1726  1723  0 16:25 ?        00:00:00 /usr/local/zend/gui/lighttpd/sbin/php -c /usr/local/zend/gui/lighttpd/etc/php-fcgi.ini
zend      1727  1723  0 16:25 ?        00:00:00 /usr/local/zend/gui/lighttpd/sbin/php -c /usr/local/zend/gui/lighttpd/etc/php-fcgi.ini
zend      1728  1723  0 16:25 ?        00:00:00 /usr/local/zend/gui/lighttpd/sbin/php -c /usr/local/zend/gui/lighttpd/etc/php-fcgi.ini
zend      1729  1723  0 16:25 ?        00:00:00 /usr/local/zend/gui/lighttpd/sbin/php -c /usr/local/zend/gui/lighttpd/etc/php-fcgi.ini
zend      1730  1723  0 16:25 ?        00:00:00 /usr/local/zend/gui/lighttpd/sbin/php -c /usr/local/zend/gui/lighttpd/etc/php-fcgi.ini
lighttpd  4688     1  0 16:32 ?        00:00:00 /usr/sbin/lighttpd -f /etc/lighttpd/lighttpd.conf
[root@rhel6-ncpa ~]# service lighttpd status
lighttpd (pid  4688) is running...
[root@rhel6-ncpa ~]# service httpd status
httpd is stopped
[root@rhel6-ncpa ~]# check_ncpa.py -H localhost -t mytoken -M services -q "service=httpd,match=exact"
OK: httpd is running
```

**Comment by jomann09** [comment]
Can you run this and show me the output?
`check_ncpa.py -H localhost -t mytoken -M processes -q 'name=httpd' --list`
I am doing a direct check for name using psutil's list of processes, and looking for the service name specifically, I would expect it'll show none so it's odd that it would be coming back as running.

**Comment by jvandermeulen** [comment]
Indeed, it shows none.
```
[root@rhel6-ncpa ~]# check_ncpa.py -H localhost -t mytoken -M processes -q 'name=httpd' --list
{
    "processes": []
}
```

**Comment by jomann09** [comment]
I'll test this more here in a bit with the same setup you're using, more or less, and see if I can figure out what is causing that to show up as running.

**Comment by jvandermeulen** [comment]
Excellent... If you think I can assist in testing please let me know

**Comment by jomann09** [comment]
I overlooked this... so I just fixed it. Really simple change. a3e8eca9f409082506ba24ec9bb9b075380160f1

However, I should just give a little note that apparently using `service httpd status` requires special privileges so it will show up as unknown unless running the agent's daemon as root.

**Comment by jvandermeulen** [comment]
@jomann09 tomorrow I will be visiting the customer this issue was raised for. The servers running lighttpd are EL6 x86_64. Could you please build a package under the https://assets.nagios.com/downloads/ncpa/dev/ tree for EL6? Thank you in advance.

**Comment by jomann09** [comment]
Sure  thing, I will build it now. I should be releasing 2.1.2 today too.
