### ISSUE TITLE
Passive checks fail when the service has spaces in the name

### ISSUE THREAD

**Issue by ludmilmm** [NagiosEnterprises/ncpa#390]
Passive checks fail when the service has spaces in the service/display name. I was able to recreate the issue on Windows 7, NCPA ver. 2.0.5.

When I use the API Passive Check Example:
`%HOSTNAME%|<service name> = services?service=AMD External Events Utility&status=running`

given by API, I end up with the following error in the GUI:

> UNKNOWN: No services selected with 'service' value given

In order to solve the issue, I had to change my service definition from this:

`%HOSTNAME%|AMD External Events Utility = services?service=AMD External Events Utility&status=running`

to this:

`%HOSTNAME%|AMD External Events Utility = services?service=AMD+External+Events+Utility&status=running`

**Comment by jomann09** [comment]
Fixed this in 0d77bd6efe9fc36512054d1a8c2d759181024c8d
