### ISSUE TITLE
Check Statistics Missing in NCPA 2.0.4+ Dashboard

### ISSUE THREAD

**Issue by corvar** [NagiosEnterprises/ncpa#394]
I have not installed NCPA 2.0.3, so I can't comment on that.

In NCPA 2.0.2, passive checks are shown in the GUI dashboard, the quantity shows on the dashboard, and clicking "Checks" lists the specific check performed, when, results, etc.

As of NCPA 2.0.4, that functionality seems to be gone, and is still gone in 2.0.5.

I may be missing something in the CHANGES file, but I don't see where it is mentioned that it is expected to be gone.

**Comment by jomann09** [comment]
Are you able to take a screenshot of this for me? I am not sure what specific part you mean. If you're referring to the number of check results, and it's empty, then that might be a bug.

**Comment by corvar** [comment]
![ncpa2-good](https://user-images.githubusercontent.com/1695677/31411283-c6636f62-add6-11e7-9b98-b0441e5b6905.PNG)
![ncpa1](https://user-images.githubusercontent.com/1695677/31411284-c6781d9a-add6-11e7-80de-9abbf9d00db4.PNG)
![ncpa1-good](https://user-images.githubusercontent.com/1695677/31411286-c694b7f2-add6-11e7-9fc4-e11ae4f26b25.PNG)
![ncpa2](https://user-images.githubusercontent.com/1695677/31411287-c6a8b7fc-add6-11e7-9076-f7e372e42ae5.PNG)

A 2.0.2 agent and a 2.0.5 agent, configured the same way as far as I can tell, both of them are properly reporting results passively via nrdp.

**Comment by jomann09** [comment]
This is likely a bug, I will take a look. I see that one of mine seems to not be updating the db either. There were some changes in 2.0.4 to how it wrote to the DB so that might have caused this.

**Comment by jomann09** [comment]
Looks like passive checks were not being reported in > 2.0.4 so I fixed it here bb26119d7ca526b061327cb60401007671a8724d for 2.0.6
