### ISSUE TITLE
Passive service definition <servicename> does not allow :

### ISSUE THREAD

**Issue by box293** [NagiosEnterprises/ncpa#395]
If your service definition <servicename> has a `:` in the name then it causes the command to fail.

Here is an example:
```
%HOSTNAME%|Disk Used root: = disk/logical/| --warning 80 --critical 90 --units Gi
```
OR:
```
%HOSTNAME%|Disk Usage E: = disk/logical/E:/used_percent --warning 80 --critical 90
```

The output sent to NRDP is:
```
The node (=) requested does not exist.
```

In `var/log/ncpa_passive.log` you see the following message:
```
2017-10-19 11:34:54,977 9248 INFO Running check: = disk/logical/| --warning 80 --critical 90 --units Gi
2017-10-19 11:34:54,977 9248 WARNING Unable to parse all arguments from instruction. Mis-paired option: Gi
```
OR
```
2017-10-19 11:34:54,977 9248 WARNING Unable to parse all arguments from instruction. Mis-paired option: 90
```

This occurs on Windows and Linux.

I could not find any information in the NCPA documentation on characters that cannot be used in the `<servicename>`.

**Comment by jomann09** [comment]
Going to close this because this can't be "fixed" although in the newest versions of Python 3 it won't be an issue. Essentially the `:` is used as a way to break values out in the config parser, just like the `=` sign, which we use in the examples. You can't change that in Python 2.x either.
