### ISSUE TITLE
NCPA listener error 500 when started via upstart

### ISSUE THREAD

**Issue by frogstarr78** [NagiosEnterprises/ncpa#399]
I'm having a number of servers that with issues similar to this reported issue, although slightly different. https://github.com/NagiosEnterprises/ncpa/issues/365

The problem I'm having, specifically, is when starting the daemon via the upstart script `sudo /etc/init.d/ncpa_listener start` it doesn't work. I have to manually run the daemon `/usr/local/ncpa/ncpa_listener --start` in order to get it to work.

When using the upstart script, everything appears to have worked. I get a process ID. I can see it in ps aux or top. I can see that the server says it's listening on port 5693 using netstat, but when calling the check on the remote nagios server I receive a 500 Internal server error.

I'm having this issue on two CentOS 7 servers. They are both running version 2.0.5. I've tried removing and reinstalling and updating (they were running 2.0.4).

Attached is an example of the error log.
[ncpa_listener.log](https://github.com/NagiosEnterprises/ncpa/files/1441774/ncpa_listener.log)

I can provide an strace stack trace also if needed.

**Comment by jomann09** [comment]
This is an issue when running in some virtualize environments with no procs. I'm going to be building the 2.0.6 versions tomorrow and I will verify that the try/catch for this is in there. I thought we just needed to upgrade psutils but I thought it was already updated for 2.0.5 - but I will check it again.

**Comment by jomann09** [comment]
This is actually a different issue and I've fixed it for 2.0.6 in f851f79c52f98ae88fae408ad3632bbe3d584210

**Comment by frogstarr78** [comment]
This is still an issue in version 2.0.6

**Comment by frogstarr78** [comment]
Fixed the issues for me. Thank you
