### ISSUE TITLE
Thresholds that start with colon : don't work

### ISSUE THREAD

**Issue by box293** [NagiosEnterprises/ncpa#402]
Thresholds that start with colon `:` don't work.

I was reading this:
https://github.com/NagiosEnterprises/ncpa/issues/205#issuecomment-160688210

Just a number is treated as `-c :15` which means anything up to 15 passes the test, but anything above 15 fails. 

So here's the normal test:
```
./check_ncpa.py -H 10.25.254.50 -t Str0ngT0k3n -M 'disk/logical/|/used_percent' --warning 90 --critical 95
OK: Used_percent was 35.20 % | 'used_percent'=35.20%;90;95;
```
Here is the test but putting a colon at the beginning:
```
./check_ncpa.py -H 10.25.254.50 -t Str0ngT0k3n -M 'disk/logical/|/used_percent' --warning :90 --critical :95
Improper warning/critical format.
```

**Comment by jomann09** [comment]
This will be fixed in the next version of the plugin (which will come out with NCPA 2.1 also)

**Comment by jomann09** [comment]
Actually forget what I said, it's not part of the plugin - the thresholds are actually checked inside the agent so it will be in 2.1
