### ISSUE TITLE
Windows Counters from 'Security System-Wide Statistics' return 0 data. 

### ISSUE THREAD

**Issue by zabulon1** [NagiosEnterprises/ncpa#403]
Nagios NCAP Agent 2.0.5
Windows server 2016

I'm trying to get counters from:

> \Security System-Wide Statistics\NTLM Authentications
> \Security System-Wide Statistics\Kerberos Authentications
> 

But they both return 0. If i run the windows perfmon they have lot of data !

From the windows Agent API:
`https://WINServerX:5693/api/windowscounters/Security System-Wide Statistics/NTLM Authentications?check=true
`
```
{
    "returncode": 0,
    "stdout": "OK: \\Security System-Wide Statistics\\NTLM Authentications was 0.00 NTLM Authentications | '\\Security System-Wide Statistics\\NTLM Authentications'=0.00;;;"
}
```
AND 

`https://WINServerX:5693/api/windowscounters/Security System-Wide Statistics/Kerberos Authentications
`
```
{
    "returncode": 0,
    "stdout": "OK: \\Security System-Wide Statistics\\Kerberos Authentications was 0.00 Kerberos Authentications | '\\Security System-Wide Statistics\\Kerberos Authentications'=0.00;;;"
}

```
From window Perfmon
![permon](https://user-images.githubusercontent.com/17967848/33291349-8733c278-d393-11e7-8a47-63bf37f5d0c0.jpg)

Am I missing something ?

Dominic

**Comment by jomann09** [comment]
Does this counter happen to be per second? Unfortunately in order to get per-second data for a counter you have to add a `sleep` time to the command so you'd do `&sleep=1` in the URL to get 1 second worth of counter data.

**Comment by zabulon1** [comment]
OK !!!  So i add "-q 'sleep=1'" in the check command $ARG1$ and it work fine !!  

Thank you very much

**Comment by jomann09** [comment]
Awesome glad it's working, any per second counter will need that extra sleep argument
