### ISSUE TITLE
Passive check definition for multiple services returns only one

### ISSUE THREAD

**Issue by jvandermeulen** [NagiosEnterprises/ncpa#404]
Using the NCPA Gui (API Endpoint: Services) I selected two services  (_match type_=exact match).  The URL looks like this:

> https://localhost:5693/api/services?service=SONICWALL_NetExtender&service=FortiSslvpnDaemon&check=true

After hitting the reload button: the outcome is as expected:

> { "returncode": 0, "stdout": "OK: SONICWALL_NetExtender is running, FortiSslvpnDaemon is running" }

However the suggested config line for a passive service (provided by View in alternate format > As passive check config definition) is wrong. It returns only one service. The suggested line is:

> %HOSTNAME%|<service name> = services?service=SONICWALL_NetExtender&service=FortiSslvpnDaemon

Only the first service is returned here. I can't find the proper syntax for checking both services as passive check.

**Comment by box293** [comment]
I can also reproduce this.

I was able to do a work around by doing a regex match, for example:

```
%HOSTNAME%|Service Test 2 = services?service=^WinRM$|^Winmgmt$&match=regex
```

Nagios receives:
```
[1511828983] PASSIVE SERVICE CHECK: S1601;Service Test 2;0;OK: WinRM is running, Winmgmt is running
```

**Comment by jomann09** [comment]
I'll take a look at this, sounds like a bug with how the passive check connects to the API

**Comment by jomann09** [comment]
Fixed, should work properly now with url-based checks.
