### ISSUE TITLE
NCPA - Windows event message log not listed on the alarm

### ISSUE THREAD

**Issue by senthilchokkalingam** [NagiosEnterprises/ncpa#405]
NCPA - Windows event message log not listed on the alarm. Agent is ncpa-2.0.6.exe

Query #1
=========

In the Query 1, it lists the message but not marked as warning.

[nagios@xi01.net ~]$ /usr/local/nagios/libexec/check_ncpa.py -H IP -t 'token123' -P 5693 -M 'logs' -q 'name=Application,severity=WARNING,application=SnapShotCheck,logged_after=4h,event_id=1' -w 1 -l list
{
"logs": [
{
"Application": [
{
"category": "1",
"severity": "WARNING",
"event_id": "1",
"application": "SnapShotCheck",
"computer_name": "domain.net",
"message": "The following VM has a snapshot older than 5 days (@{VM=Server01; Size=2.24 GB; Created=11/17/2017 20:13:24})\r\n",
"time_generated": "11/28/17 15:07:43"
}

Query #2
========

If I remove -l list, it will mark the alarm as warning but will give only the count of the event log (not the actual message of the event log like below..So this makes hard as we have to login to the server to identify what the event is all about.

[nagios@xi01.net ~]$ /usr/local/nagios/libexec/check_ncpa.py -H IP -t 'token123' -P 5693 -M 'logs' -q 'name=Application,severity=WARNING,application=SnapShotCheck,logged_after=4h,event_id=1' -w 1

WARNING: Application has 1 logs, Total Count has 1 logs (Time range - last 4 hours) | 'Application'=1;0;; 'Total Count'=1;0;;

We need the alarm as warning and list the contents of the message as well like below..

The following VM has a snapshot older than 5 days (@{VM=Server01; Size=2.24 GB; Created=11/17/2017 20:13:24})\r\n",
"time_generated": "11/28/17 15:07:43"

**Comment by jomann09** [comment]
This currently doesn't exist yet, but I can add this as a feature request. I was considering putting the logs it finds into the long output for the checks, which would allow you to see the logs by default.

**Comment by senthilchokkalingam** [comment]
Thanks Jake.  Will the fix include actual alarm such as warning/critical and contents of the message/log as well?   Also, any time line on the fix please?

**Comment by jomann09** [comment]
Do you mean still have it show as WARNING: <output> ?

I think this can be added for 2.1, considering that code-wise it's not a big change.

**Comment by senthilchokkalingam** [comment]
Yes. For example, if we put the list (check disabled) using this query..this is what we get.
 /usr/local/nagios/libexec/check_ncpa.py -H IP -t 'token123' -P 5693 -M 'logs' -q 'name=Application,severity=WARNING,application=SnapShotCheck,logged_after=4h,event_id=1' -w 1 -l list

![image](https://user-images.githubusercontent.com/32526987/33448692-47976f1c-d5cc-11e7-9829-62bae0e6b235.png)

if we put the check enabled, it will only show the total number of logs without any content like below
 /usr/local/nagios/libexec/check_ncpa.py -H IP -t 'token123' -P 5693 -M 'logs' -q 'name=Application,severity=WARNING,application=SnapShotCheck,logged_after=4h,event_id=1' -w 1

![image](https://user-images.githubusercontent.com/32526987/33448777-8564dee2-d5cc-11e7-966e-cb7c20c6902c.png)

**Comment by senthilchokkalingam** [comment]
We need to have Warning marked as Warning and Error/Critical marked as Critical along with the actual message/event log.

**Comment by jomann09** [comment]
Okay great thanks for explaining I will get this in here for 2.1.

**Comment by senthilchokkalingam** [comment]
Thank you Jake

**Comment by jomann09** [comment]
Added to 2.1 in 0b542f8230c9c0483f397dfdc998572a2748dc18
