### ISSUE TITLE
NCPA 2.1.0 - System API endpoint

### ISSUE THREAD

**Issue by jvandermeulen** [NagiosEnterprises/ncpa#411]
Found a backward compatibility issue related to the `system` API part of the brand new 2.1.0 version.
Please observe the following examples.

> [nagios@xi ~]$ /usr/local/nagios/libexec/check_ncpa.py -H win-ncpa-210 -t ${TOKEN} -P 5693  -M "system/agent_version"
> need more than 2 values to unpack
> [nagios@xi ~]$ /usr/local/nagios/libexec/check_ncpa.py -H win-ncpa-210 -t ${TOKEN} -P 5693  -M "system/node"
> need more than 2 values to unpack
> [nagios@xi ~]$ /usr/local/nagios/libexec/check_ncpa.py -H win-ncpa-210 -t ${TOKEN} -P 5693  -M "system/agent_version"  -l
> {
>     "agent_version": "2.1.0"
> }
> [nagios@xi ~]$ /usr/local/nagios/libexec/check_ncpa.py -V
> check_ncpa.py, Version 1.1.1

Switching to the previous version (NCPA 2.0.6).. it gives us:

> [nagios@xi ~]$ /usr/local/nagios/libexec/check_ncpa.py -H win-ncpa-206 -t ${TOKEN} -P 5693  -M "system/agent_version"
> OK: Agent_version was ['2.0.6']
> [nagios@xi ~]$ /usr/local/nagios/libexec/check_ncpa.py -H win-ncpa-206 -t ${TOKEN} -P 5693  -M "system/node"
> OK: Node was ['win-ncpa-206']

Most of our customers use some of the API `system` endpoints like `release, node`, or `agent_version` for displaying informational "checks" in Nagios GUI. After upgrading to version 2.1.0 all those checks would end up as state `UNKNOWN` with output "`need more than 2 values to unpack`"

I suspect recent changes with regards to the `uptime` endpoint cause this behaviour, but I'm not sure about this.

**Comment by karatalapu80** [comment]
I see similar error for services running and processes as well

2017-12-20 17:29:51,108 22571 INFO Running check: system/agent_version
2017-12-20 17:29:51,293 22571 INFO Did not receive normal values. Unable to find meaningful check.
2017-12-20 17:29:51,294 22571 ERROR need more than 2 values to unpack
Traceback (most recent call last):
  File "/root/ncpa/agent/listener/nodes.py", line 292, in run_check
ValueError: need more than 2 values to unpack

**Comment by jomann09** [comment]
I'm taking a look, for the processes endpoint, that should work, what were you passing for that one?

**Comment by jomann09** [comment]
Fixed this in b873dc9bf890e2c93df8c3db2548a1d4cddf125a

I'll release a 2.1.1 soon but I will do some other checks in case there was another issue.

**Comment by karatalapu80** [comment]
Sorry I had a typo in the configuration that caused the issue. Please ignore my message. 

Thanks
Krishna

**Comment by jomann09** [comment]
No problem, I'm going to close this and I will probably release the next version tomorrow morning. Thanks for finding this.
