### ISSUE TITLE
Max retries exceeded [Failed to establish a new connection]

### ISSUE THREAD

**Issue by pilot513** [NagiosEnterprises/ncpa#412]
Today on Client-Side get error:

`2017-12-24` 14:59:15,966 13138 ERROR HTTPSConnectionPool(host='NRDPhost', port=443): Max retries exceeded with url: /nrdp/ (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fe4bf13e7d0>: Failed to establish a new connection: [Errno 111] Connection refused',))`

This is a problem on the httpd side ?

**Comment by jomann09** [comment]
That seems like an issue with httpd on the NRDP side. Can you connect to your nrdp location from the box that is running NCPA?

**Comment by pilot513** [comment]
Thank you! I figured it out. The problem was with one of the passive processing plug-ins - check_jmx. He did not pass authorization, while the passive-listener when sending the result to NRDP gave such a message

**Comment by jomann09** [comment]
Awesome, glad you got it figured out.
