### ISSUE TITLE
New bug introduced in 2.1: service endpoint broken

### ISSUE THREAD

**Issue by gerapeldoorn** [NagiosEnterprises/ncpa#416]
Hi,

Since ncpa version 2.1 I cannot check if services are running on Centos7:

[root@nagiosxi ~]# /usr/local/nagios/libexec/check_ncpa.py -H my-hostname -t 'yadayada' -P 5693 -M 'service/kubelet/running'
The node (service) requested does not exist. You may be trying to access the 'services' node.

* yum downgrade ncpa-2.0.6-1.el7.centos **on my-hostname**

[root@nagiosxi ~]# /usr/local/nagios/libexec/check_ncpa.py -H my-hostname -t 'yadayada' -P 5693 -M 'service/kubelet/running'
OK: kubelet is running

Thanks,
Ger

**Comment by jvandermeulen** [comment]
Hello Ger, it seems NCPA 2.1.1 enforces using the new syntax mentioned in paragraph _Deprecated service and process nodes_ on https://www.nagios.org/ncpa/help.php#index-changes-in-2 
(this documentation is also available on every NCPA client at https://my-hostname:5693)

In your case the syntax should be:
` /usr/local/nagios/libexec/check_ncpa.py -H my-hostname -t 'yadayada' -P 5693 -M services -q "service=kubelet,status=running"` where `status=running ` is optional (as _running_ is default)

Regards, Jørgen

**Comment by gerapeldoorn** [comment]
Hi Jørgen,

Great, that fixes the issue. Thanks and see you soon!

Ger
