### ISSUE TITLE
ImportError: No module named site

### ISSUE THREAD

**Issue by karatalapu80** [NagiosEnterprises/ncpa#417]
Using ncpa on centos7 I am seeing this error. 

```
{ "returncode": 1, "stdout": "Could not find platform independent libraries \nCould not find platform dependent libraries \nConsider setting $PYTHONHOME to [:]\nImportError: No module named site"
}
```
I am using the latest version of ncpa (2.1.1). I donot see any issues on centos 6. Its only happens with centos 7. Also running the plugin manually I do not see any import errors this only happens with python based plugins. Wanted to check if you are aware of any issues with ncpa on centos 7 .

Thanks
Krishna

**Comment by jomann09** [comment]
We are aware of the issue, we were exporting a value into the `LD_LIBRARY_PATH` in the init script in `/etc/init.d/ncpa_<type>` you can remove that export line and restart NCPA and it should work. We are going to be fixing this for 2.1.2 by doing this a different way. It shouldn't have any effects on CentOS 7.

**Comment by jomann09** [comment]
Removed what was causing the issue in ae462b5cf526c3d66e4f1dbef94540928141f9b7
