### ISSUE TITLE
Perf data difference from 2.0.5 to 2.1.1

### ISSUE THREAD

**Issue by metabsd** [NagiosEnterprises/ncpa#418]
HI,

I update 4 Centos ncpa agent on 29 december. This morning I double check couple thing before starting to deploy that version on all other RHEL/Centos server. I don't see any graph information in Nagios XI perf graph on the 4 Centos I update. I think I find why. Before the update the default perf output was used_percent and now I see other information about used in Megabyte. I don't change my configuration

SERVER A with NCPA version 2.0.5.
ncpa-2.0.5-1.el6.x86_64
From Nagios XI Server I run that command : `check_ncpa.py -H servera -t 'token' -P 5693 -M 'disk/logical/|opt' -u M -w 90 -c 95`

Result:
```
OK: Used disk space was 41.80 % (Used: 2462.95 MB, Total_size: 6207.11 MB, Free: 3425.44 MB) | 'used_percent'=41.80%;90;95;
```

SERVER B with NCPA version 2.1.1.
ncpa-2.1.1-1.el7.centos.x86_64

From Nagios XI I run that command : `check_ncpa.py -H serverb -t 'token' -P 5693 -M 'disk/logical/|var|lib|elasticsearch' -u M -c 85`

Result : 
```
OK: Used disk space was 38.30 % (Used: 123375.86 MB, Free: 198694.26 MB, Total: 322070.12 MB) | 'used'=123375.86MB;;85; 'free'=198694.26MB;;85; 'total'=322070.12MB;;85;
```

The perf data seem to be different. I think Nagios XI cannot continue to show the data because he change.

Thank you!!!

**Comment by box293** [comment]
This can be resolved by specifically targetting the `/used_percent` node, for example:

Normally:
```
./check_ncpa.py -H 10.25.13.37 -t 3RuC3sR3PuS -P 5693 -M 'disk/logical/|' -u M -c 85

OK: Used disk space was 9.80 % (Used: 1456.61 MB, Free: 13422.69 MB, Total: 14879.29 MB) | 'used'=1456.61MB;;85; 'free'=13422.69MB;;85; 'total'=14879.29MB;;85;
```

With `/used_percent` node:
```
./check_ncpa.py -H 10.25.13.37 -t 3RuC3sR3PuS -P 5693 -M 'disk/logical/|/used_percent' -u M -c 85

OK: Used_percent was 9.80 % | 'used_percent'=9.80%;;85;
```

After about 15 minutes your graph data should start to update.

**Comment by jomann09** [comment]
There is also a KB article I can look for that explains how to update the RRD file with the new data points. But barring that you can do what @box293 said or if historical data doesn't matter, you can reset the RRDs by deleting them for the services you are having problems with.

**Comment by jomann09** [comment]
How to delete a data point from an RRD:
https://support.nagios.com/kb/article/nagios-xi-how-to-delete-a-data-source-from-an-rrd-file-497.html

How to update your RRD with new data points:
https://support.nagios.com/kb/article.php?id=149

**Comment by jvandermeulen** [comment]
@jomann09 when `/used_percent` is omitted the three different data sources (`used`, `free` and `total`) in the performance data output should be _calculated_ thresholds in megabytes (_unit of measurement_ specified for was `-u M`) instead of percentages imho.

So instead of..

> 'used'=1456.61MB;;85;

I would expect 

> 'used'=1456.61MB;;273759.60;

Do you agree?

**Comment by jomann09** [comment]
Yes I agree, I will add that in for the next release and mark this as a bug also.

**Comment by box293** [comment]
While we are talking about multiple nodes, is it possible to chose which nodes will be returned? Like:
```
OK: Used disk space was 9.80 % (Used: 1456.61 MB) | 'used_percent'=9.80%;;85 'used'=1456.61MB;;2000;
```

Along the lines @jvandermeulen would it be possible to have thresholds for different nodes? Like `used_percent=10%` OR `used=2000`.

**Comment by jomann09** [comment]
That is a good idea, and I think you should probably post it as a feature request for 3 since it is going to have to be one of those things we re-work in 3. Currently, there isn't an easy way to create multiple thresholds (it just wasn't thought about at the time) so we would likely want to build it in for the new structure.

**Comment by jomann09** [comment]
Added perfdata properly with 5c42866d7da4697f26526cdf69727becd560b986 and will be releasing 2.1.2 shortly.
