### ISSUE TITLE
NCPA 2.0.X -> 2.1.1 windowscounters for RDP doesn't work

### ISSUE THREAD

**Issue by manas3** [NagiosEnterprises/ncpa#429]
Hey Guys,

I was looking at the documentation but no luck yet to fix.

I recently testing upgrade of ncpa agents in few of my Windows servers and after the upgrade to 2.1.1 the Terminal services active sessions check is not working anymore.

But agents running on 2.0.X still works fine

This is the service check from NagiosXI
`
ncpa_check.py -t 'token' -P 5693 -M "windowscounters/Terminal Services/Active Sessions" -w 200 -c 1000 
`

Can you please help what's wrong?

Thanks 
Manas

**Comment by jomann09** [comment]
There is actually a bug in 2.1.1 involving windows counters which is probably why you're having the issue. If you look in the `ncpa_listener.log` in the `var/logs` folder wherever you installed it in your Windows machine you should see errors from trying to call that endpoint. It is resolved in 2.1.2 and should be out relatively soon once I get the last couple fixes in.
