### ISSUE TITLE
change system time，The script stops

### ISSUE THREAD

**Issue by chenzilong444** [NagiosEnterprises/ncpa#430]
i find my system time error，so i forward the time，then ,every script stopped，is that ncpa use the system time as Time slice？can i let it use server time?

the other question
   when i open a program which update camera data ，last update is updating ，but the last check will not change

**Comment by jomann09** [comment]
I don't think we do anything that relies specifically on the system's time. Can you check in `/usr/local/ncpa/var/log/ncpa_listener.log` and copy in anything that is an error?

Are you running a plugin? I'd also check the log and let me know.

**Comment by jomann09** [comment]
Closing this due to lack of information. Let us know if you have any other questions.
