### ISSUE TITLE
Building on VMware Photon 1.0

### ISSUE THREAD

**Issue by tonykli** [NagiosEnterprises/ncpa#433]
Hello, I am trying to build the ncpa package on this distribution. (It is used by vSphere 6.5) But it fails probably because of this: 

/usr/lib/gcc/x86_64-unknown-linux-gnu/5.3.0/include-fixed/limits.h:168:61: fatal error: limits.h: No such file or directory

By googling I found out, that this probably has to do with kernel-headers, but  AFAIK those are installed. (linux-dev-4.4.115-1.ph1.x86_64 on this distribution). The whole output is included below.

[all.txt](https://github.com/NagiosEnterprises/ncpa/files/1733552/all.txt)

**Comment by jomann09** [comment]
So you have `glibc` / `glibc-devel` installed also? I'm not all that familiar with the operating system, is it a clone of something?

**Comment by tonykli** [comment]
Nice. That get me going. The glibc-devel package was indeed missing. This is a rpm based distribution which seems to be using at least a lot of the same package names as fedora. 

I was able to successfully build the rpm package, after installing these packages with tdnf:

linux-api-headers.noarch
libgcc-devel.x86_64
libgcc-atomic.x86_64
linux-dev.x86_64
glibc-devel.x86_64
binutils.x86_64
binutils-devel.x86_64
make
elfutils
diffutils

Not sure if all of those are needed.

Anyway I installed this package on a vsphere 6.5 appliance and it works!

**Comment by jomann09** [comment]
Awesome! Glad to see it working. I can do a bit of testing and add it to the list it tells you to install when you are manually building it.

**Comment by box293** [comment]
@tonykli If you are able to give us any specific list of commands then we can also add this to our documentation (https://support.nagios.com/kb/article/ncpa-how-to-build-ncpa-from-source-521.html).

**Comment by jomann09** [comment]
Closing this, if you'd like to share more info please do.
