### ISSUE TITLE
NCPA SLES 11 SP2  An error occurred:'value'

### ISSUE THREAD

**Issue by pnavarrotre** [NagiosEnterprises/ncpa#434]
Running NCPA on SLES 11 SP3. Getting error below for the three default service checks in Nagios XI web interface. Server is up and ping is fine. Can connect over HTTPS port 5693 fine and see service checks with status OK and live data works fine.

NCPA 2.1.1
ncpa-2.1.1.os11x86_64.rpm

SLES 11 SP4 

In Nagios XI:
NCPA CPU, Main Memory, Swap Usage - Status Unknown

[nagios@nagios.tre.state.ma.us ~]$ /usr/local/nagios/libexec/check_ncpa.py -H vms1.tre.state.ma.us -t 'TRE-NCPA-NXI-Token' -P 5693 -M memory/virtual/percent -w 60 -c 80 -v
Connecting to: https://vms1.tre.state.ma.us:5693/api/memory/virtual/percent/?token=TRE-NCPA-NXI-Token&warning=60&critical=80&check=1
File returned contained:
{
    "returncode": 0,
    "stdout": "OK: Percent was 20.00 % | 'percent'=20.00%;60;80;"
}
An error occurred:'value'

Thanks.

**Comment by jomann09** [comment]
Are you using the latest version of check_ncpa.py?

**Comment by pnavarrotre** [comment]
The Nagios XI appliance version is 5.4.12 released 1/16/2018. It’s check_ncpa.py is date 11/4/2016. I looked at the code and it states version 0.3.5. I figured since it is an appliance it would update all components. Should I download and install the latest check_ncpa.py which is version 1.1.1? Thanks.

Peter L. Navarro
Assistant Treasurer of IT
Massachusetts State Treasury
1 Ashburton Place 12th Floor
Boston, MA 02108-1518
E-mail: pnavarro@tre.state.ma.us<mailto:pnavarro@tre.state.ma.us>
Tel.: 617-367-9333 x 665
Fax: 617-367-7748

**Comment by jomann09** [comment]
I believe you need version 1.0+ but that should be updated on the VM you had. You can go to Admin > Manage Config Wizards > Check for Updates in the GUI and upgrade the NCPA wizard. That should update your NCPA wizard and plugin to the latest version. I will double check this against SLES 11 here but I haven't had issues myself.

**Comment by pnavarrotre** [comment]
That did it. NCPA was upgraded to 1.5.3. check_ncpa.py itself on the appliance was upgraded to 1.1.2.
Sorry about that. Thanks for your help.

Peter L. Navarro
Assistant Treasurer of IT
Massachusetts State Treasury
1 Ashburton Place 12th Floor
Boston, MA 02108-1518
E-mail: pnavarro@tre.state.ma.us<mailto:pnavarro@tre.state.ma.us>
Tel.: 617-367-9333 x 665
Fax: 617-367-7748

**Comment by jomann09** [comment]
No problem, glad that fixed it!
