### ISSUE TITLE
Interogate NCPA API Endpoint Services get invalid result (UNKNOW)

### ISSUE THREAD

**Issue by Leonardomanetti** [NagiosEnterprises/ncpa#438]
Hi **support**, 
after update NCPA linux version from 2.0.6 to 2.1.3, query result of services status report an invalid result.

With previous version 2.0.6 all works fine
example: 
./check_ncpa.py -H host -t ‘*******' -M 'services' -q 'service=postfix'
OK: postfix is running

while after update to 2.1.3:
example: 
./check_ncpa.py -H host '********' -M 'services' -q 'service=postfix'
CRITICAL: postfix is unknown (should be running)

With new versione 2.1.3, browsing API Endpoint services on web interface "https://host:5693/gui/api",   several services are on incorrect status (UNKNOW)

![captureaaa](https://user-images.githubusercontent.com/37104335/37026154-d71cde22-212d-11e8-9ae6-03127fbde8f6.JPG)

**Comment by jomann09** [comment]
So in 2.1.3 there were changes with how services work. I'm assuming you're running on EL6? Basically the unknown status means that there was no accurate way for us to check if the process was running without writing in special tests that check if the service's process is running. This was done because the services that now show up as unknown were highly inaccurate and we don't want to tell people something is up if we aren't really sure it is.

**Comment by Leonardomanetti** [comment]
Hi support, 
i'm using CentOS release 6.9. So, i've understand with NCPA 2.1.3 can't monitoring status of several services.
What do you suggest for workaround this issue? Remain on previous version, otherwise?
Thank you for answer
LM

**Comment by jomann09** [comment]
Remaining on the previous version would probably be fine if that works for you. The only other way around it would be to run a custom plugin/shell script that would grab statuses of the things you want if you knew exactly how to check for them.

**Comment by pconti80** [comment]
Hi there,
same issue here with ubuntu 14.04 on several services ncpa is reporting that are stopped, while they are running.
Services involved:
mysql, postfix, newrelic-plugin.

Services' init script are the default from distribution

**Comment by metabsd** [comment]
Hi, I have the same prolem on all RHEL 6 with ncpa 2.1.3. Can you handle that please ?

```
[root@sldtws0273 log]# service postfix status
master (pid  60837) is running...
[root@sldtws0273 log]# /etc/init.d/postfix status
master (pid  60837) is running...
```

But Nagios see the result like that.

```
CRITICAL: postfix is unknown (should be running), rsyslog is unknown (should be running), sshd is running, vasd is running, crond is running, ntpd is running
```

**Comment by metabsd** [comment]
I try to upgrade to 2.1.4 to see if the bug is fix but I have it. I also downgrade  and try 2.1.2, 2.1.1, 2.1.0 and I have the same problem. Do you plan to fix it shortly ?

Thank you!

**Comment by metabsd** [comment]
Really wierd I see rsyslog ok in 2.1.0 but the status is unknown with 2.1.4 ....

**Comment by jomann09** [comment]
So the fix was that the service status is set to unknown if NCPA can't actually verify the status of the service that is running. I will take another look into the ones you mentioned above.

**Comment by jomann09** [comment]
I'm closing this since #391 is an enhancement in 3 that should make this better. Including, hopefully, more information on why a service is unknown and possibly other checks to find service status.
