### ISSUE TITLE
Nagios interface check - An error occurred:HTTP Error 500: INTERNAL SERVER ERROR

### ISSUE THREAD

**Issue by CSimpiFoN** [NagiosEnterprises/ncpa#441]
OS: CentOS 7
check_ncpa.py version: Version 1.1.3
NCPA version: 2.1.3-1.el7.cento - installed by Yum, from the official Nagios repository
Cannot monitor the network interfaces with the new version anymore. The NCPA plugin with Nagios drops back the following error if I run it with the -v flag:
An error occurred:HTTP Error 500: INTERNAL SERVER ERROR
Command:
python /usr/local/nagios/libexec/check_ncpa.py -H {hostname} -t '{token}' -M 'interface/eth1' -v

Also, the NCPA listener API stops working if I want to see the network interface as Nagios check.
Steps to reproduce:
Log in to API -> API -> 'Endpoint: Interface' -> Select an interface -> Tick 'Run as a Nagios check' -> Reload
Result:
The API loading circles keep moving forever, but never shows actual result.

**Comment by jomann09** [comment]
Looks like this is a bug. I'll file it for the next bug fix release.

**Comment by jomann09** [comment]
Fixed in 317f5a11aa4f34e8224e01644470cf38432d2829
