### ISSUE TITLE
ncpa-2.1.3.exe download is being identified by Symantec Endpoint Protection as a Security risk "WS.Reputation.1"

### ISSUE THREAD

**Issue by sampath4970** [NagiosEnterprises/ncpa#442]
I downloaded ncpa-2.1.3.exe from https://www.nagios.org/ncpa/#downloads.

But the exe is being detected by SEP as Security Risk "WS.Reputation.1" and is being blocked.

Is there  an alternate location I can download it from?

Thank You

**Comment by jomann09** [comment]
There isn't any other download. The `WS.Reputation.1` security risk error is interesting. I am not sure how Symmantic is getting that data for NCPA (https://www.symantec.com/security_response/writeup.jsp?docid=2010-051308-1854-99) what I am guessing is that it is looking inside the archive to see what sorts of files it has and for whatever reason it thinks that it could be potentially bad. However, that is the proper link and the official version.

**Comment by jomann09** [comment]
We are submitting a request for whitelist as a false positive, we may not get an update right away but as I said above the the download is the proper one.

**Comment by jomann09** [comment]
I'm going to close this since it looks like we recieved a response from Symantec that it will be removed. Please let us know if it fails again after update.
