### ISSUE TITLE
How can I disable the RSA algorithm and enable a more secure one?

### ISSUE THREAD

**Issue by pilot513** [NagiosEnterprises/ncpa#443]
Disable RSA encryption

ROBOT only affects TLS cipher modes that use RSA encryption. Most modern TLS connections use an Elliptic Curve Diffie Hellman key exchange and need RSA only for signatures. We believe RSA encryption modes are so risky that the only safe course of action is to disable them. Apart from being risky these modes also lack forward secrecy.

By disabling RSA encryption we mean all ciphers that start with TLS_RSA. It does not include the ciphers that use RSA signatures and include DHE or ECDHE in their name. These ciphers are not affected by our attack.

Based on some preliminary data we also believe the compatibility costs of disabling RSA encryption modes are relatively low. Cloudflare shared with us that around one percent of their connections use the RSA encryption modes. Disabling these modes on the HTTPS server operated by one of the authors caused no notable problems.

**Comment by ericloyd** [comment]
Rather than wait for code to be recompiled, you could _stunnel_ the traffic yourself and encrypt it that way.

**Comment by pilot513** [comment]
I can't usage in my environment "stunnel".
But i want resolve this problem. 
This link describe more: https://www.trustzone.com/robot-attack-rsa-encryption-vulnerable-choose-ecc-tlsssl-certificates-ensure-security

**Comment by ericloyd** [comment]
I understand the problem.  I was offering a potential solution.  I am sorry it won't work for you.

**Comment by pilot513** [comment]
Also, for same http-servers you can check (& generate) config:
https://mozilla.github.io/server-side-tls/ssl-config-generator/

**Comment by pilot513** [comment]
Ericloyd, thank you for you solution, but this indeed don't right for me.
I very ask the developer to respond, and help find a solution in this situation

**Comment by pilot513** [comment]
For check sslscan result look: sslscan hostname:5693 | grep RSA
I want to disable:
    Accepted  TLS12  256 bits  ECDHE-RSA-AES256-GCM-SHA384
    Accepted  TLS12  256 bits  ECDHE-RSA-AES256-SHA384
    Accepted  TLS12  256 bits  ECDHE-RSA-AES256-SHA
    Accepted  TLS12  128 bits  ECDHE-RSA-AES128-GCM-SHA256
    Accepted  TLS12  128 bits  ECDHE-RSA-AES128-SHA256
    Accepted  TLS12  128 bits  ECDHE-RSA-AES128-SHA
I want to leave only:
    Accepted  TLS12  256 bits  AES256-GCM-SHA384
    Accepted  TLS12  256 bits  AES256-SHA256
    Accepted  TLS12  256 bits  AES256-SHA
    Accepted  TLS12  256 bits  CAMELLIA256-SHA

**Comment by jomann09** [comment]
Currently we do not open the SSL ciphers up to changing in the config. I can probably add this fairly easy for version 2.1.4 but I will need to do a little bit of testing.

**Comment by pilot513** [comment]
It's will be very good

**Comment by jomann09** [comment]
Added this into the next release which should be out this week at some point.
