### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe9 in position 7369: ordinal not in range(128)

### ISSUE THREAD

**Issue by tbrewski** [NagiosEnterprises/ncpa#446]
Hello,

Nagios Core 4.3.4 running on the latest Debian Stretch monitoring ~100 Windows servers (all running NCPA 2.1.3).

We started observing 'UNKNOWN: Error occurred while running the plugin. Use the verbose flag for more details.' errors for the Process Count check for some servers. No other checks or servers are affected.

Those affected are all Windows 2012 R2 x64 servers with a high number of processes (above 500) since they are used as RDP hosts.

Here is the output of running the check from the server:

% python check_ncpa.py -H srv-rds02.local.net -t 'pass' -P 5693 -M processes -w 500 -c 700 -d -v

Connecting to: https://srv-rds02.local.net:5693/api/processes/?token=pass&warning=500&critical=700&delta=True&check=1
An error occurred:HTTP Error 500: INTERNAL SERVER ERROR

The following error is observed on the client (ncpa_listener.log):

2018-04-03 10:14:22,538:ERROR:app:Exception on /api/processes/ [GET]
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\flask\app.py", line 1817, in wsgi_app
  File "C:\Python27\lib\site-packages\flask\app.py", line 1477, in full_dispatch_request
  File "C:\Python27\lib\site-packages\flask\app.py", line 1381, in handle_user_exception
  File "C:\Python27\lib\site-packages\flask\app.py", line 1475, in full_dispatch_request
  File "C:\Python27\lib\site-packages\flask\app.py", line 1461, in dispatch_request
  File "C:\ncpa\agent\listener\server.py", line 168, in token_auth_decoration
  File "C:\ncpa\agent\listener\server.py", line 926, in api
  File "C:\ncpa\agent\listener\processes.py", line 422, in run_check
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe9 in position 6970: ordinal not in range(128)

I have a feeling it has something to do with a higher number returned.

Thank you.

**Comment by jomann09** [comment]
This is actually because the process probably had a character that NCPA couldn't read, this has been a problem sometimes for a while now. We are currently testing Python 3 which should handle this much better.

**Comment by tbrewski** [comment]
Thank you. That was it, although in my case it doesn't seem to be the process name but rather the username.

I can access API GUI without issues and while searching the process list I think I found the one causing troubles:

`{
            "username": "LOCAL\\M�lanieG",
            "mem_percent": [
                0.05,
                "%"
            ],
            "exe": "C:\\Program Files\\VMware\\VMware View\\Agent\\bin\\vmware-view-unity-shell.exe",
            "name": "vmware-view-unity-shell.exe",
            "cpu_percent": [
                0,
                "%"
            ],
            "mem_vms": [
                0,
                "GB"
            ],
            "cmd": "C:\\Program Files\\VMware\\VMware View\\Agent\\bin\\vmware-view-unity-shell.exe",
            "pid": 8116,
            "mem_rss": [
                0.02,
                "GB"
            ]
        }`

**Comment by jomann09** [comment]
That makes sense, there are a issues with Python 2.7 and the conversion of things to and from utf-8 etc that seem to be causing a lot of trouble, I've worked on some fixes in the past but they don't always work on all systems. I am going to close this since it's already an issue here on github. #439
