### ISSUE TITLE
Loose performance graph after upgrading to 2.1.3

### ISSUE THREAD

**Issue by metabsd** [NagiosEnterprises/ncpa#449]
Hi,
```
./check_ncpa.py -H slpcfg0269.saq.qc.ca -t '<your token>' -M 'disk/logical/|var' -w 90 -c 95 -u M
```
Would result in the following output:
```
OK: Used disk space was 47.10 % (Used: 3531.63 MB, Free: 3974.07 MB, Total: 7505.71 MB) | 'used'=3531.63MB;6755;7130; 'free'=3974.07MB;6755;7130; 'total'=7505.71MB;6755;7130;
```

Before upgrading I have that graph:

![image](https://user-images.githubusercontent.com/7953470/38561624-7d2dcb6c-3ca6-11e8-86c8-07980a034849.png)

I think it's about the number of performance stat I receive now. 
Before I receive only 1 and now I receive 3 stats. How I fix that ? I loose all my stats ?

**Comment by box293** [comment]
Can you have a look at this issue and let us know if it is related to the problem you are having?

https://github.com/NagiosEnterprises/ncpa/issues/418

**Comment by metabsd** [comment]
I use that https://support.nagios.com/kb/article/nagios-xi-icmp-and-ping-checks-stopped-graphing-149.html and it's working now. My brain hurting :) Thank you!!!
