### ISSUE TITLE
Processes command returns nagios incompatible results

### ISSUE THREAD

**Issue by HackerJL** [NagiosEnterprises/ncpa#450]
Diving into the NCPA system and hitting a road block.

I have a need or two to monitor to make sure existing processes are running.  Example: explorer.exe (if its logged in) or in my example cases blueiris.exe (camera software).

In moving from NSclient++ to NCPA, im not getting the parsed data from the API.  For example, the command 
`./check_ncpa.py -H localhost -t '<your token>' -M 'processes' -c 0 -q 'name=blueiris.exe'`

gives me the following output:

    CRITICAL: Process count for processes named blueiris.exe was 1 | 'process_count'=1;;0;        'cpu'=30.3%;;; 'memory'=9.4%;;; 'memory_vms'=0.54GB;;; 'memory_rss'=0.4GB;;;
    Processes Matched
    PID: Name: Username: Exe: Memory: CPU
    -----------------------------------
    6480: BlueIris.exe: DESKTOP-3VP3NP1\EWPCam1: 9.4 % (VMS 0.54 GB, RSS 0.40 GB): 30.30 %
    Total Memory: 9.40 % (VMS 0.54 GB, RSS 0.40 GB)
    Total CPU: 30.30 %`

Ive also tried:
`./check_ncpa.py -H localhost -t '<your token>' 'processes' -w 2 -c 0 -q 'exe=blueiris.exe'`
results in
`OK: Process count for exes named blueiris.exe was 0 | 'process_count'=0;2;0;`

The results of this are displayed right in the API when you tell it to generate the check_ncpa.py command too.

**Comment by box293** [comment]
I've got some examples here in this KB article that may help: https://support.nagios.com/kb/article/process-checks-782.html

I'm pretty sure it comes down to the thresholds you are using, I think you might want `-c 1:1`.

**Comment by HackerJL** [comment]
the add-on to the command
`-M 'process/vmtoolsd/count' -c 1:1` 
isnt valid for 2.x.

It complaints:
`The processes () requested does not exist. You may be trying to access the 'processes' node.`

**Comment by box293** [comment]
Good pickup, I'll get that KB article updated.

However I think the `1:1` is what you are after, for example:

```
./check_ncpa.py -H 192.168.55.1 -t Str0ngT0k3n -M 'processes' -c 1:1 -q 'name=blueiris.exe'

CRITICAL: Process count for processes named blueiris.exe was 0 | 'process_count'=0;;1:1;
```

And the exit code:
```
echo $?

2
```

**Comment by HackerJL** [comment]
Command run:
`/usr/local/nagios/libexec/check_ncpa.py -H 192.168.0.6 -t 'TOKEN' -M 'processes' -c 1:1 -q 'name=blueiris.exe''

Result:

    OK: Process count for processes named blueiris.exe was 1 | 'process_count'=1;;1:1; 'cpu'=30.0%;;;  'memory'=9.72%;;; 'memory_vms'=0.54GB;;; 'memory_rss'=0.42GB;;;
    Processes Matched
    PID: Name: Username: Exe: Memory: CPU
    -----------------------------------
    6480: BlueIris.exe: DESKTOP-3VP3NP1\EWPCam1: 9.72 % (VMS 0.54 GB, RSS 0.42 GB): 30.00 %
    Total Memory: 9.72 % (VMS 0.54 GB, RSS 0.42 GB)
    Total CPU: 30.00 %

Afraid, no change - unless im missing something there...

**Comment by box293** [comment]
So I don't think I clearly understand what the problem is.

**Comment by HackerJL** [comment]
I should be getting back one string of code back: example:
`OK: Process count for processes named blueiris.exe was 1` 

without the rest trailing (I believe).  Nagios is unable to parse that as 'ok' due to all the data its receiving (again, I believe).  My nagios check is failing on this one saying its 'critical' even when its not.  All other search strings return limited data, not the entire paragraph.

**Comment by box293** [comment]
OK great, so the last example you provided was:


> Command run:
> /usr/local/nagios/libexec/check_ncpa.py -H 192.168.0.6 -t 'TOKEN' -M 'processes' -c 1:1 -q 'name=blueiris.exe'
> 
> Result:
> 
> OK: Process count for processes named blueiris.exe was 1 | 'process_count'=1;;1:1; 'cpu'=30.0%;;;  'memory'=9.72%;;; 'memory_vms'=0.54GB;;; 'memory_rss'=0.42GB;;;
> Processes Matched
> PID: Name: Username: Exe: Memory: CPU
> -----------------------------------
> 6480: BlueIris.exe: DESKTOP-3VP3NP1\EWPCam1: 9.72 % (VMS 0.54 GB, RSS 0.42 GB): 30.00 %
> Total Memory: 9.72 % (VMS 0.54 GB, RSS 0.42 GB)
> Total CPU: 30.00 %
> 
> Afraid, no change - unless im missing something there...

Anything after the pipe (|) is simply performance data, it has no effect on how Nagios interprets that as OK or CRITICAL (I had a look at the `check_ncpa.py` plugin and it does not have an argument to disable performance data).

It is the exit code returned by `check_ncpa.py` that tells Nagios if it is OK or CRITICAL. Hence immediately after executing your check type `echo $?` and that will return the numeric value of the state Nagios will use.

Are you using another script to run the `check_ncpa.py` plugin? If this is the case then you will need to catch the exit code from the `check_ncpa.py` plugin in this script and return this exit code to Nagios with your script.

**Comment by HackerJL** [comment]
It appears to be working!  Many thanks.  The extra data was troubling and proved not to be an issue.  

Many thanks on the documentation change from 'process' to processes

**Comment by HackerJL** [comment]
Before I depart and close this, I want to know the syntax on say the following situation:

I want to monitor the process, critical if 0, but also greater than 5.  And just for the fun, warning over 3
