### ISSUE TITLE
Process names on OS X

### ISSUE THREAD

**Issue by sh-msh** [NagiosEnterprises/ncpa#454]
ncpa_listener and ncpa_passive do not show up in process list when using the 'ps' command. Tested with NCPA 2.1.4 on OS X 10.13.4.

How to reproduce: Install NCPA as per instructions. Look for process using 'ps'.

> foo:LaunchDaemons root# ps -ef|grep [n]cpa
> foo:LaunchDaemons root#

Processes can be seen using 'top'.

Or like this:

> foo:LaunchDaemons root# ps -ef|grep -- '-[n]'
>   502 50397     1   0 11:46AM ??         0:02.95 -n
>   502 50399     1   0 11:46AM ??         0:00.12 -n

Apparently you have to pass the path of the executable that is specified in the plist under <key>Program</key> as first argument to <key>ProgramArguments</key> (see https://developer.apple.com/legacy/library/documentation/Darwin/Reference/ManPages/man3/execvp.3.html#//apple_ref/doc/man/3/execvp ) - "The first argument, by convention, should point to the file name associated with the file being executed".

Proposed fix:
```
diff --git a/agent/build_resources/ncpa_listener.plist b/agent/build_resources/ncpa_listener.plist
index 86c2244..76aa78a 100644
--- a/agent/build_resources/ncpa_listener.plist
+++ b/agent/build_resources/ncpa_listener.plist
@@ -12,6 +12,7 @@
         <string>/usr/local/ncpa/ncpa_listener</string>
         <key>ProgramArguments</key>
         <array>
+                <string>/usr/local/ncpa/ncpa_listener</string>
                 <string>-n</string>
         </array>
     </dict>
diff --git a/agent/build_resources/ncpa_passive.plist b/agent/build_resources/ncpa_passive.plist
index 50208ec..ec737f8 100644
--- a/agent/build_resources/ncpa_passive.plist
+++ b/agent/build_resources/ncpa_passive.plist
@@ -12,6 +12,7 @@
         <string>/usr/local/ncpa/ncpa_passive</string>
         <key>ProgramArguments</key>
         <array>
+                <string>/usr/local/ncpa/ncpa_passive</string>
                 <string>-n</string>
         </array>
     </dict>
```

Then the processes can be grepped for properly:

> foo:LaunchDaemons root# ps -ef|grep [n]cpa
>   502 50914     1   0  1:50PM ??         0:00.36 /usr/local/ncpa/ncpa_listener -n
>   502 50923     1   0  1:50PM ??         0:00.33 /usr/local/ncpa/ncpa_passive -n
> foo:LaunchDaemons root#

**Comment by jomann09** [comment]
This was removed during a commit and I don't recall why. I'll add it back in. Might have just been overlooked.

**Comment by jomann09** [comment]
I'm actually re-building 2.1.4 on OS X for this fix. Will also be available in the next version.
