### ISSUE TITLE
Apropos ssl_chipers option

### ISSUE THREAD

**Issue by pilot513** [NagiosEnterprises/ncpa#455]
Hello.
In v.2.1.4 present option "ssl_chipers"
When i set it in ncps.cfg core can't parsed line:

ConfigParser.ParsingError: File contains parsing errors: /usr/local/ncpa/etc/ncpa.cfg
        [line 79]: 'ssl_ciphers AES256-GCM-SHA384,AES256-SHA256,AES256-SHA,CAMELLIA256-SHA\n'

Can you help set it ? 
Thanks.

**Comment by jomann09** [comment]
Looks like you're missing the equals in the line, plus it should be:
```
ssl_ciphers = AES256-GCM-SHA384:AES256-SHA256:AES256-SHA:CAMELLIA256-SHA
```
Just like you define it for Apache.

**Comment by pilot513** [comment]
Thanks! 
The documentation should be correlated, because in it set "Comma separated list of ciphers."

**Comment by jomann09** [comment]
Oh yeah, I will change that, thanks for pointing it out!
