### ISSUE TITLE
NCPA memory leak

### ISSUE THREAD

**Issue by ramachandran25** [NagiosEnterprises/ncpa#460]
Hi,

I found that NCPA listener process consumes high memory on few servers compared than other servers. Upon checking the "handles" in the task manager was higher count, due to that it ends up consuming more memory and it caused system hanging at some point. It came to normal when I restart the NCPA Listener service.

**Comment by jomann09** [comment]
Do you have any specific checks that are running on those servers that aren't on the others? Also, are you using any passive checks? I'd be interested in some of the setup you have to see if there is a bug in how it runs checks.

**Comment by ramachandran25** [comment]
Honestly no, It runs the same checks running on other server...

**Comment by ramachandran25** [comment]
I’m running through the check_ncpa.py... I’m just having checks like CPU, Memory, Service, disk usage and windows counters.. overall checks would be around 40 checks per server.

**Comment by jomann09** [comment]
One last question and I can see if I can't get it to use a bunch of memory. How long were they running, an estimate is fine, days, weeks, month+?

**Comment by ramachandran25** [comment]
They were running for 2 weeks.

**Comment by ramachandran25** [comment]
We had the same issue for 4 servers in the past 2 days. @jomann09

**Comment by jomann09** [comment]
My test ones are still running without any change, what does the system monitor look like when it's running? Can you screenshot or show how much memory/cpu is being used? Is there any errors in the `ncpa_listener.log` file in `C:\Program Files (x86)\Nagios\NCPA\var\log` ?

**Comment by ramachandran25** [comment]
How can I attach the screenshot here? The NCPA listener process memory was consuming around 2K.

This is what nagiosXI returns the output when the ncpa listener service hangs, however, the service is still running.

UNKNOWN: Error occurred while running the plugin. Use the verbose flag for more details

When I use the verbose mode it returns the connection refused as below.
An error occurred:<urlopen error [Errno 111] Connection refused>

This is what i can see in the logfile during the issue.
2018-05-21 14:27:40,029:ERROR:windowscounters:(-2147481643, 'CollectQueryData', 'No data to return.')
Traceback (most recent call last):
  File "C:\ncpa\agent\listener\windowscounters.py", line 43, in counter_method
  File "C:\ncpa\agent\listener\windowscounters.py", line 60, in get_counter_val
error: (-2147481643, 'CollectQueryData', 'No data to return.')
2018-05-21 14:28:10,746:ERROR:windowscounters:(-2147481643, 'CollectQueryData', 'No data to return.')
Traceback (most recent call last):
  File "C:\ncpa\agent\listener\windowscounters.py", line 43, in counter_method
  File "C:\ncpa\agent\listener\windowscounters.py", line 60, in get_counter_val
error: (-2147481643, 'CollectQueryData', 'No data to return.')
2018-05-21 14:37:00,772:ERROR:windowscounters:(-2147481643, 'CollectQueryData', 'No data to return.')
Traceback (most recent call last):
  File "C:\ncpa\agent\listener\windowscounters.py", line 43, in counter_method
  File "C:\ncpa\agent\listener\windowscounters.py", line 60, in get_counter_val
error: (-2147481643, 'CollectQueryData', 'No data to return.')
2018-05-21 14:37:05,825:ERROR:windowscounters:(-2147481643, 'CollectQueryData', 'No data to return.')
Traceback (most recent call last):
  File "C:\ncpa\agent\listener\windowscounters.py", line 43, in counter_method
  File "C:\ncpa\agent\listener\windowscounters.py", line 60, in get_counter_val
error: (-2147481643, 'CollectQueryData', 'No data to return.')
2018-05-21 14:38:00,223:ERROR:windowscounters:(-2147481643, 'CollectQueryData', 'No data to return.')
Traceback (most recent call last):
  File "C:\ncpa\agent\listener\windowscounters.py", line 43, in counter_method
  File "C:\ncpa\agent\listener\windowscounters.py", line 60, in get_counter_val
error: (-2147481643, 'CollectQueryData', 'No data to return.')
2018-05-21 14:38:11,549:ERROR:windowscounters:(-2147481643, 'CollectQueryData', 'No data to return.')
Traceback (most recent call last):
  File "C:\ncpa\agent\listener\windowscounters.py", line 43, in counter_method
  File "C:\ncpa\agent\listener\windowscounters.py", line 60, in get_counter_val
error: (-2147481643, 'CollectQueryData', 'No data to return.')
2018-05-21 14:39:00,329:ERROR:windowscounters:(-2147481643, 'CollectQueryData', 'No data to return.')
Traceback (most recent call last):
  File "C:\ncpa\agent\listener\windowscounters.py", line 43, in counter_method
  File "C:\ncpa\agent\listener\windowscounters.py", line 60, in get_counter_val
error: (-2147481643, 'CollectQueryData', 'No data to return.')

**Comment by ramachandran25** [comment]
I would like to give an update on this, We have disabled all service checks from NagiosXI and ran the CPU and Perfmon checks in through the command line. We found that CPU checks don't impact the memory and handles but when we ran the perfmon counter checks the memory and handles was keep on increasing and never came down. I did an average math here, per perfmon check it consumes around 20kb to 30kb so 3minute is per check interval for 32 perfmon checks for a day is 300MB aprx.

**Comment by jomann09** [comment]
That actually may be a bug, I will look into it and hopefully find the issue. I believe the way the windows counters are working that this would make sense.

**Comment by jomann09** [comment]
Can you give me an example of the checks that were causing this issue too?

**Comment by ramachandran25** [comment]
We are running the custom application perfmon counters... for the security contrain we couldn’t give you the checks though I can give you how it was running...

**Comment by jomann09** [comment]
Sure, how it is running is fine. I just need an example to try myself, because I can't get it to hold the memory usage. 

Are you running them as a plugin or using the `windowscounters` section?

**Comment by ramachandran25** [comment]
This is my check, for security contrain I changed servername as local host and queue name as custom_queue... -M 'windowscounters/MSMQ Queue(localhost/private$$/custom_queue)/Bytes in Queue'

**Comment by jomann09** [comment]
I believe there is an issue with how the counters and queries are handled in the actual `windowscounters` node. I can build you a test version of 2.1.5 if you'd like to see if it solves the issue for you.

**Comment by jomann09** [comment]
Here is a beta version of 2.1.5 if you'd like to try to see if it resolves the issue. https://assets.nagios.com/downloads/ncpa/dev/

**Comment by box293** [comment]
> How can I attach the screenshot here?

You can just drag it into this "Write" window and it'll upload it.

**Comment by ramachandran25** [comment]
@jomann09 I'm glad that you fixed my problem. It seems better than before, however, I will leave it run for 1 day and give you an update on this.

Thanks a lot for all your instant support :+1:  Your support is highly appreciated.
![handles](https://user-images.githubusercontent.com/29451971/40401941-b43d628e-5e66-11e8-8933-762c6fc57cab.JPG)

@box293 Thank you man, it works.

**Comment by jomann09** [comment]
Awesome glad to hear the problem is fixed. Let me know how it goes.

**Comment by ramachandran25** [comment]
I left it run for 2 days, it seems stable now. Thank you for your great support man :+1:

**Comment by jomann09** [comment]
Great! We will release 2.1.5 next week some time.

**Comment by ramachandran25** [comment]
@jomann09 Are you planning to release the ncpa 2.1.5 this week? We are gonna start installing on customer production servers next week. It would be great if you release over the weekend.

Thank you :)

**Comment by jomann09** [comment]
I am going to try to release it today if possible. I have some issues with SLES/SuSE installs that I want to be fixed before I build 2.1.5

**Comment by ramachandran25** [comment]
Sorry to bother you. It would be great if you release as soon as possible as we are going live Today. @jomann09

**Comment by jomann09** [comment]
I'm working on it today, unfortunately there has been issues with some packages on suse so I have been trying to solve that. Will try to get this done in the next few hours.

**Comment by ramachandran25** [comment]
That's sweet... thanks for your update.
