### ISSUE TITLE
Not pulling some Windows counters

### ISSUE THREAD

**Issue by cdienger** [NagiosEnterprises/ncpa#461]
2.1.4

Returning zero which differs with what Windows is reporting in perfmon:

windowscounters/LogicalDisk(_Total)/% Disk Time
windowscounters/LogicalDisk(_Total)/Avg. Disk Read Queue Length (while running when running find /c/ -name '*.txt' -exec cat {} \;)
windowscounters/LogicalDisk(_Total)/% Idle Time
windowscounters/PhysicaDisk(_Total)/% Disk Time
windowscounters/Processor(_Total)/% Idle Time 

Testing with:

./check_ncpa.py -v '-H' '<hostname>' '-M' '<perf_counter>' '-P' '5693' '-t' '<a_secret_token>'

**Comment by jomann09** [comment]
I'm not sure what the sleep/wait time is when you are running them with perfmon, but if you set a sleep time the % ones will work. I am not sure about the Avg. Disk Read Queue Length, but may not have had any in thee when I was running it.

**Comment by jomann09** [comment]
```
https://localhost:5693/api/windowscounters/Processor(_Total)/% Idle Time?sleep=5
```

**Comment by jomann09** [comment]
Closing this because I tested them all and got output with sleep!
