### ISSUE TITLE
NCPA 2.1.4 looking for NFS Mount Point?

### ISSUE THREAD

**Issue by sampath4970** [NagiosEnterprises/ncpa#462]
There was an issue with 2.0x versions where NCPA was looking for CIFS & NFS Mounts which was causing NCPA to hang when a NFS Mount Point is not accessible.

If I remember correctly, the v2.1.x started excluding CIFS & NFS Mounts in Linux VMs. But looks like that issue still exists on v2.1.4. Today we started noticing NCPA hung issue on about 250 VMs and we were neither able to check status nor restart the Agent. This was fixed by recycling NFS Services on our NFS Server. 

Please suggest.

**Comment by jomann09** [comment]
NCPA's config (ncpa.cfg) now can use `exclude_fs_types` and by default has a whole list of file types to exclude. Are your mount points that are causing problems showing up when you go to the disk section in NCPA?

**Comment by sampath4970** [comment]
Yes, I can see couple of NFS Mount Points in "Disks" section which appears to be the ones that are causing the problem.

NCPA was upgraded to v2.1.4 recently on these servers.

**Comment by jvandermeulen** [comment]
@sampath4970 when you upgrade NCPA your config (ncpa.cfg) will remain, it won't be affected by the upgrade to a newer package. New options and defaults (at least for RPM packages) will be written as _ncpa.cfg.rpmnew_. What I normally do is copy _ncpa.cfg.rpmnew_ to _ncpa.cfg_, then make corrections for the token (community_string) and other options we changed and then restart ncpa_listener

**Comment by sampath4970** [comment]
@jomann09 Here is the fstype from Disk API Endpoint for the Mount Points I was referring to.

 "fstype": "nfs4"

  "device_name": [
            "nfs.ux.local:/apps/jenkins"
        ],

**Comment by jomann09** [comment]
You'll definitely have to add `nfs4` to the list of excludes in the `ncpa.cfg` in order for it not to show up. It is not on the default list. Your config probably doesn't have an excludes line so it is using the defaults. You should be able to find the excludes line in the new one that is pointed out above.

**Comment by jomann09** [comment]
Going to close this as resolved. If you have any other issues with this don't hesitate to respond.
