### ISSUE TITLE
Issue with restarting the ncpa_listener on SLES and OpenSUSE 11.4 64-bit

### ISSUE THREAD

**Issue by ludmilmm** [NagiosEnterprises/ncpa#464]
There is an issue with restarting the ncpa_listener on SLES and OpenSUSE 11.4 64-bit. The problem (in SLES 11.4 64-bit) was reported initially on the Nagios support forum here:

[https://support.nagios.com/forum/viewtopic.php?t=48773#252584](https://support.nagios.com/forum/viewtopic.php?t=48773#252584)

`$ /etc/init.d/ncpa_listener restart`
`Stopped NCPA Listener`
`zipimport.ZipImportError: can't decompress data; zlib not available`
`Fatal Python error: unable to locate initialization module`
`/etc/init.d/ncpa_listener: line 37: 5835 Aborted $BASEDIR/ncpa_listener --stop`
`Started NCPA Listener`
`another instance seems to be running (pid 5761), exiting`

I see a similar error in OpenSUSE 11.4 64-bit:

`linux-aa2t:/tmp # /etc/init.d/ncpa_listener restart`
`Stopped NCPA Listener`
`Traceback (most recent call last):`
 ` File "/usr/local/lib/python2.7/site-packages/cx_Freeze-4.3.4-py2.7-linux-x86_64.egg/cx_Freeze/initscripts/Console.py", line 27, in <module>`
  `File "ncpa_listener.py", line 8, in <module>`
  `File "/root/ncpa/agent/listener/certificate.py", line 2, in <module>`
  `File "/usr/local/lib/python2.7/site-packages/OpenSSL/__init__.py", line 8, in <module>`
  `File "/usr/local/lib/python2.7/site-packages/OpenSSL/crypto.py", line 12, in <module>`
  `File "/usr/local/lib/python2.7/site-packages/cryptography/x509/__init__.py", line 7, in <module>`
`ImportError: cannot import name certificate_transparency`
`Started NCPA Listener`
`another instance seems to be running (pid 4524), exiting`

**Comment by jomann09** [comment]
This has been fixed in 2.1.5 - there will actually be new (different) builds for SUSE now. We will be supporting:

SLE 11 32 / SLE 11 64 / SLE 12 64
OpenSUSE Leap 15 / OpenSUSE Tumbleweed
