### ISSUE TITLE
Please add sleep parameter to check_ncpa.py

### ISSUE THREAD

**Issue by KonstantinShvaykovskiy** [NagiosEnterprises/ncpa#465]
Hi, this is a follow-up for issue #461 . It looks like if we apply sleep then the problem is resolved.

Could we please release a version of check_ncpa.py that would be able to accept the sleep parameter? 

@jomann09  worked on this and has more details.

Thank you!

**Comment by jomann09** [comment]
Just for reference you can do `-q 'sleep=5'` to have it sleep for 5 seconds, anything passed in the query arguments will be passed. This could be done as a separate option though, so we can throw this in.

**Comment by KonstantinShvaykovskiy** [comment]
Thank you @jomann09! Since sleep needs to be constantly applied for performance counters it feels that there would be a value in having it a separate parameter. That way we could create a command that incorporates sleep instead of placing sleep of every single individual monitor that we will write.

**Comment by jomann09** [comment]
Added for check_ncpa.py version 2.0

**Comment by yderi** [comment]
Faced the same problem, almost refuse to use NCPA plugin, but at the last moment came across this post. Thanks a lot
