### ISSUE TITLE
license appears to not allow third-party plugins

### ISSUE THREAD

**Issue by douglasawh** [NagiosEnterprises/ncpa#467]
The NCPA license appears to not allow for third-party plugins, which I do not believe is the intent. The section of the NCPA license below also doesn't make it clear whether things from the Exchange are "distributed by the Company". It's probably worth at least having an exception for things on the Exchange.

"The Software may only be used in conjunction with products, projects, and other software distributed by the Company. Any standalone use of the Software, or use of the Software in conjunction with products, projects, or other software not authored or distributed by the Company - including third-party software that competes with the offerings of Company - is strictly prohibited and is a direct violation of the terms of the license."

**Comment by jomann09** [comment]
The license does allow for 3rd party plugins. The license is restricting the actual application from being used or distributed by competing products that it would be deployed/used with. There have been internal discussions about this and the license may end up changing but for now this is what it is.
