### ISSUE TITLE
check_ncpa from command line

### ISSUE THREAD

**Issue by mannyci** [NagiosEnterprises/ncpa#470]
Hi,

I am seem to be unable to figure out to run a ncpa processes check from CLI. I am sure I am missing something obvious. 

I want to filter process consuming more than a mem_percentage.

`#check_ncpa.py -t 'token' -P 5000 -M 'processes' -q 'mem_percentage>=10' -H testmachine -w 0 -c 1`

This returns all the process, don't filter them.

Any idea how can I achieve this?
Thanks

**Comment by jomann09** [comment]
We don't actually look for the > symbol. You just put the percentage you'd like it to check for >= to. So you can just put in `-q 'mem_percent=10'` which should get you the data you'd want.
