### ISSUE TITLE
Linux packages: do not install to /usr/local

### ISSUE THREAD

**Issue by kenyon** [NagiosEnterprises/ncpa#472]
Linux packages are not supposed to install anything under /usr/local.

https://fedoraproject.org/wiki/Packaging:Guidelines#Filesystem_Layout

https://www.debian.org/doc/debian-policy/#the-operating-system

**Comment by jvandermeulen** [comment]
Although you have a point in questioning the default install path it is still possible to relocate the RPM package (as it's relocatable).

> [root@el7]# rpm -Uvh --prefix=/opt https://assets.nagios.com/downloads/ncpa/ncpa-latest.el7.x86_64.rpm
Retrieving https://assets.nagios.com/downloads/ncpa/ncpa-latest.el7.x86_64.rpm
Preparing...                          ################################# [100%]
Updating / installing...
   1:ncpa-2.1.5-1.el7.centos          ################################# [100%]

Verify it's installed underneath /opt (obeying `--prefix=/opt`) looking at configfiles (all other files are also underneath /opt/ncpa install tree)
>   [root@el7]# rpm -ql ncpa --configfiles
/opt/ncpa/etc/ncpa.cfg
/opt/ncpa/etc/ncpa.cfg.d/example.cfg
>

Unfortunately you can't use yum to relocate, so I won't recommend installing it like this. But if someone in our organization insists in putting it underneath /opt... here you go.

**Comment by hedenface** [comment]
Across the entire Nagios suite of software, we use `/usr/local/` as our default installation locations. There is no intention of changing that default at this time. That said, we would accept any reasonable contributions for separate package files containing alternative locations.

**Comment by kenyon** [comment]
Yes, from reading Nagios documentation I understand that you are doing it wrong across the entire Nagios suite of software. Fortunately, the nagios packages in EPEL are packaged properly.

**Comment by ericloyd** [comment]
This is tedious. RHEL 7 docs (https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/storage_administration_guide/ch-filesystem#s1-filesystem-fhs) state that:

> The /usr/ directory should also contain a /local/ subdirectory. As per the FHS, this subdirectory is used by the system administrator when installing software locally, and should be safe from being overwritten during system updates. 

If you want to delve deeper, FHS 2.3 standard (http://www.pathname.com/fhs/pub/fhs-2.3.html#USRLOCALLOCALHIERARCHY) is where that information comes from and makes it clear that /usr/local is an appropriate place to install software.

**Comment by kenyon** [comment]
@ericloyd /usr/local is not an appropriate place for packaged software to install files. On a RHEL system, try `repoquery --list '*' | grep -E '^/usr/local/'`. You'll  find that the only package which installs anything to /usr/local is the `filesystem` package which creates the basic directory layout.

Why so much resistance to crafting quality software?

**Comment by ericloyd** [comment]
> Why so much resistance to crafting quality software?

> Probably because RHEL is neither the only game in town nor an authority.

^----this

**Comment by kenyon** [comment]
On 2018-06-27T15:25:49-0700, Omnitec Corporation <notifications@github.com> wrote:
> On Wed, 27 Jun 2018, Kenyon Ralph wrote:
> 
> > Why so much resistance to crafting quality software?
> >
> Probably because RHEL is neither the only game in town nor an authority.

Perhaps you missed the link to Debian's policy.

Please enlighten me on Linux distributions which install packages to
/usr/local.

-- 
Kenyon Ralph

**Comment by ericloyd** [comment]
@kenyon I agree with your right to champion this cause, but I think there are better causes to champion.  Look at /usr/local on any modern Linux system and you'll see lots of software placed there by systems administrators.  Maybe you should pull it and change all the code to reference the locations that you think they should be.  That would be much more useful than this squabbling that has started.

I'm done.

**Comment by kenyon** [comment]
On 2018-06-27T15:34:46-0700, Eric Loyd <notifications@github.com> wrote:
> @kenyon I agree with your right to champion this cause, but I think there are better causes to champion.  Look at /usr/local on any modern Linux system and you'll see lots of software placed there by systems administrators.  Maybe you should pull it and change all the code to reference the locations that you think they should be.  That would be much more useful than this squabbling that has started.
> 
> I'm done.

Yes, you are exactly right, software should be placed in /usr/local by
systems administrators. Not by packages.

Maybe someone should fix this and some other basic problems so that
the packages would be fit for acceptance into official repositories.
That would be useful.

**Comment by ericloyd** [comment]
It's turtles all the way down.  Who types the "yum" command?  On our boxes, it's a systems administrator.  You're being pedantic and I would rather Nagios NEVER be accepted into repos.  I want to install it and compile it from source if I can.

**Comment by hedenface** [comment]
I actually like the idea of people being able to install it via repos - although that isn't ***my*** particular cup of tea. However, this takes real work which takes real time. Again, we're willing to accept reasonable pull requests.

**Comment by jomann09** [comment]
I'm a bit opposite in the sense that I don't think it's necessary for this particular package to be in the default repos - though it would definitely make it easier for people.

That aside though, as @hedenface and @ericloyd pointed out our other projects also use /usr/local and you can always build your own RPM based on our spec file (it is open source) so I don't see a reason to change this.

**Comment by kenyon** [comment]
Well, I can see why Icinga happened.

**Comment by ericloyd** [comment]
I love how you have to have the last word. You remind me of Andrew Tanenbaum. At any rate, being snide will not help your cause.

**Comment by Matty-uk** [comment]
I was about to raised this exact issue, having been fighting with alien due to building from source failing to create the .deb file for armhf as it's against the Debian policy.

I've subsequently learned how to override the policy to enable the .deb file conversion.  Documentation covering source installs could do with updating to include it.  However, that does not resolve the issue mentioned here, which is the reason why a override needs to be added.
