### ISSUE TITLE
Linux packages: files and directories should be owned by root, not nagios

### ISSUE THREAD

**Issue by kenyon** [NagiosEnterprises/ncpa#473]
On Linux, the files and directories installed by the package should not be owned by nagios, they should be owned by root. If there is a bug in ncpa, which runs as user nagios, then the process could write to any of those files, for example, overwriting ncpa.cfg. I can imagine an attacker replacing some ncpa binaries with their own malicious program.

**Comment by box293** [comment]
Thanks for brining this to our attention.

**Comment by jomann09** [comment]
I will look into the permissions for the next version. I think that they could definitely be more restrictive.

**Comment by jomann09** [comment]
I am re-working the RPM spec file along with permission changes to files/directories so that it works better with specialized system setups and whatnot.
