### ISSUE TITLE
Linux packages: do not bundle copies of other packages

### ISSUE THREAD

**Issue by kenyon** [NagiosEnterprises/ncpa#474]
The Linux packages should not be bundling other packages for convenience. The packages should declare their dependencies and let the package management system install them.

https://fedoraproject.org/wiki/Packaging:Guidelines#Bundling_and_Duplication_of_system_libraries

https://www.debian.org/doc/debian-policy/#convenience-copies-of-code

https://fedoraproject.org/wiki/Bundled_Libraries
https://wiki.debian.org/EmbeddedCodeCopies
https://wiki.gentoo.org/wiki/Why_not_bundle_dependencies

**Comment by jomann09** [comment]
This is something we have debated in the past. As of right now we are not looking to be included in any repositories other than our own and which I do agree that bundling dependencies in most situations is bad, it's also one of the reasons it works well for certain people. In general this won't change although in NCPA 3 we may be able to bundle only the python libraries that are necessary and require the other libraries using the RPM.
