### ISSUE TITLE
NCPA Port exhaustion issue

### ISSUE THREAD

**Issue by ramachandran25** [NagiosEnterprises/ncpa#479]
Hi,

I'm running into the issue for the two of the prod servers like the following error. I tried to check whether 5693 port is open but the connection does not seem to be opened. I changed the port number(5694) in the ncpa.cfg file and it's working fine.

error: [Errno 10048] Only one usage of each socket address (protocol/network address/port) is normally permitted: ('0.0.0.0', 5693)
2018-07-30 12:34:42,592:ERROR:ncpa_windows:[Errno 10048] Only one usage of each socket address (protocol/network address/port) is normally permitted: ('0.0.0.0', 5693)
Traceback (most recent call last):

Thanks
Ram

**Comment by jomann09** [comment]
This error almost always means that a version of NCPA is already running. If you look at the process manager does it show multiple versions of ncpa_listener.exe ? Although it is possible you may have some other software configured to run on port 5693 which would also cause this error. Only one thing can be bound to a port at any time.

**Comment by ramachandran25** [comment]
Hi, 

We got the same error again but this time on multiple servers, I see the dead ncpa_listener.exe process is running... I’m trying to kill it by force but no luck... server restart is the only solution currently but that is not a solution for production servers.... need your advice on this please
