### ISSUE TITLE
 NCPA fails if there are spaces in argument -a -q

### ISSUE THREAD

**Issue by jardysx** [NagiosEnterprises/ncpa#481]
I tried running a script with ncpa.
NCPA agent version 2.1.5
check_ncpa.py version 1.1.3

Working:
/check_ncpa.py -t 'mytoken' -H X.X.X.X -P 5693 -M 'plugins/check_winfile.exe' -q 'args=--target C:\Test\,args=--compare eq,args=--critical 2'
/check_ncpa.py -t 'mytoken' -H X.X.X.X -P 5693 -M 'plugins/check_winfile.exe' -a '--target C:\Test\ --compare eq --critical 2'

Doesn't working:
/check_ncpa.py -t 'mytoken' -H X.X.X.X -P 5693 -M 'plugins/check_winfile.exe' -q 'args=--target C:\Program Files (x86)\Nagios\test.txt,args=--filter age lt -8 hours,args=--critical 0'
/check_ncpa.py -t 'mytoken' -H X.X.X.X -P 5693 -M 'plugins/check_winfile.exe' -a "--target 'C:\Program Files (x86)\Nagios\test.txt' --filter 'age lt -8 hours' --critical '0'"

I think the problem is with arguments -a and -q when there is a space. "Program Files (x86)" "age lt -8 hours".

I read in discussions about a similar problem with the -m argument. https://github.com/NagiosEnterprises/ncpa/issues/14

**Comment by jomann09** [comment]
After some internal testing we found out that the plugin itself needs to use double \ so you'd need to do something like:
```
args=--target C:\\Program Files (x86)\\Nagios\\test.txt
```
But we also haven't been able to get it to properly run the command, it shows up fine in the log and it is running the proper command (if you turn on the debug log in ncpa.cfg and then watch the ncpa_listener.log file) you can copy the command it makes and run it via the cmdline and it will work properly.

**Comment by jardysx** [comment]
Thanks for the reply. I tried it, but it's same.
 
-q 'args=--target C:\File\' -v
args=--target+C%3A%5CFile%5C
{
    "returncode": 0,
    "stdout": "FILE OK - 2 files to consider |'selected files'=2;;; 'all files'=2 'deleted files'=0"
}

uginnodes:Running process with command line: `C:\Program Files (x86)\Nagios\NCPA\plugins\check_winfile.exe --target C:\File\`
2018-08-02 09:26:16,085:INFO:handler:X.X.X.X - - [2018-08-02 09:26:16] "GET /api/plugins/check_winfile.exe/?token=mytoken&check=1&args=--target+C%3A%5CFile%5C HTTP/1.1" 200 267 0.265000


-q 'args=--target C:\Program File\' -v 
args=--target+C%3A%5CProgram+File%5C
{
    "returncode": 3,
    "stdout": "FILE UNKNOWN - Target does not exist"
}

uginnodes:Running process with command line: `C:\Program Files (x86)\Nagios\NCPA\plugins\check_winfile.exe --target C:\Program File\`
2018-08-02 09:26:45,486:INFO:handler:X.X.X.X - - [2018-08-02 09:26:45] "GET /api/plugins/check_winfile.exe/?token=mytoken&check=1&args=--target+C%3A%5CProgram+File%5C HTTP/1.1" 200 218 0.281000


 -q 'args=--target C:\\Program File\\' -v
args=--target+C%3A%5C%5CProgram+File%5C%5C
{
    "returncode": 3,
    "stdout": "FILE UNKNOWN - Target does not exist"
}

uginnodes:Running process with command line: `C:\Program Files (x86)\Nagios\NCPA\plugins\check_winfile.exe --target C:\\Program File\\`
2018-08-02 09:27:04,565:INFO:handler:X.X.X.X - - [2018-08-02 09:27:04] "GET /api/plugins/check_winfile.exe/?token=mytoken&check=1&args=--target+C%3A%5C%5CProgram+File%5C%5C HTTP/1.1" 200 218 0.250000


Problem with file names isn't for us so big as a problem with spaces in argument --filter age lt -8 hours. We tried lots of combinations with / \ " '.

**Comment by jomann09** [comment]
Still looking into this, when you add the extra slash it sends the proper command but it doesn't run correctly on Windows. I am assuming it has something to do with how it is ran through NCPA but not sure if it will fix it or not.

**Comment by jomann09** [comment]
Closing this in favor of the linked issue.
