### ISSUE TITLE
Question: passive curl check

### ISSUE THREAD

**Issue by Nexxurs** [NagiosEnterprises/ncpa#485]
I have a local Webserver with an endpoint /version. I want to check if the server is running and send the version as context (if the website isn't available, let's conclude the server is down) 

At the moment I'm using the process endpoint to check if the server is running, but that's not optimal in my case.

I haven't found anything relateable in the documentation. Is there a plugin I can use?

**Comment by jomann09** [comment]
Closing this question, feel free to let us know if you have any other questions or run into issues.
