### ISSUE TITLE
NCPA 2.1.5 fails to start on AIX7.1

### ISSUE THREAD

**Issue by pauldanielbarnes** [NagiosEnterprises/ncpa#486]
After downloading and installing the latest RPM for AIX7.1, I receive the following error starting the ncpa listener service;
```
/root # /usr/local/ncpa/ncpa_listener -n
exec(): 0509-036 Cannot load program /usr/local/ncpa/ncpa_listener because of the following errors:
        0509-150   Dependent module libpython2.7.a(libpython2.7.so) could not be loaded.
        0509-022 Cannot load module libpython2.7.a(libpython2.7.so).
        0509-026 System error: A file or directory in the path name does not exist.
```

**Comment by jomann09** [comment]
Without python on the system (using the linux tools that IBM provides) you have to make sure you set the `LIBPATH` when you are running the service from the command line.

So it would be something like:
```
LIBPATH=/usr/local/ncpa /usr/local/ncpa/ncpa_listener -n
```

**Comment by pauldanielbarnes** [comment]
Same with the libpath
# LIBPATH=/usr/local/ncpa /usr/local/ncpa/ncpa_listener -n
exec(): 0509-036 Cannot load program /usr/local/ncpa/ncpa_listener because of the following errors:
        0509-150   Dependent module libpython2.7.a(libpython2.7.so) could not be loaded.
        0509-022 Cannot load module libpython2.7.a(libpython2.7.so).
        0509-026 System error: A file or directory in the path name does not exist.

**Comment by jomann09** [comment]
Can you show me what an `ls -l` shows in the `/usr/local/ncpa` directory?

**Comment by pauldanielbarnes** [comment]
# ls -l /usr/local/ncpa
total 91328
-rw-r--r--    1 nagios   nagios        11806 Jun 11 22:57 _bisect.so
-rw-r--r--    1 nagios   nagios       273007 Jun 11 22:57 _cffi_backend.so
-rw-r--r--    1 nagios   nagios       139047 Jun 11 22:57 _codecs_cn.so
-rw-r--r--    1 nagios   nagios       151242 Jun 11 22:57 _codecs_hk.so
-rw-r--r--    1 nagios   nagios        34035 Jun 11 22:57 _codecs_iso2022.so
-rw-r--r--    1 nagios   nagios       241140 Jun 11 22:57 _codecs_jp.so
-rw-r--r--    1 nagios   nagios       129687 Jun 11 22:57 _codecs_kr.so
-rw-r--r--    1 nagios   nagios       102009 Jun 11 22:57 _codecs_tw.so
-rw-r--r--    1 nagios   nagios        55999 Jun 11 22:57 _collections.so
-rw-r--r--    1 nagios   nagios       242690 Jun 11 22:57 _ctypes.so
-rw-r--r--    1 nagios   nagios        20375 Jun 11 22:57 _functools.so
-rw-r--r--    1 nagios   nagios        36616 Jun 11 22:57 _hashlib.so
-rw-r--r--    1 nagios   nagios        25164 Jun 11 22:57 _heapq.so
-rw-r--r--    1 nagios   nagios       275079 Jun 11 22:57 _io.so
-rw-r--r--    1 nagios   nagios        65585 Jun 11 22:57 _json.so
-rw-r--r--    1 nagios   nagios        31525 Jun 11 22:57 _locale.so
-rw-r--r--    1 nagios   nagios        55136 Jun 11 22:57 _multibytecodec.so
-rw-r--r--    1 nagios   nagios        51678 Jun 11 22:57 _multiprocessing.so
-rw-r--r--    1 nagios   nagios        22145 Jun 11 22:57 _random.so
-rw-r--r--    1 nagios   nagios       134835 Jun 11 22:57 _socket.so
-rw-r--r--    1 nagios   nagios       157234 Jun 11 22:57 _sqlite3.so
-rw-r--r--    1 nagios   nagios       174367 Jun 11 22:57 _ssl.so
-rw-r--r--    1 nagios   nagios        66546 Jun 11 22:57 _struct.so
-rw-r--r--    1 nagios   nagios        78416 Jun 11 22:57 array.so
-rw-r--r--    1 nagios   nagios        30645 Jun 11 22:57 binascii.so
drwxr-xr-x    2 nagios   nagios         4096 Aug 29 14:26 build_resources
-rw-r--r--    1 nagios   nagios        62187 Jun 11 22:57 bz2.so
-rw-r--r--    1 nagios   nagios       158018 Jun 11 22:57 cPickle.so
-rw-r--r--    1 nagios   nagios        30036 Jun 11 22:57 cStringIO.so
-rw-r--r--    1 nagios   nagios         7801 Jun 11 22:57 cryptography.hazmat.bindings._constant_time.so
-rw-r--r--    1 nagios   nagios      1998987 Jun 11 22:57 cryptography.hazmat.bindings._openssl.so
-rw-r--r--    1 nagios   nagios       155513 Jun 11 22:57 datetime.so
drwxr-xr-x    3 nagios   nagios          256 Aug 29 14:26 etc
-rw-r--r--    1 nagios   nagios        19550 Jun 11 22:57 fcntl.so
-rw-r--r--    1 nagios   nagios       178669 Jun 11 22:57 gevent._semaphore.so
-rw-r--r--    1 nagios   nagios        39892 Jun 11 22:57 gevent._socket3.py
-rw-r--r--    1 nagios   nagios       397734 Jun 11 22:57 gevent.ares.so
-rw-r--r--    1 nagios   nagios       687334 Jun 11 22:57 gevent.libev.corecext.so
-rw-r--r--    1 nagios   nagios        50172 Jun 11 22:57 greenlet.so
-rw-r--r--    1 nagios   nagios        13171 Jun 11 22:57 grp.so
-rw-r--r--    1 nagios   nagios       101707 Jun 11 22:57 itertools.so
-rw-r--r--    1 nagios   nagios         7878 Jun 11 22:57 jinja2.asyncsupport.py
-rw-r--r--    1 nagios   nagios     18942504 Jun 11 22:57 libcrypto.a
-rw-r--r--    1 nagios   nagios      3050171 Jun 11 22:57 libcrypto.so
-rw-r--r--    1 nagios   nagios        60010 Jun 11 22:57 libffi.a
-rw-r--r--    1 nagios   nagios      2278647 Jun 11 22:57 libgcc_s.a
-rw-r--r--    1 nagios   nagios      3316123 Jun 11 22:57 libpython2.7.so
-rw-r--r--    1 nagios   nagios      3672948 Jun 11 22:57 library.zip
-rw-r--r--    1 nagios   nagios      5073815 Jun 11 22:57 libsqlite3.a
-rw-r--r--    1 nagios   nagios       729439 Jun 11 22:57 libssl.so
drwxr-xr-x    4 nagios   nagios          256 Jun 11 22:57 listener
-rw-r--r--    1 nagios   nagios        10243 Jun 11 22:57 markupsafe._speedups.so
-rw-r--r--    1 nagios   nagios       248441 Jun 11 22:57 math.so
-rw-r--r--    1 nagios   nagios        38840 Jun 11 22:57 mmap.so
-rwxr-xr-x    1 nagios   nagios       749780 Jun 11 22:57 ncpa_listener
-rwxr-xr-x    1 nagios   nagios       749780 Jun 11 22:57 ncpa_passive
-rw-r--r--    1 nagios   nagios        71083 Jun 11 22:57 operator.so
drwxr-xr-x    2 nagios   nagios          256 Aug 29 14:26 plugins
-rw-r--r--    1 nagios   nagios        64192 Jun 11 22:57 psutil._psutil_aix.so
-rw-r--r--    1 nagios   nagios        23928 Jun 11 22:57 psutil._psutil_posix.so
-rw-r--r--    1 nagios   nagios        92372 Jun 11 22:57 pyexpat.so
-rw-r--r--    1 nagios   nagios        46917 Jun 11 22:57 readline.so
-rw-r--r--    1 nagios   nagios        30690 Jun 11 22:57 select.so
-rw-r--r--    1 nagios   nagios        42433 Jun 11 22:57 strop.so
-rw-r--r--    1 nagios   nagios        26841 Jun 11 22:57 termios.so
-rw-r--r--    1 nagios   nagios        46734 Jun 11 22:57 time.so
-rw-r--r--    1 nagios   nagios       709061 Jun 11 22:57 unicodedata.so
drwxr-xr-x    4 nagios   nagios          256 Jun 11 22:57 var
-rw-r--r--    1 nagios   nagios        36901 Jun 11 22:57 zlib.so

**Comment by pauldanielbarnes** [comment]
I've now installed the python RPM and have a new failing module for libsqlite;
$> LIBPATH=/usr/local/ncpa /usr/local/ncpa/ncpa_listener -n
exec(): 0509-036 Cannot load program /usr/local/ncpa/ncpa_listener because of the following errors:
        0509-150   Dependent module libsqlite3.so could not be loaded.
        0509-022 Cannot load module libsqlite3.so.
        0509-026 System error: A file or directory in the path name does not exist.

**Comment by pauldanielbarnes** [comment]
So based on this thread,https://support.nagios.com/forum/viewtopic.php?f=6&t=48872 I have rolled back to version 2.1.1 of the AIX NCPA and the service started. So is there an issue with version 2.1.5 for AIX and wat am I missing between 2.1.1 and 2.1.5?

**Comment by jomann09** [comment]
2.1.1 was built on AIX 6.x with 3rd party python and a few other differences. I am looking into getting a new build of 2.1.5 that will fix issues, but it works on some systems but not on others.

**Comment by pauldanielbarnes** [comment]
Thank you for the help

**Comment by jomann09** [comment]
I have updated the build and I believe it includes everything that we need. If you'd like to try it:
https://assets.nagios.com/downloads/ncpa/ncpa-2.1.5.aix7.1.ppc.rpm

**Comment by pauldanielbarnes** [comment]
Same error with the new RPM as with the previous 2.1.5 RPM

root@da1017 /home/brickwoodp # /usr/local/ncpa/ncpa_listener -n
exec(): 0509-036 Cannot load program /usr/local/ncpa/ncpa_listener because of the following errors:
        0509-150   Dependent module libsqlite3.so could not be loaded.
        0509-022 Cannot load module libsqlite3.so.
        0509-026 System error: A file or directory in the path name does not exist.
root@da1017 /home/brickwoodp # rpm -qa | grep ncpa
ncpa-2.1.5-2

Kind regards,

Paul Barnes
Mid-Range Systems Team Lead

**Comment by pauldanielbarnes** [comment]
I removed both versions of the package and reinstalled the newer RPM provided, this gives a new set of errors when specifying the LIBPATH;

 LIBPATH=/usr/local/ncpa ncpa_listener -n
Traceback (most recent call last):
  File "/opt/freeware/lib/python2.7/site-packages/cx_Freeze-4.3.4-py2.7-aix-7.1.egg/cx_Freeze/initscripts/Console.py", line 27, in <module>
  File "ncpa_listener.py", line 8, in <module>
  File "/tmp/test/ncpa/agent/listener/certificate.py", line 2, in <module>
  File "/opt/freeware/lib/python2.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
  File "/opt/freeware/lib/python2.7/site-packages/OpenSSL/rand.py", line 12, in <module>
  File "/opt/freeware/lib/python2.7/site-packages/OpenSSL/_util.py", line 6, in <module>
  File "/opt/freeware/lib/python2.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 12, in <module>
  File "ExtensionLoader_cryptography_hazmat_bindings__openssl.py", line 25, in <module>
  File "ExtensionLoader_cryptography_hazmat_bindings__openssl.py", line 17, in __bootstrap__
ImportError:    0509-022 Cannot load module /usr/local/ncpa/cryptography.hazmat.bindings._openssl.so.
        0509-150   Dependent module /opt/freeware/lib/libssl.a(libssl.so) could not be loaded.
        0509-152   Member libssl.so is not found in archive
        0509-022 Cannot load module /usr/local/ncpa/cryptography.hazmat.bindings._openssl.so.
        0509-150   Dependent module /usr/local/ncpa/cryptography.hazmat.bindings._openssl.so could not be loaded.

**Comment by jomann09** [comment]
Thanks a lot, this helps.

**Comment by jomann09** [comment]
I think I finally got it to have the proper dependencies. Unfortunately the build AIX server I have access to doesn't work well for testing, since it always works with or without them.

**Comment by pauldanielbarnes** [comment]
Hi Jake,

The AIX7.1 NCPA 2.1.5 RPM is still dated 11 June on the https://assets.nagios.com/downloads/ncpa/ repo.

[[   ]][https://assets.nagios.com/downloads/ncpa/][ ]

ncpa-2.1.5.aix7.1.ppc.rpm<https://assets.nagios.com/downloads/ncpa/ncpa-2.1.5.aix7.1.ppc.rpm>

11-Jun-2018 18:02

17M





Is there a newer version you’ve updated somewhere else?

Kind regards,

Paul Barnes
Mid-Range Systems Team Lead

**Comment by jomann09** [comment]
You may need to do a hard refresh of the page, it's showing Aug 31st as the date for the aix 2.1.5 builds.

**Comment by pauldanielbarnes** [comment]
Installed the latest and got the following error:
$ LIBPATH=/usr/local/ncpa /usr/local/ncpa/ncpa_listener -n
Traceback (most recent call last):
  File "/opt/freeware/lib/python2.7/site-packages/cx_Freeze-4.3.4-py2.7-aix-7.1.egg/cx_Freeze/initscripts/Console.py", line 27, in <module>
  File "ncpa_listener.py", line 5, in <module>
  File "/tmp/test/ncpa/agent/ncpadaemon.py", line 14, in <module>
  File "/tmp/test/ncpa/agent/listener/database.py", line 5, in <module>
  File "/tmp/test/ncpa/agent/listener/server.py", line 11, in <module>
  File "/tmp/test/ncpa/agent/listener/psapi.py", line 245, in <module>
  File "/tmp/test/ncpa/agent/listener/psapi.py", line 216, in get_root_node
  File "/tmp/test/ncpa/agent/listener/psapi.py", line 177, in get_disk_node
AttributeError: 'NoneType' object has no attribute 'split'
da1008:/root $ rpm -qa | grep ncpa
ncpa-2.1.5-3

**Comment by jomann09** [comment]
Do you not actually have any disks/mounts? Or can the user that is running ncpa not have permissions to see them? I will have to take a look at that section, it should error out nicely if there is no disks available to parse.

**Comment by pauldanielbarnes** [comment]
No, there are plenty of mounted filesystems. I'm running the ncpa as root which can list and return all mounted filesystems.

da1008:/root $ lspv
hdisk0          00c4e537dbcfb5e4                    sysvg           active
hdisk1          00c4e537dbcf996d                    rootvg          active
hdisk3          00c4e537dbcffc1a                    mfdev_vg        active
da1008:/root $ df -g
Filesystem    GB blocks      Free %Used    Iused %Iused Mounted on
/dev/hd4           0.50      0.18   65%     5242    11% /
/dev/hd2           5.00      2.48   51%    51727     8% /usr
/dev/hd9var        1.00      0.35   66%     1188     2% /var
/dev/hd3           1.75      1.75    1%      310     1% /tmp
/dev/hd1           0.12      0.09   27%      515     3% /home
/proc                 -         -    -        -      - /proc
/dev/hd10opt       1.00      0.37   64%    25114    23% /opt
/dev/nmonlv        0.12      0.12    2%        5     1% /var/nmon_stats
/dev/mfdev_lvB      0.25      0.25    2%      443     1% /interfaces
/dev/mfdev_lvC     12.25      8.41   32%     3120     1% /oracle
/dev/mfdev_lvD     96.00     39.76   59%       34     1% /oracle/MD1/sapdata1
/dev/mfdev_lvE     56.00     31.06   45%       19     1% /oracle/MD1/sapdata2
/dev/mfdev_lvF     51.00     30.08   42%       21     1% /oracle/MD1/sapdata3
/dev/mfdev_lvG     51.00     31.01   40%       23     1% /oracle/MD1/sapdata4
/dev/mfdev_lvH     51.00     31.00   40%       14     1% /oracle/MD1/sapdata5
/dev/mfdev_lvI     60.00     30.64   49%       18     1% /oracle/MD1/sapdata6
/dev/mfdev_lvJ     15.00      4.77   69%    71415     6% /usr/sap
/dev/mfdev_lvK      2.00      0.42   80%    11946    11% /sapmnt
/dev/mfdev_lvL      0.25      0.25    1%        4     1% /lsmw
/dev/mfdev_lvN      9.00      1.48   84%    40444    11% /oracle/MD1/11203
/dev/rootlvA       0.12      0.08   35%      273     2% /home/redwood
/dev/rootlvB       1.12      1.07    6%      450     1% /home/redadmin
/dev/flaglv        0.12      0.12    1%        6     1% /var/flagfiles
/dev/oracle12_lv     20.00      7.92   61%    35164     2% /oracle/MD1/12102
shvsdata01-stg.services.howdens.corp:/OPTIPLAN_DEV       2.50      2.47    2%     2667     2% /optiplan_dev

da1008:/root $ LIBPATH=/usr/local/ncpa /usr/local/ncpa/ncpa_listener -n
Traceback (most recent call last):
  File "/opt/freeware/lib/python2.7/site-packages/cx_Freeze-4.3.4-py2.7-aix-7.1.egg/cx_Freeze/initscripts/Console.py", line 27, in <module>
  File "ncpa_listener.py", line 5, in <module>
  File "/tmp/test/ncpa/agent/ncpadaemon.py", line 14, in <module>
  File "/tmp/test/ncpa/agent/listener/database.py", line 5, in <module>
  File "/tmp/test/ncpa/agent/listener/server.py", line 11, in <module>
  File "/tmp/test/ncpa/agent/listener/psapi.py", line 245, in <module>
  File "/tmp/test/ncpa/agent/listener/psapi.py", line 216, in get_root_node
  File "/tmp/test/ncpa/agent/listener/psapi.py", line 177, in get_disk_node
AttributeError: 'NoneType' object has no attribute 'split'

**Comment by jomann09** [comment]
Interesting... I am patching it and will make another build. This shouldn't happen , since fstype should always exist but I will add a check so it doesn't have issues. I'll post back soon with updates.

**Comment by jomann09** [comment]
I've built a new version that should be available to download now. It should fix this issue.
