### ISSUE TITLE
ncpa not sending data to nagios.

### ISSUE THREAD

**Issue by tobcorp** [NagiosEnterprises/ncpa#487]
[ncpa_passive.log](https://github.com/NagiosEnterprises/ncpa/files/2361217/ncpa_passive.log)
Hi!
I have a problem with 1 of my Machines running ncpa.
I got about a dozen Machines placed on strategic places around the "municapality" to measure the access to centrally placed db's, app servers and other stuff. a few of them are laptops for different reasons.
**The culprit in question is:**
a laptop, running win7 Enterprise. 
ncpa 2.1.1 newly installed.
windows firewall set to allow all outbound traffic atm.
Connecting with browser to nrdp-adress works fine.
atm. only 1 ps-script running and the default cpu/mem/disk stuff.
connecting to https://localhost:5693 works fine. Tab "checks" shows the checks works fine.
But: NCPA will not send to Nagios. Receiving end works fine.
There are error in ncpa_passive log, but i can not make heads or tail with it:
2018-09-07 15:23:30,200:ERROR:ncpacheck:Error with JSON: No JSON object could be decoded. JSON was: <!DOCTYPE html>
<html lang='en'>
    <head>
        <title>Page Not Found &middot; NCPA</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="NCPA Web Interface">
        <meta name="author" content="Nagios Enterprises, LLC">
        <link rel="shortcut icon" type="image/png" href="/static/img/ncpa.png" />
        <link rel="icon" type="image/png" href="/static/img/ncpa.png" />
        <link rel='stylesheet' href='/static/css/bootstrap.min.css'>
        <link rel='stylesheet' href='/static/css/font-awesome.min.css'>
        <link rel='stylesheet' href='/static/css/ncpa.css'>
        
        
        <script src='/static/js/jquery.2.2.4.min.js'></script>
        <script src='/static/js/bootstrap.min.js'></script>
        <script src='/static/js/d3.v4.min.js'></script>
        <script src='/static/js/main.js'></script>
        
        
    </head>

Edit: attached a partial log since forum didn't like the html tags
;)

**Comment by stefan-wuensch** [comment]
Try turning up the log level with `loglevel = debug` under the `[passive]` section. 

I'm curious what you get on and after the line `DEBUG Handling JSON response`
...because I'm dealing with an issue that might be the same as yours. More on my issue soon.

**Comment by tobcorp** [comment]
**This seems to be solved now.**

**Comment by jomann09** [comment]
That would definitely cause problems if you were using windows counters! Sorry about the late response on this and I am glad it's working for you. I'll close this but feel free to open another if you find any issues.
