### ISSUE TITLE
NCPA Plugin Windows Host PowerShell version.

### ISSUE THREAD

**Issue by jolejo10** [NagiosEnterprises/ncpa#489]
Hello I'm trying to execute the [veeam plugin](https://exchange.nagios.org/directory/Plugins/Backup-and-Recovery/Others/check_veeam_backups/details) in NCPA. 
The issue is that VeeamPSSnapin is in PowerShell version 2 only.
And no module are load in the powershell version 5 which NCPA run natively.

I've try to edit the ncpa.cfg file to this but it does do anything.
.ps1 = powershell -version 2.0 -ExecutionPolicy Bypass -File $plugin_name $plugin_args

I've also try to run the powershell script from inside a bat file but still no success.
powershell -version 2.0 -file "C:\progra.... to the script"

Still saying it's a version 5 PS...
Any idea.
Trying this on Windows server 2016..
Thank you.

**Comment by jomann09** [comment]
Have you installed the powershell v2 engine on the server? I'm looking at https://docs.microsoft.com/en-us/powershell/scripting/setup/starting-the-windows-powershell-2.0-engine?view=powershell-6 which is probably why you added the -version 2.0 to the command? It doesn't work in the cmdline right?
