### ISSUE TITLE
Move service/services remedy

### ISSUE THREAD

**Issue by scot0357** [NagiosEnterprises/ncpa#49]
Move the quick remedy for the service/services API breakage into the nodes. This will make it much easier to reason about the entry point of the entire API. This will be done before https://github.com/NagiosEnterprises/ncpa/issues/47 and after https://github.com/NagiosEnterprises/ncpa/issues/30.

**Comment by jomann09** [comment]
Closing this since these are becoming deprecated and will no longer be usable!
