### ISSUE TITLE
NCPA Agent on AIX not starting [Errno 127] Value too large to be stored in data type

### ISSUE THREAD

**Issue by typer100** [NagiosEnterprises/ncpa#490]
Using IBM repo. Did a yum update. Installed new agent 2.1.5-4. Same issue.

root@sxpcog0630:/root# LIBPATH=/usr/local/ncpa /usr/local/ncpa/ncpa_passive -n
ERROR:root:failed to start due to an exception
Traceback (most recent call last):
  File "/tmp/test/ncpa/agent/ncpadaemon.py", line 167, in start
  File "/tmp/test/ncpa/agent/ncpadaemon.py", line 48, in setup_root
OSError: [Errno 127] Value too large to be stored in data type: '/tmp'
ERROR:root:[Errno 127] Value too large to be stored in data type: '/tmp'
Traceback (most recent call last):
  File "ncpa_passive.py", line 88, in <module>
  File "/tmp/test/ncpa/agent/ncpadaemon.py", line 76, in main
  File "/tmp/test/ncpa/agent/ncpadaemon.py", line 167, in start
  File "/tmp/test/ncpa/agent/ncpadaemon.py", line 48, in setup_root
OSError: [Errno 127] Value too large to be stored in data type: '/tmp'

root@sxpcog0630:/root# oslevel -s
7100-04-06-1806

Thanks.

**Comment by typer100** [comment]
I think I've found the issue. In this loop which is an extract from 
File "/tmp/test/ncpa/agent/ncpadaemon.py", line 48, in setup_root

for file_x in os.listdir(tmpdir):
   print file_x

I have some inode issue in the /tmp (tmpdir). The shell as no issue dealing with them, but Python does.
I'll clean the filesystem and report back.

**Comment by jomann09** [comment]
Sorry haven't had time to check into this yet. That actually makes a lot of sense. I will take a look at making this fail gracefully though so that it won't break the agent next time.

**Comment by typer100** [comment]
Yep. That's the issue. With a clean tmpdir the agent starts.
Let me know if you include this in the next release, so that I could this this for you.
Thanks.

**Comment by jomann09** [comment]
This should be fixed in 2.1.6 / 0da72891d1ee7def05f03c7bd3312ba46a98be4d - I will be building a dev version tomorrow and you can test it if you'd like.

**Comment by jomann09** [comment]
Have been working on solaris builds, but 2.1.6 will be out very soon so closing this.
