### ISSUE TITLE
Disk Physical check return code 3

### ISSUE THREAD

**Issue by 4gemenot** [NagiosEnterprises/ncpa#495]
running below check it throw return code 3.

./check_ncpa.py -H myhostrep -t 'myKey' -M 'disk/physical/dm-0' -u Ki
unable to run check on node without check method. Requested 'dm-0' node.

But when I run below check it works.
./check_ncpa.py -H myhostrep -t 'myKey' -M 'disk/physical/dm-0/read_bytes' -u Ki
OK: Read_bytes was 245000.50 Kib | 'read_bytes'=245000.50Kib;;;

Is there a way that running the first  check command it will provides all the result check method?

Thanks,

Ronald

**Comment by jomann09** [comment]
The first check does not exist right now, only the logical disk check can do a full check on all the sub-checks. This will be changed in NCPA 3.

**Comment by 4gemenot** [comment]
Thank you Joman.
