### ISSUE TITLE
Specifying /IP during silent installation is ignored

### ISSUE THREAD

**Issue by kaba1ah** [NagiosEnterprises/ncpa#496]
Hello,

Specifying `/IP='x.x.x.x'` during silent installation seems to be ignored with NCPA 2.1.6 (and 2.1.5). Tested under Windows 2012 R2 Server and Windows 2016 Server. The full command is `ncpa-2.1.6.exe /S /TOKEN='xxx' /IP='1.2.3.4'`.

Thank you.

**Comment by jomann09** [comment]
Thanks for catching this. I re-built the 2.1.6 installer to make sure it works now. I also updated the repo for next time. Thanks again.
