### ISSUE TITLE
Send passive checks to Nagios Server outside local network.

### ISSUE THREAD

**Issue by eirikrg** [NagiosEnterprises/ncpa#498]
I wanted to know if it is possible to use NCPA passive checks to send information to a Nagios Server that it's outside the local network, and if it is, how to do it?

I just started with monitoring server so I am pretty newbie with all this think, help would be appreciated. 

Thank you in advance.

**Comment by jomann09** [comment]
Yes you can, as @box293 stated and the doc linked is probably the best resource for getting up and running right away. Let us know if you have any questions.
