### ISSUE TITLE
Using cmd parameter when searching processes on macOS not working

### ISSUE THREAD

**Issue by PH-Bluechain** [NagiosEnterprises/ncpa#501]
I've been trying to use the processes API to search for processes by their arguments. Both machines are running macOS 10.13.6, with latest ncpa on remote.
If I try `/api/processes/?token=<mytoken>&name=java&match=search&check=1` I can see all three java processes running on the remote Mac, but if I try `/api/processes/?token=<mytoken>&cmd=java&match=search&check=1` I get zero processes returned, let alone trying to search by what's in the processes arguments. Changing match to regex doesn't appear to work either—the only way I can get *any* results is by specifying `.*` as my cmd text.

**Comment by jomann09** [comment]
Interesting, I will have to test this on Mac and get back to you. If you can, can you post the results of the JSON that is given when you run the first one, with name=java?

**Comment by jomann09** [comment]
I'm going to close this since I haven't been able to replicate. Please don't hesitate to let me know if you're still having the issue with the most recent version. If you are, please send the full list of the output when you run the /api/processes call without the `check=1` parameter.
