### ISSUE TITLE
NCPA API Endpoint Processes returncode

### ISSUE THREAD

**Issue by 4gemenot** [NagiosEnterprises/ncpa#502]
Good day.

NCPA agent = 2.1.6
check NCPA = 1.1.3

I'm running two Active commands, the first command is successful and the second is not but the returncode is 0 (OK), it this possible that the result is error for the second command?

1:
./check_ncpa.py -H 10.xx.xx.xx -t '<your token>' -M 'processes' -q 'username=cafis,name=eng_svr2_nodb,cmd=/home/cafis/afis/cafis61.afis/bin/eng_svr2_nodb -j S1PRAFIS01 -k 9000 -i TPS1 -g 3 -P 1 -m dbafis/dbafis11@dbsaud -a /home/cafis/afis/cafis61.afis -s /home/cafis/afis/cafis61.afis/SYSPATH/'

Output:
OK: Process count for processes named eng_svr2_nodb was 1 | 'process_count'=1;;; 'cpu'=0.0%;;; 'memory'=0.04%;;; 'memory_vms'=260399104B;;; 'memory_rss'=101773312B;;;
Processes Matched
PID: Name: Username: Exe: Memory: CPU
-----------------------------------
28939: eng_svr2_nodb: cafis: 0.04 % (VMS 260399104.00 B, RSS 101773312.00 B): 0.00 %

Total Memory: 0.04 % (VMS 260399104.00 B, RSS 101773312.00 B)
Total CPU: 0.00 %

2:
./check_ncpa.py -H 10.xx.xx.xx -t '<your token>' -M 'processes' -q 'username=cafis,name=eng_svr2_nodb,cmd=/home/cafis/afis/cafis61.afis/bin/eng_svr2_nodb -j S1PRAFIS01 -k 9000 -i TPS -g 3 -P 1 -m dbafis/dbafis11@dbsaud -a /home/cafis/afis/cafis61.afis -s /home/cafis/afis/cafis61.afis/SYSPATH/'

Output:
OK: Process count for processes named eng_svr2_nodb was 0 | 'process_count'=0;;;

Thanks,

**Comment by box293** [comment]
You are not defining any thresholds as to what should be an "error". For example, if the result is less than 1 you can add the threshold `-c 1:`
```
./check_ncpa.py -H 10.xx.xx.xx -t '' -M 'processes' -q 'username=cafis,name=eng_svr2_nodb,cmd=/home/cafis/afis/cafis61.afis/bin/eng_svr2_nodb -j S1PRAFIS01 -k 9000 -i TPS -g 3 -P 1 -m dbafis/dbafis11@dbsaud -a /home/cafis/afis/cafis61.afis -s /home/cafis/afis/cafis61.afis/SYSPATH/' -c 1:
```

Thresholds are explained here:
https://nagios-plugins.org/doc/guidelines.html#THRESHOLDFORMAT

**Comment by 4gemenot** [comment]
Thank you Box293 your suggestion works.

**Comment by jomann09** [comment]
Awesome, let us know if you have any other issues!
