### ISSUE TITLE
Network Interface Check with threshold and performance

### ISSUE THREAD

**Issue by 4gemenot** [NagiosEnterprises/ncpa#503]
Good day.

NCPA client version 2.1.6
Check_ncpay 1.1.3
1Gbps network interface

1. How is the network check works?

I did below command to check the network interface and everything is OK output.
/usr/local/nagios/libexec/check_ncpa.py -H 10.0.70.53 -t 4G3tm3n@t -M 'interface/team0'  -v
Connecting to: https://10.0.70.53:5693/api/interface/team0/?token=4G3tm3n%40t&check=1
File returned contained:
{
    "perfdata": "'bytes_sent'=3139640832629B;;;", 
    "returncode": 0, 
    "stdout": "OK: Bytes_sent was 3139640832629 B (Dropin: 72989 packets, Bytes_recv: 1038317116402 B, Packets_recv: 2346220298 packets, Dropout: 0 packets, Errout: 0 errors, Errin: 0 errors, Packets_sent: 2047467943 packets) | 'bytes_sent'=3139640832629B;;; 'dropin'=72989;;; 'bytes_recv'=1038317116402B;;; 'packets_recv'=2346220298;;; 'dropout'=0;;; 'errout'=0;;; 'errin'=0;;; 'packets_sent'=2047467943;;;"
}
OK: Bytes_sent was 3139640832629 B (Dropin: 72989 packets, Bytes_recv: 1038317116402 B, Packets_recv: 2346220298 packets, Dropout: 0 packets, Errout: 0 errors, Errin: 0 errors, Packets_sent: 2047467943 packets) | 'bytes_sent'=3139640832629B;;; 'dropin'=72989;;; 'bytes_recv'=1038317116402B;;; 'packets_recv'=2346220298;;; 'dropout'=0;;; 'errout'=0;;; 'errin'=0;;; 'packets_sent'=2047467943;;;

And do the second check with threshold parameters and unit to Mbits, I got CRITICAL output.

/usr/local/nagios/libexec/check_ncpa.py -H 10.0.70.53 -t 4G3tm3n@t -M 'interface/team0' -w 850 -c 950 -u Mi -v
Connecting to: https://10.0.70.53:5693/api/interface/team0/?token=4G3tm3n%40t&warning=850&critical=950&units=Mi&check=1
File returned contained:
{
    "perfdata": "'bytes_sent'=2993573.67MiB;850;950;", 
    "returncode": 2, 
    "stdout": "CRITICAL: Bytes_sent was 2993573.67 MiB (Dropin: 72989 packets, Bytes_recv: 989991.13 MiB, Packets_recv: 2346643355 packets, Dropout: 0 packets, Errout: 0 errors, Errin: 0 errors, Packets_sent: 2047824033 packets) | 'bytes_sent'=2993573.67MiB;850;950; 'dropin'=72989;850;950; 'bytes_recv'=989991.13MiB;850;950; 'packets_recv'=2346643355;850;950; 'dropout'=0;850;950; 'errout'=0;850;950; 'errin'=0;850;950; 'packets_sent'=2047824033;850;950;"
}
CRITICAL: Bytes_sent was 2993573.67 MiB (Dropin: 72989 packets, Bytes_recv: 989991.13 MiB, Packets_recv: 2346643355 packets, Dropout: 0 packets, Errout: 0 errors, Errin: 0 errors, Packets_sent: 2047824033 packets) | 'bytes_sent'=2993573.67MiB;850;950; 'dropin'=72989;850;950; 'bytes_recv'=989991.13MiB;850;950; 'packets_recv'=2346643355;850;950; 'dropout'=0;850;950; 'errout'=0;850;950; 'errin'=0;850;950; 'packets_sent'=2047824033;850;950;

85% of the 1Gbits (1000MBits) = 850
95% of the 1Gbits (1000MBits) = 950

2. What is the unit stands for? Where is the unit apply for? How I can use the unit for the threshold check?

3. Is it possible to run below check?
/usr/local/nagios/libexec/check_ncpa.py -H 10.0.70.53 -t 4G3tm3n@t -M 'interface/team0/packets_recv' -M 'interface/team0/packets_sent' -M 'interface/team0/dropin' -M 'interface/team0/dropout' -w 850 -c 950 -u Mi -v

Thanks,

**Comment by Madlohe** [comment]
Hi @4gemenot, 
1.) The bytes_sent/bytes_recv are counters, not rates. You will probably want to add the -d/--delta option to get numbers in <unit>/s
2.) The unit is always a multiple of bytes. In your example, you have a device with maximum throughput of 1Gbit = 1000Mbits = 125MB ~= 119.2 MiB. Your thresholds should be like

850 Mbits => 106 MB
950 Mbits => 119 MB

So your actual check would look like
/usr/local/nagios/libexec/check_ncpa.py -H 10.0.70.53 -t 4G3tm3n@t -M 'interface/team0' -d -w 106 -c 119 -u M

3.) I think you will need to put each metric in a separate check.

If you need any more assistance beyond this, please open a thread at our forums https://support.nagios.com/forum/index.php. The "General Support" forum is open to anyone, regardless of whether they're a paying customer, and you be able to get help much faster there.

**Comment by 4gemenot** [comment]
Thank you Madlohe. 👍
