### ISSUE TITLE
NCPA  deamons wont start on AIX 7.2

### ISSUE THREAD

**Issue by Jaron-T** [NagiosEnterprises/ncpa#504]
Good day,

I have installed ncpa-2.1.6-1.ppc on an AIX 7200-02-02-1810.
But I have trouble starting the ncpa deamons (ncpa_listener and ncpa_passive).

At first it gave a memory fault but after adjusting the ulimits for the root user it started giving a segmentation fault. 

# dbx /usr/local/ncpa/ncpa_listener core
Type 'help' for help.
[using memory image in core]
reading symbolic information ...

Segmentation fault in buffered_dealloc at 0xd4e45da4 ($t1)
0xd4e45da4 (buffered_dealloc+0x204) 90640004            stw   r3,0x4(r4)

(dbx) where
buffered_dealloc() at 0xd4e45da4
frame_dealloc(0xb08cc66c) at 0xd4ca9d84
fast_function(0xb027f41c, 0x2ff216e8, 0x0, 0x0, 0x0) at 0xd4be1708
ceval.call_function(0x2ff216e8, 0x0) at 0xd4be13ec
PyEval_EvalFrameEx(0xb0a22184, 0x0) at 0xd4bdc068
fast_function(0xb027f4fc, 0x2ff21a68, 0x0, 0x0, 0x0) at 0xd4be16a0
ceval.call_function(0x2ff21a68, 0x0) at 0xd4be13ec
PyEval_EvalFrameEx(0xb0a1d47c, 0x0) at 0xd4bdc068
fast_function(0xb09054fc, 0x2ff21de8, 0x1, 0x1, 0x0) at 0xd4be16a0
ceval.call_function(0x2ff21de8, 0x0) at 0xd4be13ec
PyEval_EvalFrameEx(0xb09d5b6c, 0x0) at 0xd4bdc068
fast_function(0xb09056bc, 0x2ff22168, 0x1, 0x1, 0x0) at 0xd4be16a0
ceval.call_function(0x2ff22168, 0x0) at 0xd4be13ec
PyEval_EvalFrameEx(0xb0a0e434, 0x0) at 0xd4bdc068
fast_function(0xb09055a4, 0x2ff224e8, 0x1, 0x1, 0x0) at 0xd4be16a0
ceval.call_function(0x2ff224e8, 0x0) at 0xd4be13ec
PyEval_EvalFrameEx(0xb0057c44, 0x0) at 0xd4bdc068
PyEval_EvalCodeEx(0xb0078bf0, 0xb0036714, 0xb0036714, 0x0, 0x0, 0x0, 0x0, 0x0) at 0xd4bde520
PyEval_EvalCode(0xb0078bf0, 0xb0036714, 0xb0036714) at 0xd4bd4248
exec_statement(0xb0057184, 0xb0078bf0, 0xb0036714, 0xb0036714) at 0xd4be3f8c
PyEval_EvalFrameEx(0xb0057184, 0x0) at 0xd4bd88e0
PyEval_EvalCodeEx(0xb0078458, 0xb0053934, 0xb0053934, 0x0, 0x0, 0x0, 0x0, 0x0) at 0xd4bde520
PyEval_EvalCode(0xb0078458, 0xb0053934, 0xb0053934) at 0xd4bd4248
.() at 0x10000644
.() at 0x10000514
(dbx) quit

Is there more information needed to solve the issue?

Thanks,

Jaron

**Comment by jomann09** [comment]
How are you starting the ncpa_listener service?

**Comment by Jaron-T** [comment]
Your question made me look for otherways to start the daemon so I found in the documentation the
startsrc -s ncpa_listener command. With that it worked.

thanks for the assist.

**Comment by jomann09** [comment]
Great! Glad to hear it's working. It is best to start it with startsrc because it has to set library path for the binaries or they won't pick up some of the libraries it needs.

**Comment by Jaron-T** [comment]
we have a new issue related to this. After a rpm installation of the ncpa it will start. But when stopped with stopsrc it wont start anymore.

At first it wouldnt start because it didnt had the right permission on the directory when it got installed and because of that it wouldnt start at all.

**Comment by jomann09** [comment]
Is there anything in /usr/local/ncpa/var/log/ncpa_listener.log ?

**Comment by Jaron-T** [comment]
only this:
2018-11-15 16:22:20,044 13500806 INFO started
2018-11-15 16:22:20,046 13500806 INFO Using SSL version TLSv1_2
2018-11-15 16:29:19,102 13500806 INFO stopped


After a new start it wont write anything in the log

**Comment by jomann09** [comment]
If you use ps aux | grep ncpa what does it show? You can try ef instead too. I'm just curious if it's not registering that it needs to shut down.

**Comment by Jaron-T** [comment]
well we stopped it and that entry you see in the logfile with this line:
2018-11-15 16:29:19,102 13500806 INFO stopped

So after a start command it doenst do anything anymore.
The ps aux or ef only shows the grep command
