### ISSUE TITLE
NCPA will only start once, related to the 504 issue

### ISSUE THREAD

**Issue by Jaron-T** [NagiosEnterprises/ncpa#507]
hello jomann09 ,

We found out that during the first installation it dint start immediately because it had sufficient permission in local dir. So after adjusting that we tried to restart the ncpa.

The OS says it started it with a given PID but the log and run files doesn't show new entries and  by checking the processlist you can see it is not running.

After a rpm removal and reinstall it started. 
But when stopped with stopsrc it wont start anymore.

**Comment by jomann09** [comment]
You're talking about AIX systems? Was there an ncpa_listener.pid file in /usr/local/nagios/var and was it root/root permissions?

**Comment by Jaron-T** [comment]
Yes the file was there and was with root/root permissions. apologies for the delay, havent been working nagios for a while. 

I wont be working on it for the time being, so you may close the issue.
