### ISSUE TITLE
NCPA: v2.1.5: Windows ncpa agent put in wrong place uninstall in registry

### ISSUE THREAD

**Issue by Delfana** [NagiosEnterprises/ncpa#512]
The Windows NCPA agent installation puts uninstall registry keys in HKEY_CURRENT_USER instead of HKEY_LOCAL_MACHINE. Due to this, only the user that installed the agent can uninstall it through Add/Remove programs.

This was fixed in #169, but it looks like the code has been refactored since then and the bug has been re-introduced.

I looked at agent/build_resources/ncpa.nsi. It adds the uninstall keys to SHCTX. I'm guessing that SetShellVarContext is set to "current" (the default), while it should probably be set to "all".
[https://nsis.sourceforge.io/Reference/WriteRegExpandStr](https://nsis.sourceforge.io/Reference/WriteRegExpandStr)

**Comment by slowbrowse** [comment]
I can confirm that this issue is still present in NCPA v2.1.7

**Comment by yderi** [comment]
Also confirm, present in NCPA 2.1.6 and NCPA 2.1.7

**Comment by jomann09** [comment]
Changing the page didn't work quite right it still is doing this. I will have this resolved in NCPA 3 when we switch over to using Wix instead of NSIS.

**Comment by jomann09** [comment]
I've got this figured out and will be fixed in version 2.1.8
