### ISSUE TITLE
Random plugin issue in Windows 10

### ISSUE THREAD

**Issue by StephenHood** [NagiosEnterprises/ncpa#514]
I have a small subset of Windows 10 machines that refuse to run any plugin. I've tried completely removing NCPA and reinstalling it on these machines and nothing changes. I've updated from 2.1.5 to 2.1.6 and still no changes. I can run these plugins from the command line on the machines with no issue and they run fine on other machines via NCPA, but any time I try to run them via NCPA on these machines the return code for the check is 66. The plugin itself returns -1073741502 (or 0xC0000142). The plugins are powershell and batch scripts. I've turned debugging on for the listener's logs and the entries look no different from machines where the plugins work. There is nothing in the event viewer that indicates a problem either. Running them via check_ncpa.py also gives the same return codes mentioned above. Any suggestions on how to resolve this issue? Thanks in advance.

**Comment by jomann09** [comment]
Looking up that error code (0xC0000142) it seems like there are an awful lot of things that could cause it. If it's specifically on some systems, it's possible it's related to the policy on the system. It is supposed to be running it as a system service so it should have all permissions necessary, but if it's not able to use the console it would likely have that error.
