### ISSUE TITLE
Custom Plugins not working from configuration file (storcli)

### ISSUE THREAD

**Issue by 4gemenot** [NagiosEnterprises/ncpa#519]
Hi,

I'm using NCPA version 2.1.6.

I created the following passive check.

%HOSTNAME%|Base-RAID Controller Status|10 = /plugins/storcli64?args=/c0/dall show

Checking from the passive log I got below message.

2019-02-27 16:58:54,271 24577 DEBUG Handling JSON response: {
    "returncode": 0, 
    "stdout": "Controller = 0\nStatus = Failure\nDescription = Controller 0 not found"
}
2019-02-27 16:58:54,271 24577 DEBUG JSON response handled found stdout='Controller = 0
Status = Failure

But if I run the storcli64 /c0/dall show from the command line it works.

Controller = 0
Status = Success
Description = Show Diskgroup Succeeded

TOPOLOGY :
========

----------------------------------------------------------------------------
DG Arr Row EID:Slot DID Type  State BT      Size PDC  PI SED DS3  FSpace TR 
----------------------------------------------------------------------------
 0 -   -   -        -   RAID6 Optl  N  81.856 TB dsbl N  N   dflt N      N  
 0 0   -   -        -   RAID6 Optl  N  81.856 TB dsbl N  N   dflt N      N  
 0 0   0   9:0      11  DRIVE Onln  N   9.094 TB dsbl N  N   dflt -      N  
 0 0   1   9:1      19  DRIVE Onln  N   9.094 TB dsbl N  N   dflt -      N  
 0 0   2   9:2      18  DRIVE Onln  N   9.094 TB dsbl N  N   dflt -      N  
 0 0   3   9:3      31  DRIVE Onln  N   9.094 TB dsbl N  N   dflt -      N  
 0 0   4   9:4      23  DRIVE Onln  N   9.094 TB dsbl N  N   dflt -      N  
 0 0   5   9:5      16  DRIVE Onln  N   9.094 TB dsbl N  N   dflt -      N  
 0 0   6   9:6      34  DRIVE Onln  N   9.094 TB dsbl N  N   dflt -      N  
 0 0   7   9:7      29  DRIVE Onln  N   9.094 TB dsbl N  N   dflt -      N  
 0 0   8   9:8      20  DRIVE Onln  N   9.094 TB dsbl N  N   dflt -      N  
 0 0   9   9:9      25  DRIVE Onln  N   9.094 TB dsbl N  N   dflt -      N  
 0 0   10  9:10     21  DRIVE Onln  N   9.094 TB dsbl N  N   dflt -      N  
 1 -   -   -        -   RAID6 Optl  Y  81.856 TB dsbl N  N   dflt N      N  
 1 0   -   -        -   RAID6 Optl  Y  81.856 TB dsbl N  N   dflt N      N  
 1 0   0   10:0     33  DRIVE Onln  Y   9.094 TB dsbl N  N   dflt -      N  
 1 0   1   10:1     26  DRIVE Onln  Y   9.094 TB dsbl N  N   dflt -      N  
 1 0   2   10:2     14  DRIVE Onln  Y   9.094 TB dsbl N  N   dflt -      N  
 1 0   3   10:3     12  DRIVE Onln  Y   9.094 TB dsbl N  N   dflt -      N  
 1 0   4   10:4     15  DRIVE Onln  Y   9.094 TB dsbl N  N   dflt -      N  
 1 0   5   10:5     24  DRIVE Onln  Y   9.094 TB dsbl N  N   dflt -      N  
 1 0   6   10:6     17  DRIVE Onln  Y   9.094 TB dsbl N  N   dflt -      N  
 1 0   7   10:7     32  DRIVE Onln  Y   9.094 TB dsbl N  N   dflt -      N  
 1 0   8   10:8     35  DRIVE Onln  Y   9.094 TB dsbl N  N   dflt -      N  
 1 0   9   10:9     13  DRIVE Onln  Y   9.094 TB dsbl N  N   dflt -      N  
 1 0   10  10:10    22  DRIVE Onln  Y   9.094 TB dsbl N  N   dflt -      N  
 - -   -   10:11    28  DRIVE GHS   -   9.094 TB -    -  -   -    -      N  
 - -   -   9:11     30  DRIVE GHS   -   9.094 TB -    -  -   -    -      N  
----------------------------------------------------------------------------

DG=Disk Group Index|Arr=Array Index|Row=Row Index|EID=Enclosure Device ID
DID=Device ID|Type=Drive Type|Onln=Online|Rbld=Rebuild|Dgrd=Degraded
Pdgd=Partially degraded|Offln=Offline|BT=Background Task Active
PDC=PD Cache|PI=Protection Info|SED=Self Encrypting Drive|Frgn=Foreign
DS3=Dimmer Switch 3|dflt=Default|Msng=Missing|FSpace=Free Space Present
TR=Transport Ready

From the passive result "Status = Failure" but I got returncode 0, How to fix it?
How to fix my passive configuration for this "storcli command"?

Thanks,

**Comment by jomann09** [comment]
I do believe you have to pass it like a normal argument when you run it manually, so something like this:

```
%HOSTNAME%|Base-RAID Controller Status|10 = /plugins/storcli64/%2Fc0%2Fdall%20show
```

Not the easiest to read, but the arguments should be urlencoded and passed in using the / for NCPA 2.1.x

**Comment by jomann09** [comment]
Closing this due to url encoding, if you're still having an issue please let us know.
