### ISSUE TITLE
All Windows counter don't translate correctly

### ISSUE THREAD

**Issue by scottwilkerson** [NagiosEnterprises/ncpa#520]
In working through https://support.nagios.com/forum/viewtopic.php?t=52745 it was discovered that Windows performance counters names that end in /Transfer /Read and /Write were not being translated correctly.  In digging into the problem, the format for all counters should be one of the following
```
\\computer\object(parent/instance#index)\counter
\\computer\object(parent/instance)\counter
\\computer\object(instance#index)\counter
\\computer\object(instance)\counter
\\computer\object\counter
\object(parent/instance#index)\counter
\object(parent/instance)\counter
\object(instance#index)\counter
\object(instance)\counter
\object\counter
```

https://docs.microsoft.com/en-us/windows/desktop/perfctrs/specifying-a-counter-path

I believe the fix to this is in agent/listener/windowscounters.py changing to something like the following
```
    @staticmethod
    def get_counter_path(path):
        counter_path = '\\'
        if len(path) > 2:
            counter_path += '\\'.join(path[:-1])
            counter_path += '/' + path[-1]
        else:
            counter_path += '\\'.join(path)
        return counter_path
```
This would still however leave a few a few paths incorrect and that is when you have a counter that contains (parent/instance) such as
`\\computer\object(parent/instance)\counter`

I have a feeling that there will need to be an exception to somehow catch this as the path will likely be split into more pieces.

**Comment by Madlohe** [comment]
Test cases that need to be covered (the suggested change fails for some of these):
'No instance name/no rate'
'No instance name/Rate with/units'
'Instance Name(No slash)/no rate'
'Instance Name(No slash)/Rate with/units'
'Instance Name(with/slash)/no rate'
'Instance Name(with/slash)/Rate with/units'

This is inelegant, but here's a python regex that seems to match a WPC without computer name:

```r'^/([^(/]*)\(?(.*?)\)?/([^)]*)$'```

So ideally you'd be able to do something like
```
@staticmethod
def get_counter_path(path):
    wpc_string = '/'.join(path)
    wpc_regex = r'^/([^(/]*)\(?(.*?)\)?/([^)]*)$'
    match_list = re.split(wpc_regex, wpc_string) # returns empty strings at indices 0 and -1
    counter_path = '\\'
    if len(match_list) == 4:
        counter_path += match_list[1] + '\\' + match_list[2]
    elif len(match_list) == 5:
        counter_path += match_list[1] + '(' + match_list[2] + ')\\' + match_list[3] 
    return counter_path
```

**Comment by O-negative** [comment]
It should also be noted that from my original detection of this issue the following perf counter also fails even though it is present and accessible via perfmon.exe

\SQLServer:Databases(_Total)\Backup/Restore Throughput/sec

**Comment by jomann09** [comment]
Closing this for 2.1.7 release
