### ISSUE TITLE
zipimport.ZipImportError on starting NCPA, SLES11.4

### ISSUE THREAD

**Issue by git-rob** [NagiosEnterprises/ncpa#524]
Hi, 
I have an issue on SLES 11.4:

host1:~ # service ncpa_listener start
Started NCPA Listener
zipimport.ZipImportError: can't decompress data; zlib not available
Fatal Python error: unable to locate initialization module
/etc/init.d/ncpa_listener: line 27: 18010 Aborted                 $BASEDIR/ncpa_listener --start
host11:~ # rpm -qa |grep zlib
zlib-1.2.7-0.14.1
zlib-32bit-1.2.7-0.14.1
host1:~ # cat /etc/os-release
NAME="SLES"
VERSION="11.4"
VERSION_ID="11.4"
PRETTY_NAME="SUSE Linux Enterprise Server 11 SP4"
ID="sles"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sles:11:4"

I see that a similiar issue has been resolved for ver 2.1.5
Can I do further checks?
Thanks a lot.

**Comment by jomann09** [comment]
Thanks for bringing this up, in 2.1.6 we removed the LD_LIBRARY_PATH portion being set and it causes issues. You can either install 2.1.5 via https://assets.nagios.com/downloads/ncpa/archived/2.1.5/ncpa-2.1.5.sle11.x86_64.rpm or you can edit your `/etc/init.d/ncpa_listener` and `/etc/init.d/ncpa_passive` to add the line:
```
export LD_LIBRARY_PATH="$PATH;$BASEDIR"
```
Right after the `BASEDIR="/usr/local/ncpa"` line in those two files.

**Comment by git-rob** [comment]
Hello, 
thanks a lot. I added the line to start/stop script and it works.
This issue can be closed.

**Comment by jomann09** [comment]
Have a fix for this in 2.1.7 that doesn't involve LD_LIBRARY_PATH so closing this now.
