### ISSUE TITLE
NCPA Passive check "forward slash issue / for driver name ", Serious bug

### ISSUE THREAD

**Issue by yxm0515** [NagiosEnterprises/ncpa#525]
I am using ncpa configuration for passive check , i use the plugin for checking
The argument what i want to check  is   /data ,but when i configured ,there is a error from log
like this
ValueError: Stdout or returncode was None, cannot return meaningfully.

%HOSTNAME%|Check free disk data = plugins/check_free_disk//data/1000000/500000

i tried another way,but still got the same issue
%HOSTNAME%|Check free disk data =plugins/check_free_disk/%2Fdata/1000000/500000

ValueError: Stdout or returncode was None, cannot return meaningfully.
 plugins/check_free_disk/%2Fdata/1000000/500000
 ERROR Exception on /api/plugins/check_free_disk//data/1000000/500000 [GET]

I am confused ,how can configure the argument for this

**Comment by yxm0515** [comment]
The NCPA Version what i use is 2.1.6

**Comment by jomann09** [comment]
You should be able to pass it via the args value (if you run it from the GUI API tab then click the button in the lower-left corner to see the passive check version of it, you'll get to see an example)

Should end up like this, but with your own values
```
%HOSTNAME%|<service name> = plugins/check_free_disk?args=/data&args=1000&args=5000
```

The above would run this:
```
./check_free_disk /data 1000 5000
```

**Comment by yxm0515** [comment]
Thanks for the quick response , i don't run it form GUI API. I am using it from ncpa/etc/ncpa.cfg  on the centos7, i tried the same way what you provide 
[passive checks]
%HOSTNAME%|Check free disk /data = plugins/check_free_disk?args=/data&args=1000000&args=500000

But i still got the same issue as before, and i was stuck in this for many days.
ValueError: Stdout or returncode was None, cannot return meaningfully.
888 476 INFO Running check: plugins/check_free_disk?args=/data&args=1000000&args=500000
896 476 ERROR Exception on /api/plugins/check_free_disk/ [GET

Could you please help further check with this ?  Many thanks.

**Comment by jomann09** [comment]
When you run the plugin itself on the agent machine from the command line what is the output that you get?

Also, it looks like the exception error got cut off in the above. You can also pass the whole thing as an argument if you need to, like `args=/data 1000000 500000` which may make a difference due to quoting.

**Comment by yxm0515** [comment]
The plugin  works like this, 
OK - 'free_space'=10217558016B 'space_usage'=49% 'inode_usage'=7% | 'free_space'=10217558016B;1000000;500000;0;21002534912 'used_space'=9694511104B;;;0;21002534912

The key problem why  it got error from ncpa/etc/ncpa.cfg is that the NCPA client can't read forward slash for the drive name. I also try other plugins which doesn't include forward slash , all works. But if i use the plugin which needs to contain the argument which include drive name like " /opt  or /root ", it will get the error and then ncap will not work on the Centos 7.

**Comment by jomann09** [comment]
The whole string is passed as a URL when you use the `?args` version, I don't think it's a plugin issue, just an issue with how the check is defined. If I recall correctly it may need to be URL encoded, can you try:
```
plugins/check_free_disk?args=%2Fdata 1000000 500000
```

**Comment by yxm0515** [comment]
I still got the same issue when i tried this  plugins/check_free_disk?args=%2Fdata 1000000 500000    The drive name can't work as the argument in the plugin check

**Comment by jomann09** [comment]
If you turn on debug logging on the NCPA agent in `ncpa.cfg` for passive checks you should be able to see the whole command that it is trying to run on the system. I don't know exactly what this plugin is doing or how it's running but I know that the forward slash does properly send when using the `args` option. Just tested it again to verify.

**Comment by jomann09** [comment]
Going to close this since I haven't heard anything about about it. I just tested passive checks using the method above on a test script that just runs a `ls -l $1` in shell and it properly passed the `/tmp` folder when passed.

test.sh in the plugins folder:
```
#!/bin/bash
echo `ls -l $1`
```

The command I ran in passive config:
```
%HOSTNAME%|Test Option = plugins/test.sh?args=/tmp
```

Debug output in ncpa_passive.log:
```
2019-10-23 12:39:10,874 13725 DEBUG Running process with command line: `/usr/local/ncpa/plugins/test.sh /tmp`
2019-10-23 12:39:10,885 13725 DEBUG Handling JSON response: {
    "returncode": 0, 
    "stdout": "total 32 drwx------ 2 gdm gdm 4096 Oct 23 09:11 gconfd-gdm drwx------ 2 root root 4096 Oct 23 09:40 gconfd-root drwx------ 2 root root 4096 Oct 23 09:11 keyring-sZ1ooI drwx------ 2 gdm gdm 4096 Oct 23 09:11 orbit-gdm drwx------ 2 root root 4096 Oct 23 09:40 orbit-root drwx------ 2 gdm gdm 4096 Oct 23 09:11 pulse-HLLfDF3kfMtl drwxrwxrwt 2 root root 4096 Oct 23 08:55 VMwareDnD drwx------ 2 root root 4096 Oct 23 09:11 vmware-root"
}
```
