### ISSUE TITLE
Error return from filesystem checks returns misinterpreted data

### ISSUE THREAD

**Issue by sgallaty** [NagiosEnterprises/ncpa#526]
Nagios parses pipe in the extended return string as the beginning of perf data.  NCPA uses | (pipe) as a distinguishment to parts of a filesystem argument (node) in disk checks.

When passed a filesystem disk free check (node) for /usr/sap/blah (for example) that does not exist, NCPA responds with : 

The node (|usr|sap|blah) requested does not exist. You may be trying to access the '|' node.

Two issues here - 

The first part - "The node (|usr|sap|blah) requested does not exist. " will end up displaying in Nagios as "The node (" since the '|' character will cause Nagios to split his unescaped return string into a Description part and an "Extended description" part.

The second part is extraneous, and unhelpful.  

Also these are not 'nodes' insofar as anyone who is looking at the errors (e.g. tier 1 support, anyone not actually technically operating the plugin) so that language is specifically ambiguous.

better, and suggested would be that the return error message from the plugin be something descriptive of the actual error - e.g. 

"Error - no matching filesystem /usr/sap/blah" and return an unknown status.

That would be succinct and convey the actual status.

**Comment by jomann09** [comment]
This makes a lot of sense. I have never liked the use of pipes in place of forward slashes. You are correct that they should not be shown in the output at the very least. Marking this as a bug and will update it for the next version.

**Comment by jomann09** [comment]
So I fixed the output issue with cf44abaf81d660e7842651956290420878c4de30 but due to the way the NCPA requests work there's no quick and easy way to fix the output - since it's general output used for all requests. In NCPA 3 this will be endpoint specific, so a disk error would have better disk-related error output.
