### ISSUE TITLE
RAM memory values in CentOs 6 are incorrect

### ISSUE THREAD

**Issue by franzbeppe** [NagiosEnterprises/ncpa#528]
I installed latest NCPA version (2.1.6) on a CentOS 6.6, but values about RAM memory (memory/virtual) are incorrect (except for free memory).

 NCAP values:
"available": [ 13.98, "GB" ]
 "total": [ 16.72, "GB" ] 
"percent": [ 16.4, "%" ] 
"free": [ 3.49, "GB" ] 
"used": [ 2.06, "GB"]

"free -m" command:
                    total       used         free        shared    buffers     cached
Mem:         15943      12619       3324        398        199         7919

On the server values reported by htop, top, free -m and "cat /proc/meminfo" are the same.
The only values from NCPA which seems realistic is the free memory.
Am i wrong or is there an issue?
Regards
Francesco

**Comment by jomann09** [comment]
The memory values are given by psutil, a python module https://psutil.readthedocs.io/en/latest/#memory

The values will not match free because they are not showing the same data, the used data returned by psutil does not include things like cached, buffers, etc
