### ISSUE TITLE
Add a correct LD_LIBRARY_PATH to NCPA build for Solaris 10

### ISSUE THREAD

**Issue by Kuma569** [NagiosEnterprises/ncpa#529]
This issue had been discussed at the "NCPA build for Solaris 10 (SPARC and Intel) (#105)" thread, and moved to this new Issue. 

Symptom: Due to the missing LD_LIBRARY_PATH for Solaris 10, NCPA 2.1.6 cannot be installed and getting the follwoing errors:

> These are the errors when they install NCPA on Solaris 10 server. They are getting this error – >even after creating a symlink to libgcc_s.so.1 
>
> 
> [ Apr 3 10:43:37 Executing start method ("/usr/local/ncpa/ncpa_listener") ]
> Traceback (most recent call last):
> File "/opt/csw/lib/python2.7/site-packages/cx_Freeze-4.3.4-py2.7-solaris-2.10-sun4v.32bit.egg/cx_Freeze/initscripts/Console.py", line 27, in 
> File "ncpa_listener.py", line 3, in 
> File "/opt/csw/lib/python2.7/logging/init.py", line 26, in 
> File "/opt/csw/lib/python2.7/collections.py", line 9, in 
> ImportError: ld.so.1: ncpa_listener: fatal: relocation error: file /usr/local/ncpa/operator.so: symbol _PyUnicodeUCS4_AsDefaultEncodedString: referenced symbol not found
> [ Apr 3 10:43:37 Method "start" exited with status 1 ]
> [10:43:45 ncpa.cfg.d]# ldd /usr/local/ncpa/operator.so
> libpython2.7.so.1.0 => /usr/lib/libpython2.7.so.1.0
> libgcc_s.so.1 => /lib/libgcc_s.so.1
> libc.so.1 => /lib/libc.so.1
> libresolv.so.2 => /lib/libresolv.so.2
> libsocket.so.1 => /lib/libsocket.so.1
> libnsl.so.1 => /lib/libnsl.so.1
> librt.so.1 => /lib/librt.so.1
> libdl.so.1 => /lib/libdl.so.1
> libm.so.2 => /lib/libm.so.2
> libmp.so.2 => /lib/libmp.so.2
> libmd.so.1 => /lib/libmd.so.1
> libscf.so.1 => /lib/libscf.so.1
> libaio.so.1 => /lib/libaio.so.1
> libdoor.so.1 => /lib/libdoor.so.1
> libuutil.so.1 => /lib/libuutil.so.1
> libgen.so.1 => /lib/libgen.so.1
> /platform/sun4v/lib/libc_psr.so.1
> /lib/libm/libm_hwcap1.so.2
> /platform/sun4v/lib/libmd_psr.so.1
> [10:43:51 ncpa.cfg.d]# 

To resolve,  add **LD_LIBRARY_PATH=/usr/local/ncpa** to the service.

```
 LD_LIBRARY_PATH=/usr/local/ncpa
 
  /usr/local/ncpa/ncpa_listener -n
```

Example:

> svccfg –s ncpa_listener
> svc:/site/ncpa_listener> setenv LD_LIBRARY_PATH /usr/local/ncpa
> svc:/site/ncpa_listener> exit
> svcadm refresh ncpa_listener #reload the config with new env value
> svcadm clear ncpa_listener #get out of maintenance state
> 
> svc:/site/ncpa_listener> listprop
> multi_user_dependency dependency
> multi_user_dependency/entities fmri svc:/milestone/multi-user
> multi_user_dependency/grouping astring require_all
> multi_user_dependency/restart_on astring none
> multi_user_dependency/type astring service
> start method
> start/timeout_seconds count 60
> start/type astring method
> start/exec astring "/usr/local/ncpa/ncpa_listener"
> **start/environment astring LD_LIBRARY_PATH=/usr/local/ncpa**
> stop method
> stop/exec astring "kill $(cat /usr/local/ncpa/var/run/ncpa_listener.pid)"
> stop/timeout_seconds count 60
> stop/type astring method
> refresh method
> refresh/exec astring :true
> refresh/timeout_seconds count 60
> refresh/type astring method
> startd framework
> startd/duration astring transient
> tm_common_name template
> tm_common_name/C ustring ncpa_listener
> tm_description template
> tm_description/C ustring "The ncpa listener service. Allows connections to ncpa API."

**Comment by jomann09** [comment]
I should have this fixed in the latest versions, I think I found out why this is required and can stop it. Will update this when I can confirm on a Solaris 10 system.

**Comment by jomann09** [comment]
Working on fixing this for Solaris builds for 2.1.7 - it's related to the libraries and how Python is installed so I am working on updates which means this may take a week or two to resolve and get a new build up. Closing this for that though.
