### ISSUE TITLE
NCPA cannot handle some string in bash script

### ISSUE THREAD

**Issue by yderi** [NagiosEnterprises/ncpa#530]
Client side: NCPA agent v2.1.6 installed on Ubuntu 16.04.6 LTS server
Server side: Nagios core 4.4.3  installed on Ubuntu 16.04.6 LTS and using check_ncpa.py (__VERSION__ = '1.1.5)

When using a web page in API section try to run bash script as plugin, getting misc output, while if just running the same script directly from a client-side console, everything runs fine, no misc output
`{ "returncode": 0, "stdout": "/usr/local/ncpa/plugins/check_docker_container.sh: 5: [: xredis-server: unexpected operator\n/usr/local/ncpa/plugins/check_docker_container.sh: 10: [: x/usr/bin/docker: unexpected operator\n/usr/local/ncpa/plugins/check_docker_container.sh: 28: [: true: unexpected operator\n/usr/local/ncpa/plugins/check_docker_container.sh: 36: [: false: unexpected operator\nOK - redis-server is running. IP: 172.17.0.2, StartedAt: 2019-04-10T18:45:31.5876704Z" }`
Nagios core get state correctly, but with unnecessary output see 
exprected to get only last string with OK state
"`OK - redis-server is running. IP: 172.17.0.2, StartedAt: 2019-04-10T18:45:31.5876704Z"`"
So agent cannot handle bash code on lines 5, 10, 28, 36.
Any suggestions how to handle it?

**Comment by yderi** [comment]
were able to handle some part by rewriting code for line 5 and 10 like this
```
if [ -z "${CONTAINER}" ]; then
  echo "UNKNOWN - Container ID or Friendly Name Required"
  exit 3
fi

if [ -z "$(which docker)" ]; then
  echo "UNKNOWN - Missing docker binary"
  exit 3
fi
```
Now only left troubles with lines 28 and 36.

My current bash version is "4.3.48(1)-release"
Just figure out that running script on client side with sh gives un error,
sh ./check_docker_container.sh redis-server
and running with bash runs ok
bash ./check_docker_container.sh redis-server
So assume NCPA use sh interpreter and doesn't read interpreter from shebang in file (in my case it bash).

**Comment by yderi** [comment]
Just realized that the problem is with a double equal sign in IF statement directives.
Found two solutions:
1. In "ncpa.cfg" plugins directives, you only have one for 
`.sh = /bin/sh $plugin_name $plugin_args`
So you need to add another for the bash. Edit your "ncpa.cfg" and add  
`.bash = /bin/bash $plugin_name $plugin_args`
Restart ncpa_listener
Then rename you script extension to .bash
Everything works.
2. Rewrite a script to use single equal (=) sign instead of double (==) inside IF operator.

**Comment by jomann09** [comment]
This makes sense, since Ubuntu uses a different shell than bash, so in order to ensure you are using a bash shell you should either set it like you did in the `ncpa.cfg` or you can add `#!/bin/bash` to the top of your shell script to ensure it runs via bash.

Going to close this though as it's related to the shell that comes standard in Ubuntu and not directly due to NCPA. Let me know if you have any other questions!

**Comment by yderi** [comment]
Just added to the top of the script, it doesn't change behavior in my case. So at the recent time only rewriting a script or adding additional directives into "ncpa.cfg" works for me.
Thanks for answering.
