### ISSUE TITLE
NCPA cannot running on Solaris 11

### ISSUE THREAD

**Issue by ongsunglau** [NagiosEnterprises/ncpa#531]
NCPA keep remaining in maintenance state. 
No logs generated on /usr/local/ncpa/var/log/ncpa_listener.log too

![IMG_20190417_110717](https://user-images.githubusercontent.com/49706370/56261595-3a79ad80-610e-11e9-9fec-931585b1e399.jpg)

**Comment by jomann09** [comment]
If you run the command manually with `/usr/local/ncpa/ncpa_listener -n` what is the output?

**Comment by ongsunglau** [comment]
Sorry is my mistake, I'm using SPARC it's working now. But we found out
that svcadm are not able to restarted ncpa_listener. After we changing
string_community, need to restart ncpa_listener using svcadm refresh
ncpa_listener and svcadm enable ncpa_listener. It's keep remain maintenance
mode. But ncpa still able to running and login using default mytoken.

**Comment by jomann09** [comment]
I'm not very familiar with svcadmin so I will take a look and see if I can re-create the issue on a Solaris 11 even if it's not using SPARC.

**Comment by ongsunglau** [comment]
Our temporary solution is to kill ncpa_listener process and start ncpa_listener back again. This are the way that we found out can resolve it but not a proper way to restart ncpa_listener.

**Comment by jomann09** [comment]
Are you killing it before trying to restart it? Does Solaris try to automatically start the service for you? If so, then if it doesn't know the pid it may be putting itself into maintenance mode when it's unable to start the new one.

**Comment by ongsunglau** [comment]
Are you killing it before trying to restart it?
I am trying to restart it before kill the process. Because it keep remain
Maintenance state

Does Solaris try to automatically start the service for you?
Solaris did not try to automatically restart for me. Because while using
svcadm services cannot execute properly. Only after killing it then start
services back will re-read all configuration.

**Comment by jomann09** [comment]
I believe I've fixed the issue with solaris 11 restarts/stops there was a typo in the listener install that caused it to not kill the pid - this is fixed in 2.1.7 which I am testing builds for now and should be release in the next couple days.

**Comment by jomann09** [comment]
This should be fixed in 2.1.7 now! I see the issue was with the way it was doing the kill, you will have to remove the package then install the new one unfortunately.
