### ISSUE TITLE
NCPA v2.1.7 returns http status code 308 when queried from wizard

### ISSUE THREAD

**Issue by jvandermeulen** [NagiosEnterprises/ncpa#535]
1)
When running an XI wizard towards NCPA v2.1.7 returns "Bad token for connection." 

/usr/local/ncpa/var/log/ncpa_listener.log returns status code **308** 

`2019-05-10 14:14:29,267 12550 INFO ::ffff:192.168.16.129 - - [2019-05-10 14:14:29] "GET /testconnect?token=pkTAR@1rAxl9 HTTP/1.0" 308 548 0.001440`

Running check_ncpa.py from commandline is doing fine.

2)
Another thing to check is handling passwords with special characters. Running NCPA wizard using a custom variable like
`$USER6$=pkTAR~1#^@`
is logged as
(..)` "GET /testconnect?token=pkTAR~1 HTTP/1.0" 308 533 0.001461`

Commandline is doing fine using this password (quoted or unquoted).

**Comment by jomann09** [comment]
The wizard looks like it doesn't use urlencode() on the token which is probably the issue. I'll test it internally and will get a fix out sometime today.

**Comment by jomann09** [comment]
This is uploaded and fixed btw!

**Comment by jvandermeulen** [comment]
@jomann09 I'm afraid you have to reopen this case. Encoding may be fixed in Config Wizard v2.0.5, however still receiving **308**s when using wizard on NCPA v2.1.7 installs.

Problem is reproducible in version 2.17 only. Version 2.16 is doing fine redirecting (code **301**) resulting in **200** http response.

NCPA wizard still uses HTTP 1.0 connnection, so I suggest to reproduce it using this curl command 
 `curl -k  "https://192.168.122.107:5693/testconnect?token=demotoken" --http1.0`

On NCPA client side 'ncpa_listener.log' logs this

```
[root@ncpa_client log]# grep testconnect ncpa_listener.log
2019-05-13 21:19:09,378 21903 INFO 192.168.122.102 - - [2019-05-13 21:19:09] "GET /testconnect?token=demotoken HTTP/1.0" 308 542 0.005989
[root@ncpa_client log]# rpm -q ncpa
ncpa-2.1.7-1.el7.x86_64
```

After downgrading 'yum downgrade ncpa-2.1.6-1.el7'..

```[root@ncpa_client log]# grep testconnect ncpa_listener.log
2019-05-13 21:21:16,709 22420 INFO 192.168.122.102 - - [2019-05-13 21:21:16] "GET /testconnect?token=demotoken HTTP/1.0" 301 541 0.005120`
`[root@ncpa_client log]# rpm -q ncpa
ncpa-2.1.6-1.el7.x86_64
```

**Comment by jomann09** [comment]
Oh it looks like that's because you're going to `https://192.168.122.107:5693/testconnect?token=demotoken` and the client redirects you to `https://192.168.122.107:5693/testconnect/` with the ending forward slash. If you make the connection with the forward slash it has no problems. The actual redirection must be something built into flask I think I can add the version without the forward slash though and they will both go to the same place and not do a redirect.

**Comment by jomann09** [comment]
I added a fix for this in the next version.

**Comment by jvandermeulen** [comment]
@jomann09 Thanks for creating this NCPA pre-2.18 fix.
What about updating the wizard also? It's the  **XI wizard** that addresses the URL without trailing slash, I was only reproducing the error by looking in the ncpa_listener.log to see what URL was used by the wizard.
Another question: check_ncpa is using HTTP 1.1 while NCPA wizard is using HTTP 1.0. Is that on purpose?

**Comment by jomann09** [comment]
I've updated the NCPA wizard to use the forward slash so it doesn't cause the 308 in the logs. The reason the wizard is using HTTP 1.0 is because it's using an internal PHP function to make the request and that happens to be the version it uses.

**Comment by jvandermeulen** [comment]
Did you bump the version Jake? Checked for updates under "Manage Configuration Wizards" but still at version 2.0.5
![afbeelding](https://user-images.githubusercontent.com/838001/57723782-a3aafd00-7689-11e9-8c0e-327f911cce84.png)

**Comment by jomann09** [comment]
Sorry it takes up to 12 hours to sync but I manually synced it, should show up if you click check for updates now.

**Comment by jvandermeulen** [comment]
Thanks, works as expected now!
