### ISSUE TITLE
Repo Installlation 2.1.7

### ISSUE THREAD

**Issue by timcanty** [NagiosEnterprises/ncpa#537]
Currently trying to upgrade to the newest version, however the information on https://www.nagios.org/ncpa/#downloads seems to be incorrect now as the repo's seem to have been moved, but the documentation hasn't been updated.

In the instructions for ubuntu  it says the following:
Add the following into /etc/apt/sources.list.d/nagios.list:
deb https://repo.nagios.com/deb/ubuntu /

However that prompts with the error : The repository 'https://repo.nagios.com/deb/ubuntu  Release' does not have a Release file.

From a bit of digging around this repo seems to have been moved as I believe for 18.04 it is now https://repo.nagios.com/deb/bionic ? according to https://repo.nagios.com/?repo=deb-ubuntu

However if i try use the new location, I get the following (The repository 'https://repo.nagios.com/deb/bionic  Release' is not signed.)

any suggestions on whats occurred, have the installation instructions changed, as this hasn't been updated on the NCPA page?

**Comment by jomann09** [comment]
I'll take a look into this, they should be signed.

**Comment by jomann09** [comment]
Updated the documentation to have the proper repos also.

**Comment by jomann09** [comment]
Closing this since I fixed the repo for Ubuntu 18!
