### ISSUE TITLE
HTTP Error 500: INTERNAL SERVER ERROR

### ISSUE THREAD

**Issue by yderi** [NagiosEnterprises/ncpa#539]
Periodically experiencing: An error occurred:HTTP Error 500: INTERNAL SERVER ERROR
NCPA Version 2.1.7
Windows Server 2016
Service check using windowscounter to retrieve a CPU performance by the process.
It is not a regular error, it happens from time to time
Here some portion from "ncpa_listener.log".
`IOError: [Errno 9] Bad file descriptor
2019-05-15 07:03:32,118:ERROR:app:Exception on /api/windowscounters/Process(MyApp.Ims)/% Processor Time/ [GET]
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\flask\app.py", line 1817, in wsgi_app
  File "C:\Python27\lib\site-packages\flask\app.py", line 1477, in full_dispatch_request
  File "C:\Python27\lib\site-packages\flask\app.py", line 1381, in handle_user_exception
  File "C:\Python27\lib\site-packages\flask\app.py", line 1475, in full_dispatch_request
  File "C:\Python27\lib\site-packages\flask\app.py", line 1461, in dispatch_request
  File "C:\ncpa\agent\listener\server.py", line 169, in token_auth_decoration
  File "C:\ncpa\agent\listener\server.py", line 927, in api
  File "C:\ncpa\agent\listener\windowscounters.py", line 39, in run_check
  File "C:\ncpa\agent\listener\windowscounters.py", line 107, in get_counter_path
IOError: [Errno 9] Bad file descriptor
2019-05-15 07:05:28,641:ERROR:windowscounters:(-2147481640, 'GetFormattedCounterValue', 'A counter with a negative value was detected.')
Traceback (most recent call last):
  File "C:\ncpa\agent\listener\windowscounters.py", line 43, in counter_method
  File "C:\ncpa\agent\listener\windowscounters.py", line 79, in get_counter_val
error: (-2147481640, 'GetFormattedCounterValue', 'A counter with a negative value was detected.')
`
Is this the same bug described here #439?

**Comment by jomann09** [comment]
No I don't believe so, this is related to the counter value that is being returned being negative, which causes the error. I haven't see this happen before.

**Comment by yderi** [comment]
Here is how command itself looks like:
`$USER1$/check_ncpa.py -H $HOSTADDRESS$ -t "$USER10$" -P 5666 -M 'windowscounters/Process($ARG1$)/Private Bytes' -w $ARG2$ -c $ARG3$ -q 'sleep=30'`

**Comment by yderi** [comment]
There is also lot of error like this:
```
IOError: [Errno 9] Bad file descriptor
2019-05-10 10:26:25,772:ERROR:app:Exception on /api/windowscounters/Process(MyApp.Gateway)/% Processor Time/ [GET]
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\flask\app.py", line 1817, in wsgi_app
  File "C:\Python27\lib\site-packages\flask\app.py", line 1477, in full_dispatch_request
  File "C:\Python27\lib\site-packages\flask\app.py", line 1381, in handle_user_exception
  File "C:\Python27\lib\site-packages\flask\app.py", line 1475, in full_dispatch_request
  File "C:\Python27\lib\site-packages\flask\app.py", line 1461, in dispatch_request
  File "C:\ncpa\agent\listener\server.py", line 169, in token_auth_decoration
  File "C:\ncpa\agent\listener\server.py", line 927, in api
  File "C:\ncpa\agent\listener\windowscounters.py", line 39, in run_check
  File "C:\ncpa\agent\listener\windowscounters.py", line 107, in get_counter_path
IOError: [Errno 9] Bad file descriptor
```

**Comment by jomann09** [comment]
I will have to test this counter and see what it's doing that it is getting that error. I think the error on the last post you made means it can't read the counter. I've never passed a process name into a counter so not sure what the restrictions might be.

**Comment by yderi** [comment]
Still experiencing the problem
Can I provide you with some more information?

**Comment by jomann09** [comment]
Does the process always exist? I am testing this on an NCPA on my system:

```
[root@nagios libexec]# ./check_ncpa.py -H 192.168.5.221 -t '' -M 'windowscounters/Process(System)/% Processor Time' -q 'sleep=5'
OK: \Process(System)\% Processor Time was 2.50 % Processor Time | '\Process(System)\% Processor Time'=2.50;;;
```

Just to verify it's not the . in the process name, can you try running it with `System`?

**Comment by jomann09** [comment]
I did also just verify that if I use a counter that doesn't exist it will output the same error you are getting above. I will adjust the output to give an unknown in the next version of NCPA also.

**Comment by kaba1ah** [comment]
I believe I started experiencing the same issue after NCPA was upgraded to 2.1.7 (I haven't had a single occurrence with 2.1.6 and below).

OS: Windows 2012 R2 Datacenter 64b and Windows 2016 Datacenter 64b

`2019-05-31 15:09:25,490:ERROR:app:Exception on /api/windowscounters/Terminal Services/Active Sessions/ [GET]`
`Traceback (most recent call last):`
`  File "C:\Python27\lib\site-packages\flask\app.py", line 1817, in wsgi_app`
`  File "C:\Python27\lib\site-packages\flask\app.py", line 1477, in full_dispatch_request`
`  File "C:\Python27\lib\site-packages\flask\app.py", line 1381, in handle_user_exception`
`  File "C:\Python27\lib\site-packages\flask\app.py", line 1475, in full_dispatch_request`
`  File "C:\Python27\lib\site-packages\flask\app.py", line 1461, in dispatch_request`
`  File "C:\ncpa\agent\listener\server.py", line 169, in token_auth_decoration`
`  File "C:\ncpa\agent\listener\server.py", line 927, in api`
`  File "C:\ncpa\agent\listener\windowscounters.py", line 39, in run_check`
`  File "C:\ncpa\agent\listener\windowscounters.py", line 107, in get_counter_path`
`IOError: [Errno 9] Bad file descriptor`

The command I'm using (from the config):

`check_ncpa!-t 'xxx' -P 5693 -M "windowscounters/Terminal Services/Active Sessions" -w 20 -c 50`

**Comment by yderi** [comment]
1. Not sure about a dot charcter in process name, because of most the time Windows counter able to query info and gives a proper output. 
2. Yes, there is deploy sometime, so the process might not exist at deployment time.
3. I'll add  the  process  "system"to monitor (so we can have some comparison)
4. Just made some more testing. When I trying to query not existing process like "test.test" (it does not exist in the process list and have a dot in a name) 
Query string is: `(/Process(test.test)/% Processor Time)`
it gives the following output:
```
{
    "perfdata": "'\\Process(test.test)\\% Processor Time'=0c;50;60;",
    "returncode": 0,
    "stdout": "OK: \\Process(test.test)\\% Processor Time was 0 c | '\\Process(test.test)\\% Processor Time'=0c;50;60;"
}
```
So there is no unknown status in this case and no "INTERNAL SERVER ERROR"
Is there any more information or action I can do to help figure out a problem?

**Comment by yderi** [comment]
After adding verbosity to check_ncpa.py additional error catch
```
Connecting to: https://172.25.4.40:5666/api/windowscounters/Process%28FabricDCA%29/%25%20Processor%20Time/?token=W-Rh%27uW%26&warning=40&critical=60&check=1&sleep=30
An error occurred:[Errno 104] Connection reset by peer
```
And another problem:
```
Connecting to: https://172.25.4.41:5666/api/windowscounters/Process%28MyApp.Gateway%29/%25%20Processor%20Time/?token=W-Rh%27uW%26&warning=40&critical=60&check=1&sleep=30
An error occurred:HTTP Error 500: INTERNAL SERVER ERROR
```
I'll post them here.

**Comment by jomann09** [comment]
@kaba1ah Is it consistent? I just tested this on the latest 2.1.7 version and am not having the issue for that counter, although I do not have a 2012 Datacenter server to test it on.

@yderi The internal server error means it had a fatal error and should be in ncpa_listener.log and if it's the same counter_path issue then I would think it's related to above. The connection reset is something that is being looked into in another issue. For some reason certain windows server versions have issues with the ncpa connections.

**Comment by jomann09** [comment]
Actually it looks like the bad file descriptor is not related to the counters, there should be a second error. The file descriptor is because there is a print statement inside that get_counter_path() function that shouldn't be there (https://github.com/NagiosEnterprises/ncpa/blob/v2.1.7/agent/listener/windowscounters.py#L107)

**Comment by yderi** [comment]
In NCPA 2.1.7 client log file "ncpa_listener.log" full of the following errors:
```
2019-06-04 09:11:04,693:ERROR:app:Exception on /api/windowscounters/Process(MyApp.Communicator)/% Processor Time/ [GET]
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\flask\app.py", line 1817, in wsgi_app
  File "C:\Python27\lib\site-packages\flask\app.py", line 1477, in full_dispatch_request
  File "C:\Python27\lib\site-packages\flask\app.py", line 1381, in handle_user_exception
  File "C:\Python27\lib\site-packages\flask\app.py", line 1475, in full_dispatch_request
  File "C:\Python27\lib\site-packages\flask\app.py", line 1461, in dispatch_request
  File "C:\ncpa\agent\listener\server.py", line 169, in token_auth_decoration
  File "C:\ncpa\agent\listener\server.py", line 927, in api
  File "C:\ncpa\agent\listener\windowscounters.py", line 39, in run_check
  File "C:\ncpa\agent\listener\windowscounters.py", line 107, in get_counter_path
IOError: [Errno 9] Bad file descriptor
```
But I cannot find an error seen on Nagios web panel (when -v flag is used for check_ncpa.py) in log file "ncpa_listener.log".

**Comment by kaba1ah** [comment]
> @kaba1ah Is it consistent? I just tested this on the latest 2.1.7 version and am not having the issue for that counter, although I do not have a 2012 Datacenter server to test it on.

It happens once/twice per day every day (random time on all servers that were upgraded to 2.1.7). I changed the loglevel to debug -- hopefully it will sched some light.

**Comment by kaba1ah** [comment]
Unfortunately loglevel = debug didn't reveal anything new. The error is the same:

`2019-06-06 00:31:23,934:DEBUG:handler:Initializing WebSocket`
`2019-06-06 00:31:23,934:DEBUG:handler:Validating WebSocket request`
`2019-06-06 00:31:23,980:DEBUG:psapi:Imported windowscounters into the API tree.`
`2019-06-06 00:31:23,980:DEBUG:psapi:Imported windowslogs into the API tree.`
`2019-06-06 00:31:23,980:ERROR:app:Exception on /api/windowscounters/Terminal Services/Active Sessions/ [GET]`
`Traceback (most recent call last):`
`  File "C:\Python27\lib\site-packages\flask\app.py", line 1817, in wsgi_app`
`  File "C:\Python27\lib\site-packages\flask\app.py", line 1477, in full_dispatch_request`
`  File "C:\Python27\lib\site-packages\flask\app.py", line 1381, in handle_user_exception`
`  File "C:\Python27\lib\site-packages\flask\app.py", line 1475, in full_dispatch_request`
`  File "C:\Python27\lib\site-packages\flask\app.py", line 1461, in dispatch_request`
`  File "C:\ncpa\agent\listener\server.py", line 169, in token_auth_decoration`
`  File "C:\ncpa\agent\listener\server.py", line 927, in api`
`  File "C:\ncpa\agent\listener\windowscounters.py", line 39, in run_check`
`  File "C:\ncpa\agent\listener\windowscounters.py", line 107, in get_counter_path`
`IOError: [Errno 9] Bad file descriptor`
`2019-06-06 00:31:23,980:INFO:handler:10.9.200.31 - - [2019-06-06 00:31:23] "GET /api/windowscounters/Terminal%20Services/Active%20Sessions/?token=xxx&warning=20&critical=50&check=1 HTTP/1.1" 500 2362 0.047000`

`2019-06-06 00:32:24,036:DEBUG:handler:Initializing WebSocket`
`2019-06-06 00:32:24,036:DEBUG:handler:Validating WebSocket request`
`2019-06-06 00:32:24,069:DEBUG:psapi:Imported windowscounters into the API tree.`
`2019-06-06 00:32:24,069:DEBUG:psapi:Imported windowslogs into the API tree.`
`2019-06-06 00:32:24,069:INFO:handler:10.9.200.31 - - [2019-06-06 00:32:24] "GET /api/windowscounters/Terminal%20Services/Active%20Sessions/?token=xxx&warning=20&critical=50&check=1 HTTP/1.1" 200 374 0.047000`
`2019-06-06 00:32:26,585:DEBUG:handler:Initializing WebSocket`
`2019-06-06 00:32:26,585:DEBUG:handler:Validating WebSocket request`
`2019-06-06 00:32:26,615:DEBUG:psapi:Imported windowscounters into the API tree.`
`2019-06-06 00:32:26,615:DEBUG:psapi:Imported windowslogs into the API tree.`

In my case, the alert will be triggered after 10 attempts, so the first attempt failed, but minute after it succeeded and then it goes quite.

Please let me know whether there is anything else I can do to get more verbose logs.

I'm experiencing those errors with both Windows 2012 R2 and Windows 2016 servers with NCPA upgraded to 2.1.7. None of the servers (~200 devices) with NCPA 2.1.6 are affected.

**Comment by jomann09** [comment]
I believe this is fixed with my change in the maint branch, if you'd like to try a test build you can download it here: https://assets.nagios.com/downloads/ncpa/dev/ncpa-2.1.8-beta.exe

**Comment by yderi** [comment]
Downloaded and installed it to one machine. Keep an eye on its logs.

**Comment by yderi** [comment]
Here is first error I get in ncpa.log for NCPA-2.1.8-beta:
```
2019-06-13 05:30:25,026:ERROR:windowscounters:(-2147481643, 'CollectQueryData', 'No data to return.')
Traceback (most recent call last):
  File "C:\ncpa\agent\listener\windowscounters.py", line 43, in counter_method
  File "C:\ncpa\agent\listener\windowscounters.py", line 76, in get_counter_val
error: (-2147481643, 'CollectQueryData', 'No data to return.')
```

**Comment by yderi** [comment]
Another portion of errors (for about 2 hours period):
```
2019-06-13 05:53:57,983:ERROR:windowscounters:(-2147481640, 'GetFormattedCounterValue', 'A counter with a negative value was detected.')
Traceback (most recent call last):
  File "C:\ncpa\agent\listener\windowscounters.py", line 43, in counter_method
  File "C:\ncpa\agent\listener\windowscounters.py", line 79, in get_counter_val
error: (-2147481640, 'GetFormattedCounterValue', 'A counter with a negative value was detected.')
2019-06-13 07:34:26,970:ERROR:windowscounters:(-2147481643, 'CollectQueryData', 'No data to return.')
Traceback (most recent call last):
  File "C:\ncpa\agent\listener\windowscounters.py", line 43, in counter_method
  File "C:\ncpa\agent\listener\windowscounters.py", line 72, in get_counter_val
error: (-2147481643, 'CollectQueryData', 'No data to return.')
2019-06-13 07:34:39,239:ERROR:windowscounters:(-2147481643, 'CollectQueryData', 'No data to return.')
Traceback (most recent call last):
  File "C:\ncpa\agent\listener\windowscounters.py", line 43, in counter_method
  File "C:\ncpa\agent\listener\windowscounters.py", line 72, in get_counter_val
error: (-2147481643, 'CollectQueryData', 'No data to return.')

```

**Comment by jomann09** [comment]
Do you have a list of the counters you are using, is it possible to see them?

**Comment by yderi** [comment]
Hello,
Yes, at the moment I am using two counters:
`Process($ARG1$)\Working Set`
and
`Process($ARG1$)/% Processor Time`
Do you require some more information?
Thank you
P.S. For the period over 24 hours I experienced only errors mentioned above.

**Comment by jomann09** [comment]
Alright thanks I will test it on my side, I am really trying to get mine to give me the negative value error. The no data returned is simple to test for. I'll add whatever is needed into 2.18 once I get these tested.

**Comment by kaba1ah** [comment]
@jomann09 thank you for the beta build.

After running it for a day and using counter `windowscounters/Terminal Services/Active Sessions` I don't get any errors anymore. I will continue monitoring though.

**Comment by kaba1ah** [comment]
@jomann09 thank you for the beta build.

After running it for a day and using counter `windowscounters/Terminal Services/Active Sessions` I don't get any errors anymore. I will continue monitoring though.

**Comment by jomann09** [comment]
Alright so doing some additional testing it looks like the counter errors/exceptions when using a non-existent counter (`No data to return.` message) only display in the log when running a check. There is a value `The data is not valid.` that means that you need to add the sleep option. Specifically it seems that the  `Process($ARG1$)/% Processor Time` one does require a `sleep` of at least 1 and also requires you to use the process name but not the .exe name.

**Comment by jomann09** [comment]
I have yet to hit the negative counter value example, but there is a `factor` option that is allowed, which might be able to convert the output.

**Comment by jomann09** [comment]
In 2.1.8 I've updated the output - however note that if you have a service and are using a counter that is specific to a running service there is going to be a possibility for NCPA to return an `UNKNOWN` because if it cannot get any data from a counter it will return as such. If it returns a 0 it will return a 0 though.

**Comment by yderi** [comment]
Hello 
Where I can download version 2.1.8 from?
