### ISSUE TITLE
Windows Process Information Auth Issues

### ISSUE THREAD

**Issue by scot0357** [NagiosEnterprises/ncpa#54]
Windows processes and psutil don't seem to be getting along. There are varying issues that have been band-aided but we need to find a way to read Windows processes and get meaningful results.

Previous discussion was here https://github.com/NagiosEnterprises/ncpa/commit/cfaf1922337928d6301310d91a21145bd6562008.

**Comment by jhomann** [comment]
I believe that #230 may be related to this and will maybe help with our issues with win processes and not being able to access them all.

**Comment by jomann09** [comment]
This should not be a problem anymore.
