### ISSUE TITLE
ncpa agent 2.1.7 issues HTTP error 308?

### ISSUE THREAD

**Issue by jj29** [NagiosEnterprises/ncpa#540]
Having issue with generating conf file when using check_ncpa 1.1.3 and agent 2.1.7(on target host)

Using adhoc as certificate value in ncpa.cgf on target host. 
When I try below fails with 
`#./check_ncpa.py -H target_host -t token -l `
An error occurred:HTTP Error 308: PERMANENT REDIRECT

But check for ncpa version or any other like disk,cpu all works. 
`#check_ncpa -H target_host  -t toekn  -M 'system/agent_version'`
OK: Agent_version was ['2.1.7']

I have self signed certi in /var/ncpa.crt and .key. I also tried below and -S 2 and  3 but same error.
`check_http -I target_ip -S 1`
connect to address target_ip and port 443: Connection refused

I have other server which also have 443 closed but I can still connect to them to check services using ncpa.  

ps I am new to nagios so happy to learn more with proper guidance :)

**Comment by jomann09** [comment]
Are you trying to manually set the cert/key file? Or are you just asking about the initial 308 error? What host is the agent (ncpa) installed on?

**Comment by jj29** [comment]
First of all thanks for the reply and sory for confusions.

I didn't try setup key/crt file manually, I am using certificate= adoc in ncpa.cfg on target host(ubuntu 16.04)
Using crt/key which ncpa agent installs.

We have script that generates cfg file for the host, first it List all values under a given node. Using -l as mentioned above and if it gives value than it will check that and make cfg file. What happening here is, it cant even get the output. When using that command 
`check_ncpa -H target_ip  -t my-token -l  -v` gives error
Connecting to: https://target_ip:port/api?units=B&token=my-token ( I can get to this link using browser without issue but not being able to using check_ncpa 1.1.3 and being ncpa agent 2.1.7)
An error occurred:HTTP Error 308: PERMANENT REDIRECT.
And this what record on target_host ncpa_listener logs 
"GET /api?units=B&token=my-token HTTP/1.1" 308 531 0.001103

Same happens on ubuntu 18.04 with ncpa 2.1.7

I have other old hosts with old ncpa like 2.1.4 and some even 2.1.3 and for those hosts `check_ncpa -H target_ip  -t my-token -l  -v` and I get  
File returned contained: and all its output.

I need help getting to why I am getting 308 with ncpa agent 2.1.7 

Thanks

**Comment by tgriep** [comment]
I was able to recreate the 308 Redirect issue running NCPA version 2.1.7 on Oracle Linux Server release 6.10

Running version 1.1.5 of the check_ncpa plugin.

/usr/local/nagios/libexec/check_ncpa.py -H 192.168.3.174 -t 'ncpapass' --list -v
Connecting to: https://192.168.3.174:5693/api?token=ncpapass
An error occurred:HTTP Error 308: PERMANENT REDIRECT


ncpa_listener.log
2019-06-11 10:37:08,152 13614 INFO stopped
2019-06-11 10:37:08,717 13646 INFO started
2019-06-11 10:37:08,718 13646 INFO Using SSL version TLSv1_2
2019-06-11 10:37:36,059 13646 DEBUG Initializing WebSocket
2019-06-11 10:37:36,060 13646 DEBUG Validating WebSocket request
2019-06-11 10:37:36,064 13646 INFO ::ffff:192.168.5.223 - - [2019-06-11 10:37:36] "GET /api?token=ncpapass HTTP/1.1" 308 490 0.004476

**Comment by jomann09** [comment]
I've fixed this globally not just for testconnect like in #535
