### ISSUE TITLE
Silent upgrade of NCPA Agent on Windows

### ISSUE THREAD

**Issue by Guyver1wales** [NagiosEnterprises/ncpa#548]
I currently have 2.1.7 installed on a batch of servers.

I want to upgrade them to the new 2.1.8.

Is it enough to just run ncpa-2.1.8.exe /S
without any additional arguments and the installer will simply upgrade the agent and keep all the current settings in the ncpa.cfg file?

I just want to make sure before I start writing my PowerShell script to auomate this.

**Comment by jomann09** [comment]
Yes the silent install will just run the upgrade the same way it does from the full installer. I actually did just test it just to make sure it wouldn't cause any issues.

**Comment by Guyver1wales** [comment]
Thanks very much! 👍😁
