### ISSUE TITLE
ARM7 build

### ISSUE THREAD

**Issue by omnitec** [NagiosEnterprises/ncpa#549]
We would like to convert our ARM7 devices to NCPA, .. has anyone ever done a Raspbian build?

**Comment by ericloyd** [comment]
No, but we could do so.  I can't imagine it would fail, given that it's primarily Python driven.

**Comment by jomann09** [comment]
Working on this, there is a build tutorial in issue #477 but it may or may not work with the new versions and it probably certainly won't work with NCPA 3.

**Comment by jomann09** [comment]
Added a build for Raspbian (buster) to the official builds. Also, build.sh should work now on a clean system.
