### ISSUE TITLE
Silent upgrade of NCPA Agent on Windows does not replace the previous version

### ISSUE THREAD

**Issue by slowbrowse** [NagiosEnterprises/ncpa#551]
I'm currently using NCPA 2.1.6 and when testing a silent upgrade to NCPA 2.1.8 the previous version is not replaced, leaving both old and new versions listed in Programs and Features.

I used the `ncpa-2.1.8.exe /S` command.

![image](https://user-images.githubusercontent.com/50610197/61851988-9fd0fd80-aeb8-11e9-8935-496df1751b8c.png)

If I run a non-silent install and choose "Anyone using this computer" the same thing happens, both entries can be seen in the Program list, but choosing "Install just for me" gives the expected result of only the new version in the Program list. 

It seems the per-user installation context of version 2.1.6 is not changed during the per-machine upgrade process to version 2.1.8.

Is there a safe way to upgrade to version 2.1.8 (per-machine) without first removing 2.1.6 (per-user)?

Thanks in advance.

**Comment by jomann09** [comment]
I see that happening on mine too, it does not check on upgrade whether or not to remove the old version of the registry key so essentially it'll just stay there until deleted. You can delete it manually by running:
```
reg delete HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Uninstall\NCPA
```
as the user who installed it - and I will take a look at fixing this with the next upgrade.

**Comment by slowbrowse** [comment]
Great, many thanks for your efforts.

**Comment by jvandermeulen** [comment]
@jomann09 Did you fix this issue @slowbrowse raised here? One of my customers updated NCPA (per-machine) from v2.1.8 to 2.1.9 and after upgrade only 2.1.9 was listed.

**Comment by jomann09** [comment]
@jvandermeulen The exact issue that causes this has not been fixed yet. There shouldn't be an issue for people who didn't have the Uninstall key in the wrong place to begin with, so if they are using 2.1.8+ there should not see a duplicate.
