### ISSUE TITLE
Feature Request to run the os commands using NCPA agent

### ISSUE THREAD

**Issue by ranjithkodumbu** [NagiosEnterprises/ncpa#552]
Hi Team,

Could you please add a feature to run Operating System commands using NCPA, so that we can grab the output compare whether string/value matches and trigger an alert.

For e.g. ./check_ncpa.py -H 10.25.14.91 -t Str0ngT0k3n -M 'cmd' -a 'tail -10 /var/log/messages | grep nagios | wc -l' -desc 'nagioscontentmatch' -value -w 10 -c 15
CRITICAL: Current value for nagioscontentmatch is 16 | nagioscontentmatch=16;10;15;0;

if possible please add following arguments as well so that we can run any commands in any operating system and enable custom monitoring.

-M for calling as 'cmd'   : -M option already existing in NCPA, we need to add additional parameter to call commands, you can define any logical name for the same, something like 'cmd'

-desc : for custom description to identify the command for what it was executed for and same will be updated when there is in alert.

-value : whether custom command output is numerical, if it is numerical then need to check warning and critical threshold and alert when it breaches the threshold. We also need to consider when value is less than the threshold alert something like this option -w :15 -c :10.

--string-match : This option for matching the content in which os commands returns. If that content matches with this switch need to alert 

e.g. ./check_ncpa.py -H 10.25.14.91 -t Str0ngT0k3n -M 'cmd' -a 'tail -10 /var/log/messages | grep nagios | cut -d',' -f2' -desc 'varlogmsg' --string-match 'nagios' --critical
CRITICAL: String 'nagios' contains in the cmd output of ' /var/log/messages | grep nagios | cut -d',' -f2''

--string-negate : This option is for when the command output doesn't contain the string passed for this parameter need to alert.

e.g.  ./check_ncpa.py -H 10.25.14.91 -t Str0ngT0k3n -M 'cmd' -a 'tail -10 /var/log/messages | grep nagios | cut -d',' -f2' -desc 'varlogmsg' --string-negate 'nagios' --critical
CRITICAL: String 'nagios' doesn't exist in the cmd output of ' /var/log/messages | grep nagios | cut -d',' -f2''

I know that above mentioned feature request is quite challenging to achieve. But if we can achieve this can enable any monitoring without adding the plugins in the target node also can run in any OS where NCPA agent is running.

Thank you,
Ranjith Kumar R

**Comment by ericloyd** [comment]
I think this violates the "Cross Platform" part of the agent, as it stands today. Windows systems won't have Unix commands and vice versa.  So if you're going to send commands that are OS-specific, then you might as well distribute a plugin that does the work and then call the NCPA using the same parameters without regard for OS and make the plugin OS-specific.

In other words, checking memory should be ./check_ncpa.py <stuff>-M "check_memory" -w 10 -c 15 and the "check_memory" plugin would know how to check Windows memory or Unix memory or VMS memory or whatever.

**Comment by ranjithkodumbu** [comment]
Hi Ericloyd,

Yes, I agree. What I meant was, no need to handle OS specific commands in NCPA. But need to provide a mechanism to run OS commands using NCPA. 

e.g. ./check_ncpa.py -H 10.25.14.91 -t Str0ngT0k3n -M 'cmd' -a 'tail -10 /var/log/messages | grep nagios | cut -d',' -f2' -desc 'varlogmsg' --string-negate 'nagios' --critical

here "'tail -10 /var/log/messages | grep nagios | cut -d',' -f2' -desc 'varlogmsg'" part should take care by end user/nagios admin, I meant commands can be anything related to that particular OS. If particular command doesn't exist in that OS should trigger the error.

If it is through windows, then commands need to execute through powershell/cmd and for Linux bash/shell etc similarly for other OS.

I hope you understood what I meant.

**Comment by ericloyd** [comment]
I understand what you're asking for.  I still think it's a bad idea.  Being able to execute arbitrary commands on a server via NCPA is not a good thing, in general.

Consider this - someone breaks into your Nagios server.  Now they have the ability to execute any command they want on your server.  If the commands are limited to a pre-configured (and pre-distributed) set of plugins, the worst they could do is execute one of the plugins instead.

So I think that if you want the output of your tail...grep...cut command via NCPA, then write a one-line shell script, call it a custom plugin, and distribute it to your NCPA clients.  Then call it via the NCPA plugin method.  

This maintains overall security and eliminates the chance that malicious commands could be executed via your Nagios server over NCPA.

**Comment by ranjithkodumbu** [comment]
Hi Ericloyd,

I absolutely agree with you, we need to enhance the security standards to enable this. may be exclude the commands which is vulnerable to the server and enable only read-only commands etc. If you think that it is not possible, then you can drop since it is not good idea as per you.

Regards,
Ranjith Kumar R

**Comment by ericloyd** [comment]
Again, this is my opinion, but there already exists a method to be able to execute server commands - it's called custom plugins.  If you're already distributing an NCPA config file, then you can also distribute custom plugins, and there is no need to make any changes to NCPA at all in that case.

**Comment by ranjithkodumbu** [comment]
Yes, I agree. But currently NCPA doesn't provide an option to upload the plugins and for custom requirement need to develop custom plugins, by enabling the option I have proposed will help to achieve without plugin development. You can take a call whichever is appropriate to you.

Thank you for your time.

Regards,
Ranjith Kumar R

**Comment by ericloyd** [comment]
If you have NCPA running on a host, then you have installed an NCPA configuration file on that host.  So you have the ability to add files to that host.  Just add your custom plugins to the host, and you're all set.

Occam's Razor suggests that the easiest approach is to manage the custom plugins on the remote host rather than introduce complexity to the NCPA protocol.

**Comment by ranjithkodumbu** [comment]
You are talking about the environment where Nagios team will have full access to the servers. Think about enterprise customers where each task will be performed by different team.
OS managed by platform team, Nagios agents etc and Nagios Admins will not have any control over endpoint, every time they need to relay on Platform team. for copying plugins/permissions etc

**Comment by ericloyd** [comment]
At some point though, the NCPA configuration file has to be able to be updated to keep API keys in sync with the Nagios server.  If that is the case, then there should be no reason why the server admin team can't put the custom plugins in place that Nagios needs to do its job.

We have large Enterprise teams doing this very thing today.  I feel that adding the ability to implement any command via NCPA on your servers is going to make the server administration and security teams much more nervous than simply adding a file for a custom plugin.

**Comment by ranjithkodumbu** [comment]
Ok, You can close this topic now. Thank you for your time and comments.

**Comment by ericloyd** [comment]
To be clear - these are my opinions.  Someone from Nagios may have other opinions.  :-)

**Comment by jomann09** [comment]
I didn't chime in here earlier but I will close this. I agree with @ericloyd in that it would be bad to allow people to run arbitrary commands via the API, due to the fact that sometimes the daemon can be running as root (typically nagios though) and it would definitely be a security issue.

That being said, if you really wanted to, you could make a plugin that would basically allow you to run a command sent to it and return the values - which I wouldn't recommend but could be done.

**Comment by ranjithkodumbu** [comment]
If could be done, you can disable this option by deafult, whoever like to use can use this option. By doing this can achieve lots of things. I agree that there is a Security issue, that part should be handled by whoever is using this option.

**Comment by ericloyd** [comment]
It could be done.  But introducing a security hole that people then have to worry about closing is not good programming.  Instead, make a custom plugin that you pass your commands to and have it execute it for you as @jomann09 suggested.  This way, nothing has to change on NCPA itself and you can run your system commands as you see fit.
