### ISSUE TITLE
check_ncpa.py (Return code of 13, out of bounds) on epel repo nagios install on CentOS 7

### ISSUE THREAD

**Issue by Guyver1wales** [NagiosEnterprises/ncpa#557]
rather than re-type a lot of text, please see my thread on the nagios support forums here:
https://support.nagios.com/forum/viewtopic.php?f=7&t=55124&p=289843#p289843

Summary:
brand new CentOS 7 install
epel repo installed
nagios and nagios-plugins-all installed

https://assets.nagios.com/downloads/ncpa/check_ncpa.tar.gz  <<-- broken (file size incorrect)

Fixed using used a known working check_ncpa.py from my other nagios server installed from source.

./check_ncpa.py works from command line when run as both root and nagios users.

when run via the commands configured in commands.cfg, returns:
(Return code of 13 for service <service name> on host <hostname> was out of bounds)

**Comment by jomann09** [comment]
The issue seems to be the Windows line endings in that file, I've uploaded a new working tarball with the check_ncpa.py with Unix line endings and should fix both the issues.

**Comment by Guyver1wales** [comment]
Thanks, I just wiped that vm away and spun up a new one and did a fresh epel repo installation and ncpa is now working against my clients as expected.

cheers, this can now be closed.
