### ISSUE TITLE
Usage win32pdh.AddEnglishCounter instead win32pdh.AddCounter

### ISSUE THREAD

**Issue by ravenich** [NagiosEnterprises/ncpa#558]
Enhancement request:
Usage of win32pdh.AddEnglishCounter instead win32pdh.AddCounter for windows counters.
win32pdh.AddCounter use a internationalized version counter. This is really uncomfortable to use with multilanguage enviroment.
Example, for russian system i need to create query with russian localized counters, for english, with englesh counters, etc.

**Comment by jomann09** [comment]
This sounds like a good idea, I would agree it'd be best if it was standardized on all systems no matter what the language is on the system.

**Comment by jomann09** [comment]
I've set this in 2.2.0 thanks again for the suggestion!
