### ISSUE TITLE
Walking the NFS Directories

### ISSUE THREAD

**Issue by dbcummings** [NagiosEnterprises/ncpa#559]
This is related to closed bug "NCPA "no such file or directory" error #523".

While the NCPA listener and passive service start and ignore OSErrors on NFS connection errors, they still "climb" all of the LDAP directories that cannot be connected to because of permissions. This causes the agent to timeout when there are hundreds of failed NFS connections. The agent needs to allow for the exclusion or ignoring of certain directory structures potentially through the use of REGEX or some other method. This is a critical issue preventing installation of the agent.  NFS is included in exclude_fs_types but that isn't preventing the problem.

**Comment by jomann09** [comment]
What kind of fstype does it show when you try to list them normally from the API? If you can't, then do you have a RHEL system with python on it that you can install psutils on to test running the psutil command manually? The way we grab the disk partitions is by using https://psutil.readthedocs.io/en/latest/#psutil.disk_partitions with `all=True` set, which includes all file system partitions it can find. It only checks if it can see the directory if it does not match any of the excluded fs types in the list. 

Here is the location this happens at: https://github.com/NagiosEnterprises/ncpa/blob/master/agent/listener/psapi.py#L181

**Comment by dbcummings** [comment]
Jake,

Is there a way for us to set this to false so that it reads only physical drives?

DB

**Comment by dbcummings** [comment]
Is there a way for us to set this to **false** so that it reads only physical drives?

**Comment by dbcummings** [comment]
Looks like it is in psapi.py.

**Comment by jomann09** [comment]
If you were okay with not seeing mountpoints it can be set to false, although we will have to make it an option that can be adjusted.

**Comment by dbcummings** [comment]
We may be. What would be the impact? How quickly could we get a new version?

**Comment by jomann09** [comment]
The impact is that you would only discover local/physical drives instead when it is set to false.

> Would this prevent us from deploying monitoring to a mounted drive that isn't "seen"?

It would not allow you to run a disk usage check on any mount points besides physical drives. Is that what you mean?

If the only change is adding an option into ncpa.cfg and build a 2.1.9-1 pre-release version we can do that in the next few days (there would be no problem updating this in the future to the actual 2.1.9 version).

**Comment by dbcummings** [comment]
If you could make that package available, where it could be controlled from a configuration file, that would be great.

**Comment by dbcummings** [comment]
When will the pre-release be available to test it?

**Comment by dbcummings** [comment]
Do you know when the new package will be available?

**Comment by jomann09** [comment]
Yesterday was a holiday so I am building today, I'll let you know once the main ones are built since things like AIX/Solaris can take a couple of extra days

**Comment by jomann09** [comment]
Here's the ones that will be on the site tomorrow:
CentOS/RHEL 7: https://assets.nagios.com/downloads/ncpa/ncpa-2.1.9.el7.x86_64.rpm
CentOS/RHEL 6: https://assets.nagios.com/downloads/ncpa/ncpa-2.1.9.el6.x86_64.rpm
