### ISSUE TITLE
Problem with windowscounters and v2.1.9

### ISSUE THREAD

**Issue by numj** [NagiosEnterprises/ncpa#564]
The following query works in v2.1.4 but never returns a value in v2.1.9 (_3 circles keep spinning_) :

**https://servername:5693/api/windowscounters/Database(LSASS)/Database Cache Size (MB)**

![ScreenCapture](https://user-images.githubusercontent.com/33135052/64352859-bd6ea800-cfca-11e9-8ab3-ad2aa42edec5.png)

Suggested example query works : **/TCPv4/Connections Active**
![SuggestedExample](https://user-images.githubusercontent.com/33135052/64352995-f73fae80-cfca-11e9-962c-595a406edd6c.png)

As far as I can tell, it doesn't like **/Database(LSASS)**

**Comment by jomann09** [comment]
There were some changes made to windows counters in 2.1.7 and 2.1.8 to fix some issues, can you check your ncpa_listener.log and verify that it's not giving out any errors?

**Comment by numj** [comment]
Here's what I have in my ncpa_listener.log file :

Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\flask\app.py", line 1817, in wsgi_app
  File "C:\Python27\lib\site-packages\flask\app.py", line 1477, in
full_dispatch_request
  File "C:\Python27\lib\site-packages\flask\app.py", line 1381, in
handle_user_exception
  File "C:\Python27\lib\site-packages\flask\app.py", line 1475, in
full_dispatch_request
  File "C:\Python27\lib\site-packages\flask\app.py", line 1461, in
dispatch_request
  File "C:\ncpa\agent\listener\server.py", line 173, in
token_auth_decoration
  File "C:\ncpa\agent\listener\server.py", line 934, in api
  File "C:\ncpa\agent\listener\windowscounters.py", line 40, in run_check
  File "C:\ncpa\agent\listener\windowscounters.py", line 138, in
get_counter_path
IndexError: list index out of range
2019-09-05 15:03:14,724:ERROR:app:Exception on
/api/windowscounters/Database(LSASS)/Database Cache Size (MB)/ [GET]


I have attached a copy of the log file with this message.  Thanks!

Jean

**Comment by jomann09** [comment]
I believe this is an issue with the ( and ) in the counter, maybe having two sets. Are there any other counters that have this issue? I'm going to try re-creating it here and hopefully get a fix for the next version.

**Comment by jomann09** [comment]
This should be fixed in maint branch, I can build a testing version if you'd like to test it out.

**Comment by numj** [comment]
Yes, that would be great. Thanks!

Jean

**Comment by jomann09** [comment]
Here's a beta build if you'd like to try out the changes: https://assets.nagios.com/downloads/ncpa/dev/ncpa-2.1.10.beta.exe

**Comment by numj** [comment]
Hi Jake!

Sorry for the long delay, I was away from the office for a while.

I know you closed this issue but I wanted to let you know that I tried the
2.1.10 beta version on 4 servers and the issue has been resolved.

Thanks!

Jean

**Comment by jomann09** [comment]
Thank you for letting us know!
