### ISSUE TITLE
Perfdata field contains incomplete data at disk checks in verbose mode

### ISSUE THREAD

**Issue by ccztux** [NagiosEnterprises/ncpa#570]
The field stdout contains all datasets of perfdata, but the field perfdata contains only one dataset:
```bash
09:00:20 [root@localhost]:~/nagios_plugins/check_ncpa$ python3.7 ./check_ncpa.py -H localhost -t 'mytoken' -M 'disk/logical/C:|' -v
Connecting to: https://localhost:5693/api/disk/logical/C%3A%7C/?token=mytoken&check=1
File returned contained:
{
	"perfdata": "'used_percent'=77.10%;;;",
	"returncode": 0,
	"stdout": "OK: Used disk space was 77.10 % (Used: 182.81 GiB, Free: 54.15 GiB, Total: 236.96 GiB) | 'used'=182.81GiB;;; 'free'=54.15GiB;;; 'total'=236.96GiB;;;"
}
```

**Comment by jomann09** [comment]
This also happens in the interface endpoint and is related to how NCPA generates the perfdata/stdout

**Comment by jomann09** [comment]
Looking into this the perfdata field shouldn't even be sent out. It's used internally to determine what should be in the perfdata (after the | symbol) in stdout. I've updated it in 2.1.10 so that it does not show the perfdata value in the JSON output at all.

**Comment by jomann09** [comment]
One more update, this'll be in 2.2.0 which will be the next version now since we have quite a few enhancements going into it.
