### ISSUE TITLE
AIX - Add other AIX versions to os_compat

### ISSUE THREAD

**Issue by ssaxnagios** [NagiosEnterprises/ncpa#571]
Please add the other AIX versions to the os_compat line in /opt/freeware/lib/rpm/rpmrc on the build system you don't need to use --ignoreos option

os_compat: aix7.1: aix6.1 aix6.0 aix5.3 aix5.2 aix5.1 aix5.0 aix4.3

**Comment by jomann09** [comment]
I've added aix7.2 to the list, the os_compat line in the rpmrc for aix7.1 is already set to the above list of versions.
