### ISSUE TITLE
Please set registry product_id to enable automated installation via Ansible win_package module

### ISSUE THREAD

**Issue by cieslicki** [NagiosEnterprises/ncpa#579]
In order to leverage the "most Ansible" automated install of NCPA, we would use the win_package module. This module looks for the product_id in the registry to determine if the package is already currently installed. NCPA does not set this value at the moment.

https://docs.ansible.com/ansible/latest/modules/win_package_module.html#parameters

**Comment by jomann09** [comment]
Adding this in the next release, NSIS says to add ProductID (https://nsis.sourceforge.io/Docs/AppendixD.html) when we make the key and we should be setting it to a GUID. For WIX (when we move) https://wixtoolset.org/documentation/manual/v3/howtos/general/generate_guids.html is the same ProductID from what I can tell.

**Comment by jomann09** [comment]
Added for next release.
