### ISSUE TITLE
Physical Disk API Enpoint data points are cumulative, not live points in time

### ISSUE THREAD

**Issue by Guyver1wales** [NagiosEnterprises/ncpa#582]
So I was hoping to get 'live' data points for my disks such as read time/ms, writetime/ms etc which you have, but looking at the actual api via the gui, all the physical disk outputs are cumulative which isnt very useful at all :(

`{
    "PhysicalDrive0": {
        "read_time": [
            171571,
            "ms"
        ],
        "read_bytes": [
            319.67,
            "GiB"
        ],
        "write_count": [
            20957767,
            "c"
        ],
        "write_time": [
            22706,
            "ms"
        ],
        "write_bytes": [
            292.28,
            "GiB"
        ],
        "read_count": [
            13033944,
            "c"
        ]
    }
}`

run as a nagios check:
`{
    "perfdata": "'read_time'=171571ms;;;",
    "returncode": 0,
    "stdout": "OK: Read_time was 171571.00 ms | 'read_time'=171571ms;;;"
}`

this is unusable as check sadly as its not a live 'snapshot' of the disk access time.

is this something that can be modified?
Its not so much of an issue on windows servers as I can use the windowscounters option isntead and grab the relevant disk counters, but I cant do anything with my linux servers in terms of disk performance.

**Comment by ericloyd** [comment]
I'm not looking at the API right now, but if there is a Delta box for these endpoints, that will do what you want.

**Comment by Guyver1wales** [comment]
OMG how did I miss the delta button :(
sorry, yeah thats exactly what wanted. 
This can be closed
