### ISSUE TITLE
delta bug

### ISSUE THREAD

**Issue by Guyver1wales** [NagiosEnterprises/ncpa#583]
these are the automated check_ncpa.py outputs from the API gui for the given disk checks:
read-time/ms
-M 'disk/physical/PhysicalDrive0/read_time' --delta=1

read-bytes/KB
-M 'disk/physical/PhysicalDrive0/read_bytes' -u k --delta=1

write-time/ms
-M 'disk/physical/PhysicalDrive0/write_time' --delta=1

write-bytes/KB
-M 'disk/physical/PhysicalDrive0/write_bytes' -u k --delta=1

when actually putting these into Nagios XI and nagios core (repo installation on Centos 7) they will error stating delta does not take an input (I should have written down the exact error message sorry).
To be clear, nagios does not error when doing preflight checks, the error will show up in the webadmin website as a service error.

The correct syntax which did work is:
read-time/ms
-M 'disk/physical/PhysicalDrive0/read_time' --delta

read-bytes/KB
-M 'disk/physical/PhysicalDrive0/read_bytes' -u k --delta

write-time/ms
-M 'disk/physical/PhysicalDrive0/write_time' --delta

write-bytes/KB
-M 'disk/physical/PhysicalDrive0/write_bytes' -u k --delta

**Comment by jomann09** [comment]
This makes sense, no problem on the error output. It' due to `check_ncpa.py` not accepting a value for `--delta` so that's why it's complaining. I'll fix the API gui to give the proper command.

**Comment by jomann09** [comment]
This is fixed for the next version. Thanks again!
