### ISSUE TITLE
Windows Logs check_ncpa.py output not complete

### ISSUE THREAD

**Issue by Guyver1wales** [NagiosEnterprises/ncpa#595]
![ncpa_windows-logs](https://user-images.githubusercontent.com/22168798/69161813-9dd41f80-0ae3-11ea-84b6-6027ec415234.png)

"Run as Nagios check" option doesnt appear to provide the complete output for the criteria I have selected.

NCPA v2.2.0

**Comment by Guyver1wales** [comment]
![ncpa_windows-logs2](https://user-images.githubusercontent.com/22168798/69162211-3074be80-0ae4-11ea-9dd9-7ebcd538d7ab.png)

Your example also doesnt appear to include the complete parameters either.

**Comment by jomann09** [comment]
This is definitely not pulling everything, will get this fixed.

**Comment by jomann09** [comment]
Added in 2.2.1 which should be out soon.
