### ISSUE TITLE
Missing service behaviour - single service check

### ISSUE THREAD

**Issue by SheffSix** [NagiosEnterprises/ncpa#601]
Similar, but not exactly the same, to the previous issue I posted regarding missing services.

When checking for a single service, and it does not exist on the server. The check returns UNKNOWN as expected, but the output is unuseful.

Example:
`%HOSTNAME%|<service name> = services?service=NotAService&status=running`

Returns:
`{
    "returncode": 3,
    "stdout": "UNKNOWN: No services selected with 'service' value given"
}`

My issue here is the output does not tell me what service is was looking for. Should it not return instead:
`{
    "returncode": 3,
    "stdout": "UNKNOWN: No services selected with 'NotAService' value given"
}`
?

NCPA 2.2.0
Tested on Windows Server 2012 R2, Server 2016, and Ubuntu Server 16.04

**Comment by jomann09** [comment]
This is also fixed in 2.2.1 and will return UNKNOWN (as well as if any services are not found in a group of services, even if some are running etc)
