### ISSUE TITLE
memory/swap includes memory/virtual on Windows

### ISSUE THREAD

**Issue by akrivulya** [NagiosEnterprises/ncpa#607]
It seems on windows with 2.2.0 agent _memory/swap_ includes _memory/virtual_.

![image](https://user-images.githubusercontent.com/60314384/73134067-8a40ba00-403a-11ea-9ce6-0ef4ee6385cc.png)

Size of pagefile.sys on this server is 28Gb, while according to agent swap memory is 219Gb
Services defined as:
```
%HOSTNAME%|SWAP = memory/swap --warning 60 --critical 80 --units Gi
%HOSTNAME%|MEM = memory/virtual --warning 80 --critical 90 --units Gi
```

**Comment by jomann09** [comment]
The swap and virtual memory should match what psutils shows, here's how the explain the way swap/virtual memory works on Windows and Linux https://psutil.readthedocs.io/en/latest/#memory

**Comment by akrivulya** [comment]
Correct me if I wrong. Virtual memory is physical memory plus swap. But not opposite. This is systeminfo's output from that server:

![зображення](https://user-images.githubusercontent.com/60314384/73327988-bdfd2900-4260-11ea-94bd-a8a50c8cf6fe.png)

**Comment by jomann09** [comment]
So `memory/virtual` in NCPA is the "physical memory" line, and the `memory/swap` is the virtual memory line in Windows. These endpoints were named after the `psutil` functions, which don't have a physical + swap version. We have an enhancement request for NCPA 3 (#497) where we will be changing `memory/virtual` to `memory/physical` although it'll remain available for backwards compatibility.
