### ISSUE TITLE
Change to svcs -a output in Solaris 11.4

### ISSUE THREAD

**Issue by HunnyPuns** [NagiosEnterprises/ncpa#610]
The output of svcs -a changed in Solaris 11.4. Going off of the OpenSolaris man page for svcs, it looks like the STIME field was date,time if the service was started less than 24 hours prior. Where time would be 24 hour time, with an underscore (_) standing in place of blanks. So 9:30:15 becomes _9:30:15. This means that date and time would butt up against each other, and line.split() would come back with 3 fields. Happiness.

Now from what I can tell, Solaris is printing the time beyond 24 hours after the service started. They're also using a space instead of an underscore. So now line.split() will return 4 fields for any service started before 10:00:00. And because the rest of the script is not set to handle 4 fields, the output shows "time": "status", rather than "service": "status"

**Comment by jomann09** [comment]
This bug is fixed with #611
