### ISSUE TITLE
Service status not correct on SLES 11.4

### ISSUE THREAD

**Issue by HunnyPuns** [NagiosEnterprises/ncpa#618]
The service API isn't showing the correct status of some services in SLES 11.4. We downgraded NCPA from 2.2.1-1 all the way down to 2.1.1, where it worked properly.

Reference:
https://support.nagios.com/forum/viewtopic.php?t=57707&sid=23fdeabdaa862fa36ae7113c99feb53e

**Comment by jomann09** [comment]
Assigning this as a bug because we will want to ensure we are getting most accurate results possible.
