### ISSUE TITLE
Correct Ubuntu Release numbering

### ISSUE THREAD

**Issue by mhampl** [NagiosEnterprises/ncpa#619]
Please use the correct numbers when referring to Ubuntu releases (e.g. in README.rst)
see https://ubuntu.com/about/release-cycle and https://wiki.ubuntu.com/Releases

All single numbers like "Ubuntu 12, 14, 16, 18" have to be corrected to the numbers denoting the LTS releases 12.04, 14.04, 16.04 and 18.04

**Comment by jomann09** [comment]
Updated in the list
