### ISSUE TITLE
run_with_sudo misnamed in NCPA documentation

### ISSUE THREAD

**Issue by MarcoBorchert** [NagiosEnterprises/ncpa#623]
Configuration option run_with_sudo is misnamed in the NCPA documentation:
https://www.nagios.org/ncpa/help.php#index-changes-in-21

> run_as_sudo - Comma separated list of plugin names that should be ran through sudo

Should be `run_with_sudo` (see https://github.com/NagiosEnterprises/ncpa/blob/master/CHANGES.rst#210---12192017)

**Comment by jomann09** [comment]
Updated internal documentation for 2.2.2 to fix this, will update the website shortly.
