### ISSUE TITLE
NCPA API returns (b") unexpectedly

### ISSUE THREAD

**Issue by rjkunde** [NagiosEnterprises/ncpa#628]
Using check_ncpa.py version 1.2.2  with Python 3.6.9 on Ubuntu 18.04 LTS

Everything seems to work fine, except my API returns the following an extraneous: b"
`python3 check_ncpa.py -t APIKeyHere-P 5693 -M 'disk/logical/|snap|core|8268' -w 90 -c 95 -H 192.168.1.101`

Returns:
`b"CRITICAL: Used disk space was 100.00 % (Used: 0.09 GiB, Free: 0.00 GiB, Total: 0.09 GiB) | 'used'=0.09GiB;0;0; 'free'=0.00GiB;0;0; 'total'=0.09GiB;0;0;"
`

I've checked through all of my configs at a high level, but can't find where its coming from. It is also present in the Nagios server UI:

![image](https://user-images.githubusercontent.com/10871915/81254293-90521980-8fdf-11ea-9224-c77d625a43aa.png)

Anyone have any ideas?

**Comment by jomann09** [comment]
I'll look into this, it's likely that the cehck_ncpa.py is returning a binary string instead of a normal string, that's what the b represents. What version is the check_ncpa.py plugin on that system?

**Comment by rjkunde** [comment]
Thanks! ncpa.py: __VERSION__ = '1.2.2'

**Comment by jomann09** [comment]
Thanks, I'll have to test this on a higher version of python 3, I'm sure that's the issue, once I make a change I'll post here to let you know.

**Comment by jvandermeulen** [comment]
@jomann09 In my opinion the check_ncpa.py v1.2.2 bug is quite serious as NCPA related performance data is missing in XI 5.7 
The new plugin is returning _performance data_ but double quotes around _status information_ and _performance data_ prevent Nagios XI from identifying/showing performance data.
Imho XI 5.7 customers will have gaps in their performance data unless they downgrade to version 1.2.0.

**Comment by jomann09** [comment]
Okay this is fixed with check_ncpa.py 1.2.3 and the commit 5695ddae668751e62b417af00eb228e6f641d610 I will update the tarball on the website and update the NCPA wizard in Nagios XI for this.

**Comment by jomann09** [comment]
Updated website with new version and config wizard in XI to 3.0.2
