### ISSUE TITLE
Silent Install opens up Windows firewall on ANY port

### ISSUE THREAD

**Issue by abeerens** [NagiosEnterprises/ncpa#631]
Installation of NCPA 2.1.9 2.2.0 and 2.2.1 (other versions not tested) in Windows (tested on 8.1 and Server 2016) from the commandline, with /S argument will add a firewall rule allowing traffic on ALL pots, instead of the intended NCPA port (default 5693) only.
This is an obvious security risk.

<img width="376" alt="Capture2" src="https://user-images.githubusercontent.com/31412024/81276335-25dac100-9053-11ea-8df5-11789c9c3cfb.PNG">
<img width="618" alt="Capture" src="https://user-images.githubusercontent.com/31412024/81276337-26735780-9053-11ea-9931-3023f84048df.PNG">

**Comment by abeerens** [comment]
extra info: when the agument /PORT is used. the firewall is opened only for the specified port.

**Comment by jvandermeulen** [comment]
@jomann09 could you please update us on this issue?

**Comment by jomann09** [comment]
Reading the nsis file I can see that it is likely setting the port as a blank string instead of the default port which is what is causing this. I'll update the nsis script for 2.2.2.

**Comment by jomann09** [comment]
Testing this right now, fix should be in 6e6e76eac5da0646dd70bae8ad05843432c981d7
