### ISSUE TITLE
Documentation error in the config file.

### ISSUE THREAD

**Issue by rwerner2ucm** [NagiosEnterprises/ncpa#638]
ncpa.cfg has the new option for "allowed_hosts" with the following example:
#
# Comma separated list of allowed hosts that can access the API (and GUI)
# Exmaple: 192.168.23.15
# Example subnet: 192.168.0.0/28
#
# allowed_hosts =

however,  the correct syntax for ConfigParser objects to have a list is:
allowed_hosts: <ip_addres>[,<ip_address>,...]

If I use the '=' syntax the entries are interpreted as Integers and no IP address is considered 'allowed'.  Additionally,  if I allow don't specify that the app should only listen to IPv4,  then it will not compare the incoming IP address as a bare IPv4 address but as a version 4 address with the v6 prefix attached.  

These problems go away if I do the following.  Use the proper 'list' syntax (:),  then a list of IP addresses can be given and the option works as expected.  I also set 'ip = 0.0.0.0'

I discovered this on a RHEL 7.x box running the rpm package of 2.2.1.  I'm not sure how this hasn't bitten others but I suspect a couple of other issues I saw earlier may be related to this.

Again,  as far as I'm concerned,  this is definitely a bug in the documentation and configuration file. Nothing states that we need to add the IPv6 prefix to IPv4 addressses. If I follow the documentation for the ConfigParser class with the 'allowed_hosts' parameter,  the app seems to work as desired.  I'll test some more to make sure.

**Comment by jomann09** [comment]
Can you give examples of what did and didn't work?
The configparser part is only interpreted as a string, then in NCPA we split the "list" on every `,` and then we pass each of those into the `ipaddress.ip_network()` function to get a list of allowed addresses.

**Comment by rwerner2ucm** [comment]
allowed_hosts = 127.0.01, 169.236.11.49, 169.236.85

prevented any host (including localhost) from connecting.

allowed_hosts: 127.0.0.1, 169.236.11.49, 169.236.85

worked as desired,  allowing only those hosts to connect to the ncpa listener.




--

Robert G. Werner

Systems Administrator

University of California Merced,  Office of Information Technology

rwerner2@ucmerced.edu<mailto:rwerner2@ucmerced.edu> | it.ucmerced.edu<https://it.ucmerced.edu/> | 209.201.4368


________________________________

**Comment by ccztux** [comment]
I can confirm this issue. Tested on debian 9 with NCPA 2.2.2.
https://github.com/NagiosEnterprises/ncpa/issues/660 seems to be the same issue.
