### ISSUE TITLE
ncpa_listener fails to start when IPv6 is disabled.

### ISSUE THREAD

**Issue by ssaxnagios** [NagiosEnterprises/ncpa#648]
The default "ip = ::" is IPv6 only, if IPv6 is disabled the ncpa_listener won't start and gives:

ERROR [Errno 97] Address family not supported by protocol

Setting it to "ip = 0.0.0.0" in the ncpa.cfg resolves it.

Recommend we change the default from :: to 0.0.0.0 since IPv4 is the norm at this time.

**Comment by jomann09** [comment]
What system is this on? We've been over this a few times in other threads.

**Comment by ssaxnagios** [comment]
This was on EL6, I labbed it up and tested on EL7 with the same results. If no IPv6 it fails because :: is the default. Feel free to consider this a feature request to fall back to 0.0.0.0 if IPv6 is disabled so the ncpa_listener starts.

**Comment by ccztux** [comment]
I can confirm this issue. Tested on CentOS7.
As suggested from @ssaxnagios i have added a fallback scenario in case IPv6 is not available on a system to my existing pull request #671 

Test log:
```
2020-08-31 19:48:32,348 2326 INFO started
2020-08-31 19:48:32,358 2326 INFO Using SSL version TLSv1_2
2020-08-31 19:48:32,361 2326 INFO Failed to start ncpa_listener in dual stack mode ([Errno 97] Address family not supported by protocol)
2020-08-31 19:48:32,361 2326 INFO Falling back to IPv4 only
```

The listener is running with IPv4 only:
```
[root@centos7_ncpa_test src]# netstat -taupen | grep -i ncpa
tcp        0      0 0.0.0.0:5693            0.0.0.0:*               LISTEN      1000       23641      2326/ncpa_listener  
```
