### ISSUE TITLE
check_ncpa.py v 1.2.3 output :No such file or directory

### ISSUE THREAD

**Issue by stetkai** [NagiosEnterprises/ncpa#652]
Hi,
after the upgrade of the check_ncpa.py from version 1.2.2 to 1.2.3 I have problem with output:
" :No such file or directory "

Maybe is the same problem with unix line endings like this https://github.com/NagiosEnterprises/ncpa/issues/588 

Thanks

**Comment by jomann09** [comment]
How'd you update the plugin? from the tarball on the website?

**Comment by stetkai** [comment]
Same procedure as for version 1.2.2 - downloaded from the web, copied to Nagios server and unpacked on Nagios.

**Comment by jomann09** [comment]
Okay I think this has been updated now.

**Comment by stetkai** [comment]
Great, thank You very much
