### ISSUE TITLE
Python 3?

### ISSUE THREAD

**Issue by brd** [NagiosEnterprises/ncpa#656]
Hello!  I am curious if there is a plan to start migrating towards Python 3?

https://www.python.org/doc/sunset-python-2/

Thanks!

**Comment by jomann09** [comment]
Yeah, the next version of NCPA is going to be in Python 3, there's a few things that have to be finished in order for that to happen but it's one of the next things on the list to be worked on.

**Comment by brd** [comment]
Great to hear, thank you!

**Comment by jomann09** [comment]
I'll be posting more as we start working on it, including some testing people can do with the dev branch.

**Comment by jomann09** [comment]
Closing this since python 3 is what will be used in ncpa 3 like I mentioned above!
