### ISSUE TITLE
ncpa_listener NVT: SSL/TLS: Missing 'secure' Cookie Attribute

### ISSUE THREAD

**Issue by micoots** [NagiosEnterprises/ncpa#659]
Hi,

I've run through a server with an OpenVAS scan and it detected:

Medium (CVSS: 6.4)
NVT: SSL/TLS: Missing 'secure' Cookie Attribute

Does ncpa_listener support the ability to add the secure attribute?

**Comment by jomann09** [comment]
Interesting, I'll have to check, the cookie is managed by flask, so it may be a setting that we need to enable.

**Comment by jomann09** [comment]
This is added to 2.3.0 and is in maint f2146ca14b1aa090f359a99c2ae22452e704c882
