### ISSUE TITLE
Feature request: Add inode percentage check

### ISSUE THREAD

**Issue by MrPippin66** [NagiosEnterprises/ncpa#672]
In feature enhancement #222 (Add inodes to linux disk checks), the following checks were added for Unix:

inodes - the total number of inodes available
inodes_used - the total number of inodes used
inodes_free - the total number of free inodes

What's missing is a percentage check, which is the most common alerting metric.

I would request a counterpart to the filesystem usage check for inode usage, most likely "inodes_used_percentage"

**Comment by jomann09** [comment]
Added in 2.3.0 thanks @ccztux
