### ISSUE TITLE
how to resolve this error UNKNOWN: An error occured connecting to API. (HTTP error: '500 INTERNAL SERVER ERROR')

### ISSUE THREAD

**Issue by sysadmin-imran** [NagiosEnterprises/ncpa#675]
hi there,
i have followed this "https://assets.nagios.com/downloads/nagiosxi/docs/How-to-Monitor-Docker-Containers-with-Nagios-XI.pdf" link to monitor docker containers in a host.

/usr/local/nagios/libexec/check_ncpa.py -H 192.168.0.6 -t 'Str0ngT0k3n' -P 5693 -M plugins/check_docker.py -q "args=-H http:/v1.40/,args=-s /var/run/docker.sock,args=--check-type 'containers_memory',args=--all,args=-t 0,args=--networks-use-avg,args=-w '30',args=-c '50'"

running above command have given me below error 

UNKNOWN: An error occured connecting to API. (HTTP error: '500 INTERNAL SERVER ERROR')

i guess it could be bcoz of  "args=-H http:/v1.40/"  parameter.
i have 

what is the right parameter to be added for this option "Docker API Base URL" while configuring docker setup through Nagios server configuration UI page.

can someone guide me through to resolve this error

**Comment by ccztux** [comment]
I have tested you command and at my system it works like a charm.
Version of check_ncpa.py:
```
[root@centos7_ncpa_test client]# ./check_ncpa.py --version
check_ncpa.py, Version 1.2.3
```

Version of NCPA:
```
[root@centos7_ncpa_test client]# ./check_ncpa.py -H localhost -t 'mytoken' -P 5693 -M system/agent_version
OK: Agent_version was ['2.2.2']
```

My test plugin:
```
[root@centos7_ncpa_test client]# cat /usr/local/ncpa/plugins/check_docker.py 
#!/usr/bin/env python


print("it works")
```

Your command with my test plugin:
```
[root@centos7_ncpa_test client]# ./check_ncpa.py -H localhost -t 'mytoken' -P 5693 -M plugins/check_docker.py -q "args=-H http:/v1.40/,args=-s /var/run/docker.sock,args=--check-type 'containers_memory',args=--all,args=-t 0,args=--networks-use-avg,args=-w '30',args=-c '50'"
it works
```

Can you please check and post your check_ncpa.py and NCPA versions?
Can you try to execute your command with enabled verbose and debug mode?:
```
./check_ncpa.py -H localhost -t 'mytoken' -P 5693 -M plugins/check_docker.py -q "args=-H http:/v1.40/,args=-s /var/run/docker.sock,args=--check-type 'containers_memory',args=--all,args=-t 0,args=--networks-use-avg,args=-w '30',args=-c '50'" -v -D
```

Maybe there is something interesting in the ```/usr/local/ncpa/var/log/ncpa_listener.log```?

**Comment by jomann09** [comment]
I'm closing this, if you are still having issues feel free to open it back up and let us know!
