### ISSUE TITLE
Availability of the latest NCPA (2.2.2) for AIX & SOLARIS based systems?

### ISSUE THREAD

**Issue by inversecow** [NagiosEnterprises/ncpa#676]
For some time now the latest release of NCPA (2.2.2) has been showing "Build In Progress" on the [download page](https://www.nagios.org/ncpa/#downloads).
What is the ETA for when these builds will be completed and available for use?

**Comment by jomann09** [comment]
Building these today, should be up today or tomorrow. Working on a 2.3.0 that fixes a couple issues that some people are having with 2.2.2 and should be available in the near future.

**Comment by jomann09** [comment]
Solaris systems are building, my AIX system is no longer available, trying to build on a different one but running into issues. That might take a little longer, but hopefully tomorrow for AIX as well.
