### ISSUE TITLE
SunOS Swap Memory error

### ISSUE THREAD

**Issue by tgriep** [NagiosEnterprises/ncpa#688]
SunOS 5.11 11.4.24.75.2 sun4v sparc sun4v

The Memory check through the API is causing the following errors.

API call
curl -k -XGET "https://localhost:5693/api/memory?token=mytoken"

Generates this error.
"swap": {

            "total": "Error retrieving child: \"invalid literal for int() with base 10: 'yes'\"",

            "percent": "Error retrieving child: \"invalid literal for int() with base 10: 'yes'\"",

            "free": "Error retrieving child: \"invalid literal for int() with base 10: 'yes'\"",

            "used": "Error retrieving child: \"invalid literal for int() with base 10: 'yes'\""

        },
		
Message from the ncpa_listener.log
Traceback (most recent call last):
  File "/root/ncpa/agent/listener/nodes.py", line 65, in walk
  File "/root/ncpa/agent/listener/nodes.py", line 174, in walk
  File "/root/ncpa/agent/listener/psapi.py", line 148, in <lambda>
  File "/usr/local/lib/python2.7/site-packages/psutil/__init__.py", line 2002, in swap_memory
  File "/usr/local/lib/python2.7/site-packages/psutil/_pssunos.py", line 160, in swap_memory
ValueError: invalid literal for int() with base 10: 'yes'
2020-09-14 09:35:49,326 27397 ERROR invalid literal for int() with base 10: 'yes'

**Comment by jomann09** [comment]
Unfortunately going to have to close this one, it looks like the issue may be in the actual psutil codebase here https://github.com/giampaolo/psutil/blob/master/psutil/_pssunos.py#L160 and what is happening is the system is not displaying what it should when you run the `swap -l` command. If we can get that info, please re-open this and I can create an issue for psutil. Without knowing what the `swap` command returns though we won't know what is wrong.

**Comment by spencer-lab** [comment]
In Solaris 11.4 there is an additional `encrypted` column in the output of `swap -l`:

    $ /usr/sbin/swap -l
    swapfile                 dev            swaplo      blocks        free encrypted
    /dev/zvol/dsk/rpool/swap 303,5               0     8388608     7072944      yes

The [`swap_memory()`](https://github.com/giampaolo/psutil/blob/7050e73c48b38caf2f19409167ba8dfaa9ab9fd4/psutil/_pssunos.py#L158) function in [`_pssunos.py`](https://github.com/giampaolo/psutil/blob/7050e73c48b38caf2f19409167ba8dfaa9ab9fd4/psutil/_pssunos.py) assigns the last two columns of output to `t` & `f` variables:

    t, f = line[-2:]

To work across Solaris 10, 11.3, 11.4 it should be:

    t, f = line[3:4]

**Comment by inversecow** [comment]
@jomann09 Given your comments across two issues, curious if this will also be resolved with the new `psutil` / `ncpa` 2.3.0 release?

https://github.com/NagiosEnterprises/ncpa/issues/622#issuecomment-736087409

https://github.com/NagiosEnterprises/ncpa/issues/688#issuecomment-723399168

**Comment by jomann09** [comment]
Yes this should be fixed in psutil 5.8.0 and that is what we are using in the latest build.
