### ISSUE TITLE
zipimport.ZipImportError on Solaris 11 sparc while installing NCPA 2.2.2 

### ISSUE THREAD

**Issue by kssenthil** [NagiosEnterprises/ncpa#690]
After installing NCPA 2.2.2 package in Solaris 10 and 11 sparc systems. After installing the NCPA, ncpa_listener process dows not start and gets into maintenance mode and throws this zlib error. 

>/usr/local/ncpa/ncpa_listener
zipimport.ZipImportError: can't decompress data; zlib not available
Fatal Python error: unable to locate initialization module
Abort (core dumped)

> svcs -l ncpa_listener
fmri         svc:/site/ncpa_listener:default
enabled      true
state        maintenance
next_state   none
state_time   Thu Sep 17 08:39:34 2020
logfile      /var/svc/log/site-ncpa_listener:default.log
restarter    svc:/system/svc/restarter:default
manifest     /lib/svc/manifest/site/ncpa_listener.xml
dependency   require_all/none svc:/milestone/multi-user (online)
 

> cat /var/svc/log/site-ncpa_listener:default.log
zipimport.ZipImportError: can't decompress data; zlib not available
Fatal Python error: unable to locate initialization module
[ Sep 15 05:54:12 Method "start" failed due to signal ABRT. ]
[ Sep 17 08:28:12 Leaving maintenance because disable requested. ]
[ Sep 17 08:28:12 Disabled. ]
[ Sep 17 08:39:31 Enabled. ]
[ Sep 17 08:39:31 Rereading configuration. ]
[ Sep 17 08:39:31 Executing start method ("/usr/local/ncpa/ncpa_listener"). ]
zipimport.ZipImportError: can't decompress data; zlib not available
Fatal Python error: unable to locate initialization module
[ Sep 17 08:39:32 Method "start" failed due to signal ABRT. ]
[ Sep 17 08:39:32 Executing start method ("/usr/local/ncpa/ncpa_listener"). ]
zipimport.ZipImportError: can't decompress data; zlib not available
Fatal Python error: unable to locate initialization module
[ Sep 17 08:39:33 Method "start" failed due to signal ABRT. ]
[ Sep 17 08:39:33 Executing start method ("/usr/local/ncpa/ncpa_listener"). ]
zipimport.ZipImportError: can't decompress data; zlib not available
Fatal Python error: unable to locate initialization module
[ Sep 17 08:39:34 Method "start" failed due to signal ABRT. ]
>

Even after updating the LD_LIBRARY_PATH, ncpa_listener does not come online

> export LD_LIBRARY_PATH='/usr/local/ncpa:/lib'
> echo $LD_LIBRARY_PATH
/usr/local/ncpa:/lib
> /usr/local/ncpa/ncpa_listener
zipimport.ZipImportError: can't decompress data; zlib not available
Fatal Python error: unable to locate initialization module
Abort (core dumped)

Looking for some help to resolve this error.

**Comment by kssenthil** [comment]
Can i have some update here to resolve the NCPA 2.2.2 package for Solaris ?

Please let me know if you need any further details.

**Comment by jomann09** [comment]
I don't have a SPARC system to test on, only the build server, which it was working on when I tested it. Can you run the following command on the solaris 11 system and copy the output?
```
ldd /usr/local/ncpa/ncpa_listener
```

**Comment by kssenthil** [comment]
Here is the output of ldd command,

# ldd /usr/local/ncpa/ncpa_listener
        libsocket.so.1 =>        /lib/64/libsocket.so.1
        libnsl.so.1 =>   /lib/64/libnsl.so.1
        libdl.so.1 =>    /lib/64/libdl.so.1
        libm.so.2 =>     /lib/64/libm.so.2
        libc.so.1 =>     /lib/64/libc.so.1
        libmp.so.2 =>    /lib/64/libmp.so.2
        libmd.so.1 =>    /lib/64/libmd.so.1
        libcryptoutil.so.1 =>    /lib/64/libcryptoutil.so.1
#

**Comment by kssenthil** [comment]
Installation of ncpa-2.2.0.sol11.sparc.pkg **was successfull and ncpa_listener service become online** on Solaris Sparc 11 system
  after following these steps.

  pkgadd -d ncpa-2.2.0.sol11.sparc.pkg
  ps -ef | grep ncpa
  svcs -l ncpa_listener
  cp ncpa_listener.xml /lib/svc/manifest/site/  
  svcadm restart manifest-import
  svcadm disable ncpa_listener;
  svccfg import /lib/svc/manifest/site/ncpa_listener.xml
  svcadm restart svc:/system/manifest-import
  svcs -l ncpa_listener
  svcadm refresh ncpa_listener; svcadm clear ncpa_listener; svcadm enable ncpa_listener;  
  svcs -l ncpa_listener
  ncpa_listener service comes online after executing above steps after installing ncpa-2.2.0

  Installation of **ncpa-2.2.2.sol11.sparc.pkg was successfull and ncpa_listener service is still in maintenance mode** on the same Solaris Sparc 11 system
  after following these steps.

  pkgadd -d ncpa-2.2.2.sol11.sparc.pkg
  ps -ef | grep ncpa
  svcs -l ncpa_listener
  cp ncpa_listener.xml /lib/svc/manifest/site/  
  svcadm restart manifest-import
  svcadm disable ncpa_listener;
  svccfg import /lib/svc/manifest/site/ncpa_listener.xml
  svcadm restart svc:/system/manifest-import
  svcs -l ncpa_listener
  svcadm refresh ncpa_listener; svcadm clear ncpa_listener; svcadm enable ncpa_listener;  
  svcs -l ncpa_listener
  ncpa_listener service is still in maintenance mode after executing above steps after installing ncpa-2.2.2

**Comment by kssenthil** [comment]
@jomann09 Can you have a look at the ldd command output and let me know your comments ?

**Comment by jomann09** [comment]
Yeah that ldd command is showing the required links it needs in order to run, the odd thing is that it isn't looking for the libpython so file. I will have to try rebuilding the package on  clean sparc system.

**Comment by kssenthil** [comment]
@jomann09 can you make a dev build of NCPA 2.2.2 Solaris sparc and share me the link, so that i can download and test the package.

**Comment by kssenthil** [comment]
@jomann09 do you have any update regarding the solaris ncpa package ?

**Comment by kssenthil** [comment]
@jomann09  do you have any update regarding the solaris ncpa 2.2.2 package ?

**Comment by jomann09** [comment]
So I finally got some time to build a new package, I was testing it but it seemed like one Solaris 11.4 the service wasn't properly tracking the agent's running process. If you'd like to try the new version, there's a dev version available here https://assets.nagios.com/downloads/ncpa/dev/ncpa-2.2.2-2.sol11.pkg and let me know if it works for you. It should be able to just start up by running the ncpa_listener executable if it doesn't properly start from svcadm.

**Comment by kssenthil** [comment]
@jomann09 I have tried to install the dev package ( ncpa-2.2.2-2.sol11.pkg ) which you have provided, but still i could not make the ncpa_listener service as online, please have a look at the log file and let me know your comments,

/tmp/ncpa# ls -l ncpa-2.2.2-2.sol11.pkg
-rw-r--r--   1 root     root     21755392 Oct 13 08:43 ncpa-2.2.2-2.sol11.pkg
/tmp/ncpa# pkgadd -d ncpa-2.2.2-2.sol11.pkg

The following packages are available:
  1  ncpa     A monitoring agent (Nagios Cross-Platform Agent) for Nagios.
              (sun4) Dev Release 10/08/2020

Select package(s) you wish to process (or 'all' to process
all packages). (default: all) [?,??,q]: all

Processing package instance <ncpa> from </tmp/ncpa/ncpa-2.2.2-2.sol11.pkg>

A monitoring agent (Nagios Cross-Platform Agent) for Nagios.(sun4) Dev Release 10/08/2020
Using </usr/local> as the package base directory.
## Processing package information.
## Processing system information.
## Verifying disk space requirements.
## Checking for conflicts with packages already installed.
## Checking for setuid/setgid programs.

This package contains scripts which will be executed with super-user
permission during the process of installing this package.

Do you want to continue with the installation of <ncpa> [y,n,?] y

Installing A monitoring agent (Nagios Cross-Platform Agent) for Nagios. as <ncpa>

## Executing preinstall script.
## Installing part 1 of 1.
/usr/local/ncpa/_bisect.so
/usr/local/ncpa/_cffi_backend.so
/usr/local/ncpa/_codecs_cn.so
/usr/local/ncpa/_codecs_hk.so
/usr/local/ncpa/_codecs_iso2022.so
/usr/local/ncpa/_codecs_jp.so
/usr/local/ncpa/_codecs_kr.so
/usr/local/ncpa/_codecs_tw.so
/usr/local/ncpa/_collections.so
/usr/local/ncpa/_ctypes.so
/usr/local/ncpa/_curses.so
/usr/local/ncpa/_functools.so
/usr/local/ncpa/_hashlib.so
/usr/local/ncpa/_heapq.so
/usr/local/ncpa/_io.so
/usr/local/ncpa/_json.so
/usr/local/ncpa/_locale.so
/usr/local/ncpa/_multibytecodec.so
/usr/local/ncpa/_multiprocessing.so
/usr/local/ncpa/_random.so
/usr/local/ncpa/_socket.so
/usr/local/ncpa/_sqlite3.so
/usr/local/ncpa/_ssl.so
/usr/local/ncpa/_struct.so
/usr/local/ncpa/array.so
/usr/local/ncpa/binascii.so
/usr/local/ncpa/build_resources/LicenseAgreement.txt
/usr/local/ncpa/build_resources/listener_init
/usr/local/ncpa/build_resources/macosinstall.sh
/usr/local/ncpa/build_resources/macosuninstall.sh
/usr/local/ncpa/build_resources/ncpa_listener.plist
/usr/local/ncpa/build_resources/ncpa_passive.plist
/usr/local/ncpa/build_resources/passive_init
/usr/local/ncpa/bz2.so
/usr/local/ncpa/cPickle.so
/usr/local/ncpa/cStringIO.so
/usr/local/ncpa/cryptography.hazmat.bindings._constant_time.so
/usr/local/ncpa/cryptography.hazmat.bindings._openssl.so
/usr/local/ncpa/datetime.so
/usr/local/ncpa/etc/ncpa.cfg
/usr/local/ncpa/etc/ncpa.cfg.d/README.txt
/usr/local/ncpa/etc/ncpa.cfg.d/example.cfg
/usr/local/ncpa/etc/ncpa.cfg.sample
/usr/local/ncpa/fcntl.so
/usr/local/ncpa/gevent._semaphore.so
/usr/local/ncpa/gevent._socket3.py
/usr/local/ncpa/gevent.ares.so
/usr/local/ncpa/gevent.libev._corecffi.so
/usr/local/ncpa/gevent.libev.corecext.so
/usr/local/ncpa/greenlet.so
/usr/local/ncpa/grp.so
/usr/local/ncpa/itertools.so
/usr/local/ncpa/jinja2.asyncsupport.py
/usr/local/ncpa/libcrypto.so.1.0.0
/usr/local/ncpa/libffi.so.6
/usr/local/ncpa/libpython2.7.so.1.0
/usr/local/ncpa/library.zip
/usr/local/ncpa/libssl.so.1.0.0
/usr/local/ncpa/listener/static/css/bootstrap.min.css
/usr/local/ncpa/listener/static/css/ea.min.css
/usr/local/ncpa/listener/static/css/font-awesome.min.css
/usr/local/ncpa/listener/static/css/ncpa-graph.css
/usr/local/ncpa/listener/static/css/ncpa.css
/usr/local/ncpa/listener/static/css/sumoselect.css
/usr/local/ncpa/listener/static/fonts/FontAwesome.otf
/usr/local/ncpa/listener/static/fonts/fontawesome-webfont.eot
/usr/local/ncpa/listener/static/fonts/fontawesome-webfont.svg
/usr/local/ncpa/listener/static/fonts/fontawesome-webfont.ttf
/usr/local/ncpa/listener/static/fonts/fontawesome-webfont.woff
/usr/local/ncpa/listener/static/fonts/fontawesome-webfont.woff2
/usr/local/ncpa/listener/static/help/active.html
/usr/local/ncpa/listener/static/help/api.html
/usr/local/ncpa/listener/static/help/configuration.html
/usr/local/ncpa/listener/static/help/graphs.html
/usr/local/ncpa/listener/static/help/index.html
/usr/local/ncpa/listener/static/help/other.html
/usr/local/ncpa/listener/static/help/passive.html
/usr/local/ncpa/listener/static/img/critical.png
/usr/local/ncpa/listener/static/img/footer_lodyas.png
/usr/local/ncpa/listener/static/img/glyphicons-halflings-white.png
/usr/local/ncpa/listener/static/img/glyphicons-halflings.png
/usr/local/ncpa/listener/static/img/ncpa.png
/usr/local/ncpa/listener/static/img/shattered.png
/usr/local/ncpa/listener/static/img/warning.png
/usr/local/ncpa/listener/static/js/bootstrap.min.js
/usr/local/ncpa/listener/static/js/d3.v5.min.js
/usr/local/ncpa/listener/static/js/help.js
/usr/local/ncpa/listener/static/js/jquery.3.5.1.min.js
/usr/local/ncpa/listener/static/js/jquery.ea.1.3.5.min.js
/usr/local/ncpa/listener/static/js/jquery.ss.3.0.2.min.js
/usr/local/ncpa/listener/static/js/main.js
/usr/local/ncpa/listener/static/js/smoothie.js
/usr/local/ncpa/listener/templates/admin/checks.html
/usr/local/ncpa/listener/templates/admin/global.html
/usr/local/ncpa/listener/templates/admin/index.html
/usr/local/ncpa/listener/templates/admin/listener.html
/usr/local/ncpa/listener/templates/admin/login.html
/usr/local/ncpa/listener/templates/admin/nrdp.html
/usr/local/ncpa/listener/templates/admin/passive.html
/usr/local/ncpa/listener/templates/admin/plugins.html
/usr/local/ncpa/listener/templates/base.html
/usr/local/ncpa/listener/templates/errors/404.html
/usr/local/ncpa/listener/templates/errors/500.html
/usr/local/ncpa/listener/templates/graph.html
/usr/local/ncpa/listener/templates/gui/api.html
/usr/local/ncpa/listener/templates/gui/checks.html
/usr/local/ncpa/listener/templates/gui/dashboard.html
/usr/local/ncpa/listener/templates/gui/graphs.html
/usr/local/ncpa/listener/templates/gui/help.html
/usr/local/ncpa/listener/templates/gui/plugins.html
/usr/local/ncpa/listener/templates/gui/stats.html
/usr/local/ncpa/listener/templates/gui/tail.html
/usr/local/ncpa/listener/templates/gui/top.html
/usr/local/ncpa/listener/templates/login.html
/usr/local/ncpa/listener/templates/tail.html
/usr/local/ncpa/listener/templates/top.html
/usr/local/ncpa/markupsafe._speedups.so
/usr/local/ncpa/math.so
/usr/local/ncpa/mmap.so
/usr/local/ncpa/ncpa_listener
/usr/local/ncpa/ncpa_passive
/usr/local/ncpa/operator.so
/usr/local/ncpa/pkginfo
/usr/local/ncpa/plugins/.keep
/usr/local/ncpa/psutil._psutil_posix.so
/usr/local/ncpa/psutil._psutil_sunos.so
/usr/local/ncpa/pyexpat.so
/usr/local/ncpa/readline.so
/usr/local/ncpa/select.so
/usr/local/ncpa/simplejson._speedups.so
/usr/local/ncpa/strop.so
/usr/local/ncpa/termios.so
/usr/local/ncpa/time.so
/usr/local/ncpa/unicodedata.so
/usr/local/ncpa/var/log/ncpa_listener.log
/usr/local/ncpa/var/log/ncpa_passive.log
/usr/local/ncpa/zlib.so
[ verifying class <none> ]
## Executing postinstall script.
Waiting for site/ncpa_listener to reach online state.
It is safe to interrupt.
svcbundle: error: Problem in running svcprop.  svcprop: Couldn't find property group `restarter' for instance `svc:/site/ncpa_listener:default'.

Waiting for site/ncpa_passive to reach online state.
It is safe to interrupt.
svcbundle: error: Problem in running svcprop.  svcprop: Couldn't find property group `restarter' for instance `svc:/site/ncpa_passive:default'.


Installation of <ncpa> was successful.
/tmp/ncpa# ps -ef | grep ncpa
    root  4621  4457   0 05:11:08 pts/1       0:00 grep ncpa
/tmp/ncpa# svcs -l ncpa_listener
fmri         svc:/site/ncpa_listener:default
enabled      true
state        maintenance
next_state   none
state_time   October 14, 2020 05:10:37 AM CDT
logfile      /var/svc/log/site-ncpa_listener:default.log
restarter    svc:/system/svc/restarter:default
manifest     /lib/svc/manifest/site/ncpa_listener.xml
dependency   require_all/none svc:/milestone/multi-user (online)
/tmp/ncpa# 

:/tmp/ncpa# /usr/local/ncpa/ncpa_passive --start
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cx_Freeze-4.3.4-py2.7-solaris-2.11-sun4v.32bit.egg/cx_Freeze/initscripts/Console.py", line 27, in <module>
  File "ncpa_passive.py", line 6, in <module>
  File "/export/home/bzid/ncpa/agent/ncpadaemon.py", line 4, in <module>
ImportError: ld.so.1: ncpa_passive: fatal: relocation error: file /usr/local/ncpa/grp.so: symbol _PyInt_FromGid: referenced symbol not found
:/tmp/ncpa# /usr/local/ncpa/ncpa_listener -start
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cx_Freeze-4.3.4-py2.7-solaris-2.11-sun4v.32bit.egg/cx_Freeze/initscripts/Console.py", line 27, in <module>
  File "ncpa_listener.py", line 6, in <module>
  File "/usr/lib/python2.7/logging/__init__.py", line 26, in <module>
    import sys, os, time, cStringIO, traceback, warnings, weakref
  File "/usr/lib/python2.7/weakref.py", line 14, in <module>
    from _weakref import (
ImportError: cannot import name _remove_dead_weakref
:/tmp/ncpa#

**Comment by kssenthil** [comment]
@jomann09  do you have any comments / inputs to rectify this error ?

:/tmp/ncpa# /usr/local/ncpa/ncpa_listener -start
Traceback (most recent call last):
File "/usr/lib/python2.7/site-packages/cx_Freeze-4.3.4-py2.7-solaris-2.11-sun4v.32bit.egg/cx_Freeze/initscripts/Console.py", line 27, in
File "ncpa_listener.py", line 6, in
File "/usr/lib/python2.7/logging/init.py", line 26, in
import sys, os, time, cStringIO, traceback, warnings, weakref
File "/usr/lib/python2.7/weakref.py", line 14, in
from _weakref import (
ImportError: cannot import name _remove_dead_weakref
:/tmp/ncpa#

**Comment by jomann09** [comment]
That I have not seen before, are you using solaris 11.4 or an older version? Also you originally said the issue was happening on both solaris 11 and 10, is that still the case or is it only 11 having the issues?

**Comment by jomann09** [comment]
Okay I think the biggest issue was that the versions being built for 2.2.1/2.2.2 were for Solaris 11.4 which, incidentally, is not backwards compatible with Solaris 11.3.

I've built the new SPARC packages on Solaris 11.3 and tested them on Solaris 11.4, so they should work now:
2.3.0 - Solaris 11.3/11.4 SPARC - http://assets.nagios.com/downloads/ncpa/ncpa-2.3.0.sol11.sparc.pkg
2.3.0 - Solaris 11.3/11.4 x86 - http://assets.nagios.com/downloads/ncpa/ncpa-2.3.0.sol11.i86pc.pkg
2.3.0 - Solaris 10u11 SPARC - http://assets.nagios.com/downloads/ncpa/ncpa-2.3.0.sol10.sparc.pkg
2.3.0 - Solaris 10u11 x86 - http://assets.nagios.com/downloads/ncpa/ncpa-2.3.0.sol10.i86pc.pkg

Just a side note, I expect the same thing with Solaris 10. We only build for the very last version of Solaris 10, which is 10u11, no earlier versions are supported.

**Comment by jomann09** [comment]
I'm closing this due to it working in the clean Solaris installs I tested on. If there's any other issues please feel free to re-open or create a new issue and we can look into it further.
