### ISSUE TITLE
Nagios DEB Repository - Focal

### ISSUE THREAD

**Issue by timcanty** [NagiosEnterprises/ncpa#691]
Just wondering if you had any plans to add Focal as a Repository soon?

Used the eoan repository for a few installs and it works fine, but since Ubuntu 20.04.1 is an LTS thought you might want to think of adding it.

**Comment by jomann09** [comment]
Yeah we will be adding one, I can get this on the list to start the process.

**Comment by timcanty** [comment]
Hello can you confirm if this issue is deliberate, are we supposed to use bionic for focal servers, or is this a script issue on the webpage 

![image](https://user-images.githubusercontent.com/32928117/106505034-a7b32a00-64bf-11eb-94a6-3738ffcdd3cf.png)

**Comment by jomann09** [comment]
Yes sorry about this, it should be set properly now.

**Comment by timcanty** [comment]
thanks that's now working 👍

**Comment by timcanty** [comment]
![image](https://user-images.githubusercontent.com/32928117/106571299-e2a07680-652e-11eb-9072-a2943059caec.png)

**Comment by jomann09** [comment]
Okay this should be fixed now, I'm not sure how that happened but it seems the Packages file never updated properly.

**Comment by timcanty** [comment]
thanks 👍
