### ISSUE TITLE
check_ncpa + check_apt returns WARNING on remote but OK on local

### ISSUE THREAD

**Issue by sm3ulc** [NagiosEnterprises/ncpa#701]
Have run into mysterious return code of check_ncpa combined with check_apt. Returns correct with other plugins but check_apt seem to translate the OK to WARNING when passing the check through check_ncpa. Also not that "warnings detected." is added along the way.

**Remote check on server**
user@nagios:/usr/local/nagios/libexec$ ./check_ncpa -H server -P 5666 -M "plugins/check_apt" -a " -w 1 -c 3" --token=supersecure-token
APT WARNING: 0 packages available for upgrade (0 critical updates). warnings detected.|available_upgrades=0;;;0 critical_updates=0;;;0

user@nagios:/usr/local/nagios/libexec$ ./check_ncpa -V
check_ncpa.py, Version 1.2.3

**Local on the remote server:**
root@server:/usr/lib/nagios/plugins# ./check_apt
APT OK: 0 packages available for upgrade (0 critical updates). |available_upgrades=0;;;0 critical_updates=0;;;0

root@server:/usr/lib/nagios/plugins#./check_apt -w 0
APT WARNING: 0 packages available for upgrade (0 critical updates). |available_upgrades=0;;;0 critical_updates=0;;;0
**(note no "warnings detected.")**

root@server:/usr/lib/nagios/plugins# ./check_apt -V
check_apt v2.3.3 (nagios-plugins 2.3.3)

**Comment by ccztux** [comment]
1. Your ```check_apt``` call (local on the remote server) differs from that one, you tried with ```check_ncpa.py```
2. You have executed ```check_apt``` (local on the remote server) as user ```root```:

> **Local on the remote server:**
```
root@server:/usr/lib/nagios/plugins# ./check_apt
root@server:/usr/lib/nagios/plugins#./check_apt -w 0
```

> **Remote check on server**
```
user@nagios:/usr/local/nagios/libexec$ ./check_ncpa -H server -P 5666 -M "plugins/check_apt" -a " -w 1 -c 3" --token=supersecure-token
```

I am not sure if check_apt requires root privileges to work without issues. Can you provide the output of the following command (local on the remote server):
```
ps aux | grep -i ncpa
```

It would also be interesting, if ```check_apt``` provides the same output if you call it via ```check_ncpa.py``` the same way as local on the remote server:
```
user@nagios:/usr/local/nagios/libexec$ ./check_ncpa -H server -P 5666 -M "plugins/check_apt" --token=supersecure-token
user@nagios:/usr/local/nagios/libexec$ ./check_ncpa -H server -P 5666 -M "plugins/check_apt" -a " -w 0" --token=supersecure-token
```

**Comment by sm3ulc** [comment]
Thanks for the input! The '-w 0' was just there to show the added string in the message. 
Apart from that; we probably found evidence that the problem is with check_apt and not check_ncpa. We get different results with different users on some servers but no difference on another set of servers. We continue to try to drill down to the cause..

**Executed as user nagios and root**
root@server:/usr/lib/nagios/plugins# su -s /bin/bash -c './check_apt' nagios
APT WARNING: 0 packages available for upgrade (0 critical updates). warnings detected.|available_upgrades=0;;;0 critical_updates=0;;;0

root@server:/usr/lib/nagios/plugins# ./check_apt
APT OK: 0 packages available for upgrade (0 critical updates). |available_upgrades=0;;;0 critical_updates=0;;;0

**Executed as user nagios on another server..**
root@server2:/usr/lib/nagios/plugins# su -s /bin/bash -c './check_apt' nagios
APT OK: 0 packages available for upgrade (0 critical updates). |available_upgrades=0;;;0 critical_updates=0;;;0

**Comment by sm3ulc** [comment]
**Problem solved.** Ansible assigned incorrect flags to the repo-file. Found this with strace:

read(5, "W: Unable to read /etc/apt/sources.list.d/nagios.list - open (13: Permission denied)\n", 4096) = 85

So, inadequate checking of the file in check_apt caused the problem.
