### ISSUE TITLE
An error occurred:HTTP Error 500: INTERNAL SERVER ERROR - Checking status of windows "Dfs" service

### ISSUE THREAD

**Issue by kebagb** [NagiosEnterprises/ncpa#702]
$ ./check_ncpa.py -v -t *************** -T 120 -H ************ -M services -q check=1,match=search,service=Dfs,status=running

Connecting to: https://**********:5693/api/services/?token=**************&check=1&check=1&match=search&service=Dfs&status=running

An error occurred:HTTP Error 500: INTERNAL SERVER ERROR

The same command works fine for other services running on the same server.
Dfs (DFS Namespace) service is one of the services that are needed when running ActiveDirectory.

**Comment by ccztux** [comment]
Can you please try it with enabled debug mode ```-D```:
```
$ ./check_ncpa.py -D -t *************** -T 120 -H ************ -M services -q check=1,match=search,service=Dfs,status=running
```

The output of the list command would also be interesting:
```
$ ./check_ncpa.py -t *************** -T 120 -H ************ -M services -l
```

Which versions of ```NCPA``` and ```check_ncpa.py``` are you using and on which OS?

Is there something interesting in the ```ncpa_listener.log```?

Maybe you can increase the loglevel in the ```[listener]``` section of ```ncpa.cfg``` to ```debug```, restart the ```ncpa_listener``` service, try a check and take a look in the ```ncpa_listener.log```?

```
#
# Listener logging file level, location, and the PID location
# Default: loglevel = info (debug, info, warning, error)
# Default: logfile = var/log/ncpa_listener.log
# Default: pidfile = var/run/ncpa_listener.pid (leave listener in pid file name)
#
loglevel = debug
```

**Comment by kebagb** [comment]
Software/OS versions.

Nagios Server :
#21~18.04.1-Ubuntu SMP Wed Apr 15 09:35:56 UTC 2020
check_ncpa.py, Version 1.1.3

Host :
Windows Server 2019
NCPA agent version - 2.2.2

**Comment by kebagb** [comment]
Output from Services list (Dfs service shows in list)

./check_ncpa.py -t *************** -T 120 -H ************ -M services -l

{
    "services": {
        "WalletService": "stopped",
        "CscService": "stopped",
        "Winmgmt": "running",
        "AdtAgent": "stopped",
        "WinRM": "running",
        "ShellHWDetection": "running",
        "AppReadiness": "stopped",
        "ADWS": "running",
        "CertPropSvc": "running",
        "DmEnrollmentSvc": "stopped",
        "Power": "running",
        "Dhcp": "running",
        "iphlpsvc": "running",
        "upnphost": "stopped",
        "AppIDSvc": "stopped",
        "AJRouter": "stopped",
        "Audiosrv": "stopped",
        "KtmRm": "stopped",
        "Schedule": "running",
        "CaptureService_1cd461": "stopped",
        "DevicePickerUserSvc_15ae606": "stopped",
        "DoSvc": "stopped",
        "TrustedInstaller": "stopped",
        "NcbService": "running",
        "SstpSvc": "stopped",
        "StorSvc": "running",
        "StateRepository": "running",
        "KeyIso": "running",
        "TimeBrokerSvc": "running",
        "MSiSCSI": "stopped",
        "COMSysApp": "running",
        "IaasVmProvider": "stopped",
        "IsmServ": "running",
        "UserDataSvc_15ae606": "stopped",
        "WindowsAzureGuestAgent": "running",
        "BFE": "running",
        "tzautoupdate": "stopped",
        "bthserv": "stopped",
        "ProfSvc": "running",
        "DevicePickerUserSvc_1cd461": "stopped",
        "WpnUserService_15ae606": "running",
        "Dfs": "running",
        "FontCache": "running",
        "CDPUserSvc_15ae606": "running",
        "CaptureService_15ae606": "stopped",
        "SensorService": "stopped",
        "seclogon": "stopped",
        "smphost": "stopped",
        "vds": "running",
        "SEMgrSvc": "stopped",
        "FrameServer": "stopped",
        "RdAgent": "running",
        "swprv": "running",
        "PlugPlay": "running",
        "EntAppSvc": "stopped",
        "RasMan": "stopped",
        "WMPNetworkSvc": "stopped",
        "Themes": "running",
        "SystemEventsBroker": "running",
        "RpcLocator": "stopped",
        "DsmSvc": "stopped",
        "SENS": "running",
        "lmhosts": "running",
        "BthAvctpSvc": "stopped",
        "W32Time": "running",
        "SensorDataService": "stopped",
        "NgcCtnrSvc": "stopped",
        "NTDS": "running",
        "QualysAgent": "running",
        "LanmanServer": "running",
        "FDResPub": "stopped",
        "MSDTC": "running",
        "RemoteRegistry": "stopped",
        "WinDefend": "running",
        "NlaSvc": "running",
        "gpsvc": "running",
        "EventLog": "running",
        "WdNisSvc": "running",
        "diagnosticshub.standardcollector.service": "stopped",
        "lltdsvc": "stopped",
        "LSM": "running",
        "SensrSvc": "stopped",
        "LanmanWorkstation": "running",
        "WiaRpc": "stopped",
        "DevicesFlowUserSvc_1cd461": "stopped",
        "RpcSs": "running",
        "PerfHost": "stopped",
        "CoreMessagingRegistrar": "running",
        "AppVClient": "stopped",
        "EFS": "stopped",
        "WaaSMedicSvc": "running",
        "dot3svc": "stopped",
        "UALSVC": "running",
        "UnistoreSvc_15ae606": "stopped",
        "vmicguestinterface": "stopped",
        "BDESVC": "running",
        "GraphicsPerfSvc": "stopped",
        "RpcEptMapper": "running",
        "cbdhsvc_1cd461": "stopped",
        "DcomLaunch": "running",
        "pla": "running",
        "embeddedmode": "stopped",
        "WpnService": "running",
        "CDPSvc": "running",
        "Spooler": "running",
        "AxInstSV": "stopped",
        "WdiSystemHost": "running",
        "ConsentUxUserSvc_1cd461": "stopped",
        "UserDataSvc_1cd461": "stopped",
        "NcaSvc": "stopped",
        "WarpJITSvc": "stopped",
        "DevQueryBroker": "stopped",
        "lfsvc": "stopped",
        "KdsSvc": "stopped",
        "Wecsvc": "stopped",
        "wlidsvc": "stopped",
        "stisvc": "stopped",
        "camsvc": "stopped",
        "WSearch": "stopped",
        "WbioSrvc": "stopped",
        "RmSvc": "stopped",
        "defragsvc": "stopped",
        "WPDBusEnum": "stopped",
        "ncpapassive": "stopped",
        "PrintNotify": "stopped",
        "Eaphost": "stopped",
        "nsi": "running",
        "PrintWorkflowUserSvc_15ae606": "stopped",
        "ScDeviceEnum": "stopped",
        "NtFrs": "stopped",
        "WEPHOSTSVC": "stopped",
        "EventSystem": "running",
        "mpssvc": "running",
        "VaultSvc": "stopped",
        "PolicyAgent": "running",
        "ConsentUxUserSvc_15ae606": "stopped",
        "SNMPTRAP": "stopped",
        "SessionEnv": "running",
        "ncpalistener": "running",
        "hidserv": "stopped",
        "Netlogon": "running",
        "UmRdpService": "running",
        "SCardSvr": "stopped",
        "cbdhsvc_15ae606": "stopped",
        "sppsvc": "stopped",
        "AudioEndpointBuilder": "stopped",
        "BrokerInfrastructure": "running",
        "wercplsupport": "stopped",
        "AppXSvc": "stopped",
        "CDPUserSvc_1cd461": "running",
        "WinHttpAutoProxySvc": "running",
        "vmicvss": "running",
        "sacsvr": "running",
        "icssvc": "stopped",
        "netprofm": "running",
        "BITS": "stopped",
        "InstallService": "stopped",
        "UevAgentService": "stopped",
        "vmicheartbeat": "running",
        "WindowsAzureNetAgentSvc": "running",
        "PimIndexMaintenanceSvc_1cd461": "stopped",
        "vmicvmsession": "stopped",
        "DeviceInstall": "stopped",
        "LicenseManager": "running",
        "CryptSvc": "running",
        "AppMgmt": "running",
        "DNS": "running",
        "NetSetupSvc": "stopped",
        "vmicrdv": "running",
        "wuauserv": "running",
        "IKEEXT": "running",
        "DevicesFlowUserSvc_15ae606": "stopped",
        "TokenBroker": "running",
        "ALG": "stopped",
        "DsSvc": "running",
        "WerSvc": "stopped",
        "Kdc": "running",
        "DFSR": "running",
        "QWAVE": "stopped",
        "MapsBroker": "stopped",
        "AzureNetworkWatcherAgent": "running",
        "Sense": "stopped",
        "Dnscache": "running",
        "RemoteAccess": "stopped",
        "shpamsvc": "stopped",
        "wisvc": "stopped",
        "PrintWorkflowUserSvc_1cd461": "stopped",
        "tapisrv": "stopped",
        "msiserver": "stopped",
        "KPSSVC": "stopped",
        "DPS": "running",
        "svsvc": "stopped",
        "PcaSvc": "running",
        "fdPHost": "stopped",
        "UnistoreSvc_1cd461": "stopped",
        "DsRoleSvc": "stopped",
        "SCPolicySvc": "stopped",
        "Appinfo": "running",
        "ssh-agent": "stopped",
        "NgcSvc": "stopped",
        "dmwappushservice": "stopped",
        "vmictimesync": "running",
        "HvHost": "stopped",
        "DiagTrack": "running",
        "UserManager": "running",
        "SecurityHealthService": "stopped",
        "TieringEngineService": "stopped",
        "SgrmBroker": "stopped",
        "PimIndexMaintenanceSvc_15ae606": "stopped",
        "SSDPSRV": "stopped",
        "PhoneSvc": "stopped",
        "SharedAccess": "stopped",
        "wmiApSrv": "stopped",
        "SamSs": "running",
        "BTAGService": "stopped",
        "UsoSvc": "running",
        "RasAuto": "stopped",
        "MMAExtensionHeartbeatService": "running",
        "Wcmsvc": "running",
        "SysMain": "running",
        "NetTcpPortSharing": "stopped",
        "System Center Management APM": "stopped",
        "TabletInputService": "running",
        "ClipSVC": "stopped",
        "VSS": "running",
        "PushToInstall": "stopped",
        "Netman": "stopped",
        "TermService": "running",
        "HealthService": "running",
        "DeviceAssociationService": "stopped",
        "vmicshutdown": "running",
        "TrkWks": "stopped",
        "vmickvpexchange": "running",
        "RSoPProv": "stopped",
        "WpnUserService_1cd461": "running",
        "WdiServiceHost": "stopped"
    }
}

**Comment by kebagb** [comment]
Same call with Debug enabled :

$ ./check_ncpa.py -D -t *************** -T 120 -H ************ -M services -q check=1,match=search,service=Dfs,status=running

The stack trace:Traceback (most recent call last):
  File "./check_ncpa.py", line 274, in main
    info_json = get_json(options)
  File "./check_ncpa.py", line 221, in get_json
    ret = urlopen(url, context=ctx)
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 500: INTERNAL SERVER ERROR

**Comment by kebagb** [comment]
Contents of ncpa_listener.log with log-level=debug :

```
2020-10-14 09:08:59,454:INFO:ncpa_windows:Parsed config from: ['C:\\Program Files (x86)\\Nagios\\NCPA\\etc\\ncpa.cfg', 'C:\\Program Files (x86)\\Nagios\\NCPA\\etc\\ncpa.cfg.d\\example.cfg']
2020-10-14 09:08:59,454:INFO:ncpa_windows:Looking for plugins at: C:\Program Files (x86)\Nagios\NCPA\plugins
2020-10-14 09:08:59,454:INFO:ncpa_windows:Using SSL version TLSv1_2
2020-10-14 09:09:13,467:DEBUG:handler:Initializing WebSocket
2020-10-14 09:09:13,467:DEBUG:handler:Validating WebSocket request
2020-10-14 09:09:13,497:DEBUG:psapi:Imported windowscounters into the API tree.
2020-10-14 09:09:13,497:DEBUG:psapi:Imported windowslogs into the API tree.
2020-10-14 09:09:13,545:ERROR:app:Exception on /api/services/ [GET]
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\flask\app.py", line 1817, in wsgi_app
  File "C:\Python27\lib\site-packages\flask\app.py", line 1477, in full_dispatch_request
  File "C:\Python27\lib\site-packages\flask\app.py", line 1381, in handle_user_exception
  File "C:\Python27\lib\site-packages\flask\app.py", line 1475, in full_dispatch_request
  File "C:\Python27\lib\site-packages\flask\app.py", line 1461, in dispatch_request
  File "C:\ncpa\agent\listener\server.py", line 185, in token_auth_decoration
  File "C:\ncpa\agent\listener\server.py", line 946, in api
  File "C:\ncpa\agent\listener\services.py", line 365, in run_check
ValueError: 'DFSR' is not in list
2020-10-14 09:09:13,545:INFO:handler:******** - - [2020-10-14 09:09:13] "GET /api/services/?token=**********&check=1&check=1&match=search&service=Dfs&status=running HTTP/1.1" 500 2362 0.078000
```

NOTE: DFSR is a different service from Dfs and is running on the same server.  I can explicitly check that service using check_ncpa.py without any problem.

**Comment by kebagb** [comment]
Hope there's enough info here for someone to help.
Could it be that the agent is somehow getting confused by the two similarly named services?

**Comment by ccztux** [comment]
Thanks for providing these informations. There are [some issues](https://github.com/NagiosEnterprises/ncpa/issues/626) with the ```services``` endpoint in version 2.2.2.
A downgrade to version 2.2.1 may be help.

**Comment by kebagb** [comment]
Downgrading to 2.2.0 has helped, however it is now matching on both Dfs and DFSR, but I think I can work around that by using regex rather than search.  
As it happens, there was a test for a completely unrelated service on a different host which I realised was suffering from the same issue.  Downgrading to 2.2.0 fixed that too.

Thanks for your help @ccztux

**Comment by jomann09** [comment]
Closing this since 2.3.0 just went out and it's related to the issues that were fixed with the services endpoint.
