### ISSUE TITLE
Raspberry OS 64bit

### ISSUE THREAD

**Issue by mhzawadi** [NagiosEnterprises/ncpa#703]
Good morning,

I have started to swop over to NCPA from nrpe, I have found the switch easy and even been able to tidy out my monitoring.

But have hit an issue, the first is that your arm build is listed as 64bit. Its not, its armv7. The second is you dont even build for arm 64bit.

Could you please start building for raspberry OS 64bit?

**Comment by jomann09** [comment]
I don't really know all that much about raspberry OS. I have a pi which is armv7 which is why we build for it. Since the raspberry OS is based on Debian I do believe our Debian 64bit builds should work on it without having to specifically build one for it.

**Comment by mhzawadi** [comment]
Ok, then explains it.

When you build for the Pi, do you run the build from the Pi or from a pc/mac/server?

Also check this out - https://www.raspberrypi.org/forums/viewtopic.php?p=1668160

**Comment by mhzawadi** [comment]
have got it build on on a pi using docker, have added PR to make it work #709

**Comment by jomann09** [comment]
Thanks for the PR I will check it ang pull it in here soon.

**Comment by mhzawadi** [comment]
Hey,

I've just build an arm64 package and its up on my fork of your repo - https://github.com/mhzawadi/ncpa/releases/tag/v2.4.0
if you would like me you try an armhf as well, I can see if my older pi will build.

**Comment by jomann09** [comment]
Closing this since it works, we just don't have builds/aren't making builds of it automatically yet.
