### ISSUE TITLE
Possibility to specify different units for "normal" output and performance data.

### ISSUE THREAD

**Issue by dan-m-joh** [NagiosEnterprises/ncpa#712]
It would great to be able to specify that the performance data has another "unit" than the "normal" output.
(This would also solve an issue with rounding problems when calculating "warning/critical" values in the performance data).

For example, today I can set `-u B` too change the unit for the output and performance data.
Without `-u B`
```
$ ./check_ncpa.py -H myhost -t mytoken -M 'disk/logical/|boot' -w 80 -c 90
OK: Used disk space was 25.30 % (Used: 0.22 GiB, Free: 0.66 GiB, Total: 0.95 GiB) | 'used'=0.22GiB;1;1; 'free'=0.66GiB;1;1; 'total'=0.95GiB;1;1;
```
As you can see, both outputs are in GiB and the rounding of the warning(80%) and critical (90%) both get rounded to 1GiB which is more then the "total" (0.95GiB) is. (yes, it is probably only an issue for small volumes - but still - looks strange in Graphs when the Warning/Critical level is higher than the total).

With `-u B`
```
$ ./check_ncpa.py -H myhost -t mytoken -M 'disk/logical/|boot' -w 80 -c 90 -u B
OK: Used disk space was 25.30 % (Used: 241455104 B, Free: 711385088 B, Total: 1023303680 B) | 'used'=241455104B;818642944;920973312; 'free'=711385088B;818642944;920973312; 'total'=1023303680B;818642944;920973312;
```
No the calculation of the warning and critical values in the performance data is correct but the normal output is a little bit harder to read.

What I would like to have/propose is to have a second "unit" parameter for the performance data,  E.g. -U, --performanceunits.

Then the check would look something like this:
```
$ ./check_ncpa.py -H myhost -t mytoken -M 'disk/logical/|boot' -w 80 -c 90 -U B
OK: Used disk space was 25.30 % (Used: 0.22 GiB, Free: 0.66 GiB, Total: 0.95 GiB) | 'used'=241455104B;818642944;920973312; 'free'=711385088B;818642944;920973312; 'total'=1023303680B;818642944;920973312;
```

Regards,
Dan

**Comment by jomann09** [comment]
I'm planning on fixing this with bug #713 which is the rounding issue you talk about. It really should be rounding to two decimal places when it puts in perfdata warning and critical numbers.

**Comment by jomann09** [comment]
I'm actually going to close this, see the bug I posted above for more details about this.
