### ISSUE TITLE
License name is misleading

### ISSUE THREAD

**Issue by LeChasseur** [NagiosEnterprises/ncpa#717]
NCPA is under Nagios Open Software License Version 1.3 which makes people believe that the software is under an Open Source  License (which is not due to the restriction of sec. 3 and 6. Could you consider to rename the license to avoid such misunderstandings?

**Comment by jomann09** [comment]
I'll bring this up at the next meeting for approval to change this. Thanks for the suggestion.

**Comment by jomann09** [comment]
Wording was updated to "Community" instead of "Open" for the next version of NCPA - commit #bb2459b
