### ISSUE TITLE
The "View in alternate format" doesn't show the "sleep for x seconds" option

### ISSUE THREAD

**Issue by ludmilmm** [NagiosEnterprises/ncpa#722]
If you needed to monitor a Windows performance counter that requires the use of "Sleep for x seconds" option, you could view the correct command in the API (GUI).

Example:
`https://x.x.x.x:5693/api/windowscounters/Processor Information(_Total)/% Processor Time?sleep=5&check=true`

However, the sleep option is not shown when you try to view the command in an alternate format.

Example:
`./check_ncpa.py -H x.x.x.x -t '<your token>' -M 'windowscounters/Processor Information(_Total)/% Processor Time'`

Tested with NCPA - agent version 2.2.2

**Comment by jomann09** [comment]
Fixed in 6e70cca
