### ISSUE TITLE
How to exclude Event Id Logs in NCPA

### ISSUE THREAD

**Issue by HieiOne** [NagiosEnterprises/ncpa#734]
I was wondering if it was possible to exclude certain event ids in the logs check, I know you can filter a specific event ids like 

`-M 'logs/' -q 'name=System,event_id=12345,logged_after=15m,check=true,warning=3'`

But is it possible to exclude it instead, like:

`-M 'logs/' -q 'name=System,event_id=!12345,logged_after=15m,check=true,warning=3'`

Thanks.

**Comment by jomann09** [comment]
This isn't currently supported, I can make this an enhancement request but no idea when it would be implemented.

**Comment by jomann09** [comment]
Actually this has been requested in #737 so will close this since the functionality doesn't exist yet.
