### ISSUE TITLE
NRPE agent install fails on RHEL / CentOS 8.3

### ISSUE THREAD

**Issue by willemdh** [NagiosEnterprises/ncpa#736]
See https://support.nagios.com/forum/viewtopic.php?f=16&t=61346

NRPE Agent fails to install on RHEL / CentOS 8.3, as it requires the rpm package centos-release in get-os-info which is called by fullinstall.

centos-release no longer exists in 8.3 and is replaced by centos-linux-release

So as a temporary workaround we replaced:

`    if rpm -q centos-release; then`

By

`    if rpm -q centos-linux-release; then`

But it would be nice if this was added by nagios, so this happens out of the box.

**Comment by jomann09** [comment]
I think they sent you to the wrong github page, but this is actually something we maintain in house. I have updated the linux-nrpe-agent tarball and should be available now and work on Stream as well.
