### ISSUE TITLE
Check_ncpa.py in tar.gz is broken

### ISSUE THREAD

**Issue by yderi** [NagiosEnterprises/ncpa#748]
Hello everyone.

Does version "check_ncpa.py" 1.2.4 is corrupted inside the tar.gz archive by the following link? 

[check_ncpa.tar.gz](https://assets.nagios.com/downloads/ncpa/check_ncpa.tar.gz)

**Comment by jomann09** [comment]
Looks like there was an issue with the tarball, I uploaded a new one which will be available in the next few minutes.

**Comment by yderi** [comment]
Hello.
Looks like there is still an issue with the tar archive file.
How to reproduce.
Navigate to the following page: https://www.nagios.org/ncpa/#downloads
under the " **Nagios Plugin**
_For active checks. Version: 1.2.4_" click on link 
"Download check_ncpa.py" 
After downloading, unpack it to some temp dir. View the content of unpacked "check_ncpa.py" the size and content of the file don't look normal.
Please review and advise.

**Comment by dan-m-joh** [comment]
I can confirm this.

The Downloaded file, "check_ncpa.tar.gz", contains "CHANGES.rst" and "check_ncpa.py".
Looking closer at the "check_ncpa.py"-file I can see that it is in it self a "tar.gz"-file and that it only contains "CHANGES.rst".

**Comment by jomann09** [comment]
Okay I do believe this is fixed now, it should have the proper files.

**Comment by dan-m-joh** [comment]
Nope.
Still the same issue...

--  

D/\N

**Comment by jomann09** [comment]
Very weird, I cleared some caching and tested again and I think it's now the correct version. I was able to extract and run it.

**Comment by yderi** [comment]
I confirm
Now the archive has the correct content.
Thanks to everyone.

**Comment by dan-m-joh** [comment]
Yes, now it looks OK.
Thanks!
