### ISSUE TITLE
Passive Check Queue

### ISSUE THREAD

**Issue by scot0357** [NagiosEnterprises/ncpa#75]
Passive checks should have a queue if it fails to contact the server with a check. It should store the result somewhere and try to resend it on the next interval. This should be kept in a file in case of server restart.

**Comment by scot0357** [comment]
Changing this milestone to 1.9 due to this holding back the 1.8 which has critical fixes.

**Comment by jhomann** [comment]
Closing this due to the fact that NRDP cannot write old check data (actually it can in XI 5+ but we don't have that "available" normally and isn't very well done) so this is essentially pointless. Your checks would all come in as "now" and overwrite eachother.
