### ISSUE TITLE
check_ncpa option to return "Unknown" status when "socket timeout" is encountered

### ISSUE THREAD

**Issue by Petaris** [NagiosEnterprises/ncpa#761]
We have had issues where a bunch of services will alert with "socket timeout" messages when the host has gone down or become unresponsive.  When digging into how to address this I found that check_nrpe had an option to return an "unknown" status when that occurred, which you could then set not to alert.  Would it be possible to do the same with check_ncpa?

**Comment by Petaris** [comment]
Example alerts generated in this circumstance:

## Email alert

***** Nagios Monitor XI Alert *****

Notification Type: PROBLEM

Service: Some Service
Host: XX-SERVER-X01
Address: 10.0.0.5
State: CRITICAL

Date/Time: Sometime

Additional Info:

**CRITICAL - Socket timeout**




## API alert

Description: 	Notification Type: PROBLEM
Service: Some Service
Host: XX-SERVER-X01
Address: 10.0.0.5
State: CRITICAL
Additional Info: (**Service check timed out after 60.01 seconds**)
Date/Time: Sometime
Responders: 	SomeTeam
Owner: 	someguy@someplace.com
Details: 	
host_address 	: 	10.0.0.5
host_alias 	: 	XX-SERVER-X01
host_attempt 	: 	1
host_duration 	: 	30d 21h 51m 0s
host_group_name 	: 	olp
host_latency 	: 	0.007
host_name 	: 	XX-SERVER-X01
host_output 	: 	OK - 10.0.0.5 rta 0.266ms lost 0%
host_perf_data 	: 	rta=0.266ms;3000.000;5000.000;0; pl=0%;80;100;0;100 rtmax=0.523ms;;;; rtmin=0.179ms;;;;
host_state 	: 	UP
host_state_type 	: 	HARD
last_host_check 	: 	1618193723
last_host_state_change 	: 	1615523098
last_service_check 	: 	1618193698
last_service_state_change 	: 	1618193698
max_host_attempts 	: 	3
max_service_attempts 	: 	HARD
nagios_server 	: 	default
service_attempt 	: 	3
service_desc 	: 	Memory Usage
service_duration 	: 	0d 0h 1m 0s
service_group_name 	: 	$
service_latency 	: 	0.000
service_output 	: 	(**Service check timed out after 60.01 seconds**)
service_state 	: 	CRITICAL
service_state_type 	: 	HARD
Source: 	NagiosXIV2
Integration: 	Nagios XI (NagiosXIV2)
Created At: 	Sometime

**Comment by ccztux** [comment]
Can you please provide the versions of the ```NCPA agent``` and the client script ```check_ncpa.py``` you are using?

On my test system i get an ```UNKNOWN``` state in some different testcases.
Versions i have used for testing:
```
[root@centos7-02 src]# /usr/local/ncpa/ncpa_listener --version
ncpa_listener version, 2.3.1
```
```
[root@centos7-01 client]# ./check_ncpa.py --version
check_ncpa.py, Version 1.2.4
```


Testcase 1: The firewall on the host running the NCPA agent is blocking all traffic from the host were i have called ```check_ncpa.py```:
```
[root@centos7-01 client]# ./check_ncpa.py -H 10.0.0.117 -t mytoken -M cpu/percent -w 98 -c 99 -q aggregate=avg
UNKNOWN: Execution exceeded timeout threshold of 60s
[root@centos7-01 client]# echo $?
3
```

Testcase 2: There is no host with the ip 10.0.0.2
```
[root@centos7-01 client]# ./check_ncpa.py -H 10.0.0.2 -t mytoken -M cpu/percent -w 98 -c 99 -q aggregate=avg
UNKNOWN: An error occured connecting to API. (Connection error: '[Errno 113] No route to host')
[root@centos7-01 client]# echo $?
3
```

**Comment by ccztux** [comment]
I am surprised, because of the difference of the serviceoutput ```(**Service check timed out after 60.01 seconds**)``` here:
> ## API alert
> 
> Description: Notification Type: PROBLEM
> Service: Some Service
> Host: XX-SERVER-X01
> Address: 10.0.0.5
> State: CRITICAL
> Additional Info: (**Service check timed out after 60.01 seconds**)
> Date/Time: Sometime
> Responders: SomeTeam
> Owner: [someguy@someplace.com](mailto:someguy@someplace.com)
> Details:
> host_address : 10.0.0.5
> host_alias : XX-SERVER-X01
> host_attempt : 1
> host_duration : 30d 21h 51m 0s
> host_group_name : olp
> host_latency : 0.007
> host_name : XX-SERVER-X01
> host_output : OK - 10.0.0.5 rta 0.266ms lost 0%
> host_perf_data : rta=0.266ms;3000.000;5000.000;0; pl=0%;80;100;0;100 rtmax=0.523ms;;;; rtmin=0.179ms;;;;
> host_state : UP
> host_state_type : HARD
> last_host_check : 1618193723
> last_host_state_change : 1615523098
> last_service_check : 1618193698
> last_service_state_change : 1618193698
> max_host_attempts : 3
> max_service_attempts : HARD
> nagios_server : default
> service_attempt : 3
> service_desc : Memory Usage
> service_duration : 0d 0h 1m 0s
> service_group_name : $
> service_latency : 0.000
> service_output : (**Service check timed out after 60.01 seconds**)
> service_state : CRITICAL
> service_state_type : HARD
> Source: NagiosXIV2
> Integration: Nagios XI (NagiosXIV2)
> Created At: Sometime



and the additional info in the notification ```**CRITICAL - Socket timeout**```:
> 
> 
> Example alerts generated in this circumstance:
> ## Email alert
> 
> ***** Nagios Monitor XI Alert *****
> 
> Notification Type: PROBLEM
> 
> Service: Some Service
> Host: XX-SERVER-X01
> Address: 10.0.0.5
> State: CRITICAL
> 
> Date/Time: Sometime
> 
> Additional Info:
> 
> **CRITICAL - Socket timeout**

**Comment by Petaris** [comment]
ncpa_listener version, 2.3.0
check_ncpa.py, Version 1.2.3

Sorry, that was my mistake.  Those are actually two different examples.

The corresponding email notification had:  

> Additional Info:

> (Service check timed out after 60.01 seconds)

The "socket timeout" is from a different alert.  Sorry, I guess it is just the "Service check timed out after xx.xx seconds" that needs to be handled from the NCPA side.  The "socket timeout" came from an HTTP check, so it is not related.

**Comment by ccztux** [comment]
> ncpa_listener version, 2.3.0
> check_ncpa.py, Version 1.2.3

Thank you.

 
> Sorry, that was my mistake. Those are actually two different examples.

No problem. :)


> The corresponding email notification had:
> 
> > Additional Info:
> 
> > (Service check timed out after 60.01 seconds)
> 
> The "socket timeout" is from a different alert. Sorry, I guess it is just the "Service check timed out after xx.xx seconds" that needs to be handled from the NCPA side. The "socket timeout" came from an HTTP check, so it is not related.


The message ```Service check timed out after xx.xx seconds``` comes from nagios and you can configure the ```service_check_timeout``` which is global in the main nagios configuration file ```nagios.cfg``` [as described in the official documentation.](https://assets.nagios.com/downloads/nagioscore/docs/nagioscore/4/en/configmain.html)
Every service check will be killed when the value of the ```service_check_timeout``` will be reached.

It is also possible to configure the state which the checks should have, when the ```service_check_timeout``` will be reached with the configuration directive ```service_check_timeout_state```. [Also described in the official documentation](https://assets.nagios.com/downloads/nagioscore/docs/nagioscore/4/en/configmain.html)

I would recommend you the following:
Set the timeout option when calling ```check_ncpa.py``` and this timeout should be less then the ```service_check_timeout``` configured in your ```nagios.cfg``` for example:
```
[root@centos7-01 client]# time -p ./check_ncpa.py -H 10.0.0.117 -t mytoken --timeout=59 -M cpu/percent -w 98 -c 99 -q aggregate=avg
UNKNOWN: Execution exceeded timeout threshold of 59s
real 59.03
user 0.03
sys 0.00
```

This should help.

**Comment by ccztux** [comment]
I will change the default timeout value from 60s to 59s and provide this via a pull request. Maybe the pull request will be accepted.

**Comment by Petaris** [comment]
Thanks, we will look into making those changes.  I appreciate the help!  :)

**Comment by ccztux** [comment]
Your are welcome! :)

**Comment by jomann09** [comment]
Closing this since it's been merged. This actually makes a lot of sense, due to the timeout happening on the Core side you don't get to see the actual reason, so this is helpful.
