### ISSUE TITLE
Connection to NRDP server can hang indefinitely

### ISSUE THREAD

**Issue by ejonsson** [NagiosEnterprises/ncpa#776]
According to [Requests docs](https://docs.python-requests.org/en/master/user/quickstart/#timeouts), if a timeout value isn't defined explicitly, the request never times out.

There is no timeout value for requests.post in agent/passive/utils.py, so the timeout exception will likely never be reached.

**Comment by ccztux** [comment]
Thanks for pointing this out! I will provide a fix via a pull request.

**Comment by jomann09** [comment]
Merged the pull request for 2.4.0
