### ISSUE TITLE
not able to run ncpa under ldap user

### ISSUE THREAD

**Issue by maniasso** [NagiosEnterprises/ncpa#784]
I have installed the ncpa for AIX and I noticed the agent can't start if nagios id is from LDAP

root@server01:/home/robfm/ncpa# /usr/local/ncpa/ncpa_passive -n
ERROR:root:'getpwnam(): name not found: nagios'
Traceback (most recent call last):
  File "ncpa_passive.py", line 93, in <module>
  File "/tmp/test/ncpa/agent/ncpadaemon.py", line 78, in main
  File "/tmp/test/ncpa/agent/ncpadaemon.py", line 131, in read_basic_config
  File "/tmp/test/ncpa/agent/ncpadaemon.py", line 378, in get_uid_gid
**KeyError: 'getpwnam(): name not found: nagios'**

After create the id locally, the ncpa agent started, is there any way to overcome that? My environment is based on LDAP, no loca lusers anymore.

**Comment by MrPippin66** [comment]
I wouldn't recommend using base service accounts in LDAP, but in any case, did you setup the ID with LAM integration in mind?

http://www.redbooks.ibm.com/redbooks/pdfs/sg247165.pdf

 Chapter 2. History of AIX and LDAP 232.2.1  Loadable authentication module (LAM) framework
 
 You need that if you intend to use base OS lookup functions for IDs in AIX.

**Comment by MrPippin66** [comment]
Also....did you enable PAM? If not, that may be why base OS functions are being referenced. You need LDAP aware PAM functions, if you do.

**Comment by maniasso** [comment]
Thank you, I missed that configuration, after that it worked.
