### ISSUE TITLE
ncpa.cfg mistake causes it to not honor plugin_timeout and uses default (60) - no errors in ncpa_listener.log

### ISSUE THREAD

**Issue by ssaxnagios** [NagiosEnterprises/ncpa#798]
ncpa.cfg mistake causes it to not honor plugin_timeout and uses default (60) - no errors in ncpa_listener.log:

I tested with a .ps1 script:

```Start-Sleep -s 120```

Example:
- \# **Extensions for plugins** was missing the beginning #

```
plugin_timeout = 120

#
# Comma separated list of plugins to run through sudo. Note: You will need to update your sudoers
# configuration for these plugins to work when called with sudo.
#
# Example: check_special,check_root_files
# (Command line: sudo /<plugin_absolute_path>/check_special <arguments>)
#
# This is for Unix only (Linux, Mac OS X, etc)
#
# run_with_sudo =

#
 Extensions for plugins
# ----------------------
# The extension for the plugin denotes how NCPA will try to run the plugin. Use this
```

Adding the # back to **Extensions for plugins** and restarting the ncpa_listener service resolved it.

The other checks still worked but the timeout was 60, may want to do some config validation for anomalies.

**Comment by jomann09** [comment]
Closing this as I don't think we will be doing much config validation. If anyone has a suggestion let us know.
