### ISSUE TITLE
Feature Request: api/processes should support username as a filter

### ISSUE THREAD

**Issue by MrPippin66** [NagiosEnterprises/ncpa#809]
It's common in our environment to have multiple instances of a product run under different IDs on a single system.

The current api/processes doesn't include the ability to filter by username, which complicates monitoring using the builtin process monitor.

The report already includes 'username' in the case of  process match, so the agent already has the information, It just needs to update the filter criteria updated to include 'username'.

Example:

```OK: Process count for processes named systemd was 1
Processes Matched
PID: Name: Username: Exe: Memory: CPU
-----------------------------------
1: systemd: root: 0.02 % (VMS 0.20 GB, RSS 0.01 GB): 0.03 %

**Comment by MrPippin66** [comment]
@jomann09 Sorry to tag you, directly. Has anyone reviewed this? This is something the NRPE plugin supports, and I'd think is very desirable. I can't use that solution for Windows, since NRPE plugins aren't used on Windows.

**Comment by MrPippin66** [comment]
@jomann09 Is this being considered for future enhancement?

**Comment by MrPippin66** [comment]
@sawolf I realize there's a large backlog all pending getting 3.0 out the door, but any chance this can get evaluating for inclusion not long after? It's very limiting for our process monitoring. We're using the legacy plugins in the interim

**Comment by sawolf** [comment]
Hi @MrPippin66 - I'm not in charge of the roadmap, but I'm adding it to the milestone so that people can find it later. I don't believe the current 3.0 milestone is accurate to what we're planning to ship for that release, but I don't see a reason that this couldn't be implemented.

**Comment by MrPippin66** [comment]
Any update for this? This was aimed for 3.10, but I don't show it was included.

**Comment by ne-bbahn** [comment]
Unless I'm mistaken about what you're asking for, this is already functioning in NCPA. 

There does seem to be some discrepancies in special character parsing that are causing issues on Windows, though. 
i.e. the API is outputting a username as `MY PC Name\\username`, but to filter by this, you need to use `MY PC Name\username`. 

I will note this in an existing issue if I can find one or create a new issue if not.
