### ISSUE TITLE
NCPA not recognizing process on Linux

### ISSUE THREAD

**Issue by MrPippin66** [NagiosEnterprises/ncpa#832]
NCPA = 2.3.1
Linux = Red Hat Enterprise Linux 7.9

When running a processes check for 'ora_pmon_autoddiu' it's failing despite the process showing in a process list.

Process check:

/usr/local/nagios/libexec/check_ncpa.py -T 60 -t [ticket] -S -H ftwlxorar002 -M processes -q 'name=ora_pmon_autoddiu,critical=1:1'

Result:

CRITICAL: Process count for processes named ora_pmon_autoddiu was 0 | 'process_count'=0;;1:1;

Process does exist:

#  ps -eaf | grep ora_pmon
oracle   103680      1  0 Nov21 ?        00:01:03 ora_pmon_ciptemp
oracle   118908      1  0 Nov17 ?        00:01:48 ora_pmon_tosd1000
oracle   118976      1  0 Nov17 ?        00:01:25 ora_pmon_tut01000
oracle   118977      1  0 Nov17 ?        00:01:21 ora_pmon_rmandb
oracle   118981      1  0 Nov17 ?        00:01:23 ora_pmon_sigt1000
oracle   118983      1  0 Nov17 ?        00:01:21 ora_pmon_pmit1000
oracle   118986      1  0 Nov17 ?        00:01:36 ora_pmon_xbt01000
oracle   118988      1  0 Nov17 ?        00:01:21 ora_pmon_xbt02000
oracle   118991      1  0 Nov17 ?        00:01:25 ora_pmon_autotdiu
oracle   119450      1  0 Nov17 ?        00:01:31 ora_pmon_zdtibt01
oracle   119454      1  0 Nov17 ?        00:01:25 ora_pmon_mcat1000
oracle   119740      1  0 Nov17 ?        00:02:17 ora_pmon_cit03000
oracle   121113      1  0 Nov17 ?        00:01:25 ora_pmon_ent02000
oracle   122798      1  0 Nov17 ?        00:01:27 ora_pmon_ent03000
oracle   143637      1  0 Nov26 ?        00:01:29 ora_pmon_autoddiu

If I do a regex search, this process doesn't show up, either.

/usr/local/nagios/libexec/check_ncpa.py -T 60 -t [ticket] -H ftwlxorar002 -M processes -q 'name=ora_pmon_,match=regex,critical=1:1'
CRITICAL: Process count for processes named ora_pmon_ was 14 | 'process_count'=14;;1:1; 'cpu'=0.0%;;; 'memory'=0.3%;;; 'memory_vms'=47.84GB;;; 'memory_rss'=0.3GB;;;
Processes Matched
PID: Name: Username: Exe: Memory: CPU
-----------------------------------
103680: ora_pmon_ciptemp: oracle: 0.02 % (VMS 4.74 GB, RSS 0.02 GB): 0.00 %
118908: ora_pmon_tosd1000: oracle: 0.03 % (VMS 1.55 GB, RSS 0.03 GB): 0.00 %
118976: ora_pmon_tut01000: oracle: 0.02 % (VMS 1.23 GB, RSS 0.02 GB): 0.00 %
118977: ora_pmon_rmandb: oracle: 0.02 % (VMS 1.47 GB, RSS 0.02 GB): 0.00 %
118981: ora_pmon_sigt1000: oracle: 0.02 % (VMS 1.23 GB, RSS 0.02 GB): 0.00 %
118983: ora_pmon_pmit1000: oracle: 0.02 % (VMS 1.31 GB, RSS 0.02 GB): 0.00 %
118986: ora_pmon_xbt01000: oracle: 0.02 % (VMS 1.57 GB, RSS 0.02 GB): 0.00 %
118988: ora_pmon_xbt02000: oracle: 0.02 % (VMS 1.33 GB, RSS 0.02 GB): 0.00 %
118991: ora_pmon_autotdiu: oracle: 0.02 % (VMS 1.07 GB, RSS 0.02 GB): 0.00 %
119450: ora_pmon_zdtibt01: oracle: 0.02 % (VMS 2.56 GB, RSS 0.02 GB): 0.00 %
119454: ora_pmon_mcat1000: oracle: 0.02 % (VMS 2.61 GB, RSS 0.02 GB): 0.00 %
119740: ora_pmon_cit03000: oracle: 0.03 % (VMS 9.07 GB, RSS 0.03 GB): 0.00 %
121113: ora_pmon_ent02000: oracle: 0.02 % (VMS 9.05 GB, RSS 0.02 GB): 0.00 %
122798: ora_pmon_ent03000: oracle: 0.02 % (VMS 9.05 GB, RSS 0.02 GB): 0.00 %

Total Memory: 0.30 % (VMS 47.84 GB, RSS 0.30 GB)
Total CPU: 0.00 %

**Comment by MrPippin66** [comment]
I believe I've found the problem, and not sure if there's a way around this. Looks like "psutil" is using the information in /proc/<pid>/stat to get the process name, and in this case, despite what "ps" is showing, "psutil" is showing the process name as "oracle', since that's what /proc/<pid>/stat is showing.

**Comment by MrPippin66** [comment]
I resolved this by using "cmd" option, instead of "name".

However, the output from the check only includes "name" and not "cmd". I don't see an option to have the "cmd" supplied in the output. Am I missing something, or do I need to submit a feature request to add this?

**Comment by jomann09** [comment]
The cmd is not output and probably won't be in the future just due to the size of all the data, unless there's a good reason to add it - if there is you can submit a feature request.
