### ISSUE TITLE
ubuntu repo old version

### ISSUE THREAD

**Issue by timcanty** [NagiosEnterprises/ncpa#836]
Hi the repo for ncpa doesn't contain the new 2.4.0 version, assume this will be updated soon?

https://repo.nagios.com/deb/focal/pool/main/

**Comment by plao** [comment]
here? 

https://www.nagios.org/ncpa/#downloads

**Comment by timcanty** [comment]
![image](https://user-images.githubusercontent.com/32928117/146544750-477c1826-7a88-4ac6-804c-bbe0e2d36c02.png)
 the repo which is the recommended way to install ncpa on ubuntu only has the 2.31 and not 2.4.0

**Comment by jomann09** [comment]
Yeah sorry had an issue with the repo server it should be updated today.

**Comment by plao** [comment]
> Yeah sorry had an issue with the repo server it should be updated today.

Thanks a lot!

**Comment by jomann09** [comment]
This should be updated now, so closing this.
