### ISSUE TITLE
Question: New release with latest psutil version

### ISSUE THREAD

**Issue by ccztux** [NagiosEnterprises/ncpa#844]
Unfortunately `psutil` `5.9.0` was [released ](https://github.com/giampaolo/psutil/blob/master/HISTORY.rst)a few days after releasing `NCPA` `2.4.0`.

There are some issues which probably could be solved by an update of psutil:
- https://github.com/NagiosEnterprises/ncpa/issues/807
- https://github.com/NagiosEnterprises/ncpa/issues/768
- https://github.com/NagiosEnterprises/ncpa/issues/637
- https://github.com/NagiosEnterprises/ncpa/issues/476

Is there a plan to release a new version of `NCPA` using the latest `psutil` in the near future?

**Comment by jomann09** [comment]
We did do a version for debian 11, but we did not rebuild the current versions that exist, we may need to do a 2.4.1 version although we might be skipping to 3 depending on how things go. I'll have to talk about this internally and see if we want to do a 2.4.1 with the latest pstuil.

**Comment by ne-bbahn** [comment]
The psutil library is now pulled in automatically by pip now, so I am going to close this.
