### ISSUE TITLE
Unable to start ncpa service in Linux Server if any FileSystem issue

### ISSUE THREAD

**Issue by adi6711** [NagiosEnterprises/ncpa#852]
Nagios Support ticket :    Unable to start ncpa service in Linux Server #505820
https://support.nagios.com/tickets/tickets.php?id=17017

Unable to start ncpa service in Linux Server if any FileSystem having issue.
basically if df -h is hung then ncpa will also hang

OS Version: rhel 7.9

We tested by installing latest version of agent and tried but still issue is same.

● ├─system.slice
● └─basic.target
● ├─microcode.service
● ├─rhel-dmesg.service
● ├─[selinux-policy-migrate-local-changes@targeted.serv](mailto:selinux-policy-migrate-local-changes@targeted.serv)ice
● ├─paths.target
● ├─slices.target
● │ ├─-.slice
● │ └─system.slice
● ├─sockets.target
● │ ├─dbus.socket
● │ ├─dm-event.socket
● │ ├─iscsid.socket
● │ ├─iscsiuio.socket
● │ ├─rpcbind.socket
● │ ├─systemd-initctl.socket
● │ ├─systemd-journald.socket
● │ ├─systemd-shutdownd.socket
● │ ├─systemd-udevd-control.socket
● │ ├─systemd-udevd-kernel.socket
● │ └─uuidd.socket
● ├─sysinit.target
● │ ├─dev-hugepages.mount
● │ ├─dev-mqueue.mount
● │ ├─dmraid-activation.service
● │ ├─iscsi.service
● │ ├─kmod-static-nodes.service
● │ ├─lvm2-lvmetad.socket
● │ ├─lvm2-lvmpolld.socket
● │ ├─lvm2-monitor.service
● │ ├─multipathd.service
● │ ├─plymouth-read-write.service
● │ ├─plymouth-start.service
● │ ├─proc-sys-fs-binfmt_misc.automount
● │ ├─rhel-autorelabel-mark.service
● │ ├─rhel-autorelabel.service
● │ ├─rhel-domainname.service
● │ ├─rhel-import-state.service
● │ ├─rhel-loadmodules.service
● │ ├─sys-fs-fuse-connections.mount
● │ ├─sys-kernel-config.mount
● │ ├─sys-kernel-debug.mount
● │ ├─systemd-ask-password-console.path
● │ ├─systemd-binfmt.service
● │ ├─systemd-firstboot.service
● │ ├─systemd-hwdb-update.service
● │ ├─systemd-journal-catalog-update.service
● │ ├─systemd-journal-flush.service
● │ ├─systemd-journald.service
● │ ├─systemd-machine-id-commit.service
● │ ├─systemd-modules-load.service
● │ ├─systemd-random-seed.service
● │ ├─systemd-sysctl.service
● │ ├─systemd-tmpfiles-setup-dev.service
● │ ├─systemd-tmpfiles-setup.service
● │ ├─systemd-udev-trigger.service
● │ ├─systemd-udevd.service
● │ ├─systemd-update-done.service
● │ ├─systemd-update-utmp.service
● │ ├─systemd-vconsole-setup.service
● │ ├─cryptsetup.target
● │ ├─local-fs.target
● │ │ ├─-.mount
● │ │ ├─boot.mount
● │ │ ├─rhel-readonly.service
● │ │ ├─systemd-remount-fs.service
● │ │ ├─usr-sap.mount
● │ │ └─var-log.mount
● │ └─swap.target
● │ └─dev-mapper-vg0\x2dswap.swap
● └─timers.target
● └─systemd-tmpfiles-clean.timer

What kind of filesystems are you having trouble with? Are they local or NFS mounts?  : Issue with both FS

Update from nagios support:
I suggest you submit a bug for this issue here:
https://github.com/NagiosEnterprises/ncpa/issues

and include as many details about when and how you run into this as possible (or at least a link to this ticket)
I discussed this with one of the developers, so they're aware of it (though this is an issue we haven't heard of from anyone else until now).
I'm sorry we don't have an immediate solution for you, though.
--Jeffrey

Hope there is a bug. If possible, please simulate the issue in your lab and do the needful

**Comment by MrPippin66** [comment]
This ultimately is a problem in psutil, and would be difficult to address within NCPA. A contributor attempted to get this resolved in psutil, but this was not agreed as an issue that could be resolved in psutil, either.

https://github.com/giampaolo/psutil/issues/1931

I agree it's a problem, since it causes the entire agent to stop functioning.
