### ISSUE TITLE
Debian 11 repo

### ISSUE THREAD

**Issue by gardart** [NagiosEnterprises/ncpa#853]
I can't find the deb repo for NCPA for Debian 11 here https://repo.nagios.com/?repo=deb-debian
Will it be released for Debian 11?

**Comment by jomann09** [comment]
I'll add this to the list, should be coming soon, there is an debian 11 version of NCPA but it does not have a repo yet.
Will update this issue when it's added.

**Comment by jomann09** [comment]
I'm sorry this took so long, we've got the repo added now, should be here https://repo.nagios.com/?repo=deb-debian
