### ISSUE TITLE
How do check if a counter less than X but not zero?

### ISSUE THREAD

**Issue by riahc3** [NagiosEnterprises/ncpa#858]
Hello

Kind of a strange request I know.

I have the following (similar) check:

./check_ncpa.py -H localhost -t 'fkoldjghlkdfjhgkdf' -M 'windowscounters/acounter' -w 10: -c 5:

Which means that is gives a warning when it is less than 10 but great than 5 and it gives a critical if it is less 5 BUT....I would like it to ignore "0" (It would give a OK if 0).

Is this possible?

Thank you

**Comment by ericloyd** [comment]
Everything you need is in the document link I provided previously (https://nagios-plugins.org/doc/guidelines.html#THRESHOLDFORMAT).  You may need to use ranges and not just : to specify what you're looking for.  I think you're looking for
```
-c @1:5
```
Which means to become critical if it's between 1 and 5.  If you want less than 5, change it to @1-4.

**Comment by riahc3** [comment]
The documentation is not clear but I more or less figured it out.

**Comment by jomann09** [comment]
Closing this since it was solved.
