### ISSUE TITLE
Debugging NCPA on Windows

### ISSUE THREAD

**Issue by MrPippin66** [NagiosEnterprises/ncpa#860]
Does the Windows version have different debugging options for the command line? When I try to manually start the agent from powershell with the "-n" option, it still "daemonizes" with no output going to the shell session.

This is what I do on Unix to debug issues with errors coming from openssl.

We're running 2.4.0.

**Comment by jomann09** [comment]
Are you running a development version of NCPA or are you trying to run the regular exe from the command line?

**Comment by MrPippin66** [comment]
The pre-packaged regular version.

**Comment by jomann09** [comment]
Ah okay that makes sense, due to how cx_Freeze bundles the Windows version you can't run it as anything but a service so it will basically just start a service when you run the exe file. I don't know of a good way around it without using the repo/dev version.

**Comment by jomann09** [comment]
Closing this since no response.
