### ISSUE TITLE
Disable OPTIONS nad HEAD methods if not needed

### ISSUE THREAD

**Issue by cdienger** [NagiosEnterprises/ncpa#861]
curl -XOPTIONS https://127.0.0.1:5693 -k -v

shows that OPTIONS and HEAD methods are enabled. Can these be disabled if not needed?

**Comment by jomann09** [comment]
This is a duplicate of #819 we cannot disable options due to flask not allowing it to be disabled (maybe some day in the future? At the moment it does not allow us to.
