### ISSUE TITLE
Bandwidth usage in Mbps

### ISSUE THREAD

**Issue by davix12** [NagiosEnterprises/ncpa#862]
Is there a way to have the bandwidth usage in Mbit/s? I use this command but I can't find a way to have bits instead of bytes:
`check_ncpa.py -H 192.168.0.1 -t abcd -P 5693 -M 'interface/NIC1/bytes_recv' -u M -d 1`

**Comment by HunnyPuns** [comment]
It looks like there's not an option for *bits/s. But you can change it to another level of bytes per second by adding,

`-u M`

The above example will give you megabytes per second.

**Comment by jomann09** [comment]
As stated above, there's currently no setting for bits, a solution might be to convert it using a wrapper shell script on the Nagios/plugin side but atm there is no way to get it as bits.
