### ISSUE TITLE
NCPA agent will not install on Ubuntu 22.04 LTS 

### ISSUE THREAD

**Issue by sawolf** [NagiosEnterprises/ncpa#868]
I'm copying an issue that was placed in nagios-plugins by mistake: https://github.com/nagios-plugins/nagios-plugins/issues/656

"The NCPA agent will not install on Ubuntu 22.04 LTS. A dependency cannot be met for libssl1.0.0.

Case 00001762"

**Comment by jorgeyanesdiez** [comment]
Ideally NCPA should be able to use libssl3 but it's probably not a quick thing to fix.
Meanwhile there's this hacky, bad and probably even slightly dangerous solution, but it works: 

```
echo "deb http://security.ubuntu.com/ubuntu impish-security main" | sudo tee /etc/apt/sources.list.d/impish-security.list
sudo apt update
sudo apt install libssl1.1
sudo rm /etc/apt/sources.list.d/impish-security.list
sudo apt update
```

**Comment by ericloyd** [comment]
So 21.10 is EOL and 22.04 is the de-facto new install version these days.  Any forward movement on this yet?  We have a slate of machines destined for NCPA that we can't install on and can't muck with repo lists.

**Comment by jomann09** [comment]
Sorry for the late response on this, I've been able to build a test version of NCPA 2.4.0 on Ubuntu 22, I'm still doing some testing to ensure it's OK but it seems fine, if it's good to go it'll be added to downloads/repos here shortly.
https://assets.nagios.com/downloads/ncpa/dev/ncpa-2.4.0.u22.amd64.deb

**Comment by jomann09** [comment]
Just a side note though, this is using a bundled version of OpenSSL 1.1.1g and until NCPA 3 this is basically what'll have to be done, but NCPA 3 will likely be out by the end of the year so the good news is this is temporary, it's just necessary since we still use Python 2.7 on this version of NCPA.

**Comment by Zendog** [comment]
I am getting a 404 error on the link above. Has the updated version been added to the repos? Where can I get the updated version for testing?

**Comment by Zendog** [comment]
Looks like it is updated in the repos. I was able to install the latest version. Thanks for the work here.

**Comment by michellabbe** [comment]
The new build on the jammy repo is working fine so far, however `apt update` complains on deprecated keyring:

> W: https://repo.nagios.com/deb/jammy/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.


You should update the installation instructions of the download page.

Instead of:
```
echo "deb https://repo.nagios.com/deb/jammy /" | sudo tee -a /etc/apt/sources.list.d/nagios.list > /dev/null
wget -qO - https://repo.nagios.com/GPG-KEY-NAGIOS-V2 | sudo apt-key add -
```

This works:
```
echo "deb [signed-by=/usr/share/keyrings/ncpa.gpg] https://repo.nagios.com/deb/jammy /" | sudo tee -a /etc/apt/sources.list.d/nagios.list > /dev/null
wget -qO - https://repo.nagios.com/GPG-KEY-NAGIOS-V2 | gpg --dearmor | sudo tee /usr/share/keyrings/ncpa.gpg > /dev/null
```

**Comment by sawolf** [comment]
I think we fixed this w/ the NCPA 3 release and forgot to close
