### ISSUE TITLE
Requesting packacge for Ubuntu 22.04 LTS in repo

### ISSUE THREAD

**Issue by kfoxton** [NagiosEnterprises/ncpa#879]
The repo install method results in a dependency issue:

The following packages have unmet dependencies:
 ncpa : Depends: libssl1.1 (>= 1.1.0i) but it is not installable
E: Unable to correct problems, you have held broken packages.

**Comment by jorgeyanesdiez** [comment]
Ideally NCPA should be able to use libssl3 but it's probably not a quick thing to fix.
Meanwhile there's this hacky, bad and probably even slightly dangerous solution, but it works: 

`
echo "deb http://security.ubuntu.com/ubuntu impish-security main" | sudo tee /etc/apt/sources.list.d/impish-security.list
sudo apt update
sudo apt install libssl1.1
sudo rm /etc/apt/sources.list.d/impish-security.list
sudo apt update
`

**Comment by jorgeyanesdiez** [comment]
See https://github.com/NagiosEnterprises/ncpa/issues/868#issuecomment-1192542879

**Comment by jomann09** [comment]
Closing this as a duplicate, we will be getting a ubuntu 22 version out here soon.
