### ISSUE TITLE
Monitor Uptime in NCPA

### ISSUE THREAD

**Issue by christianbobila** [NagiosEnterprises/ncpa#883]
Hi,

May I ask what is the equivalent command to monitor application running on the host via NCPA.

Example you may refer to this picture below is via NSCLient++.

![NSClient](https://user-images.githubusercontent.com/109059555/179132240-29e4a148-dc62-42fb-81b4-a1819d626c21.jpg)

Thank you

**Comment by ericloyd** [comment]
Have you explored the NCPA wizard or the NCPA GUI at all?  It's very simple.  Go to the GUI, and go to Processes, then add whatever filter you want to find the process you're looking for.  Then select "View in alternate format" and use the check_ncpa.py format, and you can now check it easily from the NCPA agent plugin:

![image](https://user-images.githubusercontent.com/2440508/179506950-2af494ca-05af-40b4-9cb2-8b146622ea72.png)

**Comment by christianbobila** [comment]
Thank you for the information.
