### ISSUE TITLE
Notification escalation of NagiosXi

### ISSUE THREAD

**Issue by christianbobila** [NagiosEnterprises/ncpa#885]
Hi, 
May I ask on how to set up configuration "alert level" - within 30 min for alert level 1 and before or after 1 hour for alert level 2 ? Can you provide us a copy of document to walk trough.

 

I have a testing environment to try this notification on our end an error occur.

![image](https://user-images.githubusercontent.com/109059555/181397117-11af636d-d702-452d-a7fd-cca1f1d0bef1.png)

**Comment by jomann09** [comment]
This github is for NCPA and these are issues related to NCPA, not Nagios XI - you should either contact support or check out https://support.nagios.com for more info.
