### ISSUE TITLE
Finalize Python 3 and OS Support

### ISSUE THREAD

**Issue by corynorell** [NagiosEnterprises/ncpa#914]
Before an initial release of NCPA 3.0.0, we need to ensure there are no issues with Python 3 and NCPA installs on all supported operating systems.

**Comment by corynorell** [comment]
Hey @pittagurneyi,

The latest development work is currently happening on a fork of this repository. We're going to work on getting that fork merged back into this repository sooner rather than later so everyone has more insight into the latest happenings with NCPA 3.0. 

As of now, we're probably looking at another month or so to work out some of the issues regarding Windows applications of NCPA. Initial Linux and Mac builds are running but need more thorough QA before we call them good.

We're also kicking around the idea of releasing an experimental/beta build while 3.0 is still in development. If that's something you may be interested in please let me know.

I'll update the anticipated timeline now, thanks for poking me on the matter. I appreciate your patience!

**Comment by MrPippin66** [comment]
Is there any current expected due date? Last update for this is over 4 months ago.

**Comment by phreditorNG** [comment]
Folks:

NCPA v3.0.0 is in public beta, now, and can be downloaded at:  
https://www.nagios.org/ncpa/
Scroll down NCPA Beta Downloads

**Comment by MrPippin66** [comment]
Since 3.0 has long since officially been released, shouldn't this be complete?
