### ISSUE TITLE
FR:  Need Performance Graph for Services/Processes

### ISSUE THREAD

**Issue by vtracnagios** [NagiosEnterprises/ncpa#924]
A client want to have a performance graph for checking "services" and "processes".

Since checking for "services" only return "OK" for "Running" and "Failed) for "Stopped".  There isn't any "values" returned from the service check for graphing.

It would be nice to have "graph", which will let the client know if or when the NCPA agent stopped.

**Comment by ericloyd** [comment]
Are you talking about active checks performed by the Nagios server or passive checks generated by the remote host that are sent to the Nagios server through NRDP or other methods?

**Comment by vtracnagios** [comment]
The client is talking about active check data coming from NCPA to Nagios XI not displaying performing graph.

Example:
/usr/local/nagios/libexec/check_ncpa.py -H 192.168.x.x -t 'ncpaToken' -M 'services' -q 'service=ncpa_listener'
OK: ncpa_listener is running

As you can see from above, there is no value(s) returned from the check, so no graphs were generated.

**Comment by ericloyd** [comment]
This check returns a boolean value of "running" or "stopped" with no other values, that I'm aware of.  What possible performance data could it return?

**Comment by vtracnagios** [comment]
Which is why I opened this FR.
Make it return some number like "1" or "0" or "3" (unknown)  .... so that graph can be generated.

Anyway, I don't think this is really needed, but the client insisted that he wanted graph to be displayed.

**Comment by ericloyd** [comment]
This is what availability reports are for.  You should educate your customer on how to use them properly.  A world of reporting possibilities will be opened before their very eyes!

**Comment by ericloyd** [comment]
Also, why run a service check looking for the listener status?  We typically run a check looking for the NCPA server version number, then tie that as a dependency for all the active NCPA based service checks.  If that fails to respond, then the others don't trigger, plus you get to track the version number over time so you know when it's time to upgrade.

Lastly, isn't it "ncpalistener" not "ncpa_listener"?

**Comment by ccztux** [comment]
To get peformance data you can do this:

OK example:
```
08:37:18 ✓ LAB-CL01 root@cl01 ~ # /usr/lib64/meg/plugins/check_ncpa.py -H localhost -t mytoken -M services -q 'service=gssproxy' --performance
OK: gssproxy is running | 'status'=0;1;2;;
```

UNKNOWN example:

```
08:37:20 ✓ LAB-CL01 root@cl01 ~ # /usr/lib64/meg/plugins/check_ncpa.py -H localhost -t mytoken -M services -q 'service=gssproxyS' --performance
UNKNOWN: No services found for service names: gssproxyS | 'status'=3;1;2;;
```


Snippet from the help output of  `check_ncpa.py`:
```
  -p, --performance     Print performance data even when there is none. Will
                        print data matching the return code of this script
```

**Comment by ccztux** [comment]
> Also, why run a service check looking for the listener status? We typically run a check looking for the NCPA server version number, then tie that as a dependency for all the active NCPA based service checks. If that fails to respond, then the others don't trigger, plus you get to track the version number over time so you know when it's time to upgrade.
> 
> Lastly, isn't it "ncpalistener" not "ncpa_listener"?


It is `ncpa_listener`

```
08:41:07 ✓ LAB-CL01 root@cl01 ~ # /usr/lib64/meg/plugins/check_ncpa.py -H localhost -t mytoken -M services -q 'service=ncpa_listener' --performance
OK: ncpa_listener is running | 'status'=0;1;2;;
```

**Comment by vtracnagios** [comment]
Thanks guys!!  :-)
I think this issue can be close as there is an option "--performance", which can be used for this.

**Comment by vtracnagios** [comment]
I have just learned that there is an option "--performance", which can be used to generate performance graph for "services".

**Comment by ericloyd** [comment]
Ooops.  Windows sees the service name as "ncpalistener" while Linux sees it with the dash.

![image](https://user-images.githubusercontent.com/2440508/224733885-8083011f-33e5-4559-8f5f-7f1874e92c56.png)

**Comment by ccztux** [comment]
> Ooops. Windows sees the service name as "ncpalistener" while Linux sees it with the dash.
> 
> ![image](https://user-images.githubusercontent.com/2440508/224733885-8083011f-33e5-4559-8f5f-7f1874e92c56.png)

You are absolutely right. I forgot about the inconsistent naming.
