### ISSUE TITLE
Services not start after 2.4.1 is installed

### ISSUE THREAD

**Issue by gaguilard71** [NagiosEnterprises/ncpa#926]
Hi:
I am testing new NCPA version 2.4.1.
To test it I run the uninstall.exe of the installed version  ( 2.4.0).
After that I ran the ncpa installer of the new version (2.4.1) with admin privileges and after that the services listener and passive doesn´t listed into the services list.
I uninstalled version 2.4.1 and reinstalled the version 2.4.0 and services now are listed into the services.
I`d like to add that I use same settings for both installers.
I will looking forward for your comments.
Thank you.
Kind Regards.

**Comment by MrPippin66** [comment]
To be clear, after initial install of 2.4.1, you show no service names for the agent?

ncpalistener or ncpapassive

If so, can you run the following and see if an error occurs after you have 2.4.1 installed?

<install directory>\ncpa_listener.exe --install ncpalistener
<install directory>\ncpa_passive.exe --install ncpapassive

If no errors, are the services now showing?

**Comment by phreditorNG** [comment]
@gaguilard71 - what OS, distro, version, architecture? The way system services are handled has changed over time and by distro.

**Comment by phreditorNG** [comment]
I'm closing this since there has been no response for several months.
