### ISSUE TITLE
Unable To Graph Process Metrics

### ISSUE THREAD

**Issue by scot0357** [NagiosEnterprises/ncpa#93]
One can access process based metrics, but cannot graph them. This would be really cool to be able to do and its expected behavior. Handle multiple process of the same name by graphing them together.
In fact this would be a good time to think of a better way to query processes. But for now, lets focus on non-API breaking stuff.

**Comment by jomann09** [comment]
Closing this due to duplicate with #179 feature request. Will also point out that the values are now in a "graphable" version but still need a way to select a single object inside a process such a `mem_percent` or `cpu_percent`.
