### ISSUE TITLE
how do i call plugin scripts with extensions?

### ISSUE THREAD

**Issue by tonyguadagno** [NagiosEnterprises/ncpa#932]
hi, on this page https://support.nagios.com/kb/article/nagios-xi-using-scripts-plugins-with-ncpa-722.html the nagios docs give this example:
```
Test PowerShell Script From Nagios XI
The last step is to test the script from your Nagios XI server. Open an SSH session to Nagios XI and execute the following:

/usr/local/nagios/libexec/check_ncpa.py -H your_windows_server_ip_address -t your_windows_server_ncpa_token -P 5693 -M 'plugins/check_dummy.ps1' -q "args=2 Something_is_CRITICAL"
```
note that the plugin script has a .ps1 extension. 

when i try running a script with any extension, i get this error:
```
[nagios@nagios ~]$ /usr/local/nagios/libexec/check_ncpa.py -H ip -t token -P 5693 -M 'plugins/phpstatus.ps1'
UNKNOWN: An error occured connecting to API. (HTTP error: '500 INTERNAL SERVER ERROR')
```
if i take the extension off, it executes......  to be clear, I have this issue on any type of script...so script.sh does not work but script does.

so, how do i run a plugin script that has an extension?

thanks

**Comment by MrPippin66** [comment]
I assume this is on Windows. Is the extension upper or lower case. There should be a known issue if you use lower case, where for now the extension needs to be in upper case.

**Comment by tonyguadagno** [comment]
sorry, this is not windows.  it is rhel linux and it is not just powershell scripts.  any script with an extension will not work.  this seems to be contradicted by the documentation.

thx

**Comment by ericloyd** [comment]
I was unaware that PowerShell scripts ran on Linux.

What happens if you log into the machine in question as the user running the NCPA Listener (which is likely root) and execute the command you're trying to run through the agent:

```
/usr/local/ncpa/plugins/check_dummy.ps1 2 Something_is_CRITICAL
```

If it doesn't work at the command line, it won't work through the agent.

**Comment by MrPippin66** [comment]
PowerShell core is cross platform.

@tonyguadagno You said ANY extension doesn't work, and I'm not sure what you mean. The default configuration for Linux only supports by default the following:

# Defaults:
# .sh = /bin/sh $plugin_name $plugin_args
# .py = python $plugin_name $plugin_args
# .ps1 = powershell -ExecutionPolicy Bypass -File $plugin_name $plugin_args
# .vbs = cscript $plugin_name $plugin_args //NoLogo
# .bat = cmd /c $plugin_name $plugin_args

I've validated .sh works, for instance.

But...'.ps1' would be specific to Windows and you'd need to edit the config to correctly invoke powershell scripts on Linux.

**Comment by tonyguadagno** [comment]
hi, powershell is on linux and works really well (https://learn.microsoft.com/en-us/powershell/scripting/install/installing-powershell-on-linux?view=powershell-7.3#red-hat-enterprise-linux-rhel) I am able to run the script on the command line.   also, ncpa uses a user called 'nagios'.  that user can also run the script.

again, to be clear, this is not a powershell issue.  if i try to run a bash script like xyz.bash or xyz.sh that will also fail.  anytime the script has an extension, it fails.

**Comment by tonyguadagno** [comment]
ok, i appologize, i see my mistake.  this is a problem specific to powershell, i am able to run scripts with extensions for bash etc.  however, my original statement is the same....the documentation clearly states that you can run powershell scripts that way...and i get a 500 error when i try:
![image](https://user-images.githubusercontent.com/25204879/227525629-e2cdde67-b2af-4f9d-bf68-114bbf3a97ab.png)

**Comment by ericloyd** [comment]
When you log in to the target box, su to nagios, and run:

```
powershell -ExecutionPolicy Bypass -File /usr/local/ncpa/plugins/check_dummy.ps1 2 CRITICAL
```

What happens?  I'm fairly certain your PowerShell is trying to interact in a way that causes the HTTP protocol to break.

**Comment by tonyguadagno** [comment]
no, that works fine.  it is only when called via the api

```
 sudo su nagios
[sudo] password for tonyg:
[nagios@server tonyg@]$ pwsh -executionpolicy bypass -file /usr/local/ncpa/plugins/phpstatus.ps1
OK: Pool Name: www, ProcMGR: static, Total Procs: 100, IdleProcs: 48, MaxChildReached: 0, SlowReq: 0, ActiveProcs: 52 |ProcessUtilization=52%
[nagios@server tonyg@]$
```

**Comment by MrPippin66** [comment]
I'm well aware. That's because the entry is question is intended for Windows systems.

That's why it needs to be modified if you intend to run this on Linux systems.

Or..you can create an alias to "pwsh" called "powershell" in the system PATH.

**Comment by tonyguadagno** [comment]
ok, i see now...i never realized that ncpa had definitions for the extensions in its config....sorry for my ignorance.  i made this change in /usr/local/ncpa/etc/ncpa.cfg:
`.ps1 = pwsh -ExecutionPolicy Bypass -File $plugin_name $plugin_args`

and the extensions work now.  thanks for pointing me in the right direction!
