### ISSUE TITLE
what if my arguments need to use quotes?

### ISSUE THREAD

**Issue by tonyguadagno** [NagiosEnterprises/ncpa#934]
hi, i see that i can specify arguments using 

`-q "arg1=1 arg2=2"`

but what if i need to embed quotes for an argument like:

`-q "arg1="the fox""`

is this allowed?  how do i do that?
thanks

**Comment by MrPippin66** [comment]
Try escaping them with '\'

Alternatively, enclose the outside parameters with single quotes.

**Comment by tonyguadagno** [comment]
ok, i tried both and neither worked:

```
[nagios@server ~]$ /usr/local/nagios/libexec/check_ncpa.py -H 172.1.1.1-v -t token -P 5693 -M plugins/test.ps1 -q '-TheString \"bcd\"'
An error occurred:
need more than 1 value to unpack
```

**Comment by MrPippin66** [comment]
You don't want to do both, since it will cause the command to get a literal '\"' in the argument.

The issue is how to get past shell command processing semantics.

**Comment by MrPippin66** [comment]
Okay, just now fully read your command. You need to use '-a' not '-q'. 

Running Plugins with Arguments

If you are using the plugins module to execute your own custom scripts, you will likely want to be able to pass arguments to the executed script. To do this, check_ncpa.py has -a, which allows you to send a set of arguments to your script. Pay close attention to how the arguments are quoted in these examples; single quotes and double quotes matter here.

**Comment by MrPippin66** [comment]
If you want the literal argument to be 'bcd' to the command, try this:

/usr/local/nagios/libexec/check_ncpa.py -H 172.1.1.1 -v -t token -P 5693 -M plugins/test.ps1 -a "-TheString \'bcd\'"

**Comment by tonyguadagno** [comment]
same:

```
[nagios@server ~]$ /usr/local/nagios/libexec/check_ncpa.py -H 172.1.1.1 -v -t token -P 5693 -M plugins/test.ps1 -a "-TheString 'bcd'"
Connecting to: https://172.1.1.1:5693/api/plugins/test.ps1/-TheString/%5C%27bcd%5C%27?token=zIVIT5mI4FJQq9_eyJhG&check=1
File returned contained:
{
"returncode": -11,
"stdout": ""
}
```

**Comment by MrPippin66** [comment]
Isn't this the same error you had showing the instance of pwsh had core dumped?

**Comment by tonyguadagno** [comment]
err....hummm

**Comment by tonyguadagno** [comment]
yes, you are correct...again!

`-a '-arg1 "asdfasdf" '`

works on a shell script....

so the error is my issue with powershll coredumping.

thanks again!

**Comment by ccztux** [comment]
Take a look at [this](https://github.com/NagiosEnterprises/ncpa/issues/585#issuecomment-882379451). Maybe this will help you.
