### ISSUE TITLE
Version 2.4.1 missing aarch64 downloads

### ISSUE THREAD

**Issue by Matty-uk** [NagiosEnterprises/ncpa#935]
The 2.4.0 release had aarch64 downloads available e.g. ncpa-2.4.0.el8.aarch64.rpm

There does not seem to any aarch76 version available for 2.4.1.  Are these coming or do I need to install from source?

**Comment by sawolf** [comment]
Hi @Matty-uk,

We've decided not to continue building an official image for NCPA + ARM for the time being. I will make sure that there are still ways to access the 2.4.0 aarch64 RPM, but yes, I would recommend building from source.
