### ISSUE TITLE
Installation not creating services (Windows Server 2008 x64 & Windows Server 2012 R2 x64)

### ISSUE THREAD

**Issue by Duumke** [NagiosEnterprises/ncpa#94]
Hi,

I'm having some trouble getting the NCPA service installed on two of our machines.
- Windows 2008 R2 x64
- Windows 2012 R2 x64
Both having the VS 2008 Redistributable installed.

I'm installing with an account with administrator rights, but not the Administrator account itself.
While installing I don't get any indication of something going wrong during the installation. I just don't see the services in the services manager (services.msc).

Do you have any idea where this goes wrong? If there's more info needed, please let me know.

Kind Regards,
Duumke

**Comment by scot0357** [comment]
Referencing this so I can keep it all in one place.

https://github.com/NagiosEnterprises/ncpa/issues/115

Closing this to track in there.
