### ISSUE TITLE
Problem with active checks on MacOS 13.3.1

### ISSUE THREAD

**Issue by Fatboydrunk** [NagiosEnterprises/ncpa#940]
I have installed the NCPA 2.4.1 on MacOS 13.3.1
But the active checks (check_ncpa.py) from my nagios core server are returning:
An error occurred:HTTP Error 500: INTERNAL SERVER ERROR

Is the agent compatiable with MacOS 13.3.1?

**Comment by MrPippin66** [comment]
What are the NCPA logs showing?

**Comment by Fatboydrunk** [comment]
I can't see any logs, it's meant to be in /var/log/ncpa_listener.log but the log file isn't there.

I think the problem is to do with a TLS mismatch.
If I run a curl the nagios server:
curl -vik https://192.168.40.40:5693/api/system/agent_version?token=mytoken

The output is:

*   Trying 192.168.40.40...
* TCP_NODELAY set
* Connected to 192.168.40.40 (192.168.40.40) port 5693 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.0 (IN), TLS handshake, Certificate (11):
* TLSv1.0 (IN), TLS handshake, Server finished (14):
* TLSv1.0 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.0 (OUT), TLS change cipher, Client hello (1):
* TLSv1.0 (OUT), TLS handshake, Finished (20):
* TLSv1.0 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.0 / AES256-SHA
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: C=US; ST=Minnesota; L=St. Paul; O=Nagios Enterprises, LLC; OU=Development; CN=macbuilder1.armorica.gk
*  start date: Apr 17 10:43:23 2023 GMT
*  expire date: Apr 14 10:43:23 2033 GMT
*  issuer: C=US; ST=Minnesota; L=St. Paul; O=Nagios Enterprises, LLC; OU=Development; CN=macbuilder1.armorica.gk
*  SSL certificate verify result: self signed certificate (18), continuing anyway.
> GET /api/system/agent_version?token=mytoken HTTP/1.1
> Host: 192.168.40.40:5693
> User-Agent: curl/7.58.0
> Accept: */*
>
< HTTP/1.1 500 INTERNAL SERVER ERROR
HTTP/1.1 500 INTERNAL SERVER ERROR

**Comment by MrPippin66** [comment]
What TLS settings did you select on the client side in NCPA?

What are you running the check_ncpa client on?

**Comment by MrPippin66** [comment]
FYI, since this is Unix, if you run the NCPA listener in non-daemon mode, you should be more details of the TLS negotiation issue from the terminal you run it on.

**Comment by Fatboydrunk** [comment]
TLSv1.2 on the client.
Nagios core running on Ubuntu

**Comment by MrPippin66** [comment]
Can you expand on that? What are these settings on the NCPA client.

ssl_ciphers
ssl_version

**Comment by MrPippin66** [comment]
You don't have any ciphers specified? Or are you saying this is just a default install of the agent with no config file customization?

In any case, I'd again recommend running the listener from the command line in non-daemon mode. You'll get all the SSL errors reported to the terminal you're running the command.

Alternatively, and I suspect you'll get the same issue, is doing an "openssl s_client --connect \<server\>:5693" and you'll get the connection details.

But I suspect the openssl library on your ubuntu server may be running with a secure configuration that's preventing any compatible ciphers the agent is running on your OSX system.

**Comment by Fatboydrunk** [comment]
The problem I have found is that making changes to the ncpa.cfg don't take affect.
When I change the TLS version it always stays on TLSv1.

The difference with this mac compared to the others that are working fine, is it has a M chip and not intel.
And I had to install Rosetta 2 to install the agent.

Just wondering if it is compatiable with the Macs with M chips?

**Comment by MrPippin66** [comment]
Are you restarting the ncpa_listener after updating the config?

**Comment by MrPippin66** [comment]
And I agree, at this point, there needs to be an x86 and ARM version for the MACOS platforms.

**Comment by Fatboydrunk** [comment]
As the active checks aren't working,
I have now configured passive checks, which are working fine.
But I would prefer to use the active checks

**Comment by chriscareycode** [comment]
Same issue. On MacOS 13.4, the ssl_version = TLSv1_2 does not work and it defaults back to "Using SSL version TLSv1".

I verified that it is reading the config file ncpa.cfg, by modifying the logfile path, and it did write the new file I specified.
Started the process using: sudo ./ncpa_listener -n -c /usr/local/ncpa/etc/ncpa.cfg

I'm wondering if we can install a ssl package with brew to get this fixed?

**Comment by phreditorNG** [comment]
Hey @Fatboydrunk, @chriscareycode:
Sorry for you struggles. It seems likely that you would start running into these kinds of problems on newer MacOS since they tend to enforce a minimal level of security out of the box. 

Since we bundle almost all dependencies in the NCPA app so it will run almost anywhere without requiring significant changes to the server, including OpenSSL, installing OpenSSL via Brew won't help unless you do some serious hacking.

NCPA v3.0.0, currently in beta, includes OpenSSL 3+ on all supported platforms, even oldies like CentOS 7. We've just gotten MacOS (Intel-based, Catalina+) programmed and the build infrastructure set up. I'm not sure exactly when it will be available, but I will look into it, and let this forum know, shortly.

Phred

**Comment by phreditorNG** [comment]
Hey @Fatboydrunk, @chriscareycode:
You can download the public beta for NCPA v3.0.0 at: Hey https://www.nagios.org/ncpa/

**Comment by Fatboydrunk** [comment]
I can confirm that NCPA v3.0.0 is working on my Mac M1 chip MacOS 13.5 with active checks.
Thanks for your help @phreditorNG
