### ISSUE TITLE
Passive Port Check

### ISSUE THREAD

**Issue by cydo67** [NagiosEnterprises/ncpa#95]
I have placed a plugin in the plugins directory and I am running passive checks to monitor ports on the Windows server, example:

%HOSTNAME%|Port 5693 = agent/Plugins/check_tcp -p 5693
%HOSTNAME%|Port 80 = agent/Plugins/check_tcp -p 80
%HOSTNAME%|Port 443 = agent/Plugins/check_tcp -p 443

The ports monitored create a flapping situation where they flucuate between these messages:

Unable to run check on non-child node. Revise your query.
TCP OK - 0.058 second response time on 104.130.156.183 port 5693

RRD files continue to build and graphing does not have any blank spaces. 

I checked the firewall and there are no limits on the firewall for these ports.

I am using this binary:
http://exchange.nagios.org/directory/Plugins/Operating-Systems/Windows-NRPE/check_tcp/details

Any idea why the change in states or how I could make this check work consistently?

Thanks....

**Comment by scot0357** [comment]
This has officially been merged.
