### ISSUE TITLE
NCPA Agent for SUSE Linux Enterprise Server (SLES)

### ISSUE THREAD

**Issue by jkinning** [NagiosEnterprises/ncpa#96]
I tried install both ncpa-1.7.2.os12.x86_64.rpm and ncpa-1.7.2.os13.x86_64.rpm both give me the same errors when attempting to install on SLES 11sp3.

Retrieving package ncpa-1.7.2-1.x86_64 (1/1), 7.4 MiB (27.1 MiB unpacked)
Retrieving package ncpa-1.7.2-1.x86_64 (1/1), 7.4 MiB (27.1 MiB unpacked)
Installing: ncpa-1.7.2-1 [done]
Additional rpm output:
uid=1000(nagios) gid=1000(nagcmd) groups=16(dialout),33(video),1000(nagcmd)
insserv: Service syslog is missed in the runlevels 4 to use service ncpa_listener
ncpa_listener 0:off 1:off 2:on 3:on 4:on 5:on 6:off
insserv: Service syslog is missed in the runlevels 4 to use service ncpa_listener
ncpa_passive 0:off 1:off 2:on 3:on 4:on 5:on 6:off
./ncpa_posix_listener: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by ./ncpa_posix_listener)
./ncpa_posix_listener: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /usr/local/ncpa/libpython2.7.so.1.0)
Started listener...
/usr/local/ncpa/ncpa_posix_passive: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /usr/local/ncpa/ncpa_posix_passive)
/usr/local/ncpa/ncpa_posix_passive: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /usr/local/ncpa/libpython2.7.so.1.0)
Started passive agent...

The links above are for openSUSE not SLES. Is it possible to install the NCPA on the Enterprise version of SUSE?

**Comment by jhomann** [comment]
I'm building a version for SLES/OpenSUSE 11 today that will be added to the download section.
