### ISSUE TITLE
Nagios "Status Information" using NCPA showing "Connecting To"

### ISSUE THREAD

**Issue by luckyrob** [NagiosEnterprises/ncpa#960]
I have a new Nagios instance and have deployed NCPA which works. However, in the Status Detail of every device, the Status Information column does not show the stdout info. but instead shows "Connecting to..." with a URL for the result. 

Example for Status Detail for Uptime using NCPA:

Instead of showing the output, " OK: Uptime was 42 minutes 1 second | 'uptime'=2521.64s;;7776000;" it shows:

![image](https://github.com/NagiosEnterprises/ncpa/assets/67337182/1b38b24a-6683-45c1-8ed2-d8248d84e2b2)

**Status Information**
Connecting to: https://<-URL->:5693/api/system/uptime/?token=<token>&critical=7776000&check=1

Going to that URL:
{
    "returncode": 0, 
    "stdout": "OK: Uptime was 42 minutes 1 second | 'uptime'=2521.64s;;7776000;"
}

Is there a setting I might have misconfigured or is missing that would allow the proper stdout output in the Status Information column?

Stats for Nagios server:
Nagios 4.4.13
Nagios Plugins 2.4.4
NCPA ncpa-2.4.1-1.el9.x86_64

Thx in advance!

**Comment by ccztux** [comment]
It looks like you are using the argument `-v` (=verbose) in your check_command of `check_ncpa.py`

**Comment by luckyrob** [comment]
AH! Thank you @ccztux!!! That was EXACTLY the problem. I knew I was overlooking something. Greatly appreciate your response. I'll be sure to remember that in the future.  Closing this with comment.

Have a great one!!
