### ISSUE TITLE
NCPA Agent Process on Solaris keeps stopping

### ISSUE THREAD

**Issue by omkarkaravade** [NagiosEnterprises/ncpa#963]
Dear Experts,

We have recently started exploring Nagios and we were trying to install NCPA agents on some of our solaris servers. The installation went fine and we are also able to monitor required services in Nagios XI. However, we have noticed that after some time Nagios XI looses connection with the agent and we get below error in the XI.

**UNKNOWN: An error occured connecting to API. (Connection error: '[Errno 111] Connection refused')**

On further investigation we observed that the ncpa_listener process disappears after some time, even if the service status says online. If we stop and start the service again, the process appears again and connection restores. However, the process keeps disappearing after some interval. 

We tried to check the logs but couldn't find anything useful. May be we are missing something. Can you please help us. We are facing same issue on 2 servers. We have also installed NCPA on one of our RHEL box and we are not noticing this issue on RHEL.

We are on Solaris 11.4. NCPA version is 2.4.0

![image](https://github.com/NagiosEnterprises/ncpa/assets/139055454/2e867892-ad63-482b-af42-1e7521f20d2b)
![image](https://github.com/NagiosEnterprises/ncpa/assets/139055454/bc322a4f-3015-46a2-b1ab-38363094f147)

**Comment by omkarkaravade** [comment]
> this might related to same issue [#859](https://github.com/NagiosEnterprises/ncpa/issues/859).

Thank you. I will downgrade tomorrow and post results on this thread.

**Comment by MrPippin66** [comment]
Can you tell if the program memory is increasing up the point it core dumps?

**Comment by omkarkaravade** [comment]
> this might related to same issue [#859](https://github.com/NagiosEnterprises/ncpa/issues/859).

Thank you. I downgraded to 2.3.1 and the agent is running smoothly now. The agent process did not exit even once. 

@MrPippin66): No. I didn't notice any such issue.

**Comment by xera13** [comment]
> > this might related to same issue [#859](https://github.com/NagiosEnterprises/ncpa/issues/859).
> 
> Thank you. I downgraded to 2.3.1 and the agent is running smoothly now. The agent process did not exit even once.
> 
> @MrPippin66): No. I didn't notice any such issue.

Hi Sir.. May i know patch level on your solaris? Mine current 11.4 sru59 not working with agent 2.3.1
