### ISSUE TITLE
NAGIOS LDAP Integration

### ISSUE THREAD

**Issue by omkarkaravade** [NagiosEnterprises/ncpa#964]
Dear Experts,

We are trying to integrate Nagios XI with LDAP. We have created a authentication server in Nagios. However, when we connect with the credentials we are getting an empty user list. The user we are using to connect has the required privileges. We can connect and fetch users using ldapsearch with the same user.

We also verified the steps provided in the below article: No users Returned section. The entries mentioned are already available in the file.

https://support.nagios.com/kb/article/active-directory-ldap-troubleshooting-authentication-integration-600.html

The www.error-log shows below errors.  Can someone help us on this. Our Nagios XI version is 5.10.0
 
**PHP Notice: Undefined offset: 5 in /usr/local/nagiosxi/html/includes/components/ldap_ad_integration/basicLDAP.php on line 101
PHP Notice: Undefined offset: 5 in /usr/local/nagiosxi/html/includes/components/ldap_ad_integration/basicLDAP.php on line 101
PHP Warning: ldap_list(): Search: Operations error in /usr/local/nagiosxi/html/includes/components/ldap_ad_integration/basicLDAP.php on line 155
PHP Warning: ldap_get_entries() expects parameter 2 to be resource, boolean given in /usr/local/nagiosxi/html/includes/components/ldap_ad_integration/basicLDAP.php on line 156
PHP Notice: Undefined offset: 5 in /usr/local/nagiosxi/html/includes/components/ldap_ad_integration/basicLDAP.php on line 101**

![image](https://github.com/NagiosEnterprises/ncpa/assets/139055454/d8701c11-76d8-4206-ba30-e434f83e4fb2)

**Comment by ericloyd** [comment]
It feels like this would be a better question to ask through your Nagios XI license granted support from Nagios.  This isn't a support forum, it's a code debugging forum.  Plus, this is for NCPA, not Nagios XI.

You should have received the following information when you purchased your Nagios XI license:

> The renewal of your support and maintenance benefits enables you to receive access to new version upgrades, including bug and security fixes. It also includes direct access to our Support Team via our Nagios Answer Hub (up to 10 cases).
> 
> Nagios Support is provided via our Nagios Answer Hub, if you need to register for access, please use the below link.
> 
> https://info.nagios.com/answer-hub-access-new-users
> 
> You can access the Nagios Answer Hub here: https://nagios.force.com/support/s/
> 
> Getting the most value from your Nagios support benefits
> 
> Cases: 10 support cases are included with your renewal of Nagios license. Please submit a support case when you have an issue that contains private information, which will be kept confidential between you and Nagios.
> 
> Need Additional Support? You can add expedited phone support to your package and jump the line when needed. You also have the option of adding additional direct support cases. Email [csm@nagios.com](mailto:csm@nagios.com) for more information.
>

**Comment by sawolf** [comment]
I agree with Eric on this one - you will want to reach out to the Support team for help with this. This repository is specifically for bugs, features, and other issues related to the Nagios Cross-Platform Agent.
