### ISSUE TITLE
Feature request - Check all disks with a single check

### ISSUE THREAD

**Issue by bramassendorp** [NagiosEnterprises/ncpa#972]
Might be useful to have a single check, which could check all drives for free/used space (Win and Lin).

**Comment by ericloyd** [comment]
This has come up many times.  https://github.com/NagiosEnterprises/ncpa/issues/178

**Comment by sawolf** [comment]
@bramassendorp, thanks for reaching out. I agree that this would be useful.

Thanks for the cross-link, @ericloyd! I'm closing this as a duplicate, will update the other issue.
