### ISSUE TITLE
Feature request - Debian 12 support

### ISSUE THREAD

**Issue by tt-78** [NagiosEnterprises/ncpa#975]
Debian 12 (Bookworm) was released on the 10th of June, and the second point release of 12.2 is being released in just under two weeks time. I note the beta release of NCPA 3.0 has Debian 9+ in its version list - does this mean that:

1. Debian 12 is supported by NCPA 3, and/or
2. Will Debian 12 be getting support in the 2.x client?

Thanks!

**Comment by ne-bbahn** [comment]
Update: We do now officially support Debian 12 with NCPA 3 and NCPA 3 seems to be working on my instance of Debian 12. NCPA 2 should also work on Debian 12, but we have no plans to continue support for NCPA 2 at this time. If you notice any problems with NCPA on Debian 12, please post an issue. Thank you.
