### ISSUE TITLE
NCPA V3-Beta | Fails to populate Service Description in Windows10

### ISSUE THREAD

**Issue by SNapier** [NagiosEnterprises/ncpa#977]
When installing via the graphical installer on Windows10 the service description fails to populate for the NCPA service.
![Installed-service-lacks-description](https://github.com/NagiosEnterprises/ncpa/assets/50675926/a8934dd6-8993-4999-a616-8f29f53ac351)

**Comment by ne-bbahn** [comment]
I am not able to replicate this issue. Perhaps something went wrong during the installation. If the problem persists after uninstalling/re-installing, please respond here.

**Comment by SNapier** [comment]
I have uninstalled and re-installed the agent on the same device and have the same issue.
I will try on another device and see if I can re-create the issue.

**Comment by ne-bbahn** [comment]
I am not encountering this issue. I've tested on Windows 10. Nevertheless, I made a PR that sets the service description to "Nagios Cross-Platform Agent"
