### ISSUE TITLE
NCPA v3-Beta | API Memory/Swap fails with "Error retrieving child" on Windows

### ISSUE THREAD

**Issue by SNapier** [NagiosEnterprises/ncpa#979]
NCPA API for Windows Memory/Swap fails with error messages.

![windows-memory-swap-failurePNG](https://github.com/NagiosEnterprises/ncpa/assets/50675926/ffd92056-89bc-4a5a-bea1-d16c8dc5626f)

This failure causes subsequent problems within the UI related to memory/swap metrics
![mem-swap-total-delta-no-graph](https://github.com/NagiosEnterprises/ncpa/assets/50675926/18db1378-4e49-42ef-98a5-b1dce3e154df)

**Comment by ne-bbahn** [comment]
Hello,

I suspect that performance counters may be disabled in your registry. This feature has been tested and is working.
