### ISSUE TITLE
NCPA v3-Beta | Windows CPU Delta graph does not display counter data

### ISSUE THREAD

**Issue by SNapier** [NagiosEnterprises/ncpa#980]
Windows CPU Delta graph does not display counter data for the metric.

Current
Min
Max
Average

![cpu-percent-avg-delta-perfdata-noshow](https://github.com/NagiosEnterprises/ncpa/assets/50675926/aa07d992-daf3-49c7-800f-7c0619e9fd78)

**Comment by ne-bbahn** [comment]
It seems that it works if you try to re-generate the graph it will work, but this is definitely a bug.

**Comment by ne-bbahn** [comment]
PR not yet merged.

**Comment by ne-bbahn** [comment]
My original fix broke the other graphs in the `Live Data` section, so I've reverted that and am reopening this.
