### ISSUE TITLE
Run a Powershell script that requires a parameter that can have spaces

### ISSUE THREAD

**Issue by riahc3** [NagiosEnterprises/ncpa#999]
Similar to #829 , Im running 

/usr/local/nagios/libexec/check_ncpa.py -H thehost -t '' -P 5693 -M 'plugins/CheckClusterResourceGroupStatus.ps1' -a "'Cluster Group'"

But I get the following error

UNKNOWN - Resource group \'Cluster/Group\' not found

The worst part of this is

![dtcXOO4](https://github.com/NagiosEnterprises/ncpa/assets/1131521/59ff9aac-9d66-47e4-b92f-f174ae641828)

This makes no sense and is ABSURD that this happens with NCPA and Nagios XI (a paid product) in 2023.

Both sides should have logic to deal with this

**Comment by riahc3** [comment]
[nagios@nagiosxi ~]$ /usr/local/nagios/libexec/check_ncpa.py -H clu -t '' -P 5693 -M 'plugins/chkspace.ps1' -q "args='My Job',args=90,args=95"
C:\Program Files (x86)\Nagios\NCPA\plugins\chkspace.ps1 : Cannot process argument because the
value of argument "name" is not valid. Change the value of the "name" argument and run the operation again.
+ CategoryInfo : InvalidArgument: (:) [chkspace.ps1], PSArgumentException
+ FullyQualifiedErrorId : Argument,chkspace.ps1


Yet, in cli and in API it works

**Comment by riahc3** [comment]
I think I had to do all this crap to remove it

$var = $var -replace "'",""
$var = $var -replace "`"",""
$var = $var -replace "\\",""
$var = $var -replace "/'"," "

This in Nagios:

-t '' -P 5693  -M 'plugins/Script.ps1' -a '-parameteronename "Value of parameter one" -parametertwoname 85 -parameterthreename 95'

Ugly and crap in 2023

**Comment by ne-bbahn** [comment]
Which version of Nagios XI are you running?
![image](https://github.com/NagiosEnterprises/ncpa/assets/114498860/cd4dc9b1-085a-4f01-b18a-a8ec62ed45fd)
I am not encountering this issue.

**Comment by ne-bbahn** [comment]
If I don't get a response here, I will close this issue in a few days. It works fine for me as can be seen above.
